### ISSUE TITLE
PageSpeed Optimized CSS and CORS Headers

### ISSUE THREAD

**Issue by JoyceBabu** [pagespeed/ngx_pagespeed#1005]
How can I add CORS headers to pagespeed optimized css files? I have the following `location` block, and it is not matching the optimized files
```
location ~*.*\.(?:woff|woff2|ttf|otf|eot|js|css)$ {
    add_header 'Timing-Allow-Origin' "*";
    add_header 'Access-Control-Allow-Origin' "*";
    add_header "Access-Control-Allow-Methods" "GET";
    expires 12M;
    try_files $uri @backend;
}
```

I also tried adding the following config and it too did not work

```
location ~ "\.pagespeed\.(?:[a-z]\.)?[a-z]{2}\.[^.]{10}\.css" {
    add_header 'Timing-Allow-Origin' "*";
    add_header "Access-Control-Allow-Origin" "*";
    add_header "Access-Control-Allow-Methods" "GET";
}
```

**Comment by JoyceBabu** [comment]
Is it possible to add custom headers to CORS headers to pagespeed optimized resources in Nginx?

**Comment by jeffkaufman** [comment]
I think we're going to need to add something to let people set these.  Right now PageSpeed is careful to keep add_header commands from affecting the headers it sets on optimized resources because most add_header commands that are already in someone's config aren't the ones you'd want for our resources.  But there needs to be a way to say "I'm specifically trying to control the headers on .pagespeed. resources, set this please".

**Comment by jeffkaufman** [comment]
Actually, as long as you're not using LoadFromFile or outlining filters this should work.  If you set a non-caching header on foo.js, then when pagespeed creates foo.js.pagespeed.ce.HdziXmtLIV.js it should include the header.  You would need to flush your http cache, though, to pick up the new header if the input resource had a long cache lifetime.

**Comment by jeffkaufman** [comment]
(And if you have combiners than only headers present on all the input resources will be included on the output resource.)

**Comment by oschaaf** [comment]
@jeffkaufman there's also https://github.com/pagespeed/ngx_pagespeed/pull/906

**Comment by JoyceBabu** [comment]
@jeffkaufman Thank you for the reply. I am using LoadFromFile, outlining and combiners.

It would be great if there was a new directive, say `pagespeed_add_header` for adding headers to optimized resources. Or maybe PageSpeed could maintain a blacklist of headers that should not be applied on a optimized resource, and allow all other headers. The first option would provide much more control, IMHO. Is it possible to do something like this?

**Comment by jeffkaufman** [comment]
It looks like we don't need `pagespeed_add_header` because we're already maintaining a blacklist as you would like us to.  Basically, we blacklist caching related headers, and so any other headers you set on the *original* resource will get included on the pagespeed-optimized resource.

**Comment by JoyceBabu** [comment]
But then how can we target resources loaded using `LoadFromFile`?

**Comment by jeffkaufman** [comment]
Sorry, yes.  We do need a directive like this for `LoadFromFile` and also for (far less common) outlined resources.

**Comment by JoyceBabu** [comment]
Thank you for the clarification. So, can this issue be accepted as a feature request? Or do I have to file one elsewhere?

**Comment by jeffkaufman** [comment]
Added to https://github.com/pagespeed/mod_pagespeed/wiki/Accepted-Feature-Requests

**Comment by jeffkaufman** [comment]
One important use case here would be no-transform headers.

**Comment by JoyceBabu** [comment]
I am unable to use the new `crossorigin="anonymous"` attribute for script tag, because of the missing headers. Firefox will not evaluate the scripts without the correct CORS headers. Is there an ETA for this feature?

**Comment by jeffkaufman** [comment]
No one is currently working on this, sorry!

**Comment by jeffkaufman** [comment]
You're right though, that this should be higher priority.  I've pushed it up higher on https://github.com/pagespeed/mod_pagespeed/wiki/BugFix-Prioritization

**Comment by JoyceBabu** [comment]
Is there any work around for this?

**Comment by oschaaf** [comment]
There might be a workaround, this patch moves ngx_pagespeed's module position: https://gist.github.com/oschaaf/f9f71f493da928f07dba

Patching in that change moves ngx_pagespeed in the module order so that you can override headers for pagespeed resources like this:
```
location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
    add_header 'Timing-Allow-Origin' '*';
}
```

trunk-tracking has a change that allows you to position ngx_pagespeed like this through an option. Over there, this change passes all system tests except `SSI`. I just manually tried the linked patch on the latest release and it worked for me.

**Comment by JoyceBabu** [comment]
@oschaaf It failed for me with the following message

> [root@mars ngx_pagespeed-release-1.9.32.10-beta]# patch < nps_pos_aux.diff 
> patching file config
> Hunk #1 FAILED at 193.
> Hunk #2 succeeded at 201 with fuzz 1 (offset -10 lines).
> 1 out of 2 hunks FAILED -- saving rejects to file config.rej

**Comment by oschaaf** [comment]
@JoyceBabu Sorry, I pasted the wrong patch, that one was for the `master` branch. 
I updated it to work for `ngx_pagespeed-release-1.9.32.10-beta`, could you try again?

**Comment by JoyceBabu** [comment]
@oschaaf Thank you. I have manually edited the `config` file and applied the changes. It is now working correctly.

Should I try again with the new patch?

**Comment by oschaaf** [comment]
@JoyceBabu If the new patch looks correct when you compare it to your changes in your `config` file you don't need to try again as far as I'm concerned.
Are you able to set the headers now?

**Comment by JoyceBabu** [comment]
I tried the new patch and it also throwing an error, even though the patching itself is successful

> patching file config
> patch unexpectedly ends in middle of line
> Hunk #1 succeeded at 193 with fuzz 1.

**Comment by JoyceBabu** [comment]
Looks like it is just a warning
http://unix.stackexchange.com/questions/1395/what-does-patch-unexpectedly-ends-in-middle-of-line-mean

**Comment by JoyceBabu** [comment]
The cross origin headers are being duplicated for pagespeed optimized resources. For example, I am getting `Access-Control-Allow-Origin: *, *` instead of `Access-Control-Allow-Origin: *`. For original file, the header is correct.

**Comment by oschaaf** [comment]
@JoyceBabu Do you have `headers-more` available? If you use `more_set_headers` instead of `add_header` I think that the duplication will be gone.

**Comment by JoyceBabu** [comment]
Is the new option available in release `v1.10.33.2`?

**Comment by oschaaf** [comment]
@JoyceBabu changes are pending that have been reviewed but have not yet been merged, so they are not yet available in a release.

**Comment by JoyceBabu** [comment]
@oschaaf I was trying to cherry pick the fix, and found out that the patch is for mod_pagespeed. Is it not available for ngx_pagespeed?

**Comment by oschaaf** [comment]
@JoyceBabu You would need to build ngx_pagespeed against a PSOL version that includes this. No changes required for ngx_pagespeed.

**Comment by JoyceBabu** [comment]
Would it be a terribly bad idea to run PSOL master in production? Also, should the version of PSOL match with the version of ngx_pagespeed? Is it necessary to run PSOL master with ngx_pagespeed master?

**Comment by jeffkaufman** [comment]
ngx_pagespeed:master builds against the latest PSOL release.  The main reason to do this would be if you wanted to apply a patch to PSOL, but not get full updates.  This is relatively safe, especially if your patch is simple, small, and well understood.

ngx_pagespeed:trunk-tracking builds against mod_pagespeed:master.  This is what you'd do if you wanted to run at the complete bleeding edge.  In general I wouldn't recommend this for production unless you canaried it first and didn't see any issues.  (If you did see issues, though, your finding them early would be really useful!)

**Comment by mashirozx** [comment]
I meeet something like this:

>Failed to load https://a.com/tips_v3.7.json: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'https://a.com' is therefore not allowed access.

And this is my Nginx configuration:

```
        .......
        pagespeed on;
	# Default
	# Needs to exist and be writable by nginx.  Use tmpfs for best performance.
	pagespeed FileCachePath /var/ngx_pagespeed_cache;

	# Ensure requests for pagespeed optimized resources go to the pagespeed handler
	# and no extraneous headers get set.
	location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
	  add_header "" "";
	}
	location ~ "^/pagespeed_static/" { }
	location ~ "^/ngx_pagespeed_beacon$" { }

	location ~* \.(json)$ {
	    if ($http_referer = "") {   return 403;  }
            add_header 'Access-Control-Allow-Origin' *;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Headers' 'User-Agent,Keep-Alive,Content-Type';
	    
            expires 7d;
	    log_not_found off;
	}
```

**Comment by mashirozx** [comment]
I tried to remove `add_header 'Access-Control-Allow-Origin' *;` from `location ~* \.(json)${}` block, and `rm -rf /var/ngx_pagespeed_cache/*`,  but seems it it still not work. 
The JSON file worked fine before enabling ngx_pagespeed module...

**Comment by mashirozx** [comment]
I got these headers:
![image](https://user-images.githubusercontent.com/16148054/37840093-23ceed56-2ef7-11e8-9313-4730d4215909.png)
 
So may I guess problem is this?
```
location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
	  add_header "" "";
}
```
How can I fix it? 😭

**Comment by mashirozx** [comment]
I also tried to clean cache, still not work 😢
![image](https://user-images.githubusercontent.com/16148054/37843380-af54e576-2eff-11e8-9dda-3c4c3d28b8ce.png)
