### ISSUE TITLE
ngx_pagespeed/src/log_message_handler.cc error on FreeBSD

### ISSUE THREAD

**Issue by Miracle-Nya** [pagespeed/ngx_pagespeed#1008]
While I compiling the ngx_pagespeed module with nginx 1.8.0 on FreeBSD 10.2 RELEASE ports, I get some error on ngx_pagespeed/src/ngx_pagespeed/src/log_message_handler.cc:

>   -o objs/addon/src/log_message_handler.o  /usr/ports/www/nginx/work/ngx_pagespeed/src/log_message_handler.cc
/usr/ports/www/nginx/work/ngx_pagespeed/src/log_message_handler.cc:102:3: error:
      reference to 'log' is ambiguous
  log = log_in;
  ^
/usr/include/math.h:251:8: note: candidate found by name lookup is 'log'
double  log(double);
        ^
/usr/ports/www/nginx/work/ngx_pagespeed/src/log_message_handler.cc:41:12: note:
      candidate found by name lookup is '<anonymous namespace>::log'
ngx_log_t* log = NULL;
           ^
/usr/ports/www/nginx/work/ngx_pagespeed/src/log_message_handler.cc:107:7: error:
      reference to 'log' is ambiguous
  if (log->log_level >= NGX_LOG_DEBUG) {
      ^
/usr/include/math.h:251:8: note: candidate found by name lookup is 'log'
double  log(double);
        ^
/usr/ports/www/nginx/work/ngx_pagespeed/src/log_message_handler.cc:41:12: note:
      candidate found by name lookup is '<anonymous namespace>::log'
ngx_log_t* log = NULL;
           ^
/usr/ports/www/nginx/work/ngx_pagespeed/src/log_message_handler.cc:107:7: error:
      unknown type name 'log'
  if (log->log_level >= NGX_LOG_DEBUG) {
      ^
/usr/ports/www/nginx/work/ngx_pagespeed/src/log_message_handler.cc:107:10: error:
      cannot use arrow operator on a type
  if (log->log_level >= NGX_LOG_DEBUG) {
         ^
/usr/ports/www/nginx/work/ngx_pagespeed/src/log_message_handler.cc:107:10: error:
      variable declaration in condition must have an initializer
5 errors generated.
*** Error code 1

Stop.
make[3]: stopped in /usr/ports/www/nginx/work/nginx-1.8.0
*** Error code 1

Stop.
make[2]: stopped in /usr/ports/www/nginx/work/nginx-1.8.0
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/www/nginx
*** Error code 1

Stop.
make: stopped in /usr/ports/www/nginx

**Comment by jeffkaufman** [comment]
ngx_pagespeed doesn't currently support BSD because it depends on PSOL which also doesn't support BSD.  So even if we fix these issues around `log` you're still not going to be able to run ngx_pagespeed without a lot of additional work.

To follow this, please subscribe to https://github.com/pagespeed/mod_pagespeed/issues/1073
