### ISSUE TITLE
nginx real ip module 1.4

### ISSUE THREAD

**Issue by skmdrony** [pagespeed/ngx_pagespeed#1009]
i am install and compile ngx pagespeed
but problem is in my site is running cloudflare and my nginx version is 1.4.4

i see nginx -V the nginx real ip module is missing 

can you tell how i add this on running ngx pagespeed 

and its very hard to conpile nginx and pagespeed

so just plz tell me how i add nginx real ip module on nginx pagespeed

**Comment by jeffkaufman** [comment]
Sorry for missing this!

In the ngx_pagespeed [instructions](https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source) it says to run:

    ./configure --add-module=$HOME/ngx_pagespeed-release-${NPS_VERSION}-beta

If you need to add other modules, you want this instead:

    ./configure --with-http_realip_module \
         --add-module=$HOME/ngx_pagespeed-release-${NPS_VERSION}-beta
