### ISSUE TITLE
MapProxyDomain does not work with InPlaceResourceOptimization

### ISSUE THREAD

**Issue by jmarantz** [pagespeed/ngx_pagespeed#1015]
I think this should be straightforward to support, as the MapProxyDomain prefixes are established at configuration time and can be statically checked in the handler at request-time.

Note that there are a variety of ipro/MapProxyDomain tests around https://github.com/pagespeed/mod_pagespeed/blob/master/pagespeed/apache/system_test.sh#L988 but those are not shared with nginx.

In the shared system_test script there is a test for MapProxyDomain from the HTML flow: https://github.com/pagespeed/mod_pagespeed/blob/master/pagespeed/system/system_test.sh#L241

but there is no evidence of testing in that shared file for MapProxyDomain of in-place resources.

**Comment by jeffkaufman** [comment]
In normal usage this isn't a problem, because any resources PageSpeed moves onto the mapped proxied domain it will be able to create .pagespeed. resources for, but if you want to set up a server to do IPRO optimization of another server this would be a useful feature.

(This does work in Apache.)

**Comment by jeffkaufman** [comment]
Also, in general it's safer if we accept these, in case a CSS file we proxy onto our domain references something relative and we don't manage to rewrite it's url for some reason.

**Comment by jmarantz** [comment]
See https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/IuMfDTtz8sg for a related problem

**Comment by oschaaf** [comment]
I created pull requests with changes to make this work for nps (note there's also an MPS side to this). 
If the new 'trusted_input' flag in `ProxyFetch` is not a good idea and another approach would be better, I'd love to hear that.

**Comment by jeffkaufman** [comment]
LGTM.  I'll merge this along with the apache side of the change once I finish running internal tests.

**Comment by jeffkaufman** [comment]
Fixed with becc2f6
