### ISSUE TITLE
make failed with nginx-1.8.0 and nix_pagespeed-1.9.32.10

### ISSUE THREAD

**Issue by minibear0523** [pagespeed/ngx_pagespeed#1020]
[nginx-1.8.0] make                                                                                             9:47:14
make -f objs/Makefile
make[1]: Entering directory `/root/nginx-1.8.0'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -Wno-unused-local-typedefs -Wno-error  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /root/ngx_pagespeed/psol/include -I /root/ngx_pagespeed/psol/include/third_party/chromium/src -I /root/ngx_pagespeed/psol/include/third_party/google-sparsehash/src -I /root/ngx_pagespeed/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /root/ngx_pagespeed/psol/include/third_party/protobuf/src -I /root/ngx_pagespeed/psol/include/third_party/re2/src -I /root/ngx_pagespeed/psol/include/out/Release/obj/gen -I /root/ngx_pagespeed/psol/include/out/Release/obj/gen/protoc_out/instaweb -I /root/ngx_pagespeed/psol/include/third_party/apr/src/include -I /root/ngx_pagespeed/psol/include/third_party/aprutil/src/include -I /root/ngx_pagespeed/psol/include/third_party/apr/gen/arch/linux/x64/include -I /root/ngx_pagespeed/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I objs -I src/http -I src/http/modules -I src/mail \
                -o objs/addon/src/ngx_pagespeed.o \
                /root/ngx_pagespeed/src/ngx_pagespeed.cc
{standard input}: Assembler messages:
{standard input}:8970: Warning: end of file not at end of a line; newline inserted
{standard input}:10738: Error: unknown pseudo-op: `.'
cc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 4
make[1]: Leaving directory `/root/nginx-1.8.0'
make: *** [build] Error 2

**Comment by crowell** [comment]
what operating system are you using and what bits (32 or 64).

Are you following the instructions posted or do you have additional flags?

I'm guessing this is a bug in the compiler, but we've built with gcc 4.8 with no issues.

**Comment by minibear0523** [comment]
ubuntu 14.04 64bit. Someone say it is the bug with gcc which out of memory...

**Comment by minibear0523** [comment]
My gcc version is 4.8.4(Ubuntu 4.8.4-2ubuntu1~14.04)

**Comment by minibear0523** [comment]
I think I have solved this problem with expand my vps's memory from 512MB to 2GB. Thanks a lot!
