### ISSUE TITLE
Cache purge and admin

### ISSUE THREAD

**Issue by Angristan** [pagespeed/ngx_pagespeed#1024]
Hi, 

To delete the pagespeed's cache, I delete everything in /var/ngx_pagespeed_cache, is it ok ?

And how to enable the pagespeed admin page with Nginx ?

thanks

**Comment by jmarantz** [comment]
No, that is not a good way to purge cache.  Use the admin page purge
function.  See this page for admin page setup:

https://developers.google.com/speed/pagespeed/module/admin

**Comment by Angristan** [comment]
I have to put this in my server block ?

`pagespeed StatisticsPath /ngx_pagespeed_statistics;
pagespeed GlobalStatisticsPath /ngx_pagespeed_global_statistics;
pagespeed MessagesPath /ngx_pagespeed_message;
pagespeed ConsolePath /pagespeed_console;
pagespeed AdminPath /pagespeed_admin;
pagespeed GlobalAdminPath /pagespeed_global_admin;`

**Comment by jmarantz** [comment]
You also need the 'location' blocks as discussed in the doc.

**Comment by Angristan** [comment]
I get `nginx: [emerg] "pagespeed" directive "GlobalStatisticsPath" cannot be set at this scope. in /etc/nginx/global/pagespeed.conf:40"`

**Comment by oschaaf** [comment]
@Angristan `GlobalStatisticsPath` and `GlobalAdminPath` can only be set at the `http{}` level, not in a `server{}` block.

**Comment by Angristan** [comment]
I get `nginx: [emerg] "gzip_types" directive FileCachePath must be set in /etc/nginx/nginx.conf:51`
The ligne 51 is the laste line of my http block (with } )

**Comment by oschaaf** [comment]
I think configuring a `FileCachePath` in the `http{}` block will fix that. For example:

```bash
http {
   ...
   # Example - path needs to exist and be writable by nginx.  Use tmpfs for best performance.
   pagespeed FileCachePath /var/ngx_pagespeed_cache;
  ...
}
```

**Comment by Angristan** [comment]
In fact, I have a pagespeed.conf file that I include in only one server block. I don't want to use it for the others. And "pagespeed FileCachePath" is already defined in this conf file.

**Comment by jmarantz** [comment]
Can you put the FileCachePath and "pagespeed off;" in the http block, and
then turn it on in the location block where you want it?

**Comment by Angristan** [comment]
It seems to work ! But I get a 403 error on /pagespeed_admin

**Comment by Angristan** [comment]
Ok, with "allow all" it works (not a great solution ^^')

**Comment by jeffkaufman** [comment]
Instead of `allow all` for `/pagespeed_admin` you can use nginx access control rules to limit it by accessing IP or pasword: https://www.nginx.com/resources/admin-guide/restricting-access/

**Comment by Angristan** [comment]
Is it normal that even after the purge the size of my tmpfs doesn't change ?

**Comment by oschaaf** [comment]
@Angristan yes, a purge doesn't physically remove any entries. If you want a smaller cache size, you can restrict the file cache via `FileCacheSizeKb`: https://developers.google.com/speed/pagespeed/module/system#file_cache

**Comment by rajuginne** [comment]
how to access admin page

do i need to add nginx serer block

added this

location /ngx_pagespeed_statistics {  }
location /ngx_pagespeed_global_statistics {  }
location /ngx_pagespeed_message {  }
location /pagespeed_console {  }
location ~ ^/pagespeed_admin {  }
location ~ ^/pagespeed_global_admin {  }
location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" 
{ 
add_header Cache-Control "public, max-age=691200, s-maxage=691200";
add_header Last-Modified exact;
}
location ~ "^/pagespeed_static/" { }
location ~ "^/ngx_pagespeed_beacon$" { }
``

website.com/ngx_pagespeed_statistics  from browser

getting 404

for a normal host we need to pass php requests
using php -fpm


but how enable gui interface
