### ISSUE TITLE
./configure: error: C compiler cc is not found

### ISSUE THREAD

**Issue by HeikoMamerow** [pagespeed/ngx_pagespeed#1032]
Hi,
trying to build new nginx (1.9.6) - but i run in trouble:

When i run `./configure` (with or without add-module) , then i receive this:

    checking for OS
     + Linux 4.2.0-16-generic x86_64
    checking for C compiler ... not found
    
    ./configure: error: C compiler cc is not found

The `build-essential` package is installed.
`which cc` => `/usr/bin/cc`
`cc --version` => `cc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010`

Please help :-)

PS: This look like issue [#894] (https://github.com/pagespeed/ngx_pagespeed/issues/894) - but it isn't.

**Comment by crowell** [comment]
what is the output of `which cc` and `cc --version`

error go away if you do something like `export CC=gcc` or whatever compiler before running `./configure`?

**Comment by HeikoMamerow** [comment]
`which cc` => `/usr/bin/cc`
`cc --version` => `cc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010`

`export CC=gcc` brings nothing (also tryining other comiloers)

**Comment by crowell** [comment]
is /tmp mounted as noexec? that could cause this issue.

On Fri, Oct 30, 2015 at 1:21 PM, Heiko Mamerow <notifications@github.com>
wrote:

> which cc => /usr/bin/cc
> cc --version => cc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
>
> export CC=gcc brings nothing (also tryining other comiloers)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/1032#issuecomment-152592545>
> .
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by HeikoMamerow** [comment]
I'm not sure if I understand correctly:

`df -h /tmp` => `/dev/vda1`
`mount | column -t` => `/dev/vda1   on  /                                type  ext3        (rw,relatime,data=ordered)`

...This means noexec?

**Comment by crowell** [comment]
you can test this by putting a shellscript in /tmp and trying to execute
it, or what is the output of

`mount | grep tmp`

On Fri, Oct 30, 2015 at 3:03 PM, Heiko Mamerow <notifications@github.com>
wrote:

> I'm not sure if I understand correctly:
>
> df -h /tmp => /dev/vda1
> mount | column -t => /dev/vda1 on / type ext3 (rw,relatime,data=ordered)
>
> ...This means noexec?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/1032#issuecomment-152618951>
> .
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by HeikoMamerow** [comment]
`mount | grep tmp`

    udev on /dev type devtmpfs (rw,nosuid,relatime,size=1008104k,nr_inodes=252026,mode=755)
    tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=204880k,mode=755)
    tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
    tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
    tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
    tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=204880k,mode=700,uid=1000,gid=1000)

**Comment by HeikoMamerow** [comment]
Yes, i can execute a script in /tmp

**Comment by HeikoMamerow** [comment]
I could find help here: http://askubuntu.com/a/347472

Typing: `export PATH="/usr/bin:$PATH"` in the terminal before executing `./configure [...]`

**Comment by ikodev** [comment]
> Typing: export PATH="/usr/bin:$PATH" in the terminal before executing ./configure [...]

Perfect for me too @HeikoMamerow  :) thank you

**Comment by ubo5** [comment]
I also face this problem, however, it comes to be I need to use 'sudo' to have the power to access 'usr/bin/cc'

**Comment by nerrevar** [comment]
For debian you need to install `libc-dev`

**Comment by tenghuanhe** [comment]
> I also face this problem, however, it comes to be I need to use 'sudo' to have the power to access 'usr/bin/cc'

saved my day
