### ISSUE TITLE
Looking for an image filter that is bugging me 

### ISSUE THREAD

**Issue by chromafunk** [pagespeed/ngx_pagespeed#1033]
Hi guys, I set up some image filters to maximize their optimization but there is one bugger filter that is picking images inside an slider and resizing them, lowering their resolution and then stretching them to fit the slider container. What is the filter that does this ?  I am using : 

pagespeed EnableFilters lazyload_images;

pagespeed LazyloadImagesAfterOnload off;

pagespeed EnableFilters move_css_to_head;

pagespeed EnableFilters rewrite_images;

pagespeed EnableFilters recompress_images;

pagespeed EnableFilters convert_jpeg_to_progressive;

#pagespeed EnableFilters recompress_jpeg;

pagespeed EnableFilters recompress_png;

pagespeed EnableFilters strip_image_color_profile;

#pagespeed EnableFilters jpeg_subsampling;

pagespeed EnableFilters convert_png_to_jpeg;

#pagespeed EnableFilters resize_images;

pagespeed EnableFilters rewrite_style_attributes;

thanks !

**Comment by jeffkaufman** [comment]
Can you try:

    pagespeed DisableFilters resize_images;

`rewrite_images` turns on `resize_images` by default, so to turn it off you need to explicitly disable it; commenting it out isn't enough.

**Comment by jmarantz** [comment]
What Jeff said will work.  In your case, however, you might also consider
leaving resize_images on, but disallowing the particular url of the
distorted image, using "ModPagespeedDisallow url_wildcard".

I'm curious to see why it's distorted.  Are there width/height tags on the
'img' that are being overridden by styles in a CSS class or other rule
external to the tag?  If so, it might be correct to remove the overridden
img width/height tags, which should avoid pagespeed overzealously resizing
that image.  That would be the best workaround.

-Josh

**Comment by chromafunk** [comment]
These are images inside an slider. The slider container is set to 700x300 but also to a 100% wide output by the plugin ( to fill the screen ) When I inspect the element, I can see the size of the image in the container ( 700 x 300 ) is being overriden by the width: 100% ? The images themselves are way bigger than 700x300.

**Comment by chromafunk** [comment]
Okay, I have disabled max width on the plugin and changed the values, now they are being resized properly.
