### ISSUE TITLE
Pagespeed caching breaks javascript

### ISSUE THREAD

**Issue by chromafunk** [pagespeed/ngx_pagespeed#1038]
I am on a Wordpress site, some of the javascript files are malfunctioning after caching. I am not sure if its the CSS's not loading correctly or the Javascripts being disrupted. Can you send me some light to see what's up ? Not sure what filter is causing it. I am also using cloudflare. Here are my filters : 

pagespeed on;

# Needs to exist and be writable by nginx.  Use tmpfs for best performance.
pagespeed FileCachePath /tmp/pagespeed;

location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
  add_header "" "";
}
location ~ "^/pagespeed_static/" { }
location ~ "^/ngx_pagespeed_beacon$" { }

#Enable HTTPS

pagespeed FetchHttps enable;

#HTTPS certificates

pagespeed SslCertDirectory /etc/ssl/private;
pagespeed SslCertFile cert_chain.crt;

#pagespeed ModifyCachingHeaders on;

pagespeed RewriteLevel CoreFilters;

#pagespeed RewriteLevel PassThrough;

pagespeed EnableFilters prioritize_critical_css;

pagespeed EnableFilters make_google_analytics_async;

pagespeed EnableFilters move_css_to_head;

pagespeed EnableFilters move_css_above_scripts;

pagespeed EnableFilters outline_javascript;

pagespeed EnableFilters outline_css;

pagespeed EnableFilters defer_javascript;

pagespeed EnableFilters insert_dns_prefetch;

pagespeed EnableFilters combine_css;

pagespeed EnableFilters combine_javascript;

pagespeed EnableFilters convert_meta_tags;

Thanks !

**Comment by chromafunk** [comment]
Seems that the cached version is a version where part of a relevant .js is is still not loaded ?

**Comment by chromafunk** [comment]
I just tested disabling cloudflare first, then deactivating and cleaning the cache of pagespeed and all is back to normal. So cloudflare seems to not be the issue, Is there any way to debug or fine tune wich filter can be causing this ?

**Comment by jmarantz** [comment]
Can you describe in more detail the symptom you observed on your site?
That might help us identify which filter is causing trouble.

Another approach is to start with PassThrough and enable filters one at a
time until the problem appears.  In your case if you feel the problem is
JavaScript related, you can just focus on the three filters with
"javascript" in their name.

Of the filters you've enabled, defer_javascript is inherently the most
risky, so I might start with that one.

-Josh

**Comment by chromafunk** [comment]
For example, at the home page there is a background row with a youtube video on full screen. The video and text does not show up. There is also a cart box made with Jquery that slides down when you hover over it, and it is completely out as if it was locked open on hover. Other Jquery navigational interfaces don't load either.

**Comment by jmarantz** [comment]
Try turning defer_javascript off.

**Comment by chromafunk** [comment]
Actually, just before posting this, defer_javascript was off already.  It was maybe the combine javascript one then ? I will try it out.

**Comment by chromafunk** [comment]
It finally was rocket loader @Cloudflare ... What is rocket loader exactly ? Defer Parsing of JS ?
