### ISSUE TITLE
Getting ERR_CONNECTION_CLOSED with pagespeed enabled

### ISSUE THREAD

**Issue by roman01la** [pagespeed/ngx_pagespeed#1040]
Hello. I'm getting `ERR_CONNECTION_CLOSED` error when doing HTTP POST request to a server with ngx_pagespeed. I've tried `pagespeed RewriteLevel PassThrough;` option which I believe disables all filters, but the issue is still presented. The error is gone when PageSpeed module is turned off.

I'm running `Nginx 1.9.6` with `ngx_pagespeed 1.9.32.10-beta` and `--with-http_v2_module`, and Node server behind it which is getting requests via `proxy_pass`, including the failing one. The website is served over SSL/TLS.

**Comment by morlovich** [comment]
Hi... Is there any chance you are have the same issue as this thread?
https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/flaK-tpDPUk

**Comment by roman01la** [comment]
@morlovich It works, thanks a lot! I'll just put here a short manual, extracted from the thread, for others.

- Go to Nginx source directory and execute `make clean` command.
- Create file `patch.diff` with the following contents
```
diff -r b78018cfaa2f src/http/v2/ngx_http_v2.c
--- a/src/http/v2/ngx_http_v2.c Tue Oct 27 16:47:29 2015 +0300
+++ b/src/http/v2/ngx_http_v2.c Thu Oct 29 17:55:14 2015 +0300
@@ -870,8 +870,6 @@ ngx_http_v2_state_data(ngx_http_v2_conne
         return ngx_http_v2_state_skip_padded(h2c, pos, end);
     }
 
-    stream->in_closed = h2c->state.flags & NGX_HTTP_V2_END_STREAM_FLAG;
-
     h2c->state.stream = stream;
 
     return ngx_http_v2_state_read_data(h2c, pos, end);
@@ -899,6 +897,8 @@ ngx_http_v2_state_read_data(ngx_http_v2_
     }
 
     if (stream->skip_data) {
+        stream->in_closed = h2c->state.flags & NGX_HTTP_V2_END_STREAM_FLAG;
+
         ngx_log_debug1(NGX_LOG_DEBUG_HTTP, h2c->connection->log, 0,
                        "skipping http2 DATA frame, reason: %d",
                        stream->skip_data);
@@ -988,7 +988,9 @@ ngx_http_v2_state_read_data(ngx_http_v2_
                                       ngx_http_v2_state_read_data);
     }
 
-    if (stream->in_closed) {
+    if (h2c->state.flags & NGX_HTTP_V2_END_STREAM_FLAG) {
+        stream->in_closed = 1;
+
         if (r->headers_in.content_length_n < 0) {
             r->headers_in.content_length_n = rb->rest;
 
```

- Execute `patch -p1 < patch.diff` command.
- Build Nginx as usual.
