### ISSUE TITLE
How to Explide domain from operation??

### ISSUE THREAD

**Issue by sirshurf** [pagespeed/ngx_pagespeed#1043]
Let's say I have multiple sub domains an I have this rule:

pagespeed Domain *.example.org;

But the problem is that one of the subdomains I would like to exclude for example images.example.org (this domain is on external CDN, like Amazon)

Is there something like:

pagespeed DomainExlude *.example.org;

?

**Comment by oschaaf** [comment]
There's https://developers.google.com/speed/pagespeed/module/restricting_urls
For example, you could configure:
```
pagespeed Disallow "http://images.example.com*"
```

**Comment by jeffkaufman** [comment]
Note that in general you don't need to set `Domain` manually.  If you're running a site on `www.example.com` then PageSpeed will assume it has permission to modify anything on `www.example.com`.  You only need `Domain` if you want `www.example.com` to be willing to rewrite `a.example.com`, `b.example.com` etc.

**Comment by sirshurf** [comment]
But I am running a website with lots of sub domains and sub-sub domains so this is something that is important to me.

**Comment by jeffkaufman** [comment]
Let's say you want to allow pagespeed to optimize resources on all subdomains of example.org except images.example.org and scripts.example.org.  Then you can use Otto's suggestion:

```
pagespeed Domain *.example.org;
pagespeed Disallow "http://images.example.org*";
pagespeed Disallow "http:/sscripts.example.org*";
```

**Comment by sirshurf** [comment]
But will this work for sub-subdomains?
For example:

I have domains:
en.example.com
a.en.example.com
b.en.example.com
c.en.example.com

And I would like to exclude images.en.example.com

Will this work?

**Comment by jeffkaufman** [comment]
Yes, that should work for subdomans:

```
pagespeed Domain *.example.com;
pagespeed Disallow "http://images.en.example.com*";
```
