### ISSUE TITLE
How does pagespeed decide what memcached server to ask?

### ISSUE THREAD

**Issue by sirshurf** [pagespeed/ngx_pagespeed#1049]
Lets say I have a few memcached servers, by what logic does pagespeed ask them for informaiton?

**Comment by oschaaf** [comment]
PageSpeed selects a memcached server from the configured pool of memcached servers based on a hash of the key involved for the memcached operation it wants to perform. 

The hash algorithm can be found over here:
https://github.com/pagespeed/mod_pagespeed/blob/master/third_party/aprutil/apr_memcache2.c#L634

For the specifics of using that hash to pick a memcached server for the operation about to be performed, see https://github.com/pagespeed/mod_pagespeed/blob/master/third_party/aprutil/apr_memcache2.c#L177

Does that clear it up?

**Comment by sirshurf** [comment]
YES thank you!!!! Very much!!!!!
