### ISSUE TITLE
Mod pagespeed questions

### ISSUE THREAD

**Issue by Redani** [pagespeed/ngx_pagespeed#1052]
Hi,

I have already posted in google forums and didn't get any answer, hope i'll get some info in here:

I've just installed pagespeed and i'm kindda impressed how powerful it is, but i have some questions coz i still need to do so many adjustment to make my website completely compatible with this module!!

1- I had in my htaccess a rule to force trailing slash:
RewriteCond %{REQUEST_URI} /+[^\.]+$
RewriteRule ^(.+[^/])$ %{REQUEST_URI}/ [R=301,L]

but it was returning a 404 error, i had to comment these 2 lines, here is the error: GET https://www.domain.com/mod_pagespeed_beacon/?url=https%3A%2F%2Fwww.domain.com%2Fcategory%2F 404 (Not Found)

1.1- Do you know why??
1.2- what are the beacon for??

2- regarding combining css files, i see this in my element inspector: /inc/A.js,,_slippry,,_slippry.css+css,,_global.css,Mcc.z90cDa6Eiu.css.pagespeed.cf.PgY3-68Bqq.css

2.1- what is A.js is doing here?
2.2- is it normal the 2 "empty commas"?

3- is there a way to minify the html output code using pagespeed?

4- in some images, i see onload="pagespeed.CriticalImages.checkImageForCriticality(this);", what is that for?

Thanks a lot for your help
Cheers

**Comment by jmarantz** [comment]
Hi -- these are all good questions but it makes more sense to ask them in the mod_pagespeed discussion group:  https://groups.google.com/forum/#!forum/mod-pagespeed-discuss

I'm not sure what google forums you posted to, but that's the right one, and I didn't see your questions in there.
