### ISSUE TITLE
NGINX Proxy Cache Example for PS-CapabilityList?

### ISSUE THREAD

**Issue by deweydb** [pagespeed/ngx_pagespeed#1059]
I'm looking to setup separate caches based on capabilities, along the lines of what is described here:
https://developers.google.com/speed/pagespeed/module/downstream-caching#ps-capabilitylist

I found an example for Varnish 4:
https://github.com/pagespeed/ngx_pagespeed/issues/737#issuecomment-53244286

But I am wondering if there are any examples in the wild for nginx proxy cache?

From what i understand i would need to modify my proxy_cache_key with the capabilities, and then also do some regex checks to set the correct header:
proxy_set_header PS-CapabilityList "fully general optimizations only";
vs
proxy_set_header PS-CapabilityList "ll,ii,dj,jw,ws";
vs
proxy_set_header PS-CapabilityList "ll,ii,dj";

Thanks!

**Comment by deweydb** [comment]
My best attempt at converting the varnish vcl to nginx. not sure if this works though:

	
	# Define placeholder PS-CapabilityList header values for large and small
	# screens with no UA dependent optimizations. Note that these placeholder
	# values should not contain any of ll, ii, dj, jw or ws, since these
	# codes will end up representing optimizations to be supported for the
	# request.
	set $default_ps_capability_list_for_large_screens = "LargeScreen.SkipUADependentOptimizations:";
	set $default_ps_capability_list_for_small_screens = "TinyScreen.SkipUADependentOptimizations:";
	
	# As a fallback, the PS-CapabilityList header that is sent to the upstream
	# PageSpeed server should be for a large screen device with no browser
	# specific optimizations.
	set $ps_capability_list = "fully general optimizations only";
	
	# Cache-fragment 1: Desktop User-Agents that support lazyload_images (ll),
	# inline_images (ii) and defer_javascript (dj).
	# Note: Wget is added for testing purposes only.
	if ($http_user_agent ~ "(?i)Chrome/|Firefox/|Gecko|MSIE |Trident|Safari|Wget") {
	  set $ps_capability_list = "ll,ii,dj:";
	}
	# Cache-fragment 2: Desktop User-Agents that support lazyload_images (ll),
	# inline_images (ii), defer_javascript (dj), webp (jw) and lossless_webp
	# (ws).
	if ($http_user_agent ~
	    "(?i)Chrome/[2][3-9]+\.|Chrome/[[3-9][0-9]+\.|Chrome/[0-9]{3,}\.") {
	  set $ps_capability_list = "ll,ii,dj,jw,ws:";
	}
	# Cache-fragment 3: This fragment contains (a) Desktop User-Agents that
	# match fragments 1 or 2 but should not because they represent older
	# versions of certain browsers or bots and (b) Tablet User-Agents that
	# on all browsers and use image compression qualities applicable to large
	# screens. Note that even Tablets that are capable of supporting inline or
	# webp images, e.g. Android 4.1.2, will not get these advanced
	# optimizations.
	if ($http_user_agent ~ "(?i)Firefox/[1-2]\.|MSIE [5-8]\.|bot|Yahoo!|Ruby|RPT-HTTPClient|(Google \(\+https\:\/\/developers\.google\.com\/\+\/web\/snippet\/\))|Android|iPad|TouchPad|Silk-Accelerated|Kindle Fire") {
	  set $ps_capability_list = $default_ps_capability_list_for_large_screens;
	}
	# Cache-fragment 4: Mobiles and small screen Tablets will use image compression
	# qualities applicable to small screens, but all other optimizations will be
	# those that work on all browsers.
	if ($http_user_agent ~ "(?i)Mozilla.*Android.*Mobile*|iPhone|BlackBerry|Opera Mobi|Opera Mini|SymbianOS|UP.Browser|J-PHONE|Profile/MIDP|portalmmm|DoCoMo|Obigo|Galaxy Nexus|GT-I9300|GT-N7100|HTC One|Nexus [4|7|S]|Xoom|XT907") {
	  set $ps_capability_list = $default_ps_capability_list_for_small_screens;
	}
	
	
	
	proxy_set_header PS-CapabilityList $ps_capability_list;
	proxy_cache_key $ps_capability_list$scheme$host$uri$is_args$args;

**Comment by deweydb** [comment]
For anyone else that runs into this, I found some very nice examples from the test file:
https://github.com/pagespeed/ngx_pagespeed/blob/master/test/pagespeed_test.conf.template

**Comment by creativeprogramming** [comment]
very useful @deweydb  thank you
