### ISSUE TITLE
Nginx, Varnish 4 + Pagespeed

### ISSUE THREAD

**Issue by chromafunk** [pagespeed/ngx_pagespeed#1063]
Hi team ! 

I am doing Nginx as an SSL terminator ---> Varnish ----> Nginx + mod_pagespeed.

Varnish works very well with this config, got a good hit rate, the problem is that pagespeed is not being able to fetch from Varnish ? I have the console up and I am getting data but something tells me that pagespeed is not being able to fetch, as a symptom, I have seen a page processed with mod_pagespeed on first hit, but then it goes back to original state ( Varnish cache hit without mod_pagespeed optimizations ) 

Is there a way to see what is going on with pagespeed not being able to communicate with Varnish, or to see if it can communicate but maybe the handshake for the fetch is not happening ?

This is my config for mod_pagespeed : http://pastebin.com/1yGKKGzA

This is the Varnish4 config with pagespeed directives : http://pastebin.com/ibCgb910

It is just a regular wordpress Varnish4 config and it works well.

It would be nice if you can throw some light on this issue ... 

Thank you team !

**Comment by oschaaf** [comment]
@chromafunk To keep things simple I would configure ngx_pagespeed to perform loopback fetches over http in this case. That would mean you would no longer need 
```
pagespeed FetchHttps enable;
```

Instead you'd have something like:

```
pagespeed MapOriginDomain 127.0.0.1 nginx_origin_host;
```
Alternatively, you might be able to use `LoadFromFile` instead of `MapOriginDomain` if all the css/js/images are static files on disk, which would be even better:

https://developers.google.com/speed/pagespeed/module/https_support#load_from_file

You probably also have to make sure your SSL terminator forwards the original protocol, and tell ngx_pagespeed it needs to mind that header:

```
pagespeed RespectXForwardedProto on;
```
See  https://developers.google.com/speed/pagespeed/module/https_support#RespectXForwardedProto

Lastly, I'd recommend changing the rebeaconing-key to something else, as `yoursecretkey` is the default and easy to guess.

**Comment by chromafunk** [comment]
Hi Otto, I just did what you suggested, but I am still not getting optimized pages, this is the typical response header when I get a page : 

accept-ranges:bytes
age:0
cache-control:max-age=900
content-encoding:gzip
content-length:10206
content-type:text/html; charset=UTF-8
date:Wed, 09 Dec 2015 11:32:19 GMT
server:nginx/1.9.7
status:200
vary:Accept-Encoding
x-cache:HIT
x-cache-hits:20
x-page-speed:1.9.32.10-7423

But pages are not coming in optimized, they are Varnish cache non-optimized pages.

**Comment by oschaaf** [comment]
@chromafunk Did you flush Varnish's cache before retrying?

Could you try to temporarily replace this varnish configuration piece:
```
sub vcl_hit {
  # 5% of the time ignore that we got a cache hit and send the request to the
  # backend anyway for instrumentation.

  if (std.random(0, 100) < 5) {
    set req.http.PS-ShouldBeacon = "yoursecretkey";
    return (pass);
  }
}
```

With

```
sub vcl_hit {
  # Let's test without Varnish's caching first.
  return (pass);
}
```

That helps ensuring that optimized html does come through when the html is not being cached by Varnish. If that works, then the problem scope narrows down to why the html isn't being purged from Varnish by ngx_pagespeed. If optimization doesn't work without Varnish caching html either, we need to check some other things.

**Comment by chromafunk** [comment]
Whoops ! You were right. Varnish is now bypassing hits, I only get misses but pagespeed is not delivering optimized pages .... I don't get it though, I made a very simple mod_pagespeed this time for testing purposes only. Seems that it is not working.

**Comment by oschaaf** [comment]
@chromafunk you have:

```
pagespeed MapOriginDomain 127.0.0.1 nginx_origin_host;
```

I wrote `nginx_origin_host` as an example, you need to substitute that with the actual host name you are using - sorry!

**Comment by chromafunk** [comment]
Hi Otto, I understand this has to be the originator ? On this case, the SSL terminator domain ?

I have added changed : 
pagespeed MapOriginDomain "http://127.0.0.1" "https://domain.com";
pagespeed RespectXForwardedProto on;

But still no results

**Comment by oschaaf** [comment]
@chromafunk The "https://domain.com" in your configuration above needs to be equal to the "Host:" header that nginx/ngx_pagespeed will receive for the incoming requests.

**Comment by chromafunk** [comment]
I only changed the domain name on the example to hide it, but I am actually using the real domain, the main domain I am using for this website. Seems that there are hits : 

cache_backend_hits	536	1

but the pages are not being delivered ...

**Comment by oschaaf** [comment]
@chromafunk The docs for setting up Varnish with downstream caching needs to updated, which is tracked in https://github.com/pagespeed/ngx_pagespeed/issues/787

You could try reflect the upcoming vcl modifications in the docs in your configuration, see https://github.com/pagespeed/ngx_pagespeed/issues/787#issuecomment-163403583

It is a bit tricky for me to do them for you in your configuration right now, as your vcl is quite extensive,

**Comment by oschaaf** [comment]
@chromafunk 
I think the proposed changes to the docs would make the downstream caching configuration change like this for your configuration:

```diff
diff --git a/orig.vcl b/tmp.vcl
index 0f5cdf7..35e5ed7 100644
--- a/orig.vcl
+++ b/tmp.vcl
@@ -272,10 +272,6 @@ sub vcl_hash {
 # Handle the HTTP request coming from our backend
 sub vcl_backend_response {
   # Called after the response headers has been successfully retrieved from the backend.
-  if (beresp.http.Content-Type ~ "text/html") {
-     unset beresp.http.Cache-Control;
-     set beresp.http.Cache-Control = "no-cache, max-age=0";
-   }
   # Sometimes, a 301 or 302 redirect formed via Apache's mod_rewrite can mess with the HTTP port that is being passed along.
   # This often happens with simple rewrite rules in a scenario where Varnish runs on :80 and Apache on :8080 on the same box.
   # A redirect can then often redirect the end-user to a URL on :8080, where it should be :80.
@@ -358,8 +354,6 @@ sub vcl_backend_response {
     set beresp.ttl = 120s;
     return (deliver);
         }
-
-  return (deliver);
 }

 sub vcl_hit {
@@ -384,6 +378,12 @@ sub vcl_miss {
 sub vcl_deliver {
   # Called before a cached object is delivered to the client.

+  # Mark HTML as uncacheable for our responses.
+  if (beresp.http.Content-Type ~ "text/html") {
+     unset beresp.http.Cache-Control;
+     set beresp.http.Cache-Control = "no-cache, max-age=0";
+  }
+
   if (obj.hits > 0) { # Add debug header to see if it's a HIT/MISS and the number of hits, disable when not needed
     set resp.http.X-Cache = "HIT";
   } else {
```

Complete file: https://gist.github.com/6d7c812bbf6e79d06e48
Note that this removes the unconditional `return (deliver);` from `vcl_backend_response`, which you should only do if the *only reason* that was in there was for the downstream cache setup.

**Comment by chromafunk** [comment]
Hi Otto, after replacing for changed conf : 

Message from VCC-compiler:
'beresp.http.Content-Type': Not available in method 'vcl_deliver'.
At: ('input' Line 382 Pos 7)
  if (beresp.http.Content-Type ~ "text/html") {
------########################-----------------

**Comment by oschaaf** [comment]
@chromafunk whoops, sorry!

In vcl_deliver, you have `resp` not `beresp`.
So you need to change the line that fails to this:
`if (resp.http.Content-Type ~ "text/html") {`

**Comment by chromafunk** [comment]
Hi Otto, I actually have "beresp.http.Content-Type"

When I change it to be a resp I get this : 

Message from VCC-compiler:
'beresp.http.Cache-Control': cannot be unset in method 'vcl_deliver'.
At: ('input' Line 383 Pos 12)
     unset beresp.http.Cache-Control;
-----------#########################-

Running VCC-compiler failed, exited with 2

**Comment by oschaaf** [comment]
For that line, and the next one, you also need to change `beresp.` to `resp.`

**Comment by chromafunk** [comment]
Hi Otto, after extensive testing, purging cache multiple times, it is still not working correctly. Only one javascript file is being shown on the resulting html but none of the other optimizations are there. When I purge all caches and restart Varnish and Nginx, only the first time I load a page I get them with the optimizations. After that they are not being retrieved anymore.

**Comment by oschaaf** [comment]
@chromafunk can I take a look at the site somewhere?

**Comment by chromafunk** [comment]
Seems that after adding and configuring pagespeed LoadFromFile to the pagespeed conf it works .... why ?

**Comment by oschaaf** [comment]
@chromafunk If configuring `LoadFromFile` solved your problem, then somehow http(s) fetching was failing. Perhaps there was something wrong with the `MapOriginDomain` configuration, it's hard to tell - you'd have to inspect nginx's `error.log` for hints about that.

**Comment by chromafunk** [comment]
Ok Otto, seems that with LoadFromFile is working, so I will close this. Thank you !

**Comment by oschaaf** [comment]
great, closing!
