### ISSUE TITLE
Domain sharding problem !

### ISSUE THREAD

**Issue by chromafunk** [pagespeed/ngx_pagespeed#1073]
Nginx as SSL terminator ---> Varnish ---> Pagespeed ---> Nginx -- CDN

When I do domain sharding : 

```
pagespeed ShardDomain https://domain.com
                      https://1.domain.com,https://2.domain.com,https://3.domain.com,https://4.domain.com;
```
Only image assets ( jpg, png's ) are giving an error, the URL is not rewritten to the cdn sharded domains for them : 

````
https://domain.com/wp-content/uploads/2015/10/elsitar_logo_final_white_small1.png.pagespeed.ce.Af4CacesYu.png Failed to load resource: the server responded with a status of 404 (OK)

```  

Full pagespeed conf here : http://pastebin.com/1KS0fAR4

**Comment by deweydb** [comment]
I was stuck on this for a while as well. make sure your html from upstream contains the exact match.  for example you did:
pagespeed ShardDomain https://domain.com
                      https://1.domain.com,https://2.domain.com,https://3.domain.com,https://4.domain.com;

So, double check your html really has https://domain.com in it, and not say http://domain.com

Also, if re-writing doesn't complete in time (likely for first request that generates your downstream caches) then the sharding doesn't occur in the response passed back to your downstream cache (in this case varnish).  So make sure that you can see varnish is correctly receiving the downstream cache purge requests from pagepseed.  

https://developers.google.com/speed/pagespeed/module/downstream-caching

**Comment by chromafunk** [comment]
The HTML is coming as https as I am doing 

```
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
```

And I am afraid that mod_pagespeed is working correctly, as I have been able to even make real time changes to CSS files while not with CDN config only ( ginx as SSL terminator ---> Varnish ---> Pagespeed ---> Nginx )

**Comment by deweydb** [comment]
Did you test cache purge? is it working? Show me logs of it working.

**Comment by chromafunk** [comment]
Is there a way if the purging works without having to purge all caches manually ?

**Comment by oschaaf** [comment]
@chromafunk re "The problem is, the purge works, but it only does purge once. After getting the files rewritten it does NOT purge the varnish cache anymore."

Could you explain why that is a problem / why you would expect pagespeed to issue a purge request on a html page, after optimization is complete for that html page?

**Comment by deweydb** [comment]
@chromafunk 
See this image: https://developers.google.com/speed/pagespeed/module/images/downstream_caching.png
From this page:
https://developers.google.com/speed/pagespeed/module/downstream-caching

It will make things much more clear.  The fact that it is only doing the purge once is correct.  It should only do one purge after the initial page request, until the time which your downstream cache decides the document is expired.  At which point a new request will pass through to page speed, and you will likely see a second purge occur.

**Comment by deweydb** [comment]
@chromafunk honestly i think i got off track here, it seems like your cache purging is working fine.  I think the reason your sharding isn't working is unrelated to cache purge.

Please try making a request directly to your upstream, by bypassing pagespeed and the cache layers completely (perhaps curl from the server: curl http://127.0.0.1:upstream_ip/ ).  And make sure that the url's included in that HTML are exactly the same as you have in the first parameter of your pagespeed ShardDomain command.

**Comment by chromafunk** [comment]
Hi @deweydb  @oschaaf Thank you for reminding me how the downstream cache works, I really needed to doublecheck how they interact to better understand how they work together. 

The sharding is definitely working, but I think cloudfront is caching a 404 error on the images ( the rest of the files are being cached and retrieved correctly ) So I think this might be an filetype problem. Cloudfront is just caching an image that doesn't exist or is caching a 404 error. Wich is mindboggling, because the images are actually there when disabling the sharding. There is no 404 error when not sharding.

**Comment by deweydb** [comment]
I had some issues with 404s as well, i noticed later that my upstream was trying to get the images via http instead of https, and i wasn't handling images via http correctly.  Make sure your image is available via both http and https.

**Comment by chromafunk** [comment]
Ok, I have fixed it ... it was a really dumb and obvious issue ....

I had configured the LoadFromFile directive without a trailing slash on both the domain name and the path. 

Thank you for your help guys !

**Comment by chromafunk** [comment]
This is really weird ... some pictures and all the assets files are now getting cached at the CDN, but only some of the pictures won't. I am getting this errors now : 

``` 
[ngx_pagespeed 1.9.32.10-7423] http://2.domain.com/wp-includes/js/mediaelement/skipback.png (connecting to:localhost):0:serf_context_run error status=111 (Connection refused)
```

This is my config : 

```
pagespeed MapOriginDomain "http://127.0.0.1" "https://domain.com:443";
pagespeed MapOriginDomain "http://127.0.0.1" "https://domain:8081";
pagespeed LoadFromFile "https://domain.com/" "/var/www/domain.com/wordpress/";
```

I have the ssl terminator listening on 443, Varnihs is at port 8080 and the Nginx virtual host at 8081

**Comment by deweydb** [comment]
SERF issues are covered in the FAQ: https://developers.google.com/speed/pagespeed/module/faq

**Comment by chromafunk** [comment]
I don't have any rewrite rule like the one on the FAQ 

```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ /404 [L,R=301]
```

**Comment by deweydb** [comment]
I'm not really able to help you because i don't know if these are editing mistakes, or real config.

For example, this looks really wrong:

pagespeed MapOriginDomain "http://127.0.0.1" "https://domain:8081";

also this:

[ngx_pagespeed 1.9.32.10-7423] http://2.domain.com/wp-includes/js/mediaelement/skipback.png (connecting to:localhost):0:serf_context_run error status=111 (Connection refused)

**Comment by chromafunk** [comment]
I modified that based on an old thread here, just for testing. But then I have changed it again to : 
Wich is the logical configuration for this scenario: 
```
pagespeed MapOriginDomain "http://127.0.0.1" "https://domain.com";
pagespeed LoadFromFile "https://domain.com/" "/var/www/domain.com/wordpress/";

```

I am not getting any errors in Nginx now.

This is one code snippet of one of the not working images : 

```
<a href="/wp-content/uploads/2015/10/BlackFusionSitar2.png" itemprop=image class="woocommerce-main-image zoom" title="" data-rel=prettyPhoto><img width=210 height=660 src="https://1.domain.com/wp-content/uploads/2015/10/BlackFusionSitar2.png.pagespeed.ce.IAlfsc5fLf.png" class="attachment-shop_single size-shop_single wp-post-image" alt=BlackFusionSitar title=BlackFusionSitar pagespeed_url_hash=3522990726 onload="pagespeed.CriticalImages.checkImageForCriticality(this);"></a>
```

**Comment by deweydb** [comment]
https://1.domain.com/wp-content/uploads/2015/10/BlackFusionSitar2.png.pagespeed.ce.IAlfsc5fLf.png

is not a real url. what is the real url?

**Comment by chromafunk** [comment]
https://1.elsitar.com/wp-content/uploads/2015/10/BlackFusionSitar2.png.pagespeed.ce.IAlfsc5fLf.png

That is one CDN shard.

You will see that the image path has been cached at the CDN, but there is not image.

**Comment by deweydb** [comment]
The fact that this works:
https://1.elsitar.com/wp-content/uploads/2015/10/BlackFusionSitar2.png
and this doesn't:
https://1.elsitar.com/wp-content/uploads/2015/10/BlackFusionSitar2.png.pagespeed.ce.IAlfsc5fLf.png

Means your LoadFromFile is not working correctly.  If you set an error logger for the nginx server block that has:
pagespeed on;
in it.

Then watch that error log while you request:
https://1.elsitar.com/wp-content/uploads/2015/10/BlackFusionSitar2.png.pagespeed.ce.IAlfsc5fLf.png
You will see something about pagespeed not being able to find the original image.

Likely this is because in your upstream source you have something like:
<img src="http://domain.com/wp-content/uploads/2015/10/BlackFusionSitar2.png">

But your load from file directive doesn't match that:
pagespeed LoadFromFile "https://domain.com/" "/var/www/domain.com/wordpress/";

(note http vs https).

Try adding a bunch of loadFromFile directives till you get it right:
pagespeed LoadFromFile "https://127.0.0.1:upstream_port/" "/var/www/domain.com/wordpress/";
pagespeed LoadFromFile "http://127.0.0.1:upstream_port/" "/var/www/domain.com/wordpress/";
pagespeed LoadFromFile "https://domain.com/" "/var/www/domain.com/wordpress/";
pagespeed LoadFromFile "http://domain.com/" "/var/www/domain.com/wordpress/";

etc.

**Comment by deweydb** [comment]
Oh! i just noticed something else as well.  Try taking out that trailing slash.

i.e.:
  do:
    
    pagespeed LoadFromFile "https://domain.com" "/var/www/domain.com/wordpress/";

not:

    pagespeed LoadFromFile "https://domain.com/" "/var/www/domain.com/wordpress/";

**Comment by chromafunk** [comment]
I have tried this four combos and the only one that works is the first uncommented one.

On the commented out combinations pagespeed rewrites the URL's to the CDN, but doesn't rewrite / priocess any of the assets.

```
pagespeed LoadFromFile "https://elsitar.com" "/var/www/elsitar.com/wordpress/";
#pagespeed LoadFromFile "https://127.0.0.1:8081" "/var/www/elsitar.com/wordpress/";
#pagespeed LoadFromFile "http://127.0.0.1:8081" "/var/www/elsitar.com/wordpress/";
#pagespeed LoadFromFile "http://elsitar.com" "/var/www/elsitar.com/wordpress/";

```

**Comment by deweydb** [comment]
Please add this line to the server {} block that contain's: pagespeed on;

    error_log   /some/log/dir/log/ps-error.log info;

Then from terminal do:
curl -v https://elsitar.com/wp-content/uploads/2015/10/BlackFusionSitar2.png.pagespeed.ce.IAlfsc5fLf.png

And show me the output of that command, as well as the output of this command:

cat /some/log/dir/log/ps-error.log

**Comment by chromafunk** [comment]
I was just doing now after the last post, here you have some logs. Says https is not supported, but when I setup LoadFromFile like this : 
```
pagespeed LoadFromFile "https://elsitar.com" "/var/www/elsitar.com/wordpress/";
 ```
It process the files but gives these errors :
```
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-content/themes/modo/assets/js/plugins.js': as https is not supported
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-content/themes/modo/assets/js/main.js': as https is not supported
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-content/plugins/js_composer/assets/js/dist/js_composer_front.min.js': as https is not supported
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-content/plugins/parallax-backgrounds-for-vc/js/min/script-min.js': as https is not supported
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-content/plugins/js_composer/assets/lib/waypoints/waypoints.min.js': as https is not supported
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-includes/js/wp-embed.min.js': as https is not supported
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://3.elsitar.com/_.pagespeed.jo.ucf9GQ4-lM.js': as https is not supported
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-content/plugins/myMail/assets/img/loading.gif': as https is not supported
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-content/plugins/myMail/assets/img/loading.gif': as https is not supported
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-content/plugins/myMail/assets/img/loading_2x.gif': as https is not supported
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-content/uploads/2015/10/Varnish.jpg?id=3621': as https is not supported
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Should purge "https://elsitar.com/" which was served with only 82% rewriting done.
2015/12/15 00:28:04 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Purge url is http://127.0.0.1:8080/
2015/12/15 00:28:05 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Trying to serve rewritten resource in-place: https://elsitar.com/wp-content/uploads/2015/10/Varnish.jpg?id=3621
2015/12/15 00:28:05 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-content/uploads/2015/10/Varnish.jpg?id=3621': as https is not supported
2015/12/15 00:28:05 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Trying to serve rewritten resource in-place: https://elsitar.com/wp-content/uploads/2015/10/HemrajSitarProduct1.png
2015/12/15 00:28:05 [info] 22139#0: [ngx_pagespeed 1.9.32.10-7423] Cannot fetch url 'https://elsitar.com/wp-content/uploads/2015/10/HemrajSitarProduct1.png': as https is not supported
```

When I configure it with HTTP instead, the files are not being processed, only the URL sharding works.

**Comment by deweydb** [comment]
add this:

    pagespeed FetchHttps enable;

**Comment by deweydb** [comment]
Also, your loadFromFile directive is not working properly because it is trying to fetch over the web.

**Comment by deweydb** [comment]
Can you also show me the output of this command (run from the vps)

curl -v http://127.0.0.1:8081

**Comment by chromafunk** [comment]
Ok, now I don't get "https not supported" anymore, and I have changed LoadFromFile to : 
```
pagespeed LoadFromFile "http://127.0.0.1:8081" "/var/www/elsitar.com/wordpress/";
```


curl -v http://127.0.0.1:8081 output : 
```
* Rebuilt URL to: http://127.0.0.1:8081/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 127.0.0.1:8081
> Accept: */*
>
< HTTP/1.1 302 Found
* Server nginx/1.9.7 is not blacklisted
< Server: nginx/1.9.7
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: HHVM/3.10.1
< Location: https://elsitar.com/wp-signup.php?new=127.0.0.1:8081
< Date: Tue, 15 Dec 2015 00:52:23 GMT
< X-Page-Speed: 1.9.32.10-7423
```

Logs : 

```
2015/12/15 00:50:39 [info] 23818#0: [ngx_pagespeed 1.9.32.10-7423] Should purge "https://elsitar.com/shop/" which was served with only 77% rewriting done.
2015/12/15 00:50:39 [info] 23818#0: [ngx_pagespeed 1.9.32.10-7423] Purge url is http://127.0.0.1:8080/shop/
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Trying to serve rewritten resource in-place: https://elsitar.com/
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] HTTPCache key=https://elsitar.com/ fragment=elsitar.com: remembering not-cacheable status for 291 seconds.
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Trying to serve rewritten resource in-place: https://elsitar.com/
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] HTTPCache key=https://elsitar.com/ fragment=elsitar.com: remembering not-cacheable status for 291 seconds.
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] https://elsitar.com/:735:Unexpected close-tag `a', no tags are open
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] https://elsitar.com/:116:Inline element not rewritten because its size is above threshold 4096
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://use.typekit.net/hbt0llb.js'
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] https://elsitar.com/:48:Unrecognized script:'<script type='application/ld+json'></script> 48...48'
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://use.typekit.net/hbt0llb.js'
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://fast.wistia.com/static/iframe-api-v1.js'
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://use.typekit.net/hbt0llb.js'
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://fast.wistia.com/static/iframe-api-v1.js'
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://use.typekit.net/hbt0llb.js'
2015/12/15 00:50:44 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://fast.wistia.com/static/iframe-api-v1.js'
2015/12/15 00:50:46 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Trying to serve rewritten resource in-place: https://elsitar.com/shop/
2015/12/15 00:50:46 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] HTTPCache key=https://elsitar.com/shop/ fragment=elsitar.com: remembering not-cacheable status for 292 seconds.
2015/12/15 00:50:46 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Trying to serve rewritten resource in-place: https://elsitar.com/shop/
2015/12/15 00:50:46 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] HTTPCache key=https://elsitar.com/shop/ fragment=elsitar.com: remembering not-cacheable status for 292 seconds.
2015/12/15 00:50:46 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] https://elsitar.com/shop/:781:Unexpected close-tag `a', no tags are open
2015/12/15 00:50:46 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] https://elsitar.com/shop/:573:Unclosed element `div'
2015/12/15 00:50:46 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] https://elsitar.com/shop/:514:Unclosed element `div'
2015/12/15 00:50:46 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] https://elsitar.com/shop/:96:Inline element not rewritten because its size is above threshold 4096
2015/12/15 00:50:46 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://fast.wistia.com/static/iframe-api-v1.js'
2015/12/15 00:50:46 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://fast.wistia.com/static/iframe-api-v1.js'
2015/12/15 00:50:46 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://fast.wistia.com/static/iframe-api-v1.js'
2015/12/15 00:51:08 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Trying to serve rewritten resource in-place: https://elsitar.com/blog/
2015/12/15 00:51:08 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Could not rewrite resource in-place because URL is not in cache: https://elsitar.com/blog/
2015/12/15 00:51:08 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Trying to serve rewritten resource in-place: https://elsitar.com/blog/
2015/12/15 00:51:08 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Could not rewrite resource in-place because URL is not in cache: https://elsitar.com/blog/
2015/12/15 00:51:08 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] https://elsitar.com/blog/:777:Unexpected close-tag `a', no tags are open
2015/12/15 00:51:08 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] https://elsitar.com/blog/:585:Unclosed element `div'
2015/12/15 00:51:08 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] https://elsitar.com/blog/:526:Unclosed element `div'
2015/12/15 00:51:08 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] https://elsitar.com/blog/:108:Inline element not rewritten because its size is above threshold 4096
2015/12/15 00:51:08 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://fast.wistia.com/static/iframe-api-v1.js'
2015/12/15 00:51:08 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://fast.wistia.com/static/iframe-api-v1.js'
2015/12/15 00:51:08 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] No permission to rewrite 'https://fast.wistia.com/static/iframe-api-v1.js'
2015/12/15 00:51:17 [warn] 23819#0: [ngx_pagespeed 1.9.32.10-7423] elsitarfavicon.png:0:Resource based on https://1.elsitar.com/wp-content/uploads/2015/10/elsitarfavicon.png but cannot access the original
2015/12/15 00:52:23 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Trying to serve rewritten resource in-place: http://127.0.0.1:8081/
2015/12/15 00:52:23 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Could not rewrite resource in-place because URL is not in cache: http://127.0.0.1:8081/
2015/12/15 00:52:23 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Trying to serve rewritten resource in-place: http://127.0.0.1:8081/
2015/12/15 00:52:23 [info] 23819#0: [ngx_pagespeed 1.9.32.10-7423] Could not rewrite resource in-place because URL is not in cache: http://127.0.0.1:8081/
2015/12/15 00:52:23 [info] 23819#0: *151 client 127.0.0.1 closed keepalive connection
2015/12/15 00:54:56 [warn] 23819#0: [ngx_pagespeed 1.9.32.10-7423] BlackFusionSitar2.png:0:Resource based on https://1.elsitar.com/wp-content/uploads/2015/10/BlackFusionSitar2.png but cannot access the original
```

Seems that it can't find the original file .... downstream cache is 8080 and the nginx vhost is 8081

**Comment by deweydb** [comment]
That curl was just a redirect, i want to see actual page source of a page where the upstream is embedding an image. perhaps this page:

curl -v http://127.0.0.1:8081/wp-signup.php?new=127.0.0.1:8081

**Comment by chromafunk** [comment]
At the beggining of the response it says the same as the log say : the hostname was not found at the DNS cache ....  

curl -v http://127.0.0.1:8081/shop/

```
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> GET /shop/ HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 127.0.0.1:8081
> Accept: */*
>
< HTTP/1.1 302 Found
* Server nginx/1.9.7 is not blacklisted
< Server: nginx/1.9.7
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: HHVM/3.10.1
< Location: https://elsitar.com/wp-signup.php?new=127.0.0.1:8081
< Date: Tue, 15 Dec 2015 01:03:42 GMT
< X-Page-Speed: 1.9.32.10-7423
<
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by deweydb** [comment]
Your backend seems to be redirecting all the requests to:
https://elsitar.com/wp-signup.php?new=127.0.0.1:8081
Either find a place that isn't redirected, or turn off that redirect for the moment.

**Comment by chromafunk** [comment]
I am still looking to fix that redirect, it is really weird because I don't have any redirect besides the typical  ( wordpress rewrites and HTTP to HTTPS redirect + www to non-www ) So I don't really understand why the upstream server is redirecting to that URL.

But I just got this from the logs, I know this message was a bug before, but just in case : 

```
2015/12/15 02:15:12 [warn] 26633#0: [ngx_pagespeed 1.9.32.10-7423] You seem to have downstream caching configured on your server. DownstreamCacheRebeaconingKey should also be set for this to work correctly. Refer to https://developers.google.com/speed/pagespeed/module/downstream-caching#beaconing for more details.
```

**Comment by deweydb** [comment]
My bet is some wordpress plugin you have is doing that.  Try disabling all the plugins that might be guilty.

As for the downstream rebeaconing key, that is important but completely not related to this issue, they explain how to do it here:
https://developers.google.com/speed/pagespeed/module/downstream-caching

**Comment by chromafunk** [comment]
My config is right on that sense and the cache is being purged, maybe the bug is still there. I will see what could be creating that redirect and get to you guys tomorrw, thank you for your help.

**Comment by deweydb** [comment]
Also, don't do any redirects at wordpress level! including the one you mentioned that goes from HTTP to HTTPS. do that at your first layer. in your first post you called it "Nginx as SSL terminator".  Just add another server block. this is how i do it:

###########################
#  HTTP->HTTPS REDIRECT   #
###########################
server {
  listen         server.ip.goes.here:80;
  server_name    doimain.com;
  pagespeed off;
  location /{
    return 301 https://domain.com$request_uri;
  }
}

**Comment by chromafunk** [comment]
That is how I made it :+1:

**Comment by deweydb** [comment]
this redirect:
http://127.0.0.1:8081/shop/
to
https://elsitar.com/wp-signup.php?new=127.0.0.1:8081

Really smells like a wordpress plugin to me.

And it seems like it happens for ALL requests to your backend. which would explain why pagespeed can't fetch resources properly.

**Comment by deweydb** [comment]
Here i solved it for you:

https://premium.wpmudev.org/forums/topic/multisite-redirect-problem-with-noblogredirect

**Comment by chromafunk** [comment]
That made it  ! I had NO IDEA of wordpress doing this crap ! Thank you man .... I was going crazy with this. I will bookmark that thing .... I would've took me at least 2 or 3 more days if I was looking for the solution by myself .... thanks ! :+1:
