### ISSUE TITLE
Serve stale from cache instead of unoptimized from incomplete pagespeed.

### ISSUE THREAD

**Issue by deweydb** [pagespeed/ngx_pagespeed#1074]
I have an issue with how downstream caching integrates with pagespeed.
https://developers.google.com/speed/pagespeed/module/images/downstream_caching.png

In this image, on Request 1.  A partially rewritten response is served to the client.  Usually this response does not contain any of my domain sharding, or other optimizations.  Which means every time this happens, static assets are passed via my server instead of my CDN.  

Also, pagespeed tends to add a bit of overhead (which is to be expected, its doing a lot of stuff!)  So every time this happens the response is quite a bit slower than it would have been if pagespeed wasn't there at all, and i was serving directly from the backend.

In my situation, i am only caching pages for about 10 minutes.  And so these unoptimized responses can actually be quite common, especially during times of low traffic.

What i am wondering is, would it be possible to instead serve a stale cache, but also trigger pagespeed rewriting and cache regeneration?  Something like this:
![downstream_caching_with_stale_caches](https://cloud.githubusercontent.com/assets/885167/11764459/1bb45c60-a0e6-11e5-9f66-afc5f6466f70.png)

It would also be nice if I could apply this model to the re-beaconing requests as well, so that upstream pagespeed can still get hits, but we aren't making 5% of the users wait around for something that could be cached.  But maybe what i just said doesn't make any sense, i'm still a bit confused about the whole re-beaconing thing.

Alternatively, is there any way to pre-prime the caches on expiry?  I'm using a cache_key with PS_Capability_List as part of the key.  So the only way i can think of doing this would be to send automated curl requests with varying different header's so that each of the different cache buckets get filled.  But this seems like a bad way to do things, because this would kill the whole beacon system because there is no browser involved in the curl request.

**Comment by oschaaf** [comment]
would you be ok with posting questions to https://groups.google.com/forum/#!forum/ngx-pagespeed-discuss?

re: sharding
Turning on the `rewrite_domains` filter makes domain rewriting happen for unoptimized resources.

re: serve stale html
There's stale-while-revalidate, but nginx doesn't support it.

re: cache priming
You could consider not doing user-agent specific optimizations to make life easier. Its hard to give specific advise without knowing more about your specific situation.

As for the rebeaconing: that's good stuff to ask on ngx-pagespeed-discuss
