### ISSUE TITLE
Could not rewrite resource in-place because URL is not in cache

### ISSUE THREAD

**Issue by MaxLazar** [pagespeed/ngx_pagespeed#1075]
If I activate page speed, page just not responded. In error file I have next lines:

* 2015/12/13 22:59:32 [info] 10789#0: [ngx_pagespeed 1.9.32.11-7553] Trying to serve rewritten resource in-place: https://site.com/
* 2015/12/13 22:59:32 [info] 10789#0: [ngx_pagespeed 1.9.32.11-7553] Cache entry is expired: https://site.com/ (fragment=site.com)
* 2015/12/13 22:59:32 [info] 10789#0: [ngx_pagespeed 1.9.32.11-7553] Could not rewrite resource in-place because URL is not in cache: https://site.com/
* 2015/12/13 22:59:32 [info] 10789#0: [ngx_pagespeed 1.9.32.11-7553] Trying to serve rewritten resource in-place: https://site.com/
* 2015/12/13 22:59:32 [info] 10789#0: [ngx_pagespeed 1.9.32.11-7553] Cache entry is expired: https://site.com/ (fragment=site.com)
* 2015/12/13 22:59:32 [info] 10789#0: [ngx_pagespeed 1.9.32.11-7553] Could not rewrite resource in-place because URL is not in cache: https://site.com/

Thanks for any advice or suggestion!

* CentOS release 6.7 x86_64
* nginx 1.9.9 (same with 1.8.0)
* ngx_pagespeed 1.9.32.11

nginx:
> sudo ./configure --add-module=/root/custom-nginx/nginx-1.9.9/src/http/modules/ngx_pagespeed/ --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-http_v2_module --with-cc-opt='-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'

**Comment by oschaaf** [comment]
With "page just not responded", do you mean that a html request hangs? Could you be hitting this?: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mod-pagespeed-discuss/1EkahAxLg-s/dcC6jEeReVQJ

**Comment by MaxLazar** [comment]
Thanks! Yes, it helps! 
I checked many solutions yesterday but missed this one. 
Thanks again!

**Comment by oschaaf** [comment]
@keesspoelstra
