### ISSUE TITLE
Cannot combine certain .css files cause combined url too long

### ISSUE THREAD

**Issue by chromafunk** [pagespeed/ngx_pagespeed#1077]
I am getting this with a couple of .css files : 

Cannot combine https://domain.com/wp-content/themes/modo/assets/css/skins/gray.css: combined url too long.

Would it be right to increase pagespeed MaxSegmentLength ? 

If so, how do you calculate how much you need to increase ? 

Thanks !

**Comment by oschaaf** [comment]
@chromafunk Could you, in the future, post questions like this to ngx-pagespeed-discuss [1]?

Bumping `MaxSegmentLength` may help, but I'm not sure that  is the best way to go about it, as I don't know why the combined url exceeds the threshold (and why it grows that large).  

Next to capping the maximum segment length, the total url size is also capped (default max size 2083). Exceeding that also generates the same log message.

It's also good to look at why these caps are in place before making any changes, see https://developers.google.com/speed/pagespeed/module/restricting_urls#segment_length

[1] https://groups.google.com/forum/#!forum/ngx-pagespeed-discuss
