### ISSUE TITLE
Some images not being rewritten - question

### ISSUE THREAD

**Issue by chromafunk** [pagespeed/ngx_pagespeed#1078]
If an image won't met the requirements by any filter, therefore not changed, will it get sharded ? 

There are some images that are properly resized and compressed / optimized beforehand and they are not being rewritten, but not sharded either.

**Comment by oschaaf** [comment]
You want to enable the `domain_rewrite` filter.
See https://developers.google.com/speed/pagespeed/module/filter-domain-rewrite

Could you post future questions to https://groups.google.com/forum/#!forum/ngx-pagespeed-discuss ?
