### ISSUE TITLE
inline_google_font_css uses .ttf instead of .woff for IE11 

### ISSUE THREAD

**Issue by chenaren** [pagespeed/ngx_pagespeed#1080]
Hi,

I'm trying to use the inline_google_font_css filter to inline Droid Sans:
```
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Droid+Sans:400">
```

It works as expected in Chrome and Safari. 

However, in IE11 it's inlined to the .ttf type, which for Droid Sans can't be rendered by IE11 for some reason, forcing it to fall back (tested on Windows 7 on VirtualBox and Windows 8.1 on BrowserStack):

```
@font-face {
  font-family: 'Droid Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Droid Sans'), local('DroidSans'), url(http://fonts.gstatic.com/s/droidsans/v6/s-BiyweUPV0v-yRb-cjciC3USBnSvpkopQaUR-2r7iU.ttf) format('truetype');
}
```

When I directly download the css http://fonts.googleapis.com/css?family=Droid+Sans:400 in IE11, it seems to use the .woff format instead, which IE11 can render properly.

```
@font-face {
  font-family: 'Droid Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Droid Sans'), local('DroidSans'), url(http://fonts.gstatic.com/s/droidsans/v6/s-BiyweUPV0v-yRb-cjciBsxEYwM7FgeyaSgU71cLG0.woff) format('woff');
}
```

According to caniuse.com, IE 9-11 only has partial support for .ttf, while fully supporting .woff, so I don't see why inline_google_font_css would pick .ttf here:
http://caniuse.com/#feat=woff 
http://caniuse.com/#feat=ttf

I'm hoping for some way to opt for .woff for IE.

Thanks.

**Comment by jeffkaufman** [comment]
What UA is your browser sending?

(We're actually using Google Fonts' UA-capability detection, but in order to keep our cache from being impractically fragmented by the wide variety of user agents out there we canonicalize the UA first, and we might be making an incorrect "cleanup" with this UA that confuses Google Fonts.)

**Comment by jeffkaufman** [comment]
I thought PageSpeed might be being confused by IE Edge, with the a UA like `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586`, but when it canonicalizes that it leaves in `Edge/13.10586` and Google Fonts sends it woff.

**Comment by jmarantz** [comment]
IE11 and Edge are two different browsers:
http://www.itpro.co.uk/web-browsers/25068/internet-explorer-11-vs-microsoft-edge-does-windows-10s-new-browser-measure-up

But maybe IE11 is sufficiently different from older IE that we need to
classify it differently.

**Comment by jeffkaufman** [comment]
@jmarantz We don't do the classification here; Google Fonts does.  But we do strip down the UA some before sending it to Google Fonts, to improve caching, and it's possible we're stripping something that Fonts considers relevant.

**Comment by chenaren** [comment]
Did some experiment with a User-agent Switcher extension on Chrome:

Browser | UA String | uninlined | inlined
------------ | ------------- | --- | ---
IE7 | Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0) | eot | eot
IE8 | Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0) | eot | eot
IE9 | Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0) | woff | woff
IE10 | Mozilla/5.0 (compatible; WOW64; MSIE 10.0; Windows NT 6.2) | woff | woff
IE11 | Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko | woff | ttf
IE11 | Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko | woff | ttf

It worked as expected for IE 7-10, but seemed to have some trouble with IE 11's UA strings.

**Comment by jeffkaufman** [comment]
Thanks for the debugging!

"Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko" is surprising; I thought IE11 would only include "MSIE" followed by a lower number, like "7".  That is, when IE11 is identifying as IE11 it drops the MSIE token.

I need to check how we canonicalize that string.

**Comment by morlovich** [comment]
Testing with unit test suggest we don't at all, which is very confusing since that ought to work correctly.

**Comment by morlovich** [comment]
Anyway, debugging this at whole system level...

**Comment by morlovich** [comment]
So the cause of the problem is the mod_pagespeed/version string we append to end of User-Agent: while fetching resources. It seems to cause the request to not be identified as IE11 by fonts.g.c 

This is actually used for some loopback-type detection in both mod_pagespeed and ngx_pagespeed (and the ngx native fetcher has the same behavior).

**Comment by jeffkaufman** [comment]
Can we fix fonts.google.com to not consider our token?
