### ISSUE TITLE
ProcessScriptVariables still not working as expected

### ISSUE THREAD

**Issue by nikolay** [pagespeed/ngx_pagespeed#1083]
I reported this long ago so that we don't have to repeat the same thing over and over again and can replace tons of hardcoding with just:
```nginx
pagespeed LoadFromFileMatch "^https?://$http_host/" "$document_root/";
```
But it still yields:
```
"pagespeed" directive "LoadFromFileRuleMatch" Failed to compile script variables in /etc/nginx/nginx.conf
```

**Comment by nikolay** [comment]
Wrong error line! The issue is not the above, but this line:

```nginx
pagespeed LoadFromFileRuleMatch disallow .*;
pagespeed LoadFromFileRuleMatch allow \.(ico|pdf|swf|eot|woff|ttf|otf|css|js|jpeg|jpg|png|gif|svg|svgz|mpg|mpeg|mp3|m4a|m4v|mp4|ogg|wmv|mov|mng|3gpp|3gp|webp|webm|flv|avi|asx|asf)(\?.*)?$;
```
@jeffkaufman @oschaaf It seems there's no way to handle the `$` character. I tried `\$`, I tried `$$`, but they don't work. Any suggestion on how to handle this?

**Comment by nikolay** [comment]
Escape via `$ps_dollar`, duh. Sorry!

**Comment by oschaaf** [comment]
@nikolay there was also https://github.com/pagespeed/ngx_pagespeed/issues/1025, can we close that one too? If not, do you have more reproduction information for that one?
