### ISSUE TITLE
png to webp (not-lossless) option ?

### ISSUE THREAD

**Issue by centminmod** [pagespeed/ngx_pagespeed#1090]
ngx_pagespeed can convert png to webp lossless. But is there an option to save to webp not-lossless and specify a quality % ?

I did some tests at https://community.centminmod.com/posts/23323/ and ngx_pagespeed auto converts png to webp lossless and ends up at 424KB size same as if i used irfanview app to manually save to webp lossless. But if i use irfanview to save as webp with quality = 75%, the webp image is reduced to between 83-88KB and I can't perceive a difference between it and 424KB webp lossless version.

So would be nice if ngx_pagespeed had a filter for same png to webp that is not lossless :)

cheers

George

**Comment by oschaaf** [comment]
From the docs for `convert_jpeg_to_webp`: https://developers.google.com/speed/pagespeed/module/filter-image-optimize#convert_jpeg_to_webp

"With this option enabled, a gif or png image can also be converted to a lossily-encoded webp if the configuration allows it to be converted to a jpeg"

Which works with `WebpRecompressionQuality`: https://developers.google.com/speed/pagespeed/module/filter-image-optimize#WebpRecompressionQuality

Does that look like what you want?

**Comment by centminmod** [comment]
@oschaaf cheers totally overlooked that was a separate option !
