### ISSUE TITLE
CDATA wrongly stripped by rewrite_javascript

### ISSUE THREAD

**Issue by RealRancor** [pagespeed/ngx_pagespeed#1094]
ngx_pagespeed version: X-Page-Speed: 1.9.32.4-7251

Hi,

it seems that ngx_pagespeed with an enabled rewrite_javascript filter is stripping the CDATA tag/comment of the following inline javascript:

```
<script type="text/javascript"><!-- // --><![CDATA[
function pmx_setCookie(sName,sValue){return pmxXMLrequest("action=xmlhttp;pmxcook=setcookie;xml","var="+sName+"&val="+encodeURIComponent(sValue)+"&a65e4a505f=7e8f1972a17ea5245816dbc6a58f2158");}
function pmx_getCookie(sName){return pmxXMLrequest("action=xmlhttp;pmxcook=getcookie;xml;name="+sName);}// ]]></script>
```

used by https://github.com/PortaMx/PortaMx-1.54-ecl/blob/98c617c4214b6a7f46eb1abacac8f191f74d5ac6/Sources/PortaMx/LoadData.php#L2818-L2822

to the following:

```
<script type="text/javascript">function pmx_setCookie(sName,sValue){return pmxXMLrequest("action=xmlhttp;pmxcook=setcookie;xml","var="+sName+"&val="+encodeURIComponent(sValue)+"&a65e4a505f=7e8f1972a17ea5245816dbc6a58f2158");}
function pmx_getCookie(sName){return pmxXMLrequest("action=xmlhttp;pmxcook=getcookie;xml;name="+sName);}</script>
```

This makes the the page invalid on https://validator.w3.org/. Are there any chances to ignore such ``<!-- // --><![CDATA[ // ]]>`` comments/tags?

**Comment by oschaaf** [comment]
After looking at the code, it looks like the javascript filter is actually trying to conserve the `CDATA` declarations in the minification process, but only when the html is determined to be served as xhtml (or more precisely, when it is not *not* determined to be xhtml).

Is your html served as xhtml? If it is, could you paste the `Content-Type` header that is served with the xhtml here?

**Comment by RealRancor** [comment]
Thanks for your reply. My pages using the following doctype:

```<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">```

and validates as "Doctype: 	XHTML 1.0 Transitional" at https://validator.w3.org (if not using the rewrite_javascript filter).

The content type served by nginx when requesting the page containing that javascript is:

```Content-Type: text/html; charset=UTF-8```

**Comment by oschaaf** [comment]
Older browers (IE6/7) won't take doing this well, but I think that if you would serve your html with `Content-Type: application/xhtml+xml`, the `CDATA` sections would be preserved.

**Comment by RealRancor** [comment]
Hi,

thanks for your reply and sorry for the long delay.

Up to now i wasn't able to make my nginx/php-fpm setup to serve the .php files with the content type application/xhtml+xml. Have used various stuff like adding the php file to mime.types of nginx, adding a add_header or default_type statement to the php block of nginx or modifying the default_mimetype of the fpm php.ini without any luck.

But changing this looks to me more like a workaround. Is there anything what could be configured from ngx_pagespeed side to avoid stripping this CDATA away?

**Comment by jeffkaufman** [comment]
My main question here is, why are you trying to serve xhtml?  When started work on PageSpeed 5+ years ago we included handling for xhtml, but even at that time it was very rarely used.  At this point it's widely seen as something that didn't work out, and there's very little reason to serve it.  Html5 is highly backwards compatible, and is a spec that matches what browsers actually do.

**Comment by RealRancor** [comment]
Hi,

thanks for your reply and the pointer. That is something which is directly done by the Simple Machines Forums 2.0 which is using that XHTML doctype. But it seems they have changed that for their upcoming 2.1 release:

https://github.com/SimpleMachines/SMF2.1/pull/319/files

If this is just the issue here that they are serving a wrong / outdated / uncommon doctype i'm closing this for now and hope they will release 2.1 soon.
