### ISSUE TITLE
Nginx cannot find module when building inside Docker container

### ISSUE THREAD

**Issue by BenHall** [pagespeed/ngx_pagespeed#1106]
I've pushed the changes to https://github.com/benhall/docker-nginx-sticky

Reproduce:
`make`

This will run all the steps required, for example downloading and exacting the module into the root.

The build fails. The ./configure references _--add-module=/ngx_pagespeed-release-${NPS_VERSION}-beta/_ and the build fails because with _--add-module=/ngx_pagespeed-release-1.10.33.4-beta/: not found_

What am I doing wrong? Do I need to reference a different directory?

**Comment by sandys** [comment]
here's a build script that works - https://gist.github.com/redcarpetup/e52cbddb907effe70bd0

**Comment by jeffkaufman** [comment]
It looks to me like `--add-module=/ngx_pagespeed-release` should have been `--add-module=~/ngx_pagespeed-release`?

**Comment by BenHall** [comment]
It was me not reading the script correctly as I had && in the wrong place :(

https://github.com/BenHall/docker-nginx-sticky/commit/919a795b23e053c0950fabb5ea2538496259c90b

Image now correctly building, will push into production later today. Thanks for your replies
