### ISSUE TITLE
Force hash change

### ISSUE THREAD

**Issue by JoyceBabu** [pagespeed/ngx_pagespeed#1108]
Is it possible to force pagespeed to regenerate the unique hash for all urls? I have added CORS headers to all JS files. Since the file content hasn't changed, pagespeed is still serving the files using the same url. For a returning visitor, the JS files are already in their browser cache without the CORS headers.

**Comment by jeffkaufman** [comment]
You could turn on url signing: https://developers.google.com/speed/pagespeed/module/restricting_urls#url_signatures
