### ISSUE TITLE
no 32-bit with 1.10.33.4

### ISSUE THREAD

**Issue by sbagmeijer** [pagespeed/ngx_pagespeed#1109]
Not sure if I missed an announcement if I did then I apologise however it look like version 1.10.33.4 cannot be compiled with a 32-bit machine is this a mistake?

It seems when you download psol it no longer has the 32-bit files, in version 1.10.33-2 they are still available.

**Comment by jeffkaufman** [comment]
Checking now, you're right: there's a problem with the copy of 1.10.33.4.tar.gz that's on dl.google.com.  Looking into it now.

**Comment by jeffkaufman** [comment]
Can you check whether https://www.modpagespeed.com/1.10.33.4.tar.gz works for you?

**Comment by sbagmeijer** [comment]
> Can you check whether https://www.modpagespeed.com/1.10.33.4.tar.gz works for you?

Yes that one works fine!

**Comment by kyl191** [comment]
The modpagespeed.com link works for me as well. Will this be the default going forward?

**Comment by jeffkaufman** [comment]
I've fixed https://dl.google.com/dl/page-speed/psol/1.10.33.4.tar.gz to include the 32-bit binaries as well.

(The modpagespeed.com link was just for sending out the draft binary to check I hadn't missed anything in building it this time.)
