### ISSUE TITLE
nginx 1.9.10 hangs on requests with pagespeed and fancyindex

### ISSUE THREAD

**Issue by davidjb** [pagespeed/ngx_pagespeed#1111]
I have compiled Nginx 1.9.10, Pagespeed 1.10.33.4-beta, and ngx-fancyindex (latest tag, v0.3.6) on Centos 6.7 x64 and it compiles fine.  Nginx hangs when requests are made to the location block below:

~~~
server {
    listen 80 default_server;
    root /path/to/html;
    index index.html;
    pagespeed on;
    pagespeed FileCachePath /var/cache/nginx/ngx_pagespeed_cache;
    pagespeed EnableFilters collapse_whitespace;
    location / { fancyindex on; }
}
~~~

Requests work fine if I change the `fancyindex` directive to the in-built `autoindex` (the Pagespeed filters are correctly applied to `autoindex`).  Changing pagespeed filters appears to make no difference.

No errors are produced in the logs, but I'm not running the server in debug mode.

**Comment by centminmod** [comment]
hmm wonder if same problem i have here https://github.com/pagespeed/ngx_pagespeed/issues/1082 i also use fancy index as well

**Comment by davidjb** [comment]
@centminmod sounded somewhat similar, but a difference looks to be that my requests fail only to a location block with the `fancyindex` handler.  All other handlers (eg proxy, etc) continue to work fine even if a request to `fancyindex` has hung.

**Comment by oschaaf** [comment]
I suspect this may be something with fancyindex. I made a pull request to propose a fix https://github.com/aperezdc/ngx-fancyindex/pull/37

**Comment by davidjb** [comment]
Awesome, thanks! Hopefully they'll merge that over there.

**Comment by oschaaf** [comment]
@davidjb Could you try confirming the fix?
For easy patching, here's a diff:
https://patch-diff.githubusercontent.com/raw/aperezdc/ngx-fancyindex/pull/37.diff

**Comment by oschaaf** [comment]
Change was merged in fancyindex - thanks @aperezdc !

**Comment by aperezdc** [comment]
You're welcome! Thanks for the patch @oschaaf. As a matter of fact, I should go over the code and compare it to a modern `autoindex`, and see if there are more changes that should be imported into `fancyindex`. I have files aperezdc/ngx-fancyindex#38 precisely to track that task.

**Comment by jeffkaufman** [comment]
Looks like this is now fixed on the fancyindex end.

**Comment by davidjb** [comment]
@oschaaf Tested and works on Nginx 1.9.10 (and on 1.9.11 with ngx_pagespeed master), thanks @aperezdc and @oschaaf.
