### ISSUE TITLE
Support building ngx_pagespeed as a dynamic module

### ISSUE THREAD

**Issue by oschaaf** [pagespeed/ngx_pagespeed#1116]
As of 1.9.11, nginx supports loading dynamic modules:
https://www.nginx.com/resources/wiki/extending/converting/#loading-a-dynamic-module

**Comment by olavxxx** [comment]
Also interested in this feature, compiling ngx_pagespeed was all but a breeze for 1.9.10

**Comment by shawncarr** [comment]
@crowell is there any documentation anywhere at this point to show how to build and use ngx_pagespeed as a dynamic module?

**Comment by oschaaf** [comment]
@shawncarr there's an issue for tracking documentation status https://github.com/pagespeed/ngx_pagespeed/issues/1135, I left a short comment there which explains how to build ngx_pagespeed as a dynamic module.
