### ISSUE TITLE
ERR_EMPTY_RESPONSE on http but not https

### ISSUE THREAD

**Issue by JayXon** [pagespeed/ngx_pagespeed#1118]
`http://.../?ModPagespeed=off` always works
`http://.../?ModPagespeed=on&ModPagespeedFilters=` only works the first time, always ERR_EMPTY_RESPONSE afterwards
`https://.../?ModPagespeed=on&ModPagespeedFilters=` always works

```
2016/02/14 05:37:31 [alert] 23676#0: [ngx_pagespeed 1.10.33.4-0] [0214/053731:FATAL:ngx_base_fetch.cc(144)] Check failed: r->count > 0. r->count: 0
nginx: worker process() [0x81551bb]
nginx: worker process() [0x80e7937]
nginx: worker process() [0x8151d9c]
nginx: worker process() [0x80754d0]
nginx: worker process() [0x8074d80]
nginx: worker process() [0x80ed71f]
nginx: worker process() [0x8106d46]
nginx: worker process() [0x80f0d98]
nginx: worker process() [0x8052829]
nginx: worker process() [0x8055288]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_start_main+0xf3) [0xb7143a63]
nginx: worker process() [0x80558d5]
2016/02/14 05:37:31 [alert] 19979#0: worker process 23676 exited on signal 6
```

```
nginx version: nginx/1.8.1
built by gcc 4.9.2 (Debian 4.9.2-10) 
built with OpenSSL 1.0.1k 8 Jan 2015
TLS SNI support enabled
configure arguments: --add-module=/root/ngx_pagespeed-release-1.10.33.4-beta --with-http_ssl_module --with-http_spdy_module --with-ipv6 --with-http_gzip_static_module --with-ld-opt=-flto --with-cc-opt='-O3 -flto -march=native'
```

**Comment by oschaaf** [comment]
This looks like this issue: https://github.com/pagespeed/ngx_pagespeed/issues/1096
Which was resolved via https://github.com/pagespeed/ngx_pagespeed/pull/1098
Cherry-picking https://github.com/pagespeed/ngx_pagespeed/commit/b88e067c6d8173112d586fcdfe8d664c1226a00 should fix the problem

**Comment by oschaaf** [comment]
I double checked, but the fix is this is included in the upcoming release, so I am Closing this issue. Feel free to re-open if you still have a problem after patching in the commit I mentioned.
