### ISSUE TITLE
https://dl.google.com/dl/page-speed/psol/1.10.33.5.tar.gz not exist

### ISSUE THREAD

**Issue by daxthink** [pagespeed/ngx_pagespeed#1119]
I see the .5 release, but 
https://dl.google.com/dl/page-speed/psol/1.10.33.5.tar.gz not exist

**Comment by oschaaf** [comment]
Releases are announced at https://groups.google.com/forum/m/?fromgroups#!forum/ngx-pagespeed-announce , you are looking at a work in progress for the upcoming release. You can subscribe to that list to get notified about ngx_pagespeed releases.
