### ISSUE TITLE
Redirect URLs adding ",%20https://www.example.com"

### ISSUE THREAD

**Issue by batmike** [pagespeed/ngx_pagespeed#1123]
With all pagespeed directives commented out, the issue does not occur but with only this one line:

`pagespeed FileCachePath /var/cache/ngx_pagespeed;`

the resulting redirected URLs on any sites run through the nginx instance end up coming out as https://www.example.com,%20https://www.example.com and some come out with that repeated multiple times over and over. This seems to only happen within Safari as I tried the same things in Chrome and Firefox and didn't find the problem there.

I'm testing this using CentOS 6.7, nginx 1.9.10 and pagespeed 1.10.33.4.

Any thoughts on this would be very helpful. Thanks!

**Comment by oschaaf** [comment]
This sounds like https://github.com/pagespeed/ngx_pagespeed/issues/1099
Should be fixed in 1.10.33.5 which came out today.
Closing this issue, but please re-open if you still see the problem with the latest release.

**Comment by batmike** [comment]
I can confirm that fixed it. Updated to 1.10.33.5 and redirects are working as expected in Safari.

Thanks!
