### ISSUE TITLE
proxy_cache giving 404 on rewritten resources

### ISSUE THREAD

**Issue by centminmod** [pagespeed/ngx_pagespeed#1124]
Using 1.10.33.5 dynamic module and nginx 1.9.11 with proxy cache downstream configured https://developers.google.com/speed/pagespeed/module/downstream-caching for both

* http://centminmod.com port 80
* https://centminmod.com port 443

I am only getting sometimes 404 errors on rewritten pagespeed resources over centminmod.com port 443 but not port 80

From https://developers.google.com/speed/pagespeed/module/downstream-caching it gives example of purging on port 80, but what about if i purge on both port 80 and 443 for the same site ?

> For example, if you're running a cache on port 80 that reverse proxies to your site on port 8080, then you'd need to tell PageSpeed to send its PURGE requests to port 80:

I have this set in pagespeed.conf

`pagespeed DownstreamCachePurgeLocationPrefix http://localhost:80;`

So i have to have separate `DownstreamCacheRebeaconingKey` key values for 80 and 443 port sites ?

should i place `DownstreamCachePurgeLocationPrefix` in each server context instead of pagespeed.conf

so in port 80 site

`pagespeed DownstreamCachePurgeLocationPrefix http://localhost:80;`

and port 443

`pagespeed DownstreamCachePurgeLocationPrefix http://localhost:443;`

> nginx -V
> nginx version: nginx/1.9.11
> built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
> built with OpenSSL 1.0.2f 28 Jan 2016
> TLS SNI support enabled
> configure arguments: --with-ld-opt='-ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -mtune=native -mfpmath=sse -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --with-openssl-opt=enable-tlsext --add-module=../nginx-module-vts --with-libatomic --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_gzip_static_module --add-module=../ngx_brotli --add-dynamic-module=../ngx_pagespeed-release-1.10.33.5-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_realip_module --add-module=../nginx-accesskey-2.0.3 --add-module=../nginx-http-concat-master --add-module=../ngx-fancyindex-0.3.6 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.2.19 --add-module=../set-misc-nginx-module-0.29 --add-module=../echo-nginx-module-0.58 --add-module=../redis2-nginx-module-0.12 --add-module=../ngx_http_redis-0.3.7 --add-module=../lua-nginx-module-0.10.1rc1 --add-module=../lua-upstream-nginx-module-0.04 --add-module=../lua-upstream-cache-nginx-module-0.1.1 --add-module=../nginx_upstream_check_module-0.3.0 --add-module=../openresty-memc-nginx-module-4f6f78f --add-module=../openresty-srcache-nginx-module-ffa9ab7 --add-module=../headers-more-nginx-module-0.29 --with-pcre=../pcre-8.38 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=../openssl-1.0.2f

I also have set

```
pagespeed LoadFromFile "http://centminmod.com" "/path/to/web/root";
pagespeed LoadFromFile "https://centminmod.com" "/path/to/web/root";
```

FYI, if i disable https LoadFromFile, no page css/js get rewritten at all

**Comment by centminmod** [comment]
Also if centminmod.com is on a cluster of servers behind route53 geo dns, would i need to set `proxy_cache_purge` to all the ips for all servers in the cluster ?

`proxy_cache_purge PURGE from 127.0.0.1 ip2 ip3 ip4;`

from

>       # What servers should we accept PURGE requests from?  If PageSpeed isn't
>       # running on the same server as your cache, list the IP(s) of the
>       # PageSpeed machine(s) here.
>       #
>       # This requires rebuilding with the ngx_cache_purge module:
>       #   https://github.com/FRiCKLE/ngx_cache_purge
>       proxy_cache_purge PURGE from 127.0.0.1;

**Comment by oschaaf** [comment]
@centminmod 

Re: DownstreamCacheRebeaconingKey
I think you can share the same key for http and https.

Re: DownstreamCachePurgeLocationPrefix
Looks good to me, but I'm wondering what you are precisely doing for https. Are you de-encryping at the proxy and re-encryping when you go to the backend?

Re: LoadFromFile
If optimization doesn't work without LoadFromFile, pagespeed's http fetching is failing. You may have to use MapOriginDomain to point ngx_pagespeed to a server that it can use to fetch css/js from, or look at setting up https support. See these two documentation entries:
https://developers.google.com/speed/pagespeed/module/domains#mapping_origin
https://developers.google.com/speed/pagespeed/module/https_support

Re: proxy_cache_purge
If I understand correctly, each node in the cluster consists of a pagespeed-enabled webserver plus a proxy cache for the downstream caching feature. In that case, I think you need to set up proxy_cache_purge on each server{} block for each proxy cache to (only) accept purges from the pagespeed-enabled webserver that is running behind it. I can't see why purges would need to go across nodes in the cluster, but perhaps I am misinterpreting something?

Closing this issue - if you have any more questions, could we we take them to [ngx-pagespeed-discuss] (https://groups.google.com/forum/#!forum/ngx-pagespeed-discuss)?
