### ISSUE TITLE
Pagespeed not rewriting some resources

### ISSUE THREAD

**Issue by JoyceBabu** [pagespeed/ngx_pagespeed#1126]
PageSpeed is not rewriting some resources on my site. If you visit

`http://m.prokerala.com/downloads/ringtones/download.php?id=501`

`http://s0.nxstatic.com/theme/electron/assets/js/common.min.js?_=20160220` is not rewritten. Whereas `http://s0.nxstatic.com/downloads/ringtones/assets/js/electron.min.js?_=20160220` is rewritten correctly.

I have seen this happen with other files too.

**Comment by oschaaf** [comment]
Could you turn on the debug filter?:

```
pagespeed EnableFilters debug;
```

That will make PageSpeed write debug comments about it's decisions around optimization, hopefully it will emit useful diagnostic information in your case.

**Comment by JoyceBabu** [comment]
Thank you oschaaf. I enabled the filter on my local machine using docker, and got the following message

> Script http://www.prokerala.doc/theme/electron/assets/js/common.min.js is unsafe to replace

**Comment by oschaaf** [comment]
I think that is because it contains introspective javascript.
See https://developers.google.com/speed/pagespeed/module/restricting_urls#aris 

Closing this issue, but feel free to re-open if you think there still is a problem.

**Comment by JoyceBabu** [comment]
I have extend_cache enabled. So shouldn't the file be rewritten even if PS is unable to optimize the file?

**Comment by JoyceBabu** [comment]
Thank you @oschaaf. There was a `document.getElementsByTagName("script")` call in the above mentioned script which was triggering the introspective javascript test.
