### ISSUE TITLE
Chrome Canary 50 Refused to execute script when downstream proxy cache used

### ISSUE THREAD

**Issue by centminmod** [pagespeed/ngx_pagespeed#1127]
With nginx 1.9.11 and 1.10.33.5 dynamic module compiled on CentOS 6.7 and 7.2 and proxy_cache downstream caching configured I get the following errors for https://centminmod.com site in Chrome 50 Canary console with broken js and css but only if i use a upstream with load balanced backends and not an upstream with a single backend

```
upstream lb-backend {
server ip1:444;
server ip2:444;
}
```

```
(index):1 Refused to execute script from 'https://centminmod.com/js/jquery.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'https://centminmod.com/js/bootstrap.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'https://centminmod.com/js/hover-dropdown-menu.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'https://centminmod.com/js/jquery.hover-dropdown-menu-addon.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'https://centminmod.com/js/jquery.easing.1.3.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'https://centminmod.com/js/bootstrapValidator.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

if i use single backend I don't get these console messages ?

```
upstream backend {
server ip1:444;
}

**Comment by oschaaf** [comment]
If you query both backends directly for `/js/jquery.min.js`, does one of them respond with `Content-Type: text/html` in the response headers?

**Comment by centminmod** [comment]
strangely they return back the correct MIME type so no idea

in Chrome 50 Canary it seems to work now though for some reason ? is ` strict MIME type checking is enabled` a new Canary feature ?

```
cache-control:max-age=2592000
content-encoding:br
content-type:application/javascript; charset=utf-8
date:Mon, 22 Feb 2016 11:25:48 GMT
etag:W/"55a3a41f-14915"
expires:Wed, 23 Mar 2016 11:25:33 GMT
last-modified:Mon, 13 Jul 2015 11:42:23 GMT
link:<http://centminmod.com/js/jquery.min.js>; rel="canonical"
ps-capabilitylist:ll,ii,dj,jw,ws:
server:nginx centminmod
status:200
x-pcache:HIT
x-powered-by:centminmod
```

**Comment by oschaaf** [comment]
I don't think mime type checking is new. 
We should look at why the .js files are serving `content-type: text/html` sometimes. The desired response would have `content-type:application/javascript; charset=utf-8`.
Are you still observing this behavior? Does the problem go away if you take out `ngx_pagespeed`?

**Comment by centminmod** [comment]
i'm not seeing it anymore, it was that one time only but i have switched back to single backup upstream now. I haven't retried multiple backup load balanced upstreams yet as it could be related to my memcached setup https://github.com/pagespeed/ngx_pagespeed/issues/1128 ?

maybe ngx_pagespeed could have a separate persistent log file it can configure to record the mime type and headers served via pagspeed optimised resources for troubleshooting. Could be a full log or sample log ?

**Comment by oschaaf** [comment]
@centminmod 
Assuming this is resolved and closing the issue. But please re-open this if you think there still is a problem with ngx_pagespeed and using an upstream with multiple (load-balanced) backends.
