### ISSUE TITLE
CSS, JS not combing & Images are not rewriting

### ISSUE THREAD

**Issue by isaumya** [pagespeed/ngx_pagespeed#1129]
Hi,
I'm very new to this pagespeed game and I do admit that I do not have much experience with it. I've recently moved my site to a nginx vps and asked my host to install page-speed in it, so he did. But even after reading most google pagespeed docs, and adding various filters in my `pagespeed.conf`, when I look at the source code of my site, I do see some pagespeed features are working but most things are not working, like css/js combination, image rewrite, webp rewrite etc. though I have all the proper filters set on my config.
I have posted this issue to my host but I don't think they have much intensive pagespeed knowledge either. That is why you guys are my last beacon of hope. I know it is annoying to help out a noob, but please do if you can. Also I may not have much server config knowledge but I'm not a total noob that I can vouch for.

Anyways here is my website link: https://www.isaumya.com (running on wordpress)
Here is the pagespeed admin console link: http://vps.isaumya.com/pagespeed_admin/

Here is my `pagespeed.conf` settings:

````
pagespeed on;

#######################################################
# File cache settings
######################################
# needs to exist and be writable by nginx

 pagespeed FileCacheSizeKb          102400;
 pagespeed FileCacheCleanIntervalMs 3600000;
 pagespeed FileCacheInodeLimit      500000;

######################################################
# Mapping domain for HTTPS & Enabling HTTPS Fetch
######################################################

 #pagespeed MapOriginDomain "http://208.117.38.82" "https://www.isaumya.com";

#######################################################
# By default, ngx_pagespeed adds an X-PageSpeed header with a value of the version of
# ngx_pagespeed being used. This directive lets you specify the value to use instead:
# pagespeed XHeaderValue "ngx_pagespeed";

#######################################################
# let's speed up PageSpeed by storing it in the super duper fast memcached
# Ensure Memcached server installed http://centminmod.com/memcached.html
# default install for centmin mod is on port 11211, so localhost:11211 is correct
# uncomment - remove hash # in front of below 2 lines to enable
# timeout set at 100 milliseconds
#  pagespeed MemcachedThreads 1;
#  pagespeed MemcachedServers "localhost:11211";
#  pagespeed MemcachedTimeoutUs 100000;

#######################################################
## https://developers.google.com/speed/pagespeed/module/admin#virtual-hosts-and-stats
######################################
# pagespeed UsePerVhostStatistics on;

#######################################################
## 1.7.30.1 beta defaults
######################################
pagespeed PreserveUrlRelativity on;
pagespeed MaxCombinedCssBytes -1;
pagespeed ImageResolutionLimitBytes 16777216;
# pagespeed EnableFilters inline_google_font_css;

#######################################################
## 1.6.29.3 beta defaults
######################################
pagespeed AvoidRenamingIntrospectiveJavascript on;
pagespeed ImageInlineMaxBytes 3072;
pagespeed CssImageInlineMaxBytes 0;
pagespeed MaxInlinedPreviewImagesIndex -1;
pagespeed MinImageSizeLowResolutionBytes 3072;

#######################################################
## ngx_pagespeed filters settings below ##
######################################

  # show half the users an optimized site, half the regular site
  # change UA-XXXXXXXXXX-1 to your GA unique id
  # uncomment - remove hash # in front of below 5 lines to enable
#  pagespeed RunExperiment on;
#  pagespeed AnalyticsID UA-XXXXXXXXXX-1;
#  pagespeed ExperimentVariable 1;
#  pagespeed ExperimentSpec "id=1;percent=50;level=CoreFilters;enabled=collapse_whitespace,remove_comments;";
#  pagespeed ExperimentSpec "id=2;percent=50";

  # Filter settings
  # filters outlined at http://ngxpagespeed.com/ngx_pagespeed_example/
  pagespeed RewriteLevel CoreFilters;
  pagespeed EnableFilters collapse_whitespace,remove_comments;

  # make_google_analytics_async
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-make-google-analytics-async
  pagespeed EnableFilters make_google_analytics_async;

  # make_show_ads_async
  # https://developers.google.com/speed/pagespeed/module/filter-make-show-ads-async
  pagespeed EnableFilters make_show_ads_async;

  # responsive_images, responsive_images_zoom
  # https://developers.google.com/speed/pagespeed/module/filter-image-responsive
  pagespeed EnableFilters responsive_images;
  pagespeed EnableFilters responsive_images_zoom;

  # convert_to_webp_animated
  # https://developers.google.com/speed/pagespeed/module/filter-image-optimize#convert_to_webp_animated
  pagespeed EnableFilters convert_to_webp_animated;

  # inline_google_font_css
  # https://developers.google.com/speed/pagespeed/module/filter-css-inline-google-fonts
  pagespeed EnableFilters inline_google_font_css;
  # require FetchHttps if using https site
   pagespeed FetchHttps enable;

  # inline_css
  # https://developers.google.com/speed/pagespeed/module/filter-css-inline
#   pagespeed EnableFilters inline_css;
#   pagespeed CssInlineMaxBytes 2048;

  # prioritize_critical_css
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-prioritize-critical-css
   pagespeed EnableFilters prioritize_critical_css;

  # move_css_to_head
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-css-to-head
  pagespeed EnableFilters move_css_to_head;

  # move_css_above_scripts
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-css-above-scripts
  pagespeed EnableFilters move_css_above_scripts;

  # combine_css
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-css-combine
  pagespeed EnableFilters combine_css;

   # Uncomment this if you want to prevent mod_pagespeed from combining files
   # (e.g. CSS files) across paths
   #
#  pagespeed CombineAcrossPaths off;

  # combine_javascript
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-js-combine
  pagespeed EnableFilters combine_javascript;
  pagespeed MaxCombinedJsBytes 122900;

  # extend_cache
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-cache-extend
  pagespeed EnableFilters extend_cache;

  # rewrite_css
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-css-rewrite
  pagespeed EnableFilters rewrite_css;

  # rewrite_javascript
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-js-minify
  pagespeed EnableFilters rewrite_javascript;

  # inline_preview_images
  # https://developers.google.com/speed/pagespeed/module/filter-inline-preview-images
  pagespeed EnableFilters inline_preview_images;

  # lazyload_images
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-lazyload-images
  pagespeed EnableFilters lazyload_images;

  # rewrite_images
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-image-optimize
  pagespeed EnableFilters rewrite_images;
  pagespeed EnableFilters inline_images;
  pagespeed EnableFilters recompress_images;
  pagespeed EnableFilters jpeg_subsampling;
  pagespeed EnableFilters convert_png_to_jpeg;
  pagespeed EnableFilters resize_images;
  pagespeed EnableFilters convert_jpeg_to_webp;
  pagespeed EnableFilters convert_to_webp_lossless;
#   pagespeed EnableFilters insert_image_dimensions;
#   pagespeed DisableFilters rewrite_images;
#   pagespeed DisableFilters recompress_images;
#   pagespeed DisableFilters convert_png_to_jpeg;
#   pagespeed DisableFilters extend_cache_images;
#   pagespeed EnableFilters convert_png_to_jpeg;
#  pagespeed EnableFilters convert_jpeg_to_webp;
#  pagespeed EnableFilters convert_to_webp_lossless;

  # sprite_images
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-image-sprite
 pagespeed EnableFilters rewrite_css,sprite_images;

  # insert_dns_prefetch
  # https://developers.google.com/speed/docs/mod_pagespeed/filter-insert-dns-prefetch
  pagespeed EnableFilters insert_dns_prefetch;

  # InPlaceResourceOptimization
  # https://developers.google.com/speed/pagespeed/module/system#ipro
  # Enabled by default as of 1.9.32.1
  pagespeed InPlaceResourceOptimization off;
#######################################################
````
Now even after having all these filters in my config I still don't know why the js is not combining, why css is not combining and why pagespeed is not showing it's magic on the images.

I've shared all these things with you guys so that any of you can take a look and let me know what is wrong with my config that is making all these issues. Also if you guys think I should add any more filters in my config to make my site faster.

Thanks in advance.

**Comment by oschaaf** [comment]
Via 
```
curl -H "PageSpeedFilters: +debug" https://www.isaumya.com/
```

I see a lot of these comments from pagespeed, which explains why there's almost no optimization going on:
```
...
<!--4xx status code, preventing rewriting of https://www.isaumya.com/wp-content/plugins/array-toolkit/includes/css/social-style.css-->
<!--4xx status code, preventing rewriting of https://www.isaumya.com/wp-content/plugins/array-toolkit/includes/css/social-style.css-->
...
```

It  looks like pagespeed is not able to fetch files from your server and receives 404 responses. 
Do you see requests in the access logs from a user-agent that mentions pagespeed? I see you commented `MapOriginDomain`,  I think mapping https->http fails because http redirects to https on your website.

First, could you try what happens when you add this?:

```
pagespeed Domain "https://www.isaumya.com";
```

That explicitly authorizes fetching from your domain and should bypass the loopback fetching that is used by default.

If that does not work you could consider configuring pagespeed to load files from disk using `LoadFromFile`, which has an additional benefit which is that changes to the original files will trigger re-optimization immediately:
https://developers.google.com/speed/pagespeed/module/domains#ModPagespeedLoadFromFile

As you are running https this is also relevant:
https://developers.google.com/speed/pagespeed/module/https_support

**Comment by isaumya** [comment]
Hi @oschaaf,
Thanks for your reply. I have no idea why it is getting 404 on the css files. If you open the the css path, you can clearly see the files exists 

Also I disabled `pagespeed MapOriginDomain "http://208.117.38.82" "https://www.isaumya.com";` is because after adding it, nothing was changed. Now I've added the `pagespeed Domain` too but still nothings happening. The reason I dont wanna fetch files from disk is because in this server I also have some subdomains and I don't juts want to run pagesped on the root domain but for the subdomains too.

Can you please check now and let me know what should I do next?

**Comment by oschaaf** [comment]
```
pagespeed MapOriginDomain "http://208.117.38.82" "https://www.isaumya.com";
```

Fetching from http://208.117.38.82 would not work, because that lands on the default host for the server. 
But even when you would correct that, the http://www.isaumya.com cannot be used to fetch from as it redirects all requests to https. PageSpeed's fetcher will not be able to understand and follow these redirects(yet).
So it's either setting up `LoadFromFile` or debugging the SSL fetch failures. `serf_fetch_cert_errors` on http://vps.isaumya.com/pagespeed_global_admin/statistics is incrementing. Could you read https://developers.google.com/speed/pagespeed/module/https_support#configuring-ssl-certificates and see if that is set up ok on your machine?

**Comment by isaumya** [comment]
You are right. After doing this following pagespeed is working fine in both my main doamin with ssl and the subdomains. All features are working quite fine.

````
# pagespeed MapOriginDomain "http://www.isaumya.com" "https://www.isaumya.com";
 pagespeed LoadFromFile "https://www.isaumya.com" "/home/nginx/domains/isaumya.com/public/";
 pagespeed Domain https://www.isaumya.com;
 pagespeed Domain *.isaumya.com;
````

But I do see some anomalies. Like in my website the images that are used within srcset are not getting rewrited or changed to webp. Also at the footer of the website the image I have of Bigscoots it is also showing in png instead of webp.

Any idea why?
Thanks a ton for your help.

**Comment by oschaaf** [comment]
@isaumya Great to hear on your progress - but:

Please take a good look at https://developers.google.com/speed/pagespeed/module/domains#risks and restrict what gets loaded via `LoadFromFile`. You want to make sure only static files can be loaded in this manner.

E.g. I would suggest doing something like:
```
pagespeed LoadFromFileMatch "^https?://www.isaumya.com/" "/home/nginx/domains/isaumya.com/public/";
pagespeed LoadFromFileRuleMatch disallow .*;
pagespeed LoadFromFileRuleMatch allow \.css$;
pagespeed LoadFromFileRuleMatch allow \.jpe?g$;
pagespeed LoadFromFileRuleMatch allow \.png$;
pagespeed LoadFromFileRuleMatch allow \.gif$;
pagespeed LoadFromFileRuleMatch allow \.js$;
# add more extensions of you need them

# I don't think you need these when you have LoadFromFile set up
# pagespeed Domain https://www.isaumya.com;
# pagespeed Domain *.isaumya.com
```

**Comment by isaumya** [comment]
Thanks for your help again. But have you checked that the images under `srcset` are not getting rewrited by pagespeed. Also the image at the footer is not getting rewrited by pagespeed. Any idea why?

**Comment by oschaaf** [comment]
1. `srcset` attibributes can be generated  by pagespeed but the attribute's value does not (yet) get parsed and optimized. 
2. Assuming you are referencing `bigscoots_logo_250.png`, it is optimized now. PageSpeed sometimes needs a few browser refreshes before the page is fully optimized.

**Comment by oschaaf** [comment]
Seems we're all set, closing this.

**Comment by isaumya** [comment]
Thanks for all your help :smile:
