### ISSUE TITLE
nginx 1.9.11 + 1.10.33.5 beta NgxFetch failed to resolve host [localhost]

### ISSUE THREAD

**Issue by centminmod** [pagespeed/ngx_pagespeed#1131]
Getting this is message log with nginx 1.9.11 + 1.10.33.5 beta as a dynamic module with downstream caching configured
```
[Tue, 23 Feb 2016 02:18:09 GMT] [Info] [18257] Should purge "http://centminmod.com/" which was served with only 70% rewriting done.
[Tue, 23 Feb 2016 02:18:09 GMT] [Info] [18257] Purge url is http://localhost:80/
[Tue, 23 Feb 2016 02:18:09 GMT] [Warning] [18257] NgxFetch 0x7fe9e287a380: failed to resolve host [localhost]
```

> nginx -V
> nginx version: nginx/1.9.11
> built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
> built with OpenSSL 1.0.2f  28 Jan 2016
> TLS SNI support enabled
> configure arguments: --with-ld-opt='-ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -mtune=native -mfpmath=sse -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --with-openssl-opt=enable-tlsext --add-module=../nginx-module-vts --with-libatomic --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_gzip_static_module --add-module=../ngx_brotli --add-dynamic-module=../ngx_pagespeed-release-1.10.33.5-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_realip_module --add-module=../nginx-accesskey-2.0.3 --add-module=../nginx-http-concat-master --add-module=../ngx-fancyindex-0.3.6 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.2.19 --add-module=../set-misc-nginx-module-0.29 --add-module=../echo-nginx-module-0.58 --add-module=../redis2-nginx-module-0.12 --add-module=../ngx_http_redis-0.3.7 --add-module=../lua-nginx-module-0.10.1rc1 --add-module=../lua-upstream-nginx-module-0.04 --add-module=../lua-upstream-cache-nginx-module-0.1.1 --add-module=../nginx_upstream_check_module-0.3.0 --add-module=../openresty-memc-nginx-module-4f6f78f --add-module=../openresty-srcache-nginx-module-ffa9ab7 --add-module=../headers-more-nginx-module-0.29 --with-pcre=../pcre-8.38 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=../openssl-1.0.2f

**Comment by oschaaf** [comment]
The dns resolver that the native fetcher is configured to use is not able to resolve `localhost`.
If you want `/etc/hosts` to be considered while resolving, you could take a look at `dnsmasq`.

**Comment by centminmod** [comment]
i changed the `DownstreamCachePurgeLocationPrefix` from localhost to `http://centminmod.com:80` and seems to work now ? that suggests it's working ?
```
[Tue, 23 Feb 2016 12:26:58 GMT] [Info] [10436] Should purge "http://centminmod.com/http2-nginx.html" which was served with only 79% rewriting done.
[Tue, 23 Feb 2016 12:26:58 GMT] [Info] [10436] Purge url is http://centminmod.com:80/http2-nginx.html
```

**Comment by oschaaf** [comment]
That looks good to me. To validate the PURGE is processed OK, you could check the access log to see what kind of http response code was written in response. But I think pagespeed would have complained if that did not look good.
