### ISSUE TITLE
Reusing shared memory for path issue

### ISSUE THREAD

**Issue by isaumya** [pagespeed/ngx_pagespeed#1132]
Hi in my message history I'm seeing these notices quite often. After reporting this to my host he thought it might be some similar issues like https://github.com/pagespeed/ngx_pagespeed/issues/154
So he pushed the fix mentioned there, but I'm still seeing these messages on my message history. http://vps.isaumya.com/pagespeed_admin/message_history

Does anyone know a fix of this?

````
[Tue, 23 Feb 2016 05:19:29 GMT] [Info] [23185] Reusing shared memory for path: /var/ngx_pagespeed_cache purge .
[Tue, 23 Feb 2016 05:19:29 GMT] [Info] [23185] Reusing shared memory for path: /var/ngx_pagespeed_cache purge .
[Tue, 23 Feb 2016 05:19:29 GMT] [Info] [23185] Reusing shared memory for path: /var/ngx_pagespeed_cache purge .
[Tue, 23 Feb 2016 05:19:29 GMT] [Info] [23185] Reusing shared memory for path: /var/ngx_pagespeed_cache purge .
````

Also in some images it is showing `too busy to rewrite image`. like this way 

````
[Tue, 23 Feb 2016 05:29:50 GMT] [Info] [343] https://www.isaumya.com/increase-internet-download-speed/:0: https://www.isaumya.com/wp-content/uploads/2016/02/bigscoots_logo_250.png: Too busy to rewrite image.
````

Does anyone know why it shows that and if there is any fix for it.

**Comment by oschaaf** [comment]
I don't think there  is anything to fix. The message log lines you posted are all informational. Out of curiosity, how did you and your host jump to the conclusion that there was a problem?

`too busy to rewrite image` happens when pagespeed throttles the amount of images that are rewritten at the same moment:
https://developers.google.com/speed/pagespeed/module/system#image_rewrite_max

**Comment by isaumya** [comment]
My host didn't think it is a issue. I thought it was.

Thanks for the link. I read it now. So, as it keeps the number of image optimizaed at a time to 8. Do you think I should increase it?

Here is my server config:

1536 MB RAM
2 CPU available.

**Comment by oschaaf** [comment]
I think you're ok with the defaults, but looking at http://vps.isaumya.com/pagespeed_global_admin/statistics, there's a counter called `image_rewrites_dropped_due_to_load`.  That counter should stop increasing fairly quickly as optimizations are cached - if it doesn't the cache may be sized too small.

**Comment by isaumya** [comment]
Thank you for all your helps :)
