### ISSUE TITLE
IPRO responses sometimes forward a bad cache control value

### ISSUE THREAD

**Issue by oschaaf** [pagespeed/ngx_pagespeed#1138]
Cloudflare sometimes shows an error page when serving an mp3 file. It does so when it receives a bad header that looks like: `Cache-Control: ?ax-age`, as seen in `error.log`.

The server is running ngx_pagespeed 1.10.33.5

**Comment by oschaaf** [comment]
Initial report from ngx-pagespeed-discuss: https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/3cfPz35acRM

**Comment by oschaaf** [comment]
The bad cache control header is emitted when we hit the flow where IPRO does not find a cache entry and subsequently starts recording the response. In this flow the original cache-control header is passed on which is owned by an `NgxBaseFetch` instance that will be released the passed on string is put on the wire. The fix is to copy the value, pull coming up.

**Comment by jmarantz** [comment]
Thanks for tracking this down, Otto.  Is this related to specifying a threadpool in nginx?

**Comment by oschaaf** [comment]
@jmarantz No this is unrelated to specifying a threadpool in nginx, though I was looking into both things at the same time because initially I though they might be related.

**Comment by jeffkaufman** [comment]
Fixed with #1139 and 5264647a658712f2701cf19e3fb3d9269c262682
