### ISSUE TITLE
PageSpeed console totally blank in global_admin

### ISSUE THREAD

**Issue by pefoley2** [pagespeed/ngx_pagespeed#1143]
When looking at the console (https://<domain>/pagespeed_global_admin/console), I get an entirely blank white page.
Statistics, StatisticsLogging, and LogDir are all enabled in the nginx config and there are files in the logdir.
All the other pages seem to work fine, and there are no errors in the js console.

**Comment by oschaaf** [comment]
Hi, this is a known issue and is being tracked at https://github.com/pagespeed/mod_pagespeed/issues/1214

(Awkward) workaround you could use: load the console page, and subsequently enter this in the url bar:
```
javascript:void(pagespeed.startConsole())
```

Closing this as a duplicate
