### ISSUE TITLE
Doesn't combilne JS if has text/javascript directive in it

### ISSUE THREAD

**Issue by isaumya** [pagespeed/ngx_pagespeed#1144]
Hi,
as I use pagespeed on a wordpress site, I've found something.I've seen that pagespeed doesn't combine JS files with has `type='text/javascript'` directive in it. Like the following URLs:

```
<script type='text/javascript' src='https://www.example.com/wp-content/plugins/simple-comment-editing/js/simple-comment-editing.min.js'></script>
<script type='text/javascript' src='https://www.example.com/wp-includes/js/wp-embed.min.js'></script>
<script type='text/javascript' src='https://www.example.com/wp-content/plugins/wp-product-review/javascript/pie-chart.js'></script>
<script type='text/javascript' src='https://www.example.com/wp-content/plugins/wp-product-review/javascript/main.js'></script>
<script type='text/javascript' src='https://www.example.com/wp-content/themes/checkout/js/edd.js'></script>
<script type='text/javascript' src='https://www.example.com/wp-content/plugins/simple-comment-editing/js/event-manager.min.js'></script>
<script type='text/javascript' src='https://www.example.com/wp-includes/js/wp-ajax-response.min.js'></script>
```

I don't know if this is a bug or something else. But as I found it so I shared it.

**Comment by jeffkaufman** [comment]
Are you sure that's why the combining isn't happening?  Here's a demo of a page where there's `type='text/javascript'` but it's combining properly: http://www.jefftk.com/text-javascript-demo?PageSpeedFilters=combine_javascript

My guess is that it's something else, and if you add `?PageSpeedFilters=+debug` to your url and view source, PageSpeed should insert html comments to tell you what's going on.

**Comment by isaumya** [comment]
Thanks @jeffkaufman for the reply. Here is the crazy part. When I tried to see the source with `?PageSpeedFilters=+debug` it shows all js combined but when I see the page source without `?PageSpeedFilters=+debug` I see all JS getting combined except the one mentioned within `type='text/javascript'` (you can see it almost at the end of the view source.

Check out yourself:

view-source:https://www.isaumya.com/get-must-useful-features-gmail-inbox-mixmax/

and 

view-source:https://www.isaumya.com/get-must-useful-features-gmail-inbox-mixmax/?PageSpeedFilters=+debug

Very wired. No errors were mentioned either :(

**Comment by isaumya** [comment]
Oh sorry my bad. I think it's my extended browser cache.... Sorry for bothering you.
