### ISSUE TITLE
Building ngx_pagespeed with PSOL built from source

### ISSUE THREAD

**Issue by JoyceBabu** [pagespeed/ngx_pagespeed#1152]
Continuing the discussion from #1005 as it was off-topic

> Would it be a terribly bad idea to run PSOL master in production? Also, should the version of PSOL match with the version of ngx_pagespeed? Is it necessary to run PSOL master with ngx_pagespeed master? 
> ~ JoyceBabu

---
> ngx_pagespeed:master builds against the latest PSOL release. The main reason to do this would be if you wanted to apply a patch to PSOL, but not get full updates. This is relatively safe, especially if your patch is simple, small, and well understood.
> 
> ngx_pagespeed:trunk-tracking builds against mod_pagespeed:master. This is what you'd do if you wanted to run at the complete bleeding edge. In general I wouldn't recommend this for production unless you canaried it first and didn't see any issues. (If you did see issues, though, your finding them early would be really useful!)
> ~ jeffkaufman

---
I tried following the instructions at
https://github.com/pagespeed/ngx_pagespeed/wiki/Building-PSOL-From-Source

At first I tried to follow the instructions for building against `master`. But it failed as there was no directory `mod_pagespeed/src/net/instaweb/automatic`. Then I tried to build against `trunk-tracking`, which completed successfully. But compilation of nginx against the new PSOL is failing with message

> /usr/local/src/mod_pagespeed/src/pagespeed/kernel/base/proto_util.h:24:59: fatal error: google/protobuf/io/zero_copy_stream_impl_lite.h: No such file or directory
>  #include "google/protobuf/io/zero_copy_stream_impl_lite.h"
>                                                            ^
> compilation terminated.

Also, is it possible to speedup compilation by skipping the tests?

**Comment by oschaaf** [comment]
Running the tests is not part of the compilation process, so you can skip that if you are confident you will be OK.

**Comment by kuaza61** [comment]
same problem, please reply true fix here. Thanks..

(centos 7.2, nginx 1.10.1 (yum install))

**Comment by oschaaf** [comment]
@kuaza61 See https://github.com/pagespeed/ngx_pagespeed/issues/1285 - you may be building ngx_pagespeed against a version of psol/mod_pagespeed that does not match.
