### ISSUE TITLE
Image rewrite failed

### ISSUE THREAD

**Issue by XIAZY** [pagespeed/ngx_pagespeed#1179]
Hi.
I'm using PageSpeed with nginx 1.9.14. I followed [this](https://developers.google.com/speed/pagespeed/module/filter-image-optimize) document and added some filters (`rewrites_image`,  `convert_jpeg_to_webp`, `convert_to_webp_lossless`, `convert_to_webp_animated`, `recompress_webp`) to my server, but unfortunately none of them works. Pictures are not redirected and still serve as full-solution `png` files.

If I use Chrome's `view-source` function, the images are served with `pagespeed.CriticalImages.checkImageForCriticality(this);`, which seems is the reason.

Please help me to solve it, thank you so much!

**Comment by crowell** [comment]
do you have your site on the open internet now? could you post the url of it here?

**Comment by XIAZY** [comment]
Of course. My website is https://mechanus.io with core filters enabled.

**Comment by crowell** [comment]
inspecting with https://mechanus.io/?PageSpeedFilters=+debug I'm seeing some of your images being rewritten properly 

```html
<a href="https://mechanus.io/yi-ge-xin-shou-xiang-de-ss-panel-bu-shu-jiao-cheng/"><img src="/content/images/2016/04/xshadowsocks.png.pagespeed.ic.fd8k1DQIlt.webp" alt=""/><!--Image does not appear to need resizing.--><!--Image has no transparent pixels, is sensitive to compression noise, and has no animation.--><!--The image was not inlined because it has too many bytes.--></a>
```

and some are not

```html
<img src="/content/images/2016/04/blog-logo-1460033581601.png" alt="Logo"/><!--Uncacheable content, preventing rewriting of https://mechanus.io/content/images/2016/04/blog-logo-1460033581601.png--><!--Uncacheable content, preventing rewriting of https://mechanus.io/content/images/2016/04/blog-logo-1460033581601.png-->
```

Which means that the backend fetch to get the blog-logo-1460033581601.png could not cache the image, so we served the unoptimized version. (the backend fetch received a non-200 status code). Is that and the other images being served done through a redirect?

**Comment by XIAZY** [comment]
Weird, all images are served by a `root` config (including the images you posted). The page it self is served by a reverse proxy, but I think that isn't a problem.

**Comment by crowell** [comment]
Can you check your logs for the results of fetches from the user agent "Serf"?

**Comment by XIAZY** [comment]
Sure! These are some of them
```
[15/Apr/2016:23:54:24 +0800] "GET /ghost/img/touch-icon-ipad.png?v=14ed32e8a7 HTTP/1.1" 302 161 "https://mechanus.io/" "Serf/1.3.8 (mod_pagespeed/1.11.33.0-0)"
[15/Apr/2016:23:54:24 +0800] "GET /ghost/img/small.png?v=14ed32e8a7 HTTP/1.1" 302 161 "https://mechanus.io/" "Serf/1.3.8 (mod_pagespeed/1.11.33.0-0)"
[15/Apr/2016:23:54:24 +0800] "GET /ghost/img/medium.png?v=14ed32e8a7 HTTP/1.1" 302 161 "https://mechanus.io/" "Serf/1.3.8 (mod_pagespeed/1.11.33.0-0)"
[15/Apr/2016:23:57:54 +0800] "GET /assets/icon/blog-logo.png?v=14ed32e8a7 HTTP/1.1" 302 161 "https://mechanus.io/page/4/" "Serf/1.3.8 (mod_pagespeed/1.11.33.0-0)"
[15/Apr/2016:23:57:54 +0800] "GET /content/images/2016/04/blog-logo-1460033581601.png HTTP/1.1" 302 161 "https://mechanus.io/page/4/" "Serf/1.3.8 (mod_pagespeed/1.11.33.0-0)"
[16/Apr/2016:00:02:40 +0800] "GET /content/images/2016/03/cirno.png HTTP/1.1" 302 161 "https://mechanus.io/" "Serf/1.3.8 (mod_pagespeed/1.11.33.0-0)"
```

**Comment by crowell** [comment]
HTTP 302 is a url redirect. we are unable to optimized resources on redirects.

**Comment by XIAZY** [comment]
Thank you! I found the problem. This site had been attacked so I wrote a lua script to avoid CC by checking user cookies using rewrite. Seems like PageSpeed doesn't have this function.

**Comment by crowell** [comment]
thanks for letting us know the cause :+1:

**Comment by XIAZY** [comment]
By the way, I found the default nginx configuration will be overridden by PageSpeed.
I configured this
```
location /content/images/ {
    if ($http_user_agent ~* (wget|Scrapy|Curl|HttpClient)) {
        return 403;
    }
}
```
If the client tries to fetch the original file, it will successfully return a 403 code. However if it tries to fetch a image redirected by PageSpeed, it will bypass the setting.

**Comment by oschaaf** [comment]
Redirect following is in the pipeline, and being  tracked at https://github.com/pagespeed/mod_pagespeed/issues/262

As for your last comment, do you also have this in configuration as per ngx_pagespeed install documentation?  
```
location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" { add_header "" ""; }
```

If so, you may need to copy your user-agent blocking script into this location block too.
