### ISSUE TITLE
ngx_pagespeed and nginx 1.9.14

### ISSUE THREAD

**Issue by jotadrilo** [pagespeed/ngx_pagespeed#1180]
It seems that nginx 1.9.14 has some issues with ngx_pagespeed.

I compiled this version using the following versions:
ngx_pagespeed: release-1.9.32.14-beta
psol: 1.9.32.14
pagespeed: 1.9.32.14

The compilation finishes correctly but when I try to run the nginx sever, I get this error about the configuration:

`nginx: [emerg] unknown directive "gzip" in /home/user/nginx/conf/nginx.conf:31`

Also, I tried with nginx 1.9.12 and upgrade the ngx_pagespeed, psol and pagespeed versions but it is still not working. Did you notice about this before?

**Comment by crowell** [comment]
can you paste the nginx.conf that you have, and the output of `nginx -V`

**Comment by jotadrilo** [comment]
Hi, here is the output:

```
→ sudo /opt/nginxstack/nginx/sbin/nginx -Vv
nginx version: nginx/1.9.14
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --prefix=/opt/nginxstack/nginx --with-http_ssl_module --with-http_stub_status_module --with-cc-opt=-I/opt/nginxstack/common --with-ld-opt=-L/opt/nginxstack/common/lib --with-http_gzip_static_module --with-mail --with-mail_ssl_module --with-http_realip_module --with-http_stub_status_module --with-http_v2_module --add-module=/opt/nginxstack/src/gnosek-nginx-upstream-fair-5f6a3b7 --add-module=/opt/nginxstack/ruby/lib/ruby/gems/2.0.0/gems/passenger-5.0.6/ext/nginx --add-module=/opt/nginxstack/src/ngx_pagespeed-release-1.8.31.4-beta
```

and here is the `nginx.conf`:
```
user  daemon daemon;
worker_processes  auto;

error_log  "/opt/nginxstack/nginx/logs/error.log";
pid        "/opt/nginxstack/nginx/logs/nginx.pid";


events {
      worker_connections  1024;
}


http {
      include       mime.types;
      default_type  application/octet-stream;

      client_body_temp_path  "/opt/nginxstack/nginx/tmp/client_body" 1 2;
      proxy_temp_path "/opt/nginxstack/nginx/tmp/proxy" 1 2;
      fastcgi_temp_path "/opt/nginxstack/nginx/tmp/fastcgi" 1 2;
      scgi_temp_path "/opt/nginxstack/nginx/tmp/scgi" 1 2;
      uwsgi_temp_path "/opt/nginxstack/nginx/tmp/uwsgi" 1 2;

      access_log  "/opt/nginxstack/nginx/logs/access.log";

      sendfile        on;

      keepalive_timeout  65;

      gzip on;
      gzip_http_version 1.1;
      gzip_comp_level 2;
      gzip_proxied any;
      gzip_vary on;
      gzip_types text/plain
          text/xml
          text/css
          text/javascript
          application/json
          application/javascript
          application/x-javascript
          application/ecmascript
          application/xml
          application/rss+xml
          application/atom+xml
          application/rdf+xml
          application/xml+rss
          application/xhtml+xml
          application/x-font-ttf
          application/x-font-opentype
          application/vnd.ms-fontobject
          image/svg+xml
          image/x-icon
          application/atom_xml;

      gzip_buffers 16 8k;
      add_header X-Frame-Options SAMEORIGIN;
      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

      # HTTP server
      server {
          listen       80;
          server_name  localhost;

          location / {
              root   html;
              index  index.html index.htm;
          }

          location ~ \.php$ {
              root           html;
              fastcgi_read_timeout 300;
              fastcgi_pass   unix:/opt/nginxstack/php/var/run/www.sock;
              fastcgi_index  index.php;
              fastcgi_param  SCRIPT_FILENAME $request_filename;
              include        fastcgi_params;
          }
      }
}
```

so, the error is:
```
nginx: [emerg] unknown directive "gzip" in /opt/nginxstack/nginx/conf/nginx.conf:31
```

I tried to just comment the gzip directives but the error persists.

Note: I recompiled it so I changed the path.

**Comment by crowell** [comment]
looks like you're using a very old version of psol.

```
--add-module=/opt/nginxstack/src/ngx_pagespeed-release-1.8.31.4-beta
```
is in your configure options.

**Comment by nikolay** [comment]
By the way, Nginx v1.9.15 got released.

**Comment by jotadrilo** [comment]
You are right, I compiled that version with an old version of ngx_pagespeed in order to check if it would work with it. I forgot to mention it.

I will compile this new Nginx with the `1.9.32.14` version of psol, pagespeed and ngx_pagespeed and I will write back.

**Comment by jotadrilo** [comment]
I tried this new version:

```
→ sudo /opt/nginxstack/nginx/sbin/nginx -Vv
nginx version: nginx/1.9.15
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --prefix=/opt/nginxstack/nginx --with-http_ssl_module --with-http_stub_status_module --with-cc-opt=-I/opt/nginxstack/common --with-ld-opt=-L/opt/nginxstack/common/lib --with-http_gzip_static_module --with-mail --with-mail_ssl_module --with-http_realip_module --with-http_stub_status_module --with-http_v2_module --add-module=/opt/nginxstack/src/gnosek-nginx-upstream-fair-5f6a3b7 --add-module=/opt/nginxstack/ruby/lib/ruby/gems/2.0.0/gems/passenger-5.0.6/ext/nginx --add-module=/opt/nginxstack/src/ngx_pagespeed-release-1.9.32.14-beta
```

and the errors is still being:
```
nginx: [emerg] unknown directive "gzip" in /opt/nginxstack/nginx/conf/nginx.conf:31
```

I used the same `nginx.conf`. Is there anything I could be missing? Nginx is working properly without the pagespeed module and I'm compiling ngx as I did with previous versions. 
However, I'm getting this error since the 1.9.11 (1.9.10 works properly with this module).

I tried to disable `--with-http_gzip_static_module` in order to discard conflicts with pagespeed and any internal compression process that nginx could be performing. I didn't get any advance.

Did you find any similar issues before?

**Comment by keesspoelstra** [comment]
Never seen this before. Let me try to reproduce this  locally.

**Comment by keesspoelstra** [comment]
Confirmed. Also when I disable ngx_pagespeed's gzip_setter code the error persists.

**Comment by keesspoelstra** [comment]
Confirmed: 1.11.33.0 will run without problems. 

I will check this weekend if there is something we can backport to get this working in 1.9.32.14.

**Comment by andyone** [comment]
This patch fix problem:

```diff
diff -urN ngx_pagespeed-1.9.32.14-beta-orig/config ngx_pagespeed-1.9.32.14-beta/config
--- ngx_pagespeed-1.9.32.14-beta-orig/config	2016-04-27 12:24:06.986198238 -0400
+++ ngx_pagespeed-1.9.32.14-beta/config	2016-04-27 12:24:38.000000000 -0400
@@ -195,10 +195,10 @@
 
   # Make pagespeed run immediately before gzip.
   HTTP_FILTER_MODULES=$(echo $HTTP_FILTER_MODULES |\
-    sed "s/$HTTP_GZIP_FILTER_MODULE/$HTTP_GZIP_FILTER_MODULE $ngx_addon_name/")
+    sed "s/ngx_http_gzip_filter_module/ngx_http_gzip_filter_module $ngx_addon_name/")
   # Make the etag header filter run immediately after gzip.
   HTTP_FILTER_MODULES=$(echo $HTTP_FILTER_MODULES |\
-    sed "s/$HTTP_GZIP_FILTER_MODULE/ngx_pagespeed_etag_filter $HTTP_GZIP_FILTER_MODULE/")
+    sed "s/ngx_http_gzip_filter_module/ngx_pagespeed_etag_filter ngx_http_gzip_filter_module/")
   CORE_LIBS="$CORE_LIBS $pagespeed_libs"
   CORE_INCS="$CORE_INCS $pagespeed_include"
   echo "List of modules (in reverse order of applicability): "$HTTP_FILTER_MODULES
```
`$HTTP_GZIP_FILTER_MODULE` is empty. Sed can't apply pattern for given data and after that we have empty `HTTP_FILTER_MODULES` variable.

```
checking for psol ... found
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
List of modules (in reverse order of applicability): 
 + ngx_pagespeed was configured
```

**Comment by jotadrilo** [comment]
I will try that patch and I will write you back.

Thank you so much.

**Comment by kossamums** [comment]
I'm having the same issues as well.  Any updates on when this bug will be fixed?

**Comment by crowell** [comment]
@kossamums is there a reason why you can't use the latest version of ngx_pagespeed?

there have been some security patches since then, so it's recommended to upgrade.

**Comment by jeffkaufman** [comment]
ngx_pagespeed 1.9.x is no longer supported, and has unpatched security vulnerabilities.  Please use the latest version (1.11).

If you need to keep using 1.9.x, you need to be backporting the security patches anyway, in which case applying the patch above (https://github.com/pagespeed/ngx_pagespeed/issues/1180#issuecomment-215142121) shouldn't be much more work.

**Comment by andyone** [comment]
@jeffkaufman 1.11 can be built on CentOS 6 with GCC 4.4.7?

**Comment by jeffkaufman** [comment]
1.11 can be built on CentOS 6, but via a secondary install of gcc-4.8 instead of the default compiler.  On [build_ngx_pagespeed_from_source](https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source) we have the steps for installing the gcc-4.8 compiler into `/opt/` in a way that won't mess with the rest of your CentOS setup.
