### ISSUE TITLE
1.11.33.1-beta?

### ISSUE THREAD

**Issue by nikolay** [pagespeed/ngx_pagespeed#1188]
PSOL recommends this bugfix release. How about ngx_pagespeed?

**Comment by nikolay** [comment]
@crowell @jeffkaufman @oschaaf any idea so that we can plan our releases?

**Comment by crowell** [comment]
https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/gleZThbWQw0 was already released on Monday.

**Comment by nikolay** [comment]
@crowell Not really: https://github.com/pagespeed/ngx_pagespeed/releases

**Comment by crowell** [comment]
whoops, just tagged thanks for the catch.
