### ISSUE TITLE
ngx_pagespeed should not optimize HTML when it is explicitly configured not to

### ISSUE THREAD

**Issue by oschaaf** [pagespeed/ngx_pagespeed#1226]
Like mod_pagespeed, ngx_pagespeed should not optimize HTML when it is explicitly configured not to do so.  The following fragment should result in only html responses for requests to http://localhhost being transformed.

```
        pagespeed Disallow *;
        pagespeed Allow http://localhost/*;
```

Noticed while diagnosing a problem reported at [1] https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mod-pagespeed-discuss/ReOcIWbH7DE/RgQSIhUyBgAJ

**Comment by hillsp** [comment]
Be careful of https://github.com/pagespeed/mod_pagespeed/issues/1294 if you're not working with trunk.

**Comment by oschaaf** [comment]
@hillsp Thanks. This reproduced when building nps against mps trunk, and it was fixed via https://github.com/pagespeed/ngx_pagespeed/pull/1225 
I see that I did not mention this issue in the commit message, so this did not close automatically. I'm going to close this issue now.
