### ISSUE TITLE
Unable to disable trailing slash redirection

### ISSUE THREAD

**Issue by jippi** [pagespeed/ngx_pagespeed#1230]
Hi,

I can't find a 'knob' to turn to make pagespeed not redirect `/hello/world/` to `/hello/world`

The problem I'm having is that the redirection it does, are wrong in our proxy setup

We have a nginx (without pagespeed) running on a box on `:80` and `:443` that will send http requests up-stream to our php instances on `:81`

What we observe is that the trailing slash redirect includes port `:81` in the url, which will end up leaking to the end-user.

I can't find a knob to either turn off this redirect, or tell pagespeed to not include the port in the redirection it's doing

**Comment by oschaaf** [comment]
Which nginx pagespeed version are you running?
There's a know issue with redirects (which was fixed in 40c05b4, included since v1.10.33.0-beta).
See https://github.com/pagespeed/ngx_pagespeed/issues/1214#issuecomment-234801778

**Comment by jippi** [comment]
We use `1.9.32.11-7553`

**Comment by oschaaf** [comment]
@jippi you could try upgrading to a version that fixes the earlier redirection problem, or cherry-pick the specific fix: https://github.com/pagespeed/ngx_pagespeed/commit/40c05b4a4ff7c8731c6ee23deea82416408dfc73 

I think that would solve your problem. The issue only occurs with relative Location: headers in redirects, so if you could write out a fully qualified url when redirecting instead, that should also fix the problem.

This issue aside, I recommend upgrading to at least version 1.9.32.14`:
https://developers.google.com/speed/pagespeed/module/release_notes#release_1.9.32.14-stable

I'm closing this issue, but please re-open if applying one of the options above did not resolve it.

**Comment by jippi** [comment]
Hi, we have tried with `1.9.32.14-0` (dotdeb nginx) 

A concrete example:

Without pagespeed enabled:

```
-> curl -I -L https://bownty.fr/c/2184
HTTP/1.1 302 Found
Date: Mon, 08 Aug 2016 09:40:11 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d483bf3e394ebd638348aab4bdff177561470649211; expires=Tue, 08-Aug-17 09:40:11 GMT; path=/; domain=.bownty.fr; HttpOnly
Set-Cookie: CAKEPHP=o7v5n68fe9nbj3om8n4bt07fn2; expires=Tue, 08-Aug-2017 15:28:57 GMT; Max-Age=31556926; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: location=1673; expires=Tue, 08-Aug-2017 09:40:11 GMT; Max-Age=31536000; path=/
Set-Cookie: overlay=id%3D1%26close%3D0; path=/
Set-Cookie: pubuid=99823; expires=Fri, 07-Aug-2020 09:40:11 GMT; Max-Age=126144000; path=/; HttpOnly
Location: https://bownty.fr/?category=restaurants
X-Bownty-Server: web03
X-Bownty-Upstream: appcluster
X-Bownty-Proxy: web02
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Server: cloudflare-nginx
CF-RAY: 2cf2016249d73d07-CPH

HTTP/1.1 302 Found
Date: Mon, 08 Aug 2016 09:40:11 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d483bf3e394ebd638348aab4bdff177561470649211; expires=Tue, 08-Aug-17 09:40:11 GMT; path=/; domain=.bownty.fr; HttpOnly
Set-Cookie: location=1673; expires=Tue, 08-Aug-2017 09:40:11 GMT; Max-Age=31536000; path=/
Location: /paris/restaurants
X-Bownty-Server: web01
X-Bownty-Upstream: appcluster
X-Bownty-Proxy: web02
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Server: cloudflare-nginx
CF-RAY: 2cf20162d9d93d07-CPH

HTTP/1.1 200 OK
Date: Mon, 08 Aug 2016 09:40:11 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d483bf3e394ebd638348aab4bdff177561470649211; expires=Tue, 08-Aug-17 09:40:11 GMT; path=/; domain=.bownty.fr; HttpOnly
Vary: Accept-Encoding
Set-Cookie: CAKEPHP=3o247mrm733sd1iopf85ojmlf6; expires=Tue, 08-Aug-2017 15:28:57 GMT; Max-Age=31556926; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: location=1673; expires=Tue, 08-Aug-2017 09:40:11 GMT; Max-Age=31536000; path=/
Set-Cookie: overlay=id%3D1%26close%3D1; path=/
Set-Cookie: pubuid=5; expires=Fri, 07-Aug-2020 09:40:11 GMT; Max-Age=126144000; path=/; HttpOnly
X-Bownty-Server: web02
X-Bownty-Upstream: appcluster
X-Bownty-Proxy: web02
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Server: cloudflare-nginx
CF-RAY: 2cf2016329da3d07-CPH
```

With pagespeed enabled:

```
-> curl -I -L https://bownty.fr/c/2184
HTTP/1.1 302 Moved Temporarily
Date: Mon, 08 Aug 2016 09:41:15 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d414afdac9ea980431e23d48151ebc2f61470649274; expires=Tue, 08-Aug-17 09:41:14 GMT; path=/; domain=.bownty.fr; HttpOnly
Set-Cookie: CAKEPHP=j3q304l72vd8ransach8u3q316; expires=Tue, 08-Aug-2017 15:30:01 GMT; Max-Age=31556926; path=/; HttpOnly
Pragma: no-cache
Set-Cookie: location=1673; expires=Tue, 08-Aug-2017 09:41:15 GMT; Max-Age=31536000; path=/
Set-Cookie: overlay=id%3D1%26close%3D0; path=/
Set-Cookie: pubuid=99823; expires=Fri, 07-Aug-2020 09:41:15 GMT; Max-Age=126144000; path=/; HttpOnly
Location: https://bownty.fr/?category=restaurants
X-Bownty-Server: web02
X-Page-Speed: 1.9.32.14-0
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
X-Bownty-Upstream: appcluster
X-Bownty-Proxy: web02
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Server: cloudflare-nginx
CF-RAY: 2cf202f0443a3d3d-CPH

HTTP/1.1 302 Moved Temporarily
Date: Mon, 08 Aug 2016 09:41:15 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d6e2d36a88cd465094d9c65dae6d7ae581470649275; expires=Tue, 08-Aug-17 09:41:15 GMT; path=/; domain=.bownty.fr; HttpOnly
Location: http://bownty.fr:81/paris/restaurants
Set-Cookie: location=1673; expires=Tue, 08-Aug-2017 09:41:15 GMT; Max-Age=31536000; path=/
X-Bownty-Server: web02
X-Page-Speed: 1.9.32.14-0
Cache-Control: max-age=0, no-cache
X-Bownty-Upstream: appcluster
X-Bownty-Proxy: web02
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Server: cloudflare-nginx
CF-RAY: 2cf202f1a43c3d3d-CPH
```

As you can see, pagespeed tries to be helpful and remove the trailing `/` from the url, but frustrating enough adds our internal port `:81` to the response, causing the end user to get stuck, since `:81` are not public to the network

Are there any way to disable this `helpful` behavior from pagespeed?

**Comment by jippi** [comment]
cc @oschaaf

**Comment by oschaaf** [comment]
@jippi The fix for this is very probably https://github.com/pagespeed/ngx_pagespeed/commit/40c05b4a4ff7c8731c6ee23deea82416408dfc73 which was not yet included in `1.9.32.14-0`. Can you try cherry-picking that commit?

**Comment by jippi** [comment]
@oschaaf currently we use a prebuild nginx package, so don't have the skills to recompile nginx and the module from scratch at this time :( 

I was under the impression that 40c05b4 contained the fix, guess not :) 

Are the fix not in any stable releases?

**Comment by oschaaf** [comment]
@jippi ngx_pagespeed currently only offers beta-releases, but some of those are linked against a stable version of the pagespeed optimization libraries. 
Having said that, ngx_pagespeed 1.11.33.2-beta [1] may be a good choice for you if there is a package available, as it is marked stable for mod_pagespeed and contains 40c05b4.

[1] https://developers.google.com/speed/pagespeed/module/release_notes
