### ISSUE TITLE
Page DOM collected

### ISSUE THREAD

**Issue by fasace** [pagespeed/ngx_pagespeed#1233]
module for a long time after its launch remains unanswered [Page DOM collected] tell me what can be the reason
he site is associated with Google Development APi installed in the console all of the requirements for the registration of a domain in the system to use module some time back was not a problem, today the problem on any website is a long response from the server optimizer to load the data from the data server of the website

**Comment by fasace** [comment]
he site is associated with Google Development APi installed in the console all of the requirements for the registration of a domain in the system to use module some time back was not a problem, today the problem on any website is a long response from the server optimizer to load the data from the data server of the website

**Comment by oschaaf** [comment]
@fasace I suspect that you are asking a question about PageSpeed Insights? Could you forward that to https://groups.google.com/forum/#!forum/pagespeed-insights-discuss ?
To help people over there understand your problem, it would help if you could attach screenshots and or any logs that show the problem.
