### ISSUE TITLE
Pagespeed module has an error

### ISSUE THREAD

**Issue by fasace** [pagespeed/ngx_pagespeed#1234]
Pagespeed module has an error: NaCl module load failed: 

pagespeedonline.pagespeedapi.runpagespeed: 100
Код ответа	Ошибки клиента (4xx)	Ошибки сервера (5xx)
pagespeedonline.pagespeedapi.runpagespeed	371	0

**Comment by oschaaf** [comment]
@fasace Are you asking a question about the PageSpeed Insights API in combination with Chrome's native client? In that case you are probably better off asking questions at the support/contact options of these products, I do not think we can help you here.

Closing this issue, but feel free to re-open if I misunderstood!

**Comment by fasace** [comment]
у меня на моем устройстве по моей необходимости все плагины работали успешно, на сегодняшний день ответ NACl Debugger либо выдает свою ошибку на архитектуру среды файлов либо долгий ответ DOM Collected, связь с API присутствует а вот почему не работает плагин...

**Comment by fasace** [comment]
установил PNaCl решает эту проблему и позволяет создавать действительно портативные и независимые от архитектур приложения. Как это происходит? Процесс компиляции разбивается на два этапа:
компиляция исходного кода в байткод, который не зависит от архитектуры;
перевод байткода в нативный код под каждую архитектуру.
 
проблем не решает

**Comment by isaumya** [comment]
@fasace if possible, please post in english so that we all can understand the problem you are facing.
