### ISSUE TITLE
build against trunk-tracking looks broken (undefined reference to `grpc_init' & 'gprc_shutdown')

### ISSUE THREAD

**Issue by oschaaf** [pagespeed/ngx_pagespeed#1237]
The build ends with:
```
        -Wl,-z,relro -Wl,--as-needed -ldl -lpthread -lpthread -lcrypt -lstdc++ /home/oschaaf/code/google/mps-ipro-vs-loadfromfile/src/pagespeed/automatic/pagespeed_automatic.a -lrt -pthread -lm -lbrotlienc -lstdc++ -lcrypto -lpcre -lssl -lcrypto -ldl -lz \
        -Wl,-E
objs/addon/src/ngx_base_fetch.o: In function `grpc::internal::GrpcLibrary::init()':
/home/oschaaf/code/google/mps-ipro-vs-loadfromfile/src/third_party/grpc/src/include/grpc++/impl/grpc_library.h:49: undefined reference to `grpc_init'
objs/addon/src/ngx_base_fetch.o: In function `grpc::internal::GrpcLibrary::shutdown()':
/home/oschaaf/code/google/mps-ipro-vs-loadfromfile/src/third_party/grpc/src/include/grpc++/impl/grpc_library.h:50: undefined reference to `grpc_shutdown'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/home/oschaaf/code/google/nginx-source'
make: *** [build] Error 2

```

**Comment by hillsp** [comment]
That's pretty odd. Did it just start?

**Comment by oschaaf** [comment]
@hillsp I didn't bisect it, so I'm not 100% sure it broke there, but what I did to work around was build against one commit earlier then https://github.com/pagespeed/mod_pagespeed/commit/3088e26a632ab67c3e493b3132affa02a862547d as that mentioned grpc. At that point the build succeeded.

**Comment by hillsp** [comment]
I just built ngx_pagespeed with no problems. I guess you have some sort of stale deps problem. Can you try re-running gclient and the ngx configure step?

**Comment by oschaaf** [comment]
@hillsp Hmm, I just was able to reproduce it again using the tip of trunk-tracking from mps and master of mps. I use a script to build freshly which has been working well for some time..  configure line for nginx:

```
MOD_PAGESPEED_DIR="$MPS_DIR/src" auto/configure \
   --add-module="$NPS" \
   --add-module="$NGX_CACHE_PURGE" \
   --add-module="$NGX_DEVEL_KIT" \
   --add-module="$SET_MISC_MODULE" \
   --add-module="$HEADERS_MORE_MODULE" \
   --add-module="$NGX_BROTLI" \
   --add-module="$NGX_LET" \
   --prefix="$PREFIX" \
   --with-ipv6 \
   --with-threads \
   --with-debug \
   --with-cc-opt="-ggdb -O0 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2" \
   --with-ld-opt='-Wl,-z,relro -Wl,--as-needed' \
   --with-http_ssl_module \
   --with-http_v2_module
```

**Comment by hillsp** [comment]
I think I forgot to checkout trunk-tracking on ngx_pagespeed, I see this now.

The cause of problem seems to be I added the alarm header to grpc.h. Something it includes tries to define a static initialiser, but the grpc symbols have been renamed so it doesn't work. Since the alarm is only used in a single test, it should be OK to just move that header.

**Comment by hillsp** [comment]
...and a quick work-around is just to comment out alarm.h in mod_pagespeed/src/pagespeed/kernel/util/grpc.h, since no-one is left to review a fix until monday at this point.

**Comment by oschaaf** [comment]
Ah, I see. Thanks for the workaround!
