### ISSUE TITLE
ngx_pagespeed outdated in relation to mod_pagespeed

### ISSUE THREAD

**Issue by kyvaith** [pagespeed/ngx_pagespeed#1247]
Is the code in ngx_pagespeed and mod_pagespeed contains the same functionality? In mod_pagespeed I see a lot of changes that I need, but I use nginx.

**Comment by oschaaf** [comment]
@kyvaith I think ngx_pagespeed and mod_pagespeed should be pretty close to feature parity, is there a specific feature or change that you are missing in ngx_pagespeed?

**Comment by kyvaith** [comment]
@oschaaf thank you for reply.
Was thinking about this: https://github.com/pagespeed/mod_pagespeed/commit/7bf8083314ba9d011c750d72893a2f91183b8c7f

and this: https://github.com/pagespeed/mod_pagespeed/commit/428b7e044e753169724e7512804d41cca9c11651

**Comment by oschaaf** [comment]
I think the changes changes you point out have not been released in either `mod_pagespeed` or `ngx_pagespeed` yet. To have them, you should build the bleeding edge version of `ngx_pagespeed` from source (or wait until the featured get released).

For building the bleeding edge version (trunk-tracking branch)  of ngx_pagespeed from source, there's https://github.com/pagespeed/ngx_pagespeed/wiki/Building-PSOL-From-Source

I'm closing this issue, but feel free to re-open if you have trouble building from source (if you go that route).

**Comment by kyvaith** [comment]
Will do. Thank you.
