### ISSUE TITLE
The preceding resource was not rewritten because its domain ($domain) is not authorized

### ISSUE THREAD

**Issue by kyvaith** [pagespeed/ngx_pagespeed#1251]
Hi,

After over a week of battle of ngx_pagespeed configuration, I've ended with one error I can't get through. I'm getting warnings like this in debug mode:
`<!--The preceding resource was not rewritten because its domain (naprawimyto.pl) is not authorized-->`
I was trying to add directive:
`pagespeed Domain naprawimyto.pl;`
and
`pagespeed Domain https://naprawimyto.pl;`
but it has no effect. I'm running multiple Nginx docker images with ngx_pagespeed and Docker proxy on front, also with help of Nginx, where HTTP/2 (SSL) magic happens but not ngx_pagespeed. 

Please help,
Thanks. :)

**Comment by oschaaf** [comment]
What hostname is used when the proxy performs a request to the server that runs ngx_pagespeed?

Also - if you terminate SSL in front of the server that runs ngx_pagespeed, you can forward the original protocol to the server that runs ngx_pagespeed via a request header to inform it about the original protocol that was used:

```
proxy_set_header X-Forwarded-Proto $scheme;
```

Subsequently you configure ngx_pagespeed to listen to that header:

```
pagespeed RespectXForwardedProto on;
```

https://developers.google.com/speed/pagespeed/module/https_support#RespectXForwardedProto

**Comment by kyvaith** [comment]
RespectXForwardedProto has no effect for me. This is my config:

Before server section:
```
# Pagespeed global configuration

pagespeed on;

pagespeed Statistics on;
pagespeed StatisticsLogging on;
pagespeed LogDir /var/log/pagespeed;
pagespeed AdminPath /pagespeed_admin;

pagespeed FileCachePath /var/ngx_pagespeed_cache;
pagespeed StatisticsPath /ngx_pagespeed_statistics;
pagespeed GlobalStatisticsPath /ngx_pagespeed_global_statistics;
pagespeed MessagesPath /ngx_pagespeed_message;
pagespeed ConsolePath /pagespeed_console;
pagespeed AdminPath /pagespeed_admin;
pagespeed GlobalAdminPath /pagespeed_global_admin;

pagespeed ForbidAllDisabledFilters true;
pagespeed PreserveUrlRelativity on;
pagespeed EnableCachePurge on;
pagespeed ForceCaching on;
# pagespeed RespectXForwardedProto on;

pagespeed FileCachePath /var/ngx_pagespeed_cache;
pagespeed MemcachedServers "memcached";

```
Inside server section:
```
# Pagespeed configuration

pagespeed MapOriginDomain "http://naprawimyto.pl" "https://naprawimyto.pl";
pagespeed LoadFromFile "https://naprawimyto.pl" "/var/www/html/";
# pagespeed RespectXForwardedProto on;

pagespeed MapRewriteDomain "https://fonts.gstatic.com" "http://fonts.gstatic.com";

location /ngx_pagespeed_statistics { allow all; }
location /ngx_pagespeed_message { allow all; }
location /pagespeed_console { allow all; }
location ~ ^/pagespeed_admin { allow all; }

location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" { add_header "" ""; }
location ~ "^/pagespeed_static/" { }
location ~ "^/ngx_pagespeed_beacon$" { }

pagespeed Disallow */amp/*;
pagespeed Disallow */admin/*;

pagespeed AvoidRenamingIntrospectiveJavascript off;
pagespeed DisableRewriteOnNoTransform off;
pagespeed SupportNoScriptEnabled false;

pagespeed RewriteLevel CoreFilters;

pagespeed EnableFilters collapse_whitespace;
pagespeed EnableFilters combine_heads;
pagespeed EnableFilters convert_to_webp_animated;
pagespeed EnableFilters dedup_inlined_images;
pagespeed EnableFilters elide_attributes;
pagespeed EnableFilters extend_cache_pdfs;
pagespeed EnableFilters inline_google_font_css;
pagespeed EnableFilters insert_dns_prefetch;
pagespeed EnableFilters local_storage_cache;
pagespeed EnableFilters make_google_analytics_async;
pagespeed EnableFilters make_show_ads_async;
pagespeed EnableFilters prioritize_critical_css;
pagespeed EnableFilters rewrite_style_attributes;
pagespeed EnableFilters sprite_images;
pagespeed EnableFilters trim_urls;
```

Please look at the source of page: https://naprawimyto.pl/?ModPagespeedFilters=%20debug from line 286.

**Comment by oschaaf** [comment]
At line 286 I see:

```
<img src="wp-content/plugins/revslider/admin/assets/images/dummy.png" alt="" title="logo_static_v6" width="1200" height="801" data-lazyload="https://naprawimyto.pl/wp-content/uploads/2016/06/logo_static_v6.jpg" data-bgposition="0% 30%" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina><!--The preceding resource was not rewritten because its domain (naprawimyto.pl) is not authorized--><!--The preceding resource was not rewritten because its domain (naprawimyto.pl) is not authorized-->
```

Your configuration has a Disallow that matches the image url:

```
pagespeed Disallow */admin/*;
```

So perhaps disallowing `*/admin*/` is to broad for you?

**Comment by kyvaith** [comment]
You are right! That was so stupid from my side, sorry.
I have one more (last one) problem - I've set ForceCaching flag, and initially all resources have cache-control:max-age=31536000 header. But after few reloads of page, more and more resources gets cache-control:max-age=300,private according to PageSpeed Insights. What could be a reason for that? I have even global config in Nginx like this:

```
location ~* \.(3gp|gif|jpg|jpeg|png|ico|wmv|webp|avi|asf|asx|mpg|mpeg|mp4|pls|mp3|mid|wav|swf|flv|exe|zip|tar|rar|gz|tgz|bz2|uha|7z|doc|docx|xls|xlsx|pdf|iso|js|css|html|htm|txt|eot|svg|ttf|woff|woff2)$ {
    gzip_static off;
    add_header Access-Control-Allow-Origin *;
    add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    access_log off;
    expires 365d;
    break;
}
```

**Comment by oschaaf** [comment]
Please note the disclaimer for enabling `ForceCaching` from https://developers.google.com/speed/pagespeed/module/filter-cache-extend:

```
This switch is intended for experimental purposes only, to help evaluate the benefit of cache extension against the effort of adding cache-control headers to resources. 
Live traffic should not be served this way.
```

Having said that, usually the `max-age:300` in `Cache-Control` is emitted by pagespeed when it still finishing up optimizations (in which case the `max-age:300` should be replaced by a long TTL shortly).

**Comment by oschaaf** [comment]
@kyvaith closing this issue, feel free to re-open if you think there's a bug with domain authorization.
Also, if you have any further questions don't hesitate to ask them over at https://groups.google.com/forum/#!forum/ngx-pagespeed-discuss
