### ISSUE TITLE
Overriding max TTL with 300s by ngx_pagespeed

### ISSUE THREAD

**Issue by kyvaith** [pagespeed/ngx_pagespeed#1254]
Hi,

I've set ForceCaching flag, and initially all resources have cache-control:max-age=31536000 header. But after few reloads of page, more and more resources gets cache-control:max-age=300,private according to PageSpeed Insights. What could be a reason for that? I have even global config in Nginx like this:

```
location ~* \.(3gp|gif|jpg|jpeg|png|ico|wmv|webp|avi|asf|asx|mpg|mpeg|mp4|pls|mp3|mid|wav|swf|flv|exe|zip|tar|rar|gz|tgz|bz2|uha|7z|doc|docx|xls|xlsx|pdf|iso|js|css|html|htm|txt|eot|svg|ttf|woff|woff2)$ {
    gzip_static off;
    add_header Access-Control-Allow-Origin *;
    add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    access_log off;
    expires 365d;
    break;
}
```

@oschaaf told me in #1251 that ForceCaching flag is for test purpose only and I'm ok with that, but isn't that strange that even with this flag more and more resources get short TTL?

Also @oschaaf siad: 
> usually the max-age:300 in Cache-Control is emitted by pagespeed when it still finishing up optimizations 

But I see reverse situation. All non optimized resources have long TTL, and those optimized have short one: https://developers.google.com/speed/pagespeed/insights/?url=naprawimyto.pl

One more thing - Is it really necessary to apply short TTL to not-yet optimized resources? They are already downloaded, there is no reason to replace them with minified/compressed one ASAP IMO.

Thanks,
Tom.

**Comment by oschaaf** [comment]
RE: "more and more resources gets cache-control:max-age=300,private according to PageSpeed Insights"

What strikes me as odd is that Insights keeps getting a (cache-extended) jpg version served:

```
https://naprawimyto.pl/wp-content/uploads/2016/08/Galeria_00011-870x430.jpg.pagespeed.ce.ImXV83iJsp.jpg
```

While I get the webp version served with chrome (with a long TTL):

```
https://naprawimyto.pl/wp-content/uploads/2016/08/xGaleria_00011-870x430.jpg.pagespeed.ic.CO58ci4Obh.webp
```

I'm not sure why that is yet, I would have thought that PSI would receive the WebP versions as well.

RE: "One more thing - is it really necessary to apply short TTL to not-yet optimized resources? They are already downloaded, there is no reason to replace them with minified/compressed one ASAP IMO."

Someone else may know better but my 2p:
- For responses that are optimized in-place, I believe only a short `s-maxage` header will be set to avoid shared caches from holding on to unoptimized responses too long as of https://github.com/pagespeed/mod_pagespeed/commit/689e3f1a0dd70c8585a2304c044b4408a8da0bc3
- For .pagespeed. urls,  shared caches like proxies also have to be considered. But in addition fully optimized resource urls that get written into html/css will be different from partially optimized ones, and as such setting  a long TTL wouldn't make much sense either (it would be cache unfriendly).

**Comment by kyvaith** [comment]
I was experimenting with different ngx_pagespeed configs for few hours, but without success. Still I get short TTL on PSI test :(
What else could I check?

**Comment by kyvaith** [comment]
Ok, found answer in [https://github.com/pagespeed/mod_pagespeed/issues/989](url) I've set:

```
pagespeed ImplicitCacheTtlMs 31536000000;
pagespeed LoadFromFileCacheTtlMs 31536000000;
```
and now everything work great. Thanks for all help :)

**Comment by jeffkaufman** [comment]
Note: the s-maxage change isn't in any released version of PageSpeed yet; it will be in the next trunk release
