### ISSUE TITLE
A version vs latest-stable vs latest-beta

### ISSUE THREAD

**Issue by nikolay** [pagespeed/ngx_pagespeed#1284]
Can you explain why there are now 3 types of releases and how we should apply this change?

**Comment by jeffkaufman** [comment]
There is one type of release, and it's numeric: N.N.N.N.  For example, 1.11.33.4.

When a release first comes out, it's beta.  After a while, either:
1) the release looks good: we label it stable
2) there are bugs we want to fix before we are ok calling stable: we put out a new release that fixes the bugs

The `latest-beta` and `latest-stable` tags will always point to the most recent release in each category.  Currently they both point to 1.11.33.4, but when 1.12.34.0 is ready we'll update the `latest-beta` tag to point there instead.

**Comment by nikolay** [comment]
Okay, thanks for clarifying! I didn't see that you actually just upgraded the already versioned 1.11.33.4.

**Comment by jeffkaufman** [comment]
Yup, nothing new for people who are already on 1.11.33.4!

(But very excited to be able to call ngx_pagespeed now)
