### ISSUE TITLE
responsive_images doesn't work

### ISSUE THREAD

**Issue by GabrielH0we** [pagespeed/ngx_pagespeed#1290]
Hello.
I'm trying to use responsive_images, but it doesn't work. When there is a dozen images on the page, only a second one have srcset attribute, but it leads to full size images.

It's latest ngx_pagespeed version and nginx-1.11.3 There are fastcgi cache and expire headers enabled.

Here is a config for pagespeed

pagespeed on;
pagespeed FileCachePath /var/ngx_pagespeed_cache;
        pagespeed FileCacheSizeKb            204800;
        pagespeed FileCacheCleanIntervalMs   7200000;
        pagespeed FileCacheInodeLimit        1000000;
        #pagespeed RewriteLevel CoreFilters;
        pagespeed MapOriginDomain "http://<website>" "https://<website>";
        pagespeed LoadFromFileMatch "^https?://<website>" "<path>";
        pagespeed LoadFromFileRuleMatch disallow .*;
        pagespeed LoadFromFileRuleMatch allow \.css$;
        pagespeed LoadFromFileRuleMatch allow \.jpe?g$;
        pagespeed LoadFromFileRuleMatch allow \.png$;
        pagespeed LoadFromFileRuleMatch allow \.gif$;
        pagespeed LoadFromFileRuleMatch allow \.js$;
        pagespeed FetchHttps enable;
        pagespeed UseExperimentalJsMinifier on;
        pagespeed DisableFilters convert_meta_tags;
        pagespeed EnableFilters rewrite_images;
        #pagespeed EnableFilters inline_images;
        #pagespeed EnableFilters prioritize_critical_css;
        #pagespeed EnableFilters combine_css,move_css_above_scripts;
        #pagespeed EnableFilters combine_javascript,rewrite_javascript;
        #pagespeed EnableFilters convert_meta_tags;
        pagespeed EnableFilters convert_jpeg_to_webp;
        pagespeed EnableFilters responsive_images,resize_images;
        #pagespeed EnableFilters insert_dns_prefetch;
        #pagespeed EnableFilters rewrite_css;

**Comment by oschaaf** [comment]
You have these lines, which look a bit odd:

```
pagespeed MapOriginDomain "http://" "https://";
pagespeed LoadFromFileMatch "^https?://" "";
```

Could you change them to something like:

```
pagespeed MapOriginDomain http://www.example.com https://www.example.com;
pagespeed LoadFromFile "https://www.example.com/" "/var/www/";
```

(You should change example.com and /var/www to the actual hostname and www root of your website).

**Comment by GabrielH0we** [comment]
Those line have my website address and path to the folder. I just removed it to paste in here. 
It doesn't work anyway.

**Comment by oschaaf** [comment]
The responsive images filter may write out html comments about why it did not add `srcset` attributes when the debug filter is enabled. 

Can you take a look at the html sources of a relevant page where with `?PageSpeedFilters=+debug` on the querystring?

**Comment by GabrielH0we** [comment]
I don't see anything like that in html source. And nothing in nginx error log.
Will that help me to see if there is any problem? Will making nginx log more verbose help?

pagespeed Statistics on;
pagespeed StatisticsLogging on;
pagespeed LogDir /var/log/pagespeed;

**Comment by oschaaf** [comment]
I had a look at a random page with `?PageSpeedFilters=+debug`, it shows all sorts of messages for me. The most important one may be (anonymized):

```
<!--The preceding resource was not rewritten because its domain (www.foo.ru) is not authorized-->
```

`https://foo.ru/` will be treated as a separate domain to `https://www.foo.ru/` by pagespeed. You could add a `MapOriginDomain` (or `LoadFromFile`) line to the configuration, to both set up and authorize pagespeed to fetch resources from www.foo.ru when serving html from foo.ru

**Comment by GabrielH0we** [comment]
Oh, it's url parameter. 

Here is what I get with it. On both desktop and in mobile screen emulator. 

`<!--ResponsiveImageFilter: Any debug messages after this refer to the virtual 1.5x image with src=https://barbosha.ru/wp-content/uploads/2014/08/xS0530185-1.jpg.pagespeed.ic.OLI_B2X65T.jpg width=1200 height=799--><!--Image does not appear to need resizing.--><!--ResponsiveImageFilter: Any debug messages after this refer to the virtual 2x image with src=https://barbosha.ru/wp-content/uploads/2014/08/xS0530185-1.jpg.pagespeed.ic.OLI_B2X65T.jpg width=1600 height=1066--><!--Image does not appear to need resizing.--><!--ResponsiveImageFilter: Any debug messages after this refer to the virtual 3x image with src=https://barbosha.ru/wp-content/uploads/2014/08/xS0530185-1.jpg.pagespeed.ic.OLI_B2X65T.jpg width=2400 height=1599--><!--Image does not appear to need resizing.--><!--ResponsiveImageFilter: Any debug messages after this refer to the virtual inlinable 3x image with src=https://barbosha.ru/wp-content/uploads/2014/08/xS0530185-1.jpg.pagespeed.ic.OLI_B2X65T.jpg width=2400 height=1599--><!--Image does not appear to need resizing.--><!--The image was not inlined because it has too many bytes.--><!--ResponsiveImageFilter: Any debug messages after this refer to the virtual full-sized image with src=https://barbosha.ru/wp-content/uploads/2014/08/xS0530185-1.jpg.pagespeed.ic.OLI_B2X65T.jpg width= height=--><!--Image does not appear to need resizing.--><img width="800" height="533" src="https://barbosha.ru/wp-content/uploads/2014/08/xS0530185-1.jpg.pagespeed.ic.OLI_B2X65T.jpg" class="attachment-full size-full wp-post-image" alt="Забег на Дне физкультурника в Самаре 9 августа 2014"/><!--ResponsiveImageFilter: Not adding 1x candidate to srcset because it is the same as previous candidate.--><!--ResponsiveImageFilter: Not adding 3x candidate to srcset because it is the same as previous candidate.--><!--ResponsiveImageFilter: Not adding 2x candidate to srcset because it is the same as previous candidate.--><!--ResponsiveImageFilter: Not adding 1.5x candidate to srcset because it is the same as previous candidate.--><!--Image does not appear to need resizing.-->                                        </figure>`

**Comment by hillsp** [comment]
Those messages are saying that there is no benefit to including different sizes because the original image is no bigger than 1x. The responsive images filter works on very large images, scaling them to the right size for different devices. It cannot make small images larger.

**Comment by GabrielH0we** [comment]
So, when you view website from 320px width screen, there is no need to resize 1200px width image? On the page I tested all images have width from 800px to 1200px.

**Comment by jeffkaufman** [comment]
If the size of the image matches the width/height specified in the html then PageSpeed won't resize the image smaller.  Instead, when sending images to small screens PageSpeed compresses the image to a lower quality level. If you would like it to trade off quality for byte savings even more aggressively, you can decrease the values of [JpegRecompressionQualityForSmallScreens](https://developers.google.com/speed/pagespeed/module/reference-image-optimize#JpegRecompressionQualityForSmallScreens) and [WebpRecompressionQualityForSmallScreens](https://developers.google.com/speed/pagespeed/module/reference-image-optimize#WebpRecompressionQualityForSmallScreens).

**Comment by MrBryan** [comment]
I have a site doing exactly what it says - specifying the width and height of the image, which are a fraction of the size of the actual image size and it just sends the giant image to the user

![image](https://cloud.githubusercontent.com/assets/1721891/19500105/2b0e67ce-954f-11e6-8386-ca24b31bd934.png)

**Comment by MrBryan** [comment]
it is rendered at the size I specify in the width/height parameters of course, but I expected pagespeed would generate a resolution appropriate version so the user isn't downloading a 3 meg file, yes?

**Comment by MrBryan** [comment]
sorry i just realized this is for ngx_pagespeed i'll start a new issue

**Comment by jeffkaufman** [comment]
@MrBryan responded on pagespeed/mod_pagespeed#1418
