### ISSUE TITLE
latest-stable can't compile

### ISSUE THREAD

**Issue by eldk** [pagespeed/ngx_pagespeed#1296]
Hello,

download latest-stable from github  to have a try, it can't compile I think for a missnamed in release : 

```
ngx_pagespeed: pagespeed optimization library not found:

   You need to separately download the pagespeed library:

     $ cd /path/to/ngx_pagespeed
     $ wget https://dl.google.com/dl/page-speed/psol/1.11.33.4.tar.gz
     $ tar -xzvf 1.11.33.4.tar.gz # expands to psol/

   Or see the installation instructions:
     https://github.com/pagespeed/ngx_pagespeed#how-to-build
```
Thanks,

Eric

**Comment by jeffkaufman** [comment]
What commands did you run?

**Comment by eldk** [comment]
./configure --add-module=$HOME/pagespeed_new/ngx_pagespeed-${NPS_VERSION} --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --error-log-path=/var/log/nginx/error.log --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi

NPS_VERSION set to latest-stable

**Comment by jeffkaufman** [comment]
You're using the manual steps, not the installer, right?

Does `$HOME/pagespeed_new/ngx_pagespeed-${NPS_VERSION}/psol` exist?

**Comment by eldk** [comment]
no

**Comment by jeffkaufman** [comment]
Did you download psol?

**Comment by eldk** [comment]
NO )))

**Comment by jeffkaufman** [comment]
The instructions have:

```
cd
NPS_VERSION=[check the release notes for the latest version]
wget https://github.com/pagespeed/ngx_pagespeed/archive/release-${NPS_VERSION}-beta.zip
unzip release-${NPS_VERSION}-beta.zip
cd ngx_pagespeed-release-${NPS_VERSION}-beta/
wget https://dl.google.com/dl/page-speed/psol/${NPS_VERSION}.tar.gz
tar -xzvf ${NPS_VERSION}.tar.gz  # extracts to psol/
```

It looks like maybe you skipped the last two steps?

**Comment by jeffkaufman** [comment]
oh, I see the problem, that `wget` will fail

**Comment by eldk** [comment]
And I missed this step

**Comment by jeffkaufman** [comment]
`https://dl.google.com/dl/page-speed/psol/latest-stable.tar.gz` doesn't exist, you need to use the actual version number in the url: https://dl.google.com/dl/page-speed/psol/1.11.33.4.tar.gz`

**Comment by eldk** [comment]
Ok jeff

**Comment by eldk** [comment]
Thanks @jeffkaufman
