### ISSUE TITLE
strip Accept-Ranges: bytes

### ISSUE THREAD

**Issue by jeffkaufman** [pagespeed/ngx_pagespeed#130]
If we're proxying an origin server that sets:

    Accept-Ranges: bytes

we should remove it.  We don't support that because we generate our html on the fly and it's not consistent.

**Comment by tekert** [comment]
Do we need to stript it also for In Place Resource Optimizacion (now on by default)?
ipro images come without Accept-Ranges: bytes currently.
content-length is also striped only in some images, not all.
ver. 1.11.33.2-0

**Comment by huibaolin** [comment]
@jeffkaufman I think we should strip this header for other resources, too.

**Comment by jeffkaufman** [comment]
Yes, we need to strip this for all ipro resources because we don't accept range requests.  Here's a test showing we do currently pass it through:

```
$ headers www.jefftk.com/nolff/foo.css | grep '^Accept-Ranges:\|^Content-Length:'
Accept-Ranges: bytes
Content-Length: 22
```

But we don't handle it:
```
$ curl -H 'Range: bytes=2-5' www.jefftk.com/nolff/foo.css
body{background:green}
```

**Comment by jeffkaufman** [comment]
Since this is also an issue for mod_pagespeed, moving this to https://github.com/pagespeed/mod_pagespeed/issues/1383
