### ISSUE TITLE
configure: error: nowas found

### ISSUE THREAD

**Issue by dikkatdeli** [pagespeed/ngx_pagespeed#1311]
hi;

i install nginx then install again with Automated Install on google dev doc. i noticed that after Automated Install which add additional nginx folder in /usr/local/nginx/ my inital set up files are in /etc/nginx.

i download seperatly nginx and pagespeed. i tried do it more than once but always get this error :
./configure: error: no /home/gedo/custom-nginx/nginx-1.10.2/src/http/modules/ngx_pagespeed//config was found

how can i solve this. 

thanks.

**Comment by jeffkaufman** [comment]
When you install nginx from source, through our installer or not, nginx's installer defaults to putting it's config file in `/usr/local/nginx/conf/` instead of `/etc/nginx`.  The idea is something like `/etc/` being for packages that the distribution installs, while `/usr/local/` is a place it's ok to install things you've built from source.

It's probably possible to pass in an argument to nginx's `./configure` to tell it to put the file somewhere else, but is it actually a problem for them to be under `/usr/local/`?

**Comment by dikkatdeli** [comment]
i am new to linux so it confuse me a lot of time to install someting on it. using ./configure and adding arguments to point to where to install i am totally lost.

Which steps should i follow ? my nginx is working well should i remove the nginx (i will re-install os its much easier for me) start installing nginx ?

i follow like all tutorials and stuck. Could you show me to what to do ?

**Comment by dikkatdeli** [comment]
i install pagespeed.

```
 /usr/local/nginx/sbin/nginx -V
nginx version: nginx/1.10.2
built by gcc 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)
configure arguments: --add-module=/root/ngx_pagespeed-latest-stable --with-cc=/opt/rh/devtoolset-2/root/usr/bin/gcc
```

when i restart service i get this:
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Stopping nginx:                                            [FAILED]
grep: unrecognized option '--add-module=/root/ngx_pagespeed-latest-stable'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
useradd: unrecognized option '--add-module=/root/ngx_pagespeed-latest-stable'
Usage: useradd [options] LOGIN
       useradd -D
       useradd -D [options]

```

**Comment by jeffkaufman** [comment]
Those are pretty weird looking errors!  It sounds like something is passing your `./configure` arguments into `grep` and `useradd`.

Could you paste all the commands you ran to get to that error?

**Comment by dikkatdeli** [comment]
i just rust this : bash <(curl -f -L -sS https://ngxpagespeed.com/install) --nginx-version 1.10.2

say yes everything that comes up

**Comment by jeffkaufman** [comment]
Did you run any commands after that?  What did you run to restart nginx?

**Comment by dikkatdeli** [comment]
just this : service nginx restart

**Comment by jeffkaufman** [comment]
You're saying you ran:

```
bash <(curl -f -L -sS https://ngxpagespeed.com/install) --nginx-version 1.10.2
service nginx restart
```
and no other commands, and got the output:

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Stopping nginx:                                            [FAILED]
grep: unrecognized option '--add-module=/root/ngx_pagespeed-latest-stable'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
useradd: unrecognized option '--add-module=/root/ngx_pagespeed-latest-stable'
Usage: useradd [options] LOGIN
       useradd -D
       useradd -D [options]
```
yes?

Because the output you're giving me looks like something is seriously messed up, in a way I really wouldn't expect from those two commands.

**Comment by dikkatdeli** [comment]
i installed nginx with yum then remove all of them with yum and delete all related directories.

install above command and configure init.d file to point nginx="/usr/local/nginx/sbin/nginx"

thats all.

**Comment by jeffkaufman** [comment]
Could you paste the changes you make to your init.d file?

**Comment by dikkatdeli** [comment]
onyl this part : nginx="/usr/local/nginx/sbin/nginx"

**Comment by jeffkaufman** [comment]
Could you paste the whole init.d file then?

**Comment by dikkatdeli** [comment]
`#!/bin/sh
#
# nginx - this script starts and stops the nginx daemon
#
# chkconfig:   - 85 15
# description:  NGINX is an HTTP(S) server, HTTP(S) reverse \
#               proxy and IMAP/POP3 proxy server
# processname: nginx
# config:      /etc/nginx/nginx.conf
# config:      /etc/sysconfig/nginx
# pidfile:     /var/run/nginx.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

nginx="/usr/local/nginx/sbin/nginx"
prog=$(basename $nginx)

NGINX_CONF_FILE="/etc/nginx/nginx.conf"

[ -f /etc/sysconfig/nginx ] && . /etc/sysconfig/nginx

lockfile=/var/lock/subsys/nginx

make_dirs() {
   # make required directories
   user=`$nginx -V 2>&1 | grep "configure arguments:" | sed 's/[^*]*--user=\([^ ]*\).*/\1/g' -`
   if [ -z "`grep $user /etc/passwd`" ]; then
       useradd -M -s /bin/nologin $user
   fi
   options=`$nginx -V 2>&1 | grep 'configure arguments:'`
   for opt in $options; do
       if [ `echo $opt | grep '.*-temp-path'` ]; then
           value=`echo $opt | cut -d "=" -f 2`
           if [ ! -d "$value" ]; then
               # echo "creating" $value
               mkdir -p $value && chown -R $user $value
           fi
       fi
   done
}

start() {
    [ -x $nginx ] || exit 5
    [ -f $NGINX_CONF_FILE ] || exit 6
    make_dirs
    echo -n $"Starting $prog: "
    daemon $nginx -c $NGINX_CONF_FILE
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -QUIT
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    configtest || return $?
    stop
    sleep 1
    start
}

reload() {
    configtest || return $?
    echo -n $"Reloading $prog: "
    killproc $nginx -HUP
    RETVAL=$?
    echo
}

force_reload() {
    restart
}

configtest() {
  $nginx -t -c $NGINX_CONF_FILE
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart|configtest)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
            ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|configtest}"
        exit 2
esac
`

**Comment by jeffkaufman** [comment]
It looks like your problem is this line:

```
   user=`$nginx -V 2>&1 | grep "configure arguments:" | sed 's/[^*]*--user=\([^ ]*\).*/\1/g' -`
```

It looks like this is assuming that you built nginx with a `--user` argument to `./configure` and trying to extract it in a way that fails badly when it's not found.

In general, reusing exiting initscripts isn't going to work because of problems like this.  Can you set one up following the instructions at http://wiki.nginx.org/InitScripts

**Comment by dikkatdeli** [comment]
i already get the script there : https://www.nginx.com/resources/wiki/start/topics/examples/redhatnginxinit/

should i delete 

`user=`$nginx -V 2>&1 | grep "configure arguments:" | sed 's/[^*]*--user=\([^ ]*\).*/\1/g' -``  part

**Comment by jeffkaufman** [comment]
Yikes, the wiki's init script shouldn't be assuming you compiled with a `--user` argument.

If you delete:

```
 user=`$nginx -V 2>&1 | grep "configure arguments:" | sed 's/[^*]*--user=\([^ ]*\).*/\1/g' -`
   if [ -z "`grep $user /etc/passwd`" ]; then
       useradd -M -s /bin/nologin $user
   fi
```

I think you'll be set.

I'll file a bug with them to fix the wiki.

Thanks!

**Comment by jeffkaufman** [comment]
Reported this to nginx: https://github.com/nginxinc/nginx-wiki/issues/318

**Comment by kimthangatm** [comment]
I use:
```
./configure --add-module=$HOME/ngx_pagespeed-release-${NPS_VERSION}-beta ${PS_NGX_EXTRA_FLAGS} --user=nobody --group=nobody
```
