### ISSUE TITLE
pagespeed works on localhost only

### ISSUE THREAD

**Issue by dikkatdeli** [pagespeed/ngx_pagespeed#1316]
Localhost show pagespeed : 

```
 curl -I localhost
HTTP/1.1 200 OK
Server: nginx/1.10.2
Content-Type: text/html
Connection: keep-alive
Date: Thu, 03 Nov 2016 16:04:03 GMT
X-Page-Speed: 1.11.33.4-0
Cache-Control: max-age=0, no-cache

```

Not other domains : 

```
curl -I http://static.example.com/wp-includes/js/media-views.js
HTTP/1.1 200 OK
Server: nginx/1.10.2
Content-Type: application/javascript
Connection: keep-alive
Access-Control-Allow-Origin: *
Pragma: public
X-Original-Content-Length: 124784
Vary: Accept-Encoding
Vary: Accept-Encoding
Content-Length: 124784
ETag: W/"PSA-aj-LsGdicHnXD"
Date: Thu, 03 Nov 2016 16:05:03 GMT
Expires: Sun, 01 Nov 2026 15:02:48 GMT
Cache-Control: max-age=315356264, public
```

**Comment by jeffkaufman** [comment]
It looks like PageSpeed is working on both requests.  For HTML we set `X-Page-Speed: 1.11.33.4-0`, while for resources we optimize in-place we set `ETag: W/"PSA-aj-...`

**Comment by jchevali** [comment]
@jeffkaufman Thanks for your input. I've been rebuilding it and reconfiguring it all day, looking for an X-Page-Speed header. I've seen "ETag" plenty of times though, so it probably was working all day (sigh)

Someone ought to update the [Official FAQ](https://developers.google.com/speed/pagespeed/module/faq) as that specifically tells us to look for X-Page-Speed (emphasis is mine):
> If you don't see an X-Mod-Pagespeed header (Apache) or X-Page-Speed header (Nginx), this means that your webserver isn't letting PageSpeed run. This could be because it isn't actually installed, you don't have it turned on in the configuration file, _or many other reasons_.

**Comment by jeffkaufman** [comment]
@jchevali updated the FAQ, thanks!
