### ISSUE TITLE
zero_copy_stream_impl_lite.h not found

### ISSUE THREAD

**Issue by froilanmendoza** [pagespeed/ngx_pagespeed#1318]
Installing ngx_pagespeed from master.zip (which I assume is 1.11.33.3) and psol 1.11.33.3 on nginx 1.10.0...  No error on configure but I get this when I do a make:

`		/home/fmendoza/nginx-1.10/nginx-1.10.0/src/http/modules/ngx_pagespeed/src/ngx_base_fetch.cc
In file included from /home/fmendoza/nginx-1.10/nginx-1.10.0/src/http/modules/ngx_pagespeed/psol/include/pagespeed/kernel/http/headers.h:24:0,
                 from /home/fmendoza/nginx-1.10/nginx-1.10.0/src/http/modules/ngx_pagespeed/psol/include/pagespeed/kernel/http/response_headers.h:24,
                 from /home/fmendoza/nginx-1.10/nginx-1.10.0/src/http/modules/ngx_pagespeed/src/ngx_pagespeed.h:38,
                 from /home/fmendoza/nginx-1.10/nginx-1.10.0/src/http/modules/ngx_pagespeed/src/ngx_base_fetch.cc:19:
/home/fmendoza/nginx-1.10/nginx-1.10.0/src/http/modules/ngx_pagespeed/psol/include/pagespeed/kernel/base/proto_util.h:24:59: fatal error: google/protobuf/io/zero_copy_stream_impl_lite.h: No such file or directory
 #include "google/protobuf/io/zero_copy_stream_impl_lite.h"
                                                           ^
compilation terminated.
make[1]: *** [objs/addon/src/ngx_base_fetch.o] Error 1
make[1]: Leaving directory `/home/fmendoza/nginx-1.10/nginx-1.10.0'
make: *** [build] Error 2
`
For reference, configure is:
sudo ./configure --prefix=/usr/local/nginx-new --with-http_v2_module --with-http_ssl_module --add-module=/home/fmendoza/nginx_brotli/ngx_brotli --add-module=/home/fmendoza/nginx-1.10/nginx-1.10.0/src/http/modules/ngx_pagespeed --user=nobody --group=nobody --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid ${PS_NGX_EXTRA_FLAGS}

Any help appreciated.  Thank you.

**Comment by jeffkaufman** [comment]
master.zip isn't right.  The correct instructions are https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source

**Comment by froilanmendoza** [comment]
Got it, thanks.  Compiled and working fine now.
