### ISSUE TITLE
Version 1.12.34.1 missing net/instaweb/public/version.h

### ISSUE THREAD

**Issue by Lofesa** [pagespeed/ngx_pagespeed#1335]
Hi all
I tried to compile the new version 1.12.34.1-beta (well, I use my own modified spec file to build rpm packages and found that the pagespeed_automatic.a debug file does not exist. As a workaround I copied the Release version in the apropiate directory Debug/linux/x64) and get the error that the file net/instaweb/public/version.h does not exists when compiling log_message_handler.cc that has  that line #include "net/instaweb/public/version.h"
Any clue on this issue? Can I safely comment these line?
Also I get other error 
In file included from /home/builder/rpmbuild/BUILD/nginx-1.11.6/ngx_pagespeed-1.12.34.1-beta/src/ngx_base_fetch.cc:27:0:
/home/builder/rpmbuild/BUILD/nginx-1.11.6/ngx_pagespeed-1.12.34.1-beta/psol/include/net/instaweb/rewriter/public/rewrite_driver.h:31:52: fatal error: net/instaweb/rewriter/cached_result.pb.h: No such file or directory
I found a cached_result.proto, that calls other .proto files in the master branch of net/instaweb/rewriter/, but these files (the .proto) are missing in the downloaded version
Thx in advance

**Comment by jeffkaufman** [comment]
This sounds like the same issue as in https://github.com/pagespeed/ngx_pagespeed/issues/1333 ; I'm going to close this one and respond on #1333

**Comment by Lofesa** [comment]
Yes, I disbled the --with-debug option in the spec file and thus compile .... thx

**Comment by leofeyer** [comment]
Actually, this is not the same as #1333. The file `net/instaweb/public/version.h` does not exist in the `Release` folder, therefore the debug build fails.

<img width="797" alt="" src="https://cloud.githubusercontent.com/assets/1192057/21239473/5561a1fe-c307-11e6-9f94-3db54f803043.png">
