### ISSUE TITLE
Enable passing nginx ./configure parameters to build_ngx_pagespeed.sh when using --assume-yes

### ISSUE THREAD

**Issue by dev169** [pagespeed/ngx_pagespeed#1340]
This would allow automated installs to configure `nginx` properly before building, without user intervention. Surely `--with-http_ssl_module` is pretty common these days, it's a shame having to forgo `--assume-yes` because of this.

**Comment by jeffkaufman** [comment]
You're right, we should definitely have this.  Working on this today.
