### ISSUE TITLE
No filter seems to be working

### ISSUE THREAD

**Issue by aristidesfl** [pagespeed/ngx_pagespeed#1348]
http://134.119.32.58:81/test.html

The image tag gets replaced in the html, but the image is not resized, optimised or converted.

nginx/1.11.7
page-speed 1.11.33.4-0

```
    pagespeed on;
    pagespeed FileCachePath /var/ngx_pagespeed_cache;
    pagespeed EnableFilters convert_jpeg_to_webp;
    pagespeed EnableFilters rewrite_images;
    pagespeed EnableFilters resize_rendered_image_dimensions;
```
```
  index index.html index.htm index.nginx-debian.html;

  server_name _;

  location / {
    # First attempt to serve request as file, then
    # as directory, then fall back to displaying a 404.
    try_files $uri $uri/ =404;
  }

  location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
   add_header "" "";
  }
  location ~ "^/pagespeed_static/" { }
  location ~ "^/ngx_pagespeed_beacon$" { }
```

**Comment by aristidesfl** [comment]
```
tmpfs      on  /var/ngx_pagespeed_cache    type  tmpfs     (rw,nosuid,nodev,noexec,nodiratime,relatime,size=1048576k)
```
Any ideas on how to troubleshoot further?

**Comment by oschaaf** [comment]
Requesting the html source with the debug filter enabled dit not result in any helpful comments.
But the image that the html references is quite big, you may be running into a size limit:
https://developers.google.com/speed/pagespeed/module/reference-image-optimize#ImageResolutionLimitBytes

Could you bump that and see if that helps?

**Comment by aristidesfl** [comment]
@oschaaf thanks that was the problem. now just resize_rendered_image_dimensions not working https://github.com/pagespeed/ngx_pagespeed/issues/1351
