### ISSUE TITLE
Use LazyloadImagesBlankUrl gives security alert in Firefox

### ISSUE THREAD

**Issue by eldk** [pagespeed/ngx_pagespeed#1358]
Hello,

Use url given in doc,  https://modpagespeed.com/doc/filter-lazyload-images#lazyload-blank-url , gives a security alert in Firefox  50.1.0 .

I have tryed with pagespeed LazyloadImagesBlankUrl "https://www.gstatic.com/psa/static/1.gif";

Then it's OK.

Maybe Pagespeed doc should alert on this.

Thanks,

Eric

**Comment by jeffkaufman** [comment]
You're right, there's no reason to be listing an http-served image there.  https://github.com/pagespeed/mod_pagespeed/pull/1476 switches this to https.

**Comment by eldk** [comment]
Thanks

**Comment by jeffkaufman** [comment]
Fix deployed!
