### ISSUE TITLE
Flattening failed: Cannot import https://fonts.googleapis.com for an unknown reason

### ISSUE THREAD

**Issue by eldk** [pagespeed/ngx_pagespeed#1359]
Hello,

I use nginx_pagespeed 1.12.34.2

I have this message in pagespeed debug : "Flattening failed: Cannot import https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,900 for an unknown reason".

CSS is like this : 
`@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,900);`

I Have some pagespeed Allow and Disallow directives with : 
`pagespeed Disallow "*";`
  	`pagespeed Allow "https://fonts.googleapis.com/*";`
        `pagespeed Allow "https://myword.domain.tld/*";`
         `pagespeed Disallow "https://myword.domain.tld/folder/one.js";` 

and no more Allow/Disallow  rules.

Before Allowing https://fonts.googleapis.com, the error message was "Cannot import https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,900 as it is on an unauthorized domain"

Thus I have : 
`pagespeed Domain https://fonts.googleapis.com;`
`pagespeed FetchHttps enable;` # done for google fonts
    `pagespeed GoogleFontCssInlineMaxBytes 5000;`
  	`pagespeed EnableFilters inline_google_font_css`

I have tryed the directives as giving in : 
https://modpagespeed.com/doc/filter-css-inline-google-fonts
https://github.com/pagespeed/ngx_pagespeed/issues/1183

My conf is : 

>Filters
cw	Collapse Whitespace
jc	Combine Javascript
gp	Convert Gif to Png
jp	Convert Jpeg to Progressive
jw	Convert Jpeg To Webp
pj	Convert Png to Jpeg
wa	Convert animated images to WebP
ws	When converting images to WebP, prefer lossless conversions
dj	Defer Javascript
hw	Flushes html
gf	Inline Google Font CSS
io	In-place optimize for browser
idp	Insert DNS Prefetch
js	Jpeg Subsampling
ll	Lazyload Images
pr	Prioritize Critical Css
rj	Recompress Jpeg
rp	Recompress Png
rw	Recompress Webp
rc	Remove Comments
jm	Rewrite External Javascript
cp	Strip Image Color Profiles
md	Strip Image Meta Data

>Options
  AvoidRenamingIntrospectiveJavascript (aris)  True
  BeaconUrl (bu)                               /ngx_pagespeed_beacon
  DefaultSharedMemoryCacheKB (dsmc)            5120
  EnableRewriting (e)                          1
  FetchHttps (fhs)                             enable
  FileCacheInodeLimit (afcl)                   500000
  FileCachePath (afcp)                         /var/cache/pagespeed/
  GlobalAdminPath (ngap)                       /pagespeed_global_admin
  GoogleFontCssInlineMaxBytes (gfci)           5000
  ImageResolutionLimitBytes (irlb)             128000000 ***
  ImplicitCacheTtlMs (ict)                     310987340000
  LazyloadImagesBlankUrl (llbu)                https://www.gstatic.com/psa/static/1.gif
  LoadFromFileCacheTtlMs (lfct)                310987340000
  LogDir (ald)                                 /var/log/pagespeed
  RequestOptionOverride (roo)                  ******
  RewriteLevel (l)                             Optimize For Bandwidth
  Statistics (ase)                             True
  StatisticsLogging (asle)                     True
  StatisticsLoggingIntervalMs (asli)           60000
  StatisticsLoggingMaxFileSizeKb (aslfs)       1024
  UrlSigningKey (usk)                         ********
Domain Lawyer
  http://myword.domain.tld/ Auth
  https://fonts.googleapis.com/ Auth
  https://myword.domain.tld/ Auth

***
 ImageResolutionLimitBytes (irlb)             128000000 ***
 this is big, because I use IPRO to rewrite and cache pictures before to send them to one Android app.

Error is given from the front page that have no big picture embedded.

Thanks,

Eric

**Comment by morlovich** [comment]
inline_google_font_css sadly doesn't work with @import; and the error message is probably because of CSS flattening attempt getting confused. If the @import is inside a <style> block inline_import_to_link might work, but otherwise I am afraid this is a missing feature.

**Comment by eldk** [comment]
Ok,
I will try the suggested workaround.
Thanks,
Eric
