### ISSUE TITLE
Pagespeed automated install. Current nginx didn't update

### ISSUE THREAD

**Issue by jericopulvera** [pagespeed/ngx_pagespeed#1366]
nginx version: nginx/1.10.0 (Ubuntu)

so when I run this it should give me a latest nginx with pagespeed.
bash <(curl -f -L -sS https://ngxpagespeed.com/install) \
     --nginx-version latest

but nothing happens. nginx version stays the same.
and when I add pagespeed on;
it says pagespeed directive not found.

**Comment by jeffkaufman** [comment]
How are you starting nginx?  If you're using an init script provided by your distro you'll need to edit it to use your newly built nginx.

**Comment by jericopulvera** [comment]
@jeffkaufman how do I edit it?

**Comment by jericopulvera** [comment]
still can't find the solution. I have tried doing this 
/usr/local/nginx/sbin/nginx -c /usr/local/nginx/conf/nginx.conf from issue #722 

after this

bash <(curl -f -L -sS https://ngxpagespeed.com/install) 
--nginx-version latest

then I got this error
```
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] still could not bind()
```
then I have killed the nginx process using sudo fuser -k 80/tcp as stated in here
https://easyengine.io/tutorials/nginx/troubleshooting/emerg-bind-failed-98-address-already-in-use/
then start nginx again.

because of this command /usr/local/nginx/sbin/nginx -c /usr/local/nginx/conf/nginx.conf 
I assumed that I can run the nginx which have been automatically installed by bash. 

but I still got this error [emerg] unknown directive "pagespeed"

**Comment by jericopulvera** [comment]
what should I do? what is the proper way to do this from the start?
I'm using ubuntu 16.04

**Comment by oschaaf** [comment]
@jericopulvera it may be easiest to install ngx_pagespeed as a dynamic module in your case, where you have nginx installed by the distribution :
```
  -m, --dynamic-module
      Build ngx_pagespeed as a dynamic module.
```

This should give you `ngx_pagespeed.so`.
You can use that to run ngx_pagespeed by adding this (early on in the file) to `nginx.conf`:

```
load_module "/path/to/ngx_pagespeed.so";
```
