### ISSUE TITLE
Pagespeed On as a variable?

### ISSUE THREAD

**Issue by ciarans** [pagespeed/ngx_pagespeed#1367]
Is it possible to have Pagespeed on as a variable?

We are using lua and openresty to set a list variables and was wondering if its possible with the pagespeed main on/off variable? We have got EnableFilters working.

```nginx
pagespeed on; #on/off
pagespeed EnableFilters "$pagespeed_vars";
```

We have tried 

```nginx
set $pagespeed_on "on";
pagespeed $pagespeed_on; #on/off
pagespeed EnableFilters "$pagespeed_vars";
```

```nginx
set $pagespeed_on on;
pagespeed "$pagespeed_on"; #on/off
pagespeed EnableFilters "$pagespeed_vars";
```

but have had no success and cant see anything in the docs. Is this possible?

We have ``pagespeed ProcessScriptVariables all;`` enabled

**Comment by oschaaf** [comment]
I had a look, and unfortunately supporting scripting of `pagespeed on|off` would need some additional handling to get it to work.

You maybe able to get close to what you want by conditionally disabling filters plus toggling `InPlaceResourceOptimization`?

**Comment by ciarans** [comment]
@oschaaf will give this ago, and let you guys know how I get on. Thank you!

**Comment by ciarans** [comment]
@oschaaf I managed to fix this by simply setting the PageSpeed=off header
