### ISSUE TITLE
second automated pagespeed install fails

### ISSUE THREAD

**Issue by jenniferlianne** [pagespeed/ngx_pagespeed#1368]
I used 

`bash <(curl -f -L -sS https://ngxpagespeed.com/install) --nginx-version latest  -a "MY_OPTION_MODULES"
`

To install nginx with pagespeed on ubuntu 14.04 which already had nginx installed via apt.  The build worked, but it installed to the wrong place using the wrong configuration files.  I wanted the configuration to be exactly the same as the ubuntu distribution, so I tried to compile again with a prefix and sbin path:

`bash <(curl -f -L -sS https://ngxpagespeed.com/install) --nginx-version latest  -a "--prefix=/etc/nginx --sbin-path=/usr/sbin MY_OPTION_MODULES"
`

But running the install script a second time fails at the link stage with "multiple definition" errors.  This happens whether I include the new directory options or not.  It is mysterious, because the install script rm's both build directories, so I'm not sure what the problem could be.  

> objs/addon/src/log_message_handler.o: In function `std::string::_M_data() const':
/home/ubuntu/ngx_pagespeed-latest-stable/src/log_message_handler.cc:101: multiple definition of `net_instaweb::log_message_handler::Install(ngx_log_s*)'
objs/addon/src/log_message_handler.o:/home/ubuntu/ngx_pagespeed-latest-stable/src/log_message_handler.cc:101: first defined here
objs/addon/src/ngx_base_fetch.o: In function `std::string::_M_data() const':
/home/ubuntu/ngx_pagespeed-latest-stable/src/ngx_base_fetch.cc:350: multiple definition of `net_instaweb::NgxBaseFetch::IsCachedResultValid(net_instaweb::ResponseHeaders const&)'
objs/addon/src/ngx_base_fetch.o:/home/ubuntu/ngx_pagespeed-latest-stable/src/ngx_base_fetch.cc:350: first defined here
objs/addon/src/ngx_base_fetch.o: In function `basic_ostream':

**Comment by oschaaf** [comment]
I fail to reproduce this. Could this be a permission problem caused by running one install with `sudo` and the other without? Are the build directories *really* removed?

**Comment by jenniferlianne** [comment]
Thanks for your help, it was my fault.  I had written a script to pull in modules from the existing nginx installation so I wouldn't lose any.  My script passed pagespeed into the -a of the install script on the second pass.  This resulted in the pagespeed files being linked twice.

I've seen a recommendation on another thread to dynamically link pagespeed to an existing installation to avoid headaches.  Why not have the install script stop and suggest this if there's a nginx already present?

**Comment by oschaaf** [comment]
That is a nice idea. I filed a feature request for that: https://github.com/pagespeed/ngx_pagespeed/issues/1369
