### ISSUE TITLE
Failed to load PageSpeed Console

### ISSUE THREAD

**Issue by 7s3** [pagespeed/ngx_pagespeed#1370]
X-Page-Speed: 1.12.34.2-0

I've run into the problem where navigating to:
http://domain.com/pagespeed_admin/console
http://domain.com/pagespeed_console

Returns the error:
> Failed to load PageSpeed Console because:
StatisticsLogging is not enabled.
LogDir is not set.

pagespeedstatslog.conf:
```
pagespeed Statistics on;
pagespeed StatisticsLogging on;
pagespeed LogDir /var/log/pagespeed;
```

pagespeedhandler.conf:

```
location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" { add_header "" ""; }
location ~ "^/pagespeed_static/" { }
location ~ "^/ngx_pagespeed_beacon$" { }
location /ngx_pagespeed_statistics { allow 127.0.0.1; allow 26.5.182.201; allow 2601:640:7200:b3:fa53:43f3:43hf:f35t; deny all; }
location /ngx_pagespeed_global_statistics { allow 127.0.0.1; allow 26.5.182.201; allow 2601:640:7200:b3:fa53:43f3:43hf:f35t; deny all; }
location /ngx_pagespeed_message { allow 127.0.0.1; allow 26.5.182.201; allow 2601:640:7200:b3:fa53:43f3:43hf:f35t; deny all; }
location /pagespeed_console { allow 127.0.0.1; allow 26.5.182.201; allow 2601:640:7200:b3:fa53:43f3:43hf:f35t; deny all; }
location ~ ^/pagespeed_admin { allow 127.0.0.1; allow 26.5.182.201; allow 2601:640:7200:b3:fa53:43f3:43hf:f35t; deny all; }
location ~ ^/pagespeed_global_admin { allow 127.0.0.1; allow 26.5.182.201; allow 2601:640:7200:b3:fa53:43f3:43hf:f35t; deny all; }
```

What's odd is that everything else works in PageSpeed Admin except for the Console. 
Anyone have an idea what could be wrong?
Thanks!

**Comment by oschaaf** [comment]
Testing with `1.12.34.2`, the console works for me. So I suspect there may be something with your configuration. Where are you including `pagespeedstatslog.conf`?

**Comment by 7s3** [comment]
So...I guess I found the problem.
In my vhost domain.com.conf I was including these three lines but they were commented out:

```
# ngx_pagespeed & ngx_pagespeed handler
#include /usr/local/nginx/conf/pagespeed.conf;
#include /usr/local/nginx/conf/pagespeedhandler.conf;
#include /usr/local/nginx/conf/pagespeedstatslog.conf;
```
I guess I didn't even think to check in the vhost configuration. Uncommenting just the third line allows me to see the console. Should I uncomment all three?

**Comment by oschaaf** [comment]
The lines in pagespeedhandler.conf are recommended to include. Im not sure what the contents of pagespeed.conf is. Happy to hear you got the console working!
