### ISSUE TITLE
memcached unix socket ?

### ISSUE THREAD

**Issue by centminmod** [pagespeed/ngx_pagespeed#1378]
was memcached unix socket ever added ?

I tried unsuccessfully using

```
  pagespeed MemcachedThreads 1;
  #pagespeed MemcachedServers "localhost:11211";
  pagespeed MemcachedServers "unix:///var/run/memcached/memcached1.sock:0";
  pagespeed MemcachedTimeoutUs 100000;
```

`nginx: [emerg] "pagespeed" directive "MemcachedServers unix:///var/run/memcached/memcached1.sock:0" Cannot set option MemcachedServers to unix:///var/run/memcached/memcached1.sock:0. Expected single server in format <host>[:<port>] in /usr/local/nginx/conf/pagespeed.conf:32`

**Comment by oschaaf** [comment]
No that was not added. UDS support for memcached and redis is tracked here: https://github.com/pagespeed/mod_pagespeed/issues/760

**Comment by centminmod** [comment]
thanks @oschaaf could of sworn that https://github.com/pagespeed/mod_pagespeed/issues/760 was marked as closed, so thought it was added heh
