### ISSUE TITLE
Nginx pagespeed modsecurity

### ISSUE THREAD

**Issue by ubuntutest** [pagespeed/ngx_pagespeed#1381]
Hello
I tried everything but I do not know how to solve that.
I'm using ubuntu 16
I installed nginx from the official repo, but then I realized that for PageSpeed I have to use a different version:
`https://modpagespeed.com/doc/build_ngx_pagespeed_from_source`
Now I would like to also install ModSecurity, but I can not figure out how.
ModSecurity and PageSpeed have their own version of nginx to compile
Is there a way to install on ubuntu16 nginx with PageSpeed and ModSecurity?

**Comment by morlovich** [comment]
You basically just need to do the preparation steps for both, and then
pass in two
--add-module=
arguments to nginx's configure script, with paths to both modules.

**Comment by ubuntutest** [comment]
Could you be more detailed?
I compile with the same link that I find here?
https://modpagespeed.com/doc/build_ngx_pagespeed_from_source
I have to download ModSecurity and place it in the correct folder, then when compiling i do --add_module ModSecurity ?

**Comment by oschaaf** [comment]
When you run the script linked on that page, eventually you will get:

```
About to build nginx.  Do you have any additional ./configure
arguments you would like to set?  For example, if you would like
to build nginx with https support give --with-http_ssl_module
If you don't have any, just press enter.
```

This is where you can pass in something like `--add-module=/path/to/modsecurity-version/nginx/modsecurity`

**Comment by ubuntutest** [comment]
I'm getting the following error, i'm trying to compile it with https support and naxsi too
```
./configure: error: invalid option "--add_module=/root/naxsi-master"
Error: Failure running './configure --add-module=/root/ngx_pagespeed-latest-stable --with-http_ssl_module --add_module=/root/naxsi-master', exiting.
```

**Comment by oschaaf** [comment]
I think you need `--add-module` instead of `--add_module`
