### ISSUE TITLE
In amp pages inline_google_font_css must be disabled

### ISSUE THREAD

**Issue by Lofesa** [pagespeed/ngx_pagespeed#1382]
When the filter inline_google_font_css is enabled, amp pages throw an error in amp test because the label <style> is not allowed but must be <style amp-custom> so in amp pages the filter must be disabled or label changed

**Comment by morlovich** [comment]
Looks like only a single amp-custom is permitted, and we might not be able to tell if there is another one, so likely the best we can do is just autodisable...

**Comment by Lofesa** [comment]
Disabled better than nake a rule to disable it in server config

**Comment by jansent** [comment]
+1 on this. It'd be great if there was an easy way to combine the inlined font with the amp-custom inlined styles, or alternatively if amp spec was updated to allow for deferred styles or better support for their own fonts.

**Comment by morlovich** [comment]
Should be fixed with that.

**Comment by jansent** [comment]
Wow thanks!
