### ISSUE TITLE
Pagespeed phpmyadmin problem

### ISSUE THREAD

**Issue by ubuntutest** [pagespeed/ngx_pagespeed#1385]
Hello,
I'm using apache with nginx as reverse proxy.
If I include Page Speed, the ../phpmyadmin page loads and becomes blank.
If I exclude Page Speed phpmyadmin working properly.
How can I fix the problem?
Thank you

**Comment by oschaaf** [comment]
Disallowing the path may help:

```
pagespeed Disallow */phpmyadmin *
```

I would love to know a bit more about the problem though.
What does the html source of the blank page look like? And the response headers?

Are there any warnings or errors in the browser dev console when you receive the blank page? 
Or in nginx's error logs?

**Comment by ubuntutest** [comment]
Hi, thanks for answer,

"What does the html source of the blank page look like? And the response headers?" phpmyadmin is visible for only a second then it disappear, white page and clean console, no errors

Nginx error.log:
`2017/02/24 16:21:44 [error] 11210#11210: *2 FastCGI sent in stderr: "Unable to open primary script: /var/www/html/index.php (No such file or directory)", client: MYIPADDRESS, server: www.MYDOMAIN.it, request: "GET /icons/ubuntu-logo.png HTTP/1.1", host: "www.MYDOMAIN.it", referrer: "http://www.MYDOMAIN.it/"`

If i add pagespeed Disallow */phpmyadmin * in pagespeed.conf, i get the following erro:
`nginx[10997]: nginx: [emerg] invalid number of arguments in "pagespeed" directive in /etc/nginx/pagespeed.conf:8`

**Comment by oschaaf** [comment]
Ugh sorry, that should have been 
```
pagespeed Disallow */phpmyadmin*
````

I accidentally put in whitespace.

**Comment by ubuntutest** [comment]
Still the same error:
`nginx[11585]: nginx: [emerg] "pagespeed" directive "Disallow" not recognized or too many arguments in /etc/nginx/pagespeed.conf:8`
But on line 8 i have this:
`    pagespeed FileCachePath /var/cache/pagespeed_cache;`

This is strange

**Comment by oschaaf** [comment]
The configuration line should end with `;`

Do you get the `FastCGI sent in stderr: "Unable to open primary script"...` error line without ngx_pagespeed?
A quick search for it shows that it is likely a permissions problem.

**Comment by ubuntutest** [comment]
Thank you bro.. that was the `;` I am embarrassed for this.
No more erros in error.log
Phpmyadmin working good.

**Comment by oschaaf** [comment]
At the moment I cannot relate the log message to anything specific to ngx_pagespeed. Therefore I would like to assume this issue resolved. If the FastCGI error message starts up showing more frequently we can re-open this.
