### ISSUE TITLE
ngx_pagespeed_beacon ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by dannymichel** [pagespeed/ngx_pagespeed#1386]
I have included location ~ "^/ngx_pagespeed_beacon$ps_dollar" { } in my server { } block but get this error.
`ngx_pagespeed_beacon ERR_BLOCKED_BY_CLIENT`

**Comment by oschaaf** [comment]
Do you use any extensions in Chrome that may block requests?

**Comment by dannymichel** [comment]
I feel stupid
It must be ublock
