### ISSUE TITLE
Downstream Caching Purge returns 403

### ISSUE THREAD

**Issue by dlucenario** [pagespeed/ngx_pagespeed#1387]
Good Day!

I've configured downstream caching on my reverse proxy server based from this [guide](https://modpagespeed.com/doc/downstream-caching). I'm currently using the PURGE method as a means to purge my cache when PageSpeed is not yet done writing. However, when I checked my logs it returns a 403 HTTP status on the PURGE method. This is when I visit my site as the purge occurs as a **background process**. When I  try to purge my cache directly via curl on my server, it returns 200. 

![nginx-pagespeed-concern](https://cloud.githubusercontent.com/assets/7834465/23446686/9681c95c-fe80-11e6-9b64-f36349e2db69.png)

Both logs are recorded coming from the **same IP address**.

**Comment by oschaaf** [comment]
To figure out why one of these requests gets a 403 response, it would be helpful to see the exact http request that nginx receives for both of them, so we can compare. If you set up nginx for debugging, those will be logged: http://nginx.org/en/docs/debugging_log.html

**Comment by dlucenario** [comment]
Thanks for the response. I've intercepted the headers to find out the difference between the two request and compared them. Looks like the '**User-Agent**' header is the one causing the 404. I don't know why. 

curl --header "Cache-Control: no-store, no-cache" --header "X-PSA-Purge-Request: 1" --header "User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Mobile Safari/537.36 (mod_pagespeed/1.12.34.2-0)" --header "Accept-Language: en-US" --request PURGE "http://www.example.com:80" **(returns 404)**

curl --header "Cache-Control: no-store, no-cache" --header "X-PSA-Purge-Request: 1" --header "Accept-Language: en-US" --request PURGE "http://www.example.com:80" **(returns 200)**

**Comment by dlucenario** [comment]
Further testing shows that the **mod_pagespeed** keyword in the User-Agent field results to 40* errors.

**Comment by oschaaf** [comment]
I am wondering: do you observe unoptimized or partially optimized html getting served from cache for long timespans? I think that that would be the consequence if `PURGE` requests originating from the module do not succeed.

A `PURGE` request that originates from the module may not return a 200/OK, when there's no actual html document in cache, but this is not something I think we need to worry about, unless it there is a consequence (e.g. stale untoptimized html continues to get served to browsers).

**Comment by dlucenario** [comment]
I've checked the logs, and at first it wasn't being optimized. I assumed it was something related with the PURGE request not having a 200/OK response. However, when I double checked my configuration it seems the **FileCacheCleanIntervalMs** was set to an extremely low number. Changing this to a higher number or a negative number resulted to the page being optimized.

Thanks for the response.
