### ISSUE TITLE
Failed to load resource: net::ERR_RESPONSE_HEADERS_TOO_BIG

### ISSUE THREAD

**Issue by allaire** [pagespeed/ngx_pagespeed#1388]
I get this error in Chrome console on some of CSS files. It happens intermittently, but when it does, the CSS of my website isn't showing correctly:

![pasted_image_at_2017_03_01_08_20_pm](https://cloud.githubusercontent.com/assets/304461/23508728/113bafdc-ff21-11e6-905c-30649a165408.png)

I haven't found a pattern yet. I tried `touch /var/ngx_pagespeed_cache/cache.flush` and reload right after, thinking it was a cache refreshing issue, but nope. When I get this error, the css has its original filename, not the pagespeed rewritten one (strangely, all the other files in the request are rewritten)

I was able to reproduce it by hitting refresh multiple times.

```
  ##
  # Pagespeed Settings
  ##

  pagespeed on;
  pagespeed FileCachePath /var/ngx_pagespeed_cache;
  pagespeed Disallow "*/wp-content/plugins/easy-swipebox/public/img/*";
  pagespeed DisableFilters recompress_images;

  # Ensure requests for pagespeed optimized resources go to the pagespeed handler
  # and no extraneous headers get set.
  location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
    add_header "" "";
  }

  location ~ "^/pagespeed_static/" { }
  location ~ "^/ngx_pagespeed_beacon$" { }
```

**Comment by oschaaf** [comment]
Could you run `curl -vv http://foo.com/css-file-with-large-headers.css` and post the output here?

**Comment by allaire** [comment]
@oschaaf Sure: https://gist.github.com/allaire/a4dc5a55439109ca5eee7caeb0a9f316

**Comment by jmarantz** [comment]
I wonder where all the vary:accept-encodings come from....

**Comment by oschaaf** [comment]
This looks like https://github.com/pagespeed/ngx_pagespeed/issues/1064
I think it's been resolved completely on `1.12.X` [1]..  The website is running `1.11.33.2`.

If you cannot upgrade, but are able to patch/rebuild the version you are currently running, there is a patch which I think will apply cleanly, and suppresses the symptom:
https://github.com/pagespeed/ngx_pagespeed/issues/1064#issuecomment-179676420

[1] https://github.com/pagespeed/ngx_pagespeed/issues/1064#issuecomment-193904280

**Comment by oschaaf** [comment]
No but you can use 1.12.34.1. See https://github.com/pagespeed/mod_pagespeed/issues/968#issuecomment-283689541

It would be great it if you could confirm the fix!

**Comment by allaire** [comment]
@oschaaf I successfully installed the latest beta using the URLs bellow:

```
default["nginx"]["pagespeed"]["version"] = "1.12.34.2"
default["nginx"]["pagespeed"]["url"]     = "https://github.com/pagespeed/ngx_pagespeed/archive/v1.12.34.2-beta.tar.gz"
default["nginx"]["psol"]["url"]          = "https://dl.google.com/dl/page-speed/psol/1.12.34.2-x64.tar.gz"
```

The psol URL should be listed somewhere :D I found the right one when the pagespeed compile failed. I was missing the `x64` part (although https://dl.google.com/dl/page-speed/psol/1.11.33.4.tar.gz does have it 🤔 )

Running `curl -vv` again doesn't spit all the `vary:accept-encodings` headers. Is this a sign that it should be fixed?

Thank you very much for the support 🍻

**Comment by oschaaf** [comment]
@allaire Thanks for the feedback, that sounds good. 
I'll check in in a week and ask you if you can run the curl command one more time. If they're still gone by then, I think we can safely consider this fixed.

**Comment by allaire** [comment]
@oschaaf Great thanks so much!

One last thing, is there a place or a naming standard for the psol archive?

**Comment by oschaaf** [comment]
@allaire See https://github.com/pagespeed/ngx_pagespeed/issues/1337, and https://github.com/pagespeed/ngx_pagespeed/issues/1337#issuecomment-266844908 in particular.

**Comment by allaire** [comment]
Yay thanks!

**Comment by allaire** [comment]
@oschaaf Everything is running smooth now, no more issues. Thanks again for helping me out, really appreciated 👍
