### ISSUE TITLE
502 error

### ISSUE THREAD

**Issue by bhanu0403** [pagespeed/ngx_pagespeed#1390]
![502](https://cloud.githubusercontent.com/assets/19969681/23649836/efd72410-0345-11e7-8482-67d0dcb78213.png)
502 Bad Gateway Error nginx

**Comment by oschaaf** [comment]
Could you provide some more information? What version of nginx and ngx_pagespeed are you running? Is there anything relevant in nginx's `error.log`?

**Comment by bhanu0403** [comment]
version of nginx :- 1.11.1,
 ngx_pagespeed not define

**Comment by bhanu0403** [comment]
how solve website sever response time in wordpress????

**Comment by oschaaf** [comment]
It looks like your website is not running ngx_pagespeed. As this is an issue tracker for ngx_pagespeed, I'm not sure we'll be able to help you here.  To speed up html response times from wordpress, I would recommend running a search query with, for example, keywords `speed up wordpress`.

**Comment by bhanu0403** [comment]
suggest any plugin for that

**Comment by oschaaf** [comment]
I'm not able to recommend any wordpress plugins, sorry! Closing this issue, as this is not related to ngx_pagespeed.
