### ISSUE TITLE
Purge Single URL doesn't work

### ISSUE THREAD

**Issue by discostur** [pagespeed/ngx_pagespeed#1394]
I'm running ngx_pagespeed 1.12.34.2-0 and the purge of a single URL doesn't work. Purging the entire cache works well.

Wether i try to purge the cache via CURL or pagespeed Admin GUI it doesn't work for a single URL:

```
curl --request PURGE 'http://proxy.kilian-ries.de/wp-content/uploads/2016/05/Regensburg-steinerne-Bruecke-1024x681.jpg'
Purge successful
```

In the access log from the apache behind nginx i can't see a reload for the purged jpeg (if i refresh the page). If i clear the whole cache i can see a reload of all resources.

**Comment by oschaaf** [comment]
Can you try purging a `.pagespeed.` version of the url instead? https://proxy.kilian-ries.de/wp-content/uploads/2016/05/xRegensburg-steinerne-Bruecke-300x199.jpg.pagespeed.ic.BXmIXiHv-e.webp

**Comment by discostur** [comment]
If i try that i get a 404 Not Found:

```
$curl --request PURGE 'http://proxy.kilian-ries.de/wp-content/uploads/2016/05/xRegensburg-steinerne-Bruecke-300x199.jpg.pagespeed.ic.BXmIXiHv-e.webp'
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

$curl --request PURGE 'http://proxy.kilian-ries.de/wp-content/uploads/2016/05/xRegensburg-steinerne-Bruecke-768x510.jpg.pagespeed.ic.2o8KxVNTae.webp'
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

$curl --request PURGE 'http://proxy.kilian-ries.de/wp-content/uploads/2016/05/x940x528.jpeg.pagespeed.ic.d0nRIKspYN.webp'
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by jmarantz** [comment]
If you do change the image to have different content before purging, does
the new content show up?

Actually purging does not work on the .pagespeed. URLs, it works on the
original URLs.  But I am interested to see your domain-mapping directives
(e.g. MapOriginDomain, MapRewriteDomain, MapProxyDomain), as well as any
LoadFromFile directives you might have.

**Comment by discostur** [comment]
@jmarantz Thats interesting ... if i don't purge the site and change the image size in wordpress (before: 300x169px after: 940x529px) then pagespeed shows me the correct image size when reloading the page. 

Pagespeed log:

```
2017/03/15 11:01:53 [info] 30349#30710: [ngx_pagespeed 1.12.34.2-0] https://proxy.kilian-ries.de/:110: Shrinking image `https://proxy.kilian-ries.de/wp-content/uploads/2016/05/940x528.jpeg' (199779 bytes) to `https://proxy.kilian-ries.de/wp-content/uploads/2016/05/x940x528.jpeg.pagespeed.ic.d0nRIKspYN.webp' (118074 bytes)
```

But i still can't see anything in the access_log form apache. So from where does pagespeed know to resize the image when i can't see anything in the access log?


My pagespeed mapping config:

```
	pagespeed Domain https://proxy.kilian-ries.de;
	pagespeed MapOriginDomain http://91.237.88.116 https://proxy.kilian-ries.de;
        pagespeed MapRewriteDomain https://proxy.kilian-ries.de http://proxy.kilian-ries.de;
        pagespeed EnableFilters rewrite_domains; 
```

**Comment by jmarantz** [comment]
If you are changing the width & height attributes in the HTML tag, that
changes PageSpeed's internal cache key, and no purge is required.
PageSpeed may not need to re-fetch the image via http, as it stores the
original image in its HTTP cache as well as the optimized images
(potentially at different resolutions depending on html tags).

You only need purging if you are changing the jpeg file on disk and expect
that to show up before its TTL expires.

Could you try purging with its https URL?

curl --request PURGE
'https://proxy.kilian-ries.de/wp-content/uploads/2016/05/Regensburg-steinerne-Bruecke-1024x681.jpg
<http://proxy.kilian-ries.de/wp-content/uploads/2016/05/Regensburg-steinerne-Bruecke-1024x681.jpg>'

**Comment by discostur** [comment]
Ok, i uploaded a new jpeg (foto1.jpg) and loaded the page (so pagespeed cached the photo). Then i changed the photo-file to another photo with the same name 

```
rm foto1-1024x677.jpg
mv foto2.jpg foto1-1024x677.jpg
```

and reloaded the page. The result was still the same photo as before.

Then i tried purging the photo

```
curl --request PURGE 'https://proxy.kilian-ries.de/wp-content/uploads/2016/05/xfoto1-1024x677.jpg'
(did http AND https purge)
```

and the page still showed the same picture. After purging the whole site (/*) the reload showd me the correct (new) picture.

**Comment by jmarantz** [comment]
Can you try removing the 'x' in front of "foto1"?  You want the purge to work on the origin name, not the rewritten name.

**Comment by yerrinaidu** [comment]
![purging](https://user-images.githubusercontent.com/38078878/38318480-68c541b2-37fd-11e8-8714-5bb158969e97.PNG)
 i was trying to purge the individual URL using the below shown curl command line, but i am unbale to purge as it is throwing some error which i attached above.

 curl --request PURGE "http://10.23.6.113/preview/69580/58612/1036/index.htm/ mediahandler/mediakit/79026/DefaultT1T2/style.css" 

Can someone please help me out

**Comment by jmarantz** [comment]
I've never seen the error message you pasted.  It's not coming from PageSpeed.  Actually it's obviously coming from Microsoft :)  What server are you running?

**Comment by yerrinaidu** [comment]
![image](https://user-images.githubusercontent.com/38078878/38573746-fd032c42-3cc4-11e8-893e-4f63b5b2424e.png)
Ia m running this curl command line on my dev server. i did change a color property in css file and tried purging this css using 
curl --request PURGE"http://10.23.6.113/preview/69580/58612/1036/index.htm/ mediahandler/mediakit/79026/DefaultT1T2/style.css" and i got the PURGE successful message as shown in the image attached. But my changes aren't getting reflected. Any kind of leads would be really helpful.

**Comment by jmarantz** [comment]
Well that response from curl looks perfect.  However, it looks like you are purging a URL based on an IP address, which I don't think is going to work.  The way the purge system works is that it builds up a map of URLs to the timestamp they were purged, so if in the live site, the request is for a different URL pointing to the same physical resource, it's not going to work.

**Comment by yerrinaidu** [comment]
currently i am testing this for Dev Urls for which IIS web page speed has been configured. purging(Purging enite cache) is working fine(Changes are getting reflected) when i go to pagespeed_admin (10.23.6.113/pagespeed_admin) as shown in the image attached. But i was not able to get this done using the command line.  
![image](https://user-images.githubusercontent.com/38078878/38581822-e5c9fd96-3cdb-11e8-97f8-5b794cbfd4e2.png)

**Comment by jmarantz** [comment]
So I'm still skeptical that the URL you are purging matches the URL exactly when viewing a web page with their browser.  Specifically, I think the user would probably access a web page with a domain, rather than an IP address, and so the purged URL will not match.

**Comment by yerrinaidu** [comment]
Both(Purging URL and web browser URL) Urls are same. we haven't deployed this in Prod yet. We are testing on Dev server internally.

**Comment by oschaaf** [comment]
@yerrinaidu perhaps this is a problem specific to the IIS version. I'll pick this up in the other thread you initiated by email.
