### ISSUE TITLE
Seeing messages in error log about ngx_pagespeed----wordpress editor disappear

### ISSUE THREAD

**Issue by ooogooo** [pagespeed/ngx_pagespeed#1396]
2017/03/21 16:46:17 [error] 20497#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:46:19 [error] 20497#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:46:21 [error] 20497#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:46:25 [error] 20497#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:46:29 [error] 20497#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:46:45 [error] 20497#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:46:47 [error] 20497#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:46:49 [error] 20497#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:46:50 [error] 20497#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:46:54 [error] 20497#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:51:01 [info] 464#0: [ngx_pagespeed 1.11.33.4-0] No threading detected. Own threads: 1 Rewrite, 1 Expensive Rewrite.
2017/03/21 16:51:01 [info] 464#0: pagespeed: rollback gzip, explicit configuration in /etc/nginx/nginx.conf:34
2017/03/21 16:51:10 [error] 820#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:52:14 [error] 820#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:52:15 [error] 820#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:52:17 [error] 820#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:52:20 [error] 820#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:52:20 [error] 820#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:52:28 [error] 820#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .
2017/03/21 16:52:32 [error] 820#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .

ngx_pagespeed  >>>>  wordpress editor  disappear
js_defer.tRzI7EHUpg.js 

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ooogooo** [comment]
ngx_pagespeed  >>>>  wordpress editor  disappear

**Comment by oschaaf** [comment]
Could you try if disabling the `defer_javascript` filter makes the WordPress editor reappear?

**Comment by ooogooo** [comment]
Thank you
wordpress editor come back

 [error] 820#0: [ngx_pagespeed 1.11.33.4-0] Invalid url requested: .>>>>>What is wrong

**Comment by Lofesa** [comment]
Hi @ooogooo 
Perhaps are you using relative url´s? I will say url w/o http: nor https: schema, like \\somesite.com

**Comment by ooogooo** [comment]
Thank you

yes

**Comment by oschaaf** [comment]
Looks like we're all set here. Closing!
