### ISSUE TITLE
ERROR: Invalid inlined_image_type in cached_result

### ISSUE THREAD

**Issue by ic1011** [pagespeed/ngx_pagespeed#1405]
Hello,

Here is the error full log entry:

`[ngx_pagespeed 1.11.33.4-0] [0412/125341:ERROR:image_rewrite_filter.cc(1950)] Invalid inlined_image_type in cached_result`

Here is the configuration of the PS module:

```
pagespeed EnableFilters prioritize_critical_css;
pagespeed EnableFilters defer_javascript;
pagespeed EnableFilters sprite_images;
pagespeed EnableFilters rewrite_images;
pagespeed EnableFilters recompress_png;
pagespeed EnableFilters convert_png_to_jpeg,convert_jpeg_to_webp;
pagespeed EnableFilters collapse_whitespace,remove_comments;
pagespeed EnableFilters convert_to_webp_animated;
pagespeed EnableFilters insert_dns_prefetch;
pagespeed EnableFilters lazyload_images;
pagespeed EnableFilters convert_to_webp_lossless;
pagespeed LazyloadImagesAfterOnload off;
```
The NGINX is version 1.10.3 build with dynamic modules and without debug.

If inline_images filter is disabled, then the error does not appear.

Any insight on what might be the cause of this?

**Comment by oschaaf** [comment]
Do you have any animated webp images referenced in the html that triggers the error getting logged?

The code that logs this error looks like:

```
  if ((image_type_value < IMAGE_UNKNOWN) ||
      (image_type_value > IMAGE_WEBP_LOSSLESS_OR_ALPHA)) {
    // IMAGE_UNKNOWN and IMAGE_WEBP_LOSSLESS_OR_ALPHA must be the smallest
    // and largest values, respectively, in ImageType enum.
    LOG(DFATAL) << "Invalid inlined_image_type in cached_result";
    return INLINE_INTERNAL_ERROR;
  }
```

(https://github.com/pagespeed/mod_pagespeed/blob/1.11.33.4/net/instaweb/rewriter/image_rewrite_filter.cc#L1950)


`ImageType` is defined as

```
enum ImageType {
  IMAGE_UNKNOWN = 0,
  IMAGE_JPEG = 1,
  IMAGE_PNG = 2,
  IMAGE_GIF = 3,
  IMAGE_WEBP = 4,
  IMAGE_WEBP_LOSSLESS_OR_ALPHA = 5,
  IMAGE_WEBP_ANIMATED = 6
};
```

**Comment by morlovich** [comment]
Ooh, nice catch. Probably should just be using  ImageType_MIN and  ImageType_MAX
