### ISSUE TITLE
Proxy_cache as a downstream cache related issues

### ISSUE THREAD

**Issue by kaixulucky** [pagespeed/ngx_pagespeed#1407]
[root@hjl100031 logs]# nginx -V
**nginx version: nginx/1.10.3**
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
built with OpenSSL 1.0.2k  26 Jan 2017
TLS SNI support enabled
configure arguments: --with-http_stub_status_module --with-http_gzip_static_module --with-http_realip_module --with-http_addition_module --with-pcre=/root/nginx/pcre-8.40 --with-zlib=/root/nginx/zlib-1.2.11 --with-openssl=/root/nginx/openssl-1.0.2k --with-pcre-jit --add-module=/root/nginx/**ngx_pagespeed-1.12.34.2-beta** --with-http_ssl_module --with-http_v2_module --add-module=/root/nginx/ngx_cache_purge-master --with-debug
### ---------------------------------------------------------------------------------------------
**Question 1: Why is pagespeed not purge the downstream cache of the Expired content (partially rewritten content)?**
According to the tutorial "https://modpagespeed.com/doc/downstream-caching" and "https://github.com/pagespeed/ngx_pagespeed/issues/1068" configured proxy_cache as a downstream cache and install purge module, will be translated by pagespeed purge Expired content (partially rewritten content), but I am here for what will not clear the action. There is no relevant record inside the log (you can manually purge).

location ~ /purge(/.*) {
             access_log  logs/purge.log  main;
             allow all;
             proxy_cache_purge filecache $1$is_args$args;
             }
**----- manually purge-----**
Successful purge

Key : /Public/images/logo.jpg
Path: /home/ngx_cache/cache/5/29/13f6aa75448bb700d348a79c7b4f4295
nginx/1.10.3
### ---------------------------------------------------------------------------------------------
**Question 2: In addition to pagespeed I set the TTL value, no other places have set the TTL value, the 300s is how the matter, where can be modified?**
pagespeed ImplicitCacheTtlMs 60000;
pagespeed LoadFromFileCacheTtlMs 100000;

**The upstream origin server does not have a TTL value related setting**
[root@hjl1000246 ~]# curl --head http://10.0.0.12/Public/images/logo.jpg       
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 13 Apr 2017 02:44:39 GMT
Content-Type: image/jpeg
Content-Length: 13179
Last-Modified: Fri, 03 Jun 2016 03:27:30 GMT
Connection: keep-alive
ETag: "5750f922-337b"
Accept-Ranges: bytes

## ------------------------Through firefox first request:---------------------
**The response header is as follows:**
Accept-Ranges	 bytes
Cache-Control	 s-maxage=10
Connection	keep-alive
Content-Length	13179
Content-Type	 image/jpeg
Date	Thu, 13 Apr 2017 05:32:18 GMT
Etag	 "5750f922-337b"
Last-Modified	 Fri, 03 Jun 2016 03:27:30 GMT
Server	 nginx
X-Cache	MISS

**Pagespeed directory structure**
[root@hjl100031 pagespeed_cache]# tree
.
└── v3
    └── 10.0.0.31
        └── http,3A
            ├── ,2F10.0.0.31
            │   └── Public
            │       └── images
            │           └── logo.jpg,
            └── ,2F10.0.0.31,3A8000
                └── Public
                    └── images
                        └── logo.jpg,

## ------------------------Through firefox second request:---------------------
**The response header is as follows:**
Accept-Ranges	 bytes
**Cache-Control	 max-age=300, s-maxage=10**
Connection	keep-alive
Content-Length	13179
Content-Type	 image/jpeg
Date	Thu, 13 Apr 2017 05:32:18 GMT
Etag	"5750f922-337b"
Expires	Thu, 13 Apr 2017 05:37:18 GMT
Last-Modified	Fri, 03 Jun 2016 03:27:30 GMT
Server	nginx
X-Cache	MISS

**Pagespeed directory structure**
[root@hjl100031 pagespeed_cache]# tree
.
├── shm_metadata_cache
│   └── snapshot
│       └── pagespeed_default_shm
│           └── metadata_cache
│               └── 1
│                   └── 64
│                       └── 11396
│                           └── 128
│                               └── 113,
└── v3
    └── 10.0.0.31
        └── http,3A
            ├── ,2F10.0.0.31
            │   └── Public
            │       └── images
            │           ├── logo.jpg,
            │           └── xlogo.jpg.pagespeed.ic.f524Si0mai.jpg,
            └── ,2F10.0.0.31,3A8000
                └── Public
                    └── images
                        └── logo.jpg,
**Pagespeed file cache content**
[root@hjl100031 images]# tail -n 9 logo.jpg, 
Last-ModifiedFri, 03 Jun 2016 03:27:30 GMTJ
ETag"5750f922-337b"J
X-CacheMISSJ
Accept-RangesbytesJ

Content-Type
image/jpegJ%
DateThu, 13 Apr 2017 05:32:18 GMTJ(
ExpiresThu, 13 Apr 2017 05:37:18 GMTJ)
Cache-Controlmax-age=300, s-maxage=10Php
[root@hjl100031 images]# tail -n 9 xlogo.jpg.pagespeed.ic.f524Si0mai.jpg, 
Accept-RangesbytesJ

Content-Type
image/jpegJ%
DateThu, 13 Apr 2017 05:32:52 GMTJ(
ExpiresFri, 13 Apr 2018 05:32:52 GMTJ!
Cache-Controlmax-age=31536000J
EtagW/"0"J.
Last-ModifiedThu, 13 Apr 2017 05:32:52 GMTJ"
X-Original-Content-Length13179Php

## ------------------------Through firefox trird request:---------------------
**The response header is as follows:**
Accept-Ranges	bytes
Cache-Control	max-age=293
Connection	keep-alive
Content-Length	5172
Content-Type	image/jpeg
Date	Thu, 13 Apr 2017 05:40:15 GMT
Etag	W/"PSA-aj-f524Si0mai"
Expires	Thu, 13 Apr 2017 05:45:09 GMT
Server	nginx
Vary	User-Agent,Save-Data
X-Cache	MISS
X-Original-Content-Length	13179

**Pagespeed file cache content**
[root@hjl100031 images]# tail -n 9 logo.jpg, 
Last-ModifiedFri, 03 Jun 2016 03:27:30 GMTJ
ETag"5750f922-337b"J
X-Cache
        REVALIDATEDJ
Accept-RangesbytesJ

Content-Type
image/jpegJ%
DateThu, 13 Apr 2017 05:40:09 GMTJ(
ExpiresThu, 13 Apr 2017 05:45:09 GMTJ)
Cache-Controlmax-age=300, s-maxage=10Php
                                     --------------
[root@hjl100031 images]# tail -n 10 xlogo.jpg.pagespeed.ic.f524Si0mai.jpg, 
X-CacheMISSJ
Accept-RangesbytesJ

Content-Type
image/jpegJ%
DateThu, 13 Apr 2017 05:32:52 GMTJ(
ExpiresFri, 13 Apr 2018 05:32:52 GMTJ!
Cache-Controlmax-age=31536000J
EtagW/"0"J.
Last-ModifiedThu, 13 Apr 2017 05:32:52 GMTJ"
X-Original-Content-Length13179Php

----------------------------------------------nginx.conf-----------------------------------------------
...omitted...
http {
proxy_temp_path  /home/ngx_cache/temp;
proxy_cache_path /home/ngx_cache/cache levels=1:2 keys_zone=filecache:512m inactive=1d max_size=200g;

pagespeed FileCachePath "/home/pagespeed_cache";
pagespeed FileCacheSizeKb            204800;
pagespeed MessageBufferSize 200000;
#pagespeed ModifyCachingHeaders off;

pagespeed Domain *.domain.co;
pagespeed Domain *.domain.com;
pagespeed Domain https://*.domain.co;  ##必须要
pagespeed Domain https://*.domain.com;#好像可以不要
pagespeed SslCertDirectory /etc/pki/tls/certs;#好像可以不要
pagespeed SslCertFile /etc/pki/tls/cert.pem;#好像可以不要
pagespeed RewriteLevel OptimizeForBandwidth;
pagespeed EnableCachePurge on;
pagespeed PurgeMethod PURGE;
pagespeed InPlaceResourceOptimization on;
pagespeed EnableFilters in_place_optimize_for_browser;
pagespeed Statistics on;
pagespeed StatisticsLogging on;
pagespeed LogDir /var/log/pagespeed;
pagespeed StatisticsPath /ngx_pagespeed_statistics;
pagespeed GlobalStatisticsPath /ngx_pagespeed_global_statistics;
pagespeed MessagesPath /ngx_pagespeed_message;
pagespeed ConsolePath /pagespeed_console;
pagespeed AdminPath /pagespeed_admin;
pagespeed GlobalAdminPath /pagespeed_global_admin;
#pagespeed InPlaceSMaxAgeSec 50;
**pagespeed ImplicitCacheTtlMs 60000;
pagespeed LoadFromFileCacheTtlMs 100000;**
#pagespeed DefaultSharedMemoryCacheKB 50000;
#pagespeed CreateSharedMemoryMetadataCache "/home/pagespeed_cache" 51200;
pagespeed LRUCacheKbPerProcess 32768;
pagespeed LRUCacheByteLimit    65536;
pagespeed DefaultSharedMemoryCacheKB 131072;

upstream my_webserver_group {
            server 10.0.0.12;
            keepalive 50;
           }
server {
        listen 8000;
        server_name  ~^(www|m|oa)\.domain\.com$;
             location / {
             pagespeed on;
             proxy_pass http://my_webserver_group;
             include conf.d/proxy.conf;
             #add_header Cache-Control "max-age=185";
             #expires 55;
             #proxy_hide_header Etag;
             #proxy_hide_header Last-Modified;
             #proxy_hide_header Expires;
             #proxy_hide_header Cache-Control;
             #proxy_ignore_headers "Expires" "Cache-Control" "Set-Cookie";
             pagespeed DownstreamCachePurgeMethod GET;
             pagespeed DownstreamCachePurgeLocationPrefix "http://$host/purge";
             pagespeed DownstreamCacheRebeaconingKey "1234";
             pagespeed DownstreamCacheRewrittenPercentageThreshold 95;
             }
server {
        listen       80;
        server_name  ~^(www|m|oa)\.domain\.com$;
        location ~ /purge(/.*) {
             access_log  logs/purge.log  main;
             allow all;
             proxy_cache_purge filecache $1$is_args$args;
             }
        location =/ {
             pagespeed off;
             proxy_pass http://my_webserver_group;
             include conf.d/proxy.conf;
           }

        location / {
             pagespeed off;
             proxy_pass http://my_webserver_group;
             include conf.d/proxy.conf;
           }
        location ~ .*\.(js|css|gif|jpg|jpeg|png)$ {
             proxy_cache filecache;
             proxy_cache_key $uri$is_args$args;
             #proxy_cache_valid 200 304 100s;
             proxy_pass http://$host:8000;
             proxy_set_header Host   $proxy_host;
             #proxy_hide_header Etag;
             #proxy_hide_header Last-Modified;
             #proxy_hide_header Expires;
             #proxy_hide_header Cache-Control;
           }

**Comment by oschaaf** [comment]
As you have set the `RewriteLevel` to `OptimizeForBandwidth`, I think you do not need to set up the downstream caching feature. (I think there is no need to purge html in that mode).

Instead, with OptimizeForBandwidth, you could consider preserving html caching headers:
https://modpagespeed.com/doc/configuration#ModifyCachingHeaders

**Comment by kaixulucky** [comment]
thank you very much! Then I will abandon the use of proxy_cache, only use pagespeed, and use the command "pagespeed ModifyCachingHeaders off;", in the "pagespeed on" where the server block controls the ttl value. @oschaaf

**Comment by oschaaf** [comment]
closing this, feel free to reopen if you run into any more issues
