### ISSUE TITLE
Question about G-Analytics

### ISSUE THREAD

**Issue by systemroot** [pagespeed/ngx_pagespeed#1410]
Hello,

I'm using ```pagespeed AnalyticsID;``` with ```Nginx 1.9.9``` & ```pagespeed-1.12.34.2-beta```

To monitor traffic. but G-Analytics is monitorig just homepage of domain "```/```" doesn't monitor visitors which come directly from google on a blog post or somewhere else. 

So. Is there anything which i can do to monitor traffic which come on my blog posts and in other pages?!

i can't find what's wrong the same code is on my domain home page, the same code appears on blog post too :confused:  but Google-analytics (Live MODE) doesn't get stats when i visit posts just when i visit home page. Does anyone else have this problem or i'm doing something wrong?

Thanks.

All Filters which are enabled
```
            pagespeed EnableFilters insert_dns_prefetch;
            pagespeed EnableFilters prioritize_critical_css;
            pagespeed EnableFilters sprite_images;
            pagespeed EnableFilters rewrite_images;
            pagespeed EnableFilters rewrite_css;
            pagespeed EnableFilters rewrite_style_attributes_with_url;
            pagespeed EnableFilters rewrite_javascript;
            pagespeed EnableFilters flatten_css_imports;
            pagespeed EnableFilters combine_javascript;
            pagespeed EnableFilters combine_css;
            pagespeed EnableFilters recompress_png;
            pagespeed EnableFilters convert_png_to_jpeg,convert_jpeg_to_webp;
            pagespeed EnableFilters collapse_whitespace,remove_comments;
            pagespeed EnableFilters canonicalize_javascript_libraries;
            pagespeed EnableFilters extend_cache;
            pagespeed EnableFilters outline_css;
            pagespeed EnableFilters outline_javascript;
            pagespeed EnableFilters move_css_above_scripts;
            pagespeed EnableFilters rewrite_domains;
            pagespeed EnableFilters resize_mobile_images;
            pagespeed EnableFilters lazyload_images;
            pagespeed EnableFilters responsive_images,resize_images;
            pagespeed EnableFilters move_css_to_head;
            pagespeed EnableFilters insert_ga;
            pagespeed AnalyticsID   UA-X0X0-X;
```

**Comment by oschaaf** [comment]
That's odd, a few questions:

- Are the any errors logged to the browser console? 
- Does `analytics.js` show up in the requests on the network panel on Chrome's dev tools for those pages? If so, what do the request/response headers look like?
- the `insert_ga` filter should inject a script which mentions `//www.google-analytics.com/analytics.js`
if you view the source of a page which does not get monitored, do you see this script being injected?
Or is it absent?

**Comment by systemroot** [comment]
>Are the any errors logged to the browser console?

Yes. On my blog are some but for some other reasons. i can't get any error which contain anything about analytics.

---
>Does analytics.js show up in the requests on the network panel on Chrome's dev tools for those pages? If so, what do the request/response headers look like?

http://i.imgur.com/jrjy6mg.png i think this is the problem :confused: 
code in blog posts
```
</script>
<script>if(window.parent==window){(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create','UA-X0X0-1','auto',{'siteSpeedSampleRate':100});ga('send','pageview');}</script>
```
i was reading http://stackoverflow.com/questions/27945501/307-redirect-when-loading-analytics-js-in-chrome and into  ``chrome://net-internals/#events`` i found 
``` --> delegate_blocked_by = "extension Adblock Plus"```

i've disable adblock and i'm able to get stats now! 

Thank you for helping :+1:
