### ISSUE TITLE
psol url 404 not found

### ISSUE THREAD

**Issue by AdsonCicilioti** [pagespeed/ngx_pagespeed#1414]
Following the instructions recommended [here](https://modpagespeed.com/doc/build_ngx_pagespeed_from_source), I come across the error in the step of getting the psol package.

Until yesterday this link was working. What happened?

The version I am trying is this:
Https://dl.google.com/dl/page-speed/psol/1.12.34.2.tar.gz

**Comment by oschaaf** [comment]
See https://github.com/pagespeed/ngx_pagespeed/issues/1337#issuecomment-266844908

**Comment by AdsonCicilioti** [comment]
Yep. Thanks!
