### ISSUE TITLE
the relative URLs is always converted to absolute URLs, in css files.

### ISSUE THREAD

**Issue by kleveralt** [pagespeed/ngx_pagespeed#1416]
nginx is serving my website as a backend server, via HTTP protocol, 
this is my config, in nginx.conf, server block,

pagespeed FileCachePath /home/cache/ngx_pagespeed_cache;
pagespeed Domain "http://mydomain.com";
pagespeed Domain "https://mydomain.com";
pagespeed LoadFromFile "https://mydomain.com" "/home/wwwroot/mydomain.com/";
pagespeed LoadFromFile "http://mydomain.com" "/home/wwwroot/mydomain.com/";
pagespeed RewriteLevel PassThrough;
pagespeed ModifyCachingHeaders off;
pagespeed PreserveUrlRelativity on;
pagespeed EnableFilters collapse_whitespace;
pagespeed EnableFilters inline_css,flatten_css_imports;
pagespeed CssInlineMaxBytes 15360;
pagespeed CssFlattenMaxBytes 30720;
pagespeed EnableFilters inline_javascript;
pagespeed JsInlineMaxBytes 15360;

the output of debug,

mod_pagespeed on
Filters:
cw	Collapse Whitespace
db	Debug
if	Flatten CSS Imports
hw	Flushes html
ci	Inline Css
ji	Inline Javascript

Options:
AvoidRenamingIntrospectiveJavascript (aris) True
CssFlattenMaxBytes (cf) 30720
CssInlineMaxBytes (ci) 15360
EnableRewriting (e) 1
FileCacheInodeLimit (afcl) 500000
JsInlineMaxBytes (ji) 15360
ModifyCachingHeaders (mch) False
PreserveUrlRelativity (pur) True
RewriteLevel (l) Pass Through

#NumFlushes            0
#EndDocument after     9791us
#Total Parse duration  8683us
#Total Render duration 6134us
#Total Idle duration   1108us
The following filters were disabled for this request:
	SupportNoscript

what happenning is,  there is a real css file, genericons.css ,
it is imported by a paraent css, which named as genericons.css too,
the pagespeed module flatten it, and rewrited the real css,

the 'no pagespeed' look,
in HTML,
`<link rel='stylesheet' id='genericons-style-css'  href='https://mydomain.com/wp-content/themes/mytheme/genericons/genericons.css' type='text/css' media='all' />`

in  https://mydomain.com/wp-content/themes/mytheme/genericons/genericons.css
@import url('genericons/genericons.css');

in  https://mydomain.com/wp-content/themes/mytheme/genericons/genericons/genericons.css
@font-face {
  font-family: "Genericons";
  src: url("./Genericons.eot");
  src: url("./Genericons.eot?") format("embedded-opentype");
  font-weight: normal;
  font-style: normal;
}

the pagespeed enabled look,
in HTML,
`<link rel='stylesheet' id='genericons-style-css' href='https://mydomain.com/wp-content/themes/mytheme/genericons/A.genericons.css.pagespeed.cf.0zPOwIgQCv.css' type='text/css' media='all'/>`

in https://mydomain.com/wp-content/themes/mytheme/genericons/A.genericons.css.pagespeed.cf.0zPOwIgQCv.css (flattened)
@font-face{font-family:"Genericons";src:url(http://mydomain.com/wp-content/themes/mytheme/genericons/genericons/Genericons.eot);

the problem is, I didn't enable the rewrite_css filter, but it was rewrited,
and URLs in this flattened css was converted always, but I have set this option,
pagespeed PreserveUrlRelativity on;

it rewrited the URLs to full URLs start with http://, causing 'mixed content' issues , I know the reason is nginx is running on HTTP.
but, is there a way to really disable this URL convert filter?

**Comment by oschaaf** [comment]
Did you see https://modpagespeed.com/doc/https_support#RespectXForwardedProto ?

**Comment by kleveralt** [comment]
Thanks, this works.
