### ISSUE TITLE
  I can't  configure ngx1.12.0 with pagespeed1.11.33.4

### ISSUE THREAD

**Issue by chaihongjun** [pagespeed/ngx_pagespeed#1417]
here is my script:
`./configure --prefix=/usr/local/nginx --user=www --group=www --with-http_stub_status_module --with-http_v2_module --with-http_ssl_module --with-ipv6 --with-http_gzip_static_module --with-http_realip_module --with-http_geoip_module  --with-http_flv_module --with-ld-opt=-ljemalloc --add-module=/root/lnmp/src/headers-more-nginx-module --add-module=/root/lnmp/src/ngx-fancyindex --add-module=/root/lnmp/src/ngx_pagespeed.1.11.33.4`
![screenshot](https://cloud.githubusercontent.com/assets/12774598/25937410/2548b604-365e-11e7-9561-b7f6947fe231.jpg)
![screenshot](https://cloud.githubusercontent.com/assets/12774598/25937424/2dd064c0-365e-11e7-8360-a4eed33a0c7c.jpg)

[autoconf.txt](https://github.com/pagespeed/ngx_pagespeed/files/992181/autoconf.txt)

**Comment by oschaaf** [comment]
`autoconf.txt` has:

```
/root/lnmp/src/ngx_pagespeed.1.11.33.4/psol/lib/Release/linux/x64/pagespeed_automatic.a(1.waitable_event_posix.o.o): In function `base::WaitableEvent::EnqueueMany(std::pair<base::WaitableEvent*, unsigned long>*, unsigned long, base::WaitableEvent::Waiter*)':
waitable_event_posix.cc:(.text._ZN4base13WaitableEvent11EnqueueManyEPSt4pairIPS0_mEmPNS0_6WaiterE+0xae): undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)'
/root/lnmp/src/ngx_pagespeed.1.11.33.4/psol/lib/Release/linux/x64/pagespeed_automatic.a(1.waitable_event_posix.o.o): In function `base::WaitableEvent::SignalOne()':
waitable_event_posix.cc:(.text._ZN4base13WaitableEvent9SignalOneEv+0x2a): undefined reference to `std::__detail::_List_node_base::_M_unhook()'
/root/lnmp/src/ngx_pagespeed.1.11.33.4/psol/lib/Release/linux/x64/pagespeed_automatic.a(1.waitable_event_posix.o.o): In function `base::WaitableEvent::Enqueue(base::WaitableEvent::Waiter*)':
waitable_event_posix.cc:(.text._ZN4base13WaitableEvent7EnqueueEPNS0_6WaiterE+0x31): undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)'
...... continues with similar messages .....
```

What os and gcc version are you using?

**Comment by chaihongjun** [comment]
I know what happened，
The GCC version is incorrect
