### ISSUE TITLE
LoadFromFileCacheTtlMs is not honored (*after* first request)

### ISSUE THREAD

**Issue by 0x42h** [pagespeed/ngx_pagespeed#1418]
When LoadFromFile is set with a custom LoadFromFileCacheTtlMs, the first request wil honor the LoadFromFileCacheTtlMs, but after the first request, it wil default back to max-age: 300 (5 minutes), as per the non-public psol code.

# Example:
inside the server config:
```
pagespeed LoadFromFile "http://example.com" "/var/www"
pagespeed LoadFromFileCacheTtlMs 31556926000;
```
## First request
Request URL:
``https://example.com/test.js?1``

Response headers:
```
HTTP/1.1 200 OK
Server: nginx/1.10.0 (Ubuntu)
Content-Type: application/javascript
Transfer-Encoding: chunked
Connection: keep-alive
Date: Tue, 16 May 2017 17:31:57 GMT
Expires: Wed, 16 May 2018 23:20:43 GMT
Last-Modified: Tue, 17 Jan 2017 14:01:55 GMT
Cache-Control: max-age=31556926, s-maxage=10
```
## Second request
Request URL:
``https://example.com/test.js?1``

Response headers:
```
Server: nginx/1.10.0 (Ubuntu)
Content-Type: application/javascript
Connection: keep-alive
X-Original-Content-Length: 32197
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 8806
ETag: W/"PSA-aj-CiswHsWsJj"
Date: Tue, 16 May 2017 17:32:53 GMT
Expires: Tue, 16 May 2017 17:37:53 GMT
Cache-Control: max-age=300
```
## Third request
Request URL:
``https://example.com/test.js?2``

Response headers:
```
Server: nginx/1.10.0 (Ubuntu)
Content-Type: application/javascript
Transfer-Encoding: chunked
Connection: keep-alive
Date: Tue, 16 May 2017 17:34:15 GMT
Expires: Wed, 16 May 2018 23:23:01 GMT
Last-Modified: Tue, 17 Jan 2017 14:01:55 GMT
Cache-Control: max-age=31556926, s-maxage=10
```
## Fourth request
Request URL:
``https://example.com/test.js?2``

Response headers:
```
Server: nginx/1.10.0 (Ubuntu)
Content-Type: application/javascript
Connection: keep-alive
X-Original-Content-Length: 32197
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 8806
ETag: W/"PSA-aj-CiswHsWsJj"
Date: Tue, 16 May 2017 17:35:03 GMT
Expires: Tue, 16 May 2017 17:40:03 GMT
Cache-Control: max-age=300
```
The even results are repeated for every request after this, with the exact same URL, maintaining the (PSOL/default) 300 seconds.

**Comment by jmarantz** [comment]
First note: https://example.com/test.js?1 and https://example.com/test.js?2 are
entirely different and unrelated URLs.

So you really have shown two different 2-request flows.  Can you also do
3rd and 4th requests for those resources?

I'm actually not sure exactly what's going on with the TTL in this flow,
but I do kjnow that you are most likely to get fully optimized output for
in-place resources starting on the third request.

**Comment by 0x42h** [comment]
After third and fourth (and many after), it keeps defaulting to 300 seconds.

**Comment by 0x42h** [comment]
Anyone?

**Comment by 0x42h** [comment]
Example: https://www.weghuis.nl/wp-content/uploads/2016/11/11357415279.jpg = max-age=300
https://www.weghuis.nl/wp-content/uploads/2016/11/11357415279.jpg?{enter not yet before entered chars here to make sure the request is "new"} = max-age=31556926, s-maxage=10

**Comment by oschaaf** [comment]
I can confirm the behaviour on master, and I think it's a bug. After looking in to it, I think that `InPlaceRewriteContext::FixFetchFallbackHeaders` needs to use `load_from_file_cache_ttl_ms_` where it now uses `implicit_cache_ttl_ms`, when it is adjusting the headers for a response that is mapped by `LoadFromFile` configuration.

**Comment by oschaaf** [comment]
Created https://github.com/pagespeed/mod_pagespeed/pull/1552 
I need to spend some more time verifying that more thorougly, but a couple of manual tests seem to indicate it addresses this.

**Comment by 0x42h** [comment]
Hallo Otto,

Something like that was my suspicion. Thank you for the confirmation.

As in [this bug report for mod_pagespeed](https://github.com/pagespeed/mod_pagespeed/issues/989)...
```
pagespeed InPlaceResourceOptimization off 
```
... circumvents the issue, but obviously then you do not have in place resource replacements.

pagespeed/mod_pagespeed#989
