### ISSUE TITLE
error  --with-http_ssl_module', exiting and error: SSL modules require the OpenSSL

### ISSUE THREAD

**Issue by wyly44** [pagespeed/ngx_pagespeed#1419]
Hello
I want to migrate from http to https and have http / 2
Do I have to activate this module or is it not necessary?

> --with-http_ssl_module
About to configure nginx with:
   ./configure --add-dynamic-module=/root/ngx_pagespeed-latest-stable --with-http_ssl_module
Does this look right? [Y/n] y

I have used the automatic installation and I have also tried manually to install the libraries

sudo apt-get install build-essential zlib1g-dev libpcre3 libpcre3-dev unzip
 
bash <(curl -f -L -sS https://ngxpagespeed.com/install) \
>      --nginx-version latest --dynamic-module

Do I need to install any more modules?

./configure: error: SSL modules require the OpenSSL library.
You can either do not enable the modules, or install the OpenSSL library
into the system, or build the OpenSSL library statically from the source
with nginx by using --with-openssl=<path> option.

Error: Failure running './configure --add-dynamic-module=/root/ngx_pagespeed-latest-stable --with-http_ssl_module', exiting.

thanks

**Comment by oschaaf** [comment]
You need to install the `libssl-dev` package if you want to have ssl support in nginx.

**Comment by oschaaf** [comment]
Closing this, feel free to reopen if there's a problem with ngx_pagespeed

**Comment by locvfx** [comment]
yum install -y openssl-devel

**Comment by StathisIoannidis** [comment]
@oschaaf 
Can you please elaborate on above comment "You need to install the libssl-dev package if you want to have ssl support in nginx."
I spent the entire morning trying to add a third party module to Nginx(ngx_http_ssl_module), as Im getting --
 nginx: [emerg] the "ssl" parameter requires ngx_http_ssl_module --.
 Would installing libssl-dev package solve my issue?
 
 Thanks a lot !!
