### ISSUE TITLE
Pagespeed gzip

### ISSUE THREAD

**Issue by rizkylab** [pagespeed/ngx_pagespeed#1422]
I get this warning from my error.log
![screen shot 2017-05-19 at 5 01 01 pm](https://cloud.githubusercontent.com/assets/1557686/26243102/e1d7c16e-3cb4-11e7-81e7-220de05cdc90.png)

on my nginx.conf
----
gzip on;
        gzip_disable "msie6";
        gzip_http_version 1.1;
        gzip_vary on;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_proxied any;
        gzip_types
                
                text/css
                text/javascript
                text/xml
                text/plain
                text/x-component
                application/javascript
                application/x-javascript
                application/json
                application/xml
                application/rss+xml
                application/atom+xml
                application/rdf+xml
                application/vnd.ms-fontobject
                font/truetype
                font/opentype
                image/svg+xml;

**Comment by oschaaf** [comment]
These are informational and harmless, you can get rid of them by bumping the log level to notice or warning.
