### ISSUE TITLE
When will next stable release?

### ISSUE THREAD

**Issue by no-cat-no** [pagespeed/ngx_pagespeed#1425]

**Comment by jmarantz** [comment]
It is being worked on.  There's been some trouble because some of our
32-build processes were reliant on dependencies that are now end-of-lifed.
Stay tuned, and sorry about the delay.

**Comment by no-cat-no** [comment]
Will it be in the summer?

**Comment by oschaaf** [comment]
There have been changes to the release process, and we're working on verifying performance of forthcoming release to make sure everything is allright. The plan is to put it out next monday!

**Comment by oschaaf** [comment]
New stable release is out!: https://groups.google.com/forum/#!topic/ngx-pagespeed-announce/6b9yPaaKF8I

**Comment by no-cat-no** [comment]
thx!!!
