### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by 0x42h** [pagespeed/ngx_pagespeed#1427]
I am told by @oschaaf that [this](https://github.com/pagespeed/ngx_pagespeed/wiki/Building-PSOL-From-Source) (build PSOL from source Wiki) information is outdated. New way:
```
git clone git@github.com:pagespeed/ngx_pagespeed.git
cd ngx_pagespeed
scripts/build_ngx_pagespeed.sh --devel
```
Please add what I might be missing/misunderstanding here, @oschaaf.

**Comment by oschaaf** [comment]
This refers to https://github.com/pagespeed/ngx_pagespeed/wiki/Building-PSOL-From-Source, right?
The steps to build mod_pagespeed have changed for master.

If you want to build ngx_pagespeed against the latest commit from mod_pagespeed, `build_ngx_pagespeed.sh` nearly gets you there except that the `mod_pagespeed` submodule is pinned on an earlier commit. I think it would be nice to have an option in the script to update the submodule to the latest commit for this purpose.

**Comment by 0x42h** [comment]
That's correct. 

I tried to add --remote to the 
```bash
run git submodule update --init --recursive
```
on line 601, hoping that that would grab all the bleeding edge stuff for the submodules, but that didn't work out, particularly for mod_pagespeed, somehow.

```
Submodule path 'testing-dependencies/set-misc-nginx-module': checked out '48908343c00a45a40365158282f61d5369d17194'
Failed to recurse into submodule path 'testing-dependencies/mod_pagespeed'
Error: Failure running 'git submodule update --init --recursive --remote', exiting.
```
Of course it's not an ideal situation to grab everything bleeding edge, so I guess we have to build in a for loop to fish out mod_pagespeed submodule for git to only let it grab the bleeding edge version of that one, right? 

I got that from [here](https://stackoverflow.com/questions/1030169/easy-way-pull-latest-of-all-submodules).

**Comment by oschaaf** [comment]
Maybe something like this can provide a workaround:

```diff
diff --git a/scripts/build_ngx_pagespeed.sh b/scripts/build_ngx_pagespeed.sh
index f230878fe..5a0e96308 100755
--- a/scripts/build_ngx_pagespeed.sh
+++ b/scripts/build_ngx_pagespeed.sh
@@ -598,7 +598,16 @@ Not deleting $directory; name is suspiciously short.  Something is wrong."
     submodules_dir="$nps_module_dir/testing-dependencies"
     if "$DEVEL"; then
       status "Downloading dependencies..."
+      # run git submodule update --init --recursive
+      run cd "$submodules_dir/mod_pagespeed"
+      run git checkout master
+      run cd ..
+      run git add "$mod_pagespeed"
+      run git commit -m "update mps dependency to bleeding edge"
+      run cd "$nps_module_dir"
+ 
       run git submodule update --init --recursive
       if [[ "$CONTINUOUS_INTEGRATION" != true ]]; then
         status "Switching submodules over to git protocol."
         # This lets us push to github by public key.
```

**Comment by 0x42h** [comment]
Hi @oschaaf,

Made some time for this today. I had to hack a little deeper to figure it all out and get a Release build out of it, but I've come a long way. Once I really know how things are stringed together I'll add some flags, but where I am stuck now is on two points. 

```bash
/usr/src/ngx_pagespeed# ls testing-dependencies/mod_pagespeed/out/
Debug  Debug_x64  Release  Release_x64
```
I see three directories there, and when I build --devel, I build into Debug. I'd like to build Release_x64, since I am on 64 bit system, but I haven't come that far yet. I got it to build Release, until:
```bash
  CXX(target) out/Release/obj.target/grpc_cpp/third_party/grpc/src/src/cpp/client/insecure_credentials.o
  CXX(target) out/Release/obj.target/grpc_cpp/third_party/grpc/src/src/cpp/client/secure_credentials.o
  CXX(target) out/Release/obj.target/grpc_cpp/third_party/grpc/src/src/cpp/common/auth_property_iterator.o
  CXX(target) out/Release/obj.target/grpc_cpp/third_party/grpc/src/src/cpp/common/secure_auth_context.o
  CXX(target) out/Release/obj.target/grpc_cpp/third_party/grpc/src/src/cpp/common/secure_channel_arguments.o
  CXX(target) out/Release/obj.target/grpc_cpp/third_party/grpc/src/src/cpp/common/secure_create_auth_context.o
  CXX(target) out/Release/obj.target/grpc_cpp/third_party/grpc/src/src/cpp/server/insecure_server_credentials.o
  CXX(target) out/Release/obj.target/grpc_cpp/third_party/grpc/src/src/cpp/server/secure_server_credentials.o
make[1]: *** No rule to make target 'out/Release/obj.target/grpc_cpp/third_party/grpc/src/src/cpp/client/channel_cc.o', needed by 'out/Release/obj.target/third_party/grpc/libgrpc_cpp.a'.  Stop.
Makefile:607: recipe for target 'internal_release_build' failed
make: *** [internal_release_build] Error 2
Error: Failure running 'make apache_release', exiting.
```
Any ideas...[?](https://www.youtube.com/watch?v=cGyQmH9NZcw&t=1m17s) 8)

**Comment by oschaaf** [comment]
@0x42h that makes me suspect there is a mismatch between mod_pagespeed and the grpc in the third party dependencies. When I:
- clone the ngx_pagespeed repo
- put the contents of https://gist.github.com/oschaaf/2e7eeb1ee8636df73bf15813b8143b03 over `scripts/build_ngx_pagespeed.sh` (which has changes to build against mod_pagespeed's bleeding edge)
- run `scripts/build_ngx_pagespeed.sh --devel`

The build completes successfully for me, could you try that?

**Comment by 0x42h** [comment]
Hi @oschaaf,

Thanks for all the help. I am going to try this out now, but this would still, I suppose, do a Debug build and not a Release_x64 build, so I will try this first and then modify it to use ``scripts/build_ngx_pagespeed.sh --psol_from_source --build-type Release`` and if I can get it going ``--build-type Release_x64``. Does that have any merrit, those ``*_x64`` folders in ``mod_pagespeed/out`` or does a x64 system automatically imply 64 bit binaries and those directories are only there for historical reasons?

**Comment by 0x42h** [comment]
Okay, great. That worked for build. Now I am following [these instructions on building my own deb by Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-add-ngx_pagespeed-to-nginx-on-debian-8), so now I was hoping to find the PSOL binaries that I would normal download, which contain binaries like ``pagespeed_automatic.a``. However, I cannot find those binaries anywhere, is that correct?

**Comment by 0x42h** [comment]
Okay, done. 

Found ``testing-dependencies/mod_pagespeed/pagespeed/automatic`` and ran make there, which built me the files I needed with the right architecture.
```bash
# objdump -f pagespeed_automatic.a | grep ^architecture
architecture: i386:x86-64, flags 0x00000011:
```
After that, copied the dir structure from the official PSOL binaries and symlinked my compiled version of ``pagespeed_automatic.a`` there and the ``testing-dependencies/mod_pagespeed`` under my ``debian/modules/ngx_pagespeed/psol/include``and followed the further instructions by [Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-add-ngx_pagespeed-to-nginx-on-debian-8), which produced a serie of .deb files.

As soon as I have done my testing and roll-out, I will probably write something up for this.

Cheers, @oschaaf, for all the help.
