### ISSUE TITLE
Error on compiling 

### ISSUE THREAD

**Issue by MixMe** [pagespeed/ngx_pagespeed#1430]
./configure: error: module ngx_pagespeed requires the pagespeed optimization library. Look in /root/nginx-1.13.1/objs/autoconf.err for more details.

**Comment by itchenyi** [comment]
[https://modpagespeed.com/doc/build_ngx_pagespeed_from_source](https://modpagespeed.com/doc/build_ngx_pagespeed_from_source)

**Comment by oschaaf** [comment]
@MixMe What steps did you take that led up to that error?

**Comment by MixMe** [comment]
hmm strange now it works :) sorry
