### ISSUE TITLE
Export Cache Metrics

### ISSUE THREAD

**Issue by discostur** [pagespeed/ngx_pagespeed#1431]
Hi,

is there a way how i can export the Cache Metrics from the PageSpeed-Admin Page (pagespeed_admin/console)? I would like to export it to Kibana / Elasticsearch or Grafana Dashboard ...

Thanks
Greets
Kilian

**Comment by oschaaf** [comment]
You can get the console data as json: http://modpagespeed.com/pagespeed_admin/console?json
You can get the stats as json too: http://modpagespeed.com/pagespeed_admin/stats_json
Does that help?

**Comment by oschaaf** [comment]
@discostur Closing this issue under th assumption you can use json console data / stats suffice, but feel free to re-open if I'm wrong about that.

**Comment by discostur** [comment]
@oschaaf sorry forgot to answer ... yes please close it! Seems that this is what i was searching for. Thanks for your help!
