### ISSUE TITLE
purging cache is not ORIGIN specific

### ISSUE THREAD

**Issue by nullmem** [pagespeed/ngx_pagespeed#1432]
When executing PERGE method to ngx_pagespeed server such as:

curl --request PURGE 'http://www.example.com/*'

The cache for *ALL* domains will be purged, not just the ORIGIN domain.

Should this not clear the cache only for www.example.com?

**Comment by jmarantz** [comment]
That is not the intent.  Can you give your pagespeed.conf file?  I want to
know how it is set up.

What happens if you run the purge from the
http://www.example.com/pagespeed_admin/cache ?

**Comment by nullmem** [comment]
pagespeed on;
pagespeed Statistics on;
pagespeed StatisticsLogging on;
pagespeed LogDir /var/log/pagespeed;
pagespeed RewriteLevel CoreFilters;
pagespeed EnableFilters extend_cache;
pagespeed FileCachePath /var/pscache;
pagespeed Disallow "*/?elementor*";
pagespeed Disallow "*/wp-admin/*";
pagespeed Disallow "*/wp-login.php*";
pagespeed EnableCachePurge on;
pagespeed PurgeMethod PURGE;

location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" { add_header "" ""; }
location ~ "^/pagespeed_static/" { }
location ~ "^/ngx_pagespeed_beacon$" { }

**Comment by jmarantz** [comment]
So, no host-blocks?

**Comment by jmarantz** [comment]
Also, the cache is shared between the different hosts?  You probably want to make a separate file-cache for each host.

**Comment by nullmem** [comment]
I include the pagespeed.conf in each host like this:
include snippets/pagespeed.conf;

as for pagespeed admin, I normally don't use it, but I enabled to test, it also invalidates entire cache.

**Comment by nullmem** [comment]
So, if I were to have sperate cache dir for each vhost, this would resolve my issue?

**Comment by nullmem** [comment]
I just verified that setting a separate FileCachePath for each vhost worked. Thank you for your help
