### ISSUE TITLE
New feature request, inline external images

### ISSUE THREAD

**Issue by MixMe** [pagespeed/ngx_pagespeed#1434]
Inline small images from any URL(external host)

**Comment by oschaaf** [comment]
There is MapProxyDomain, which could help you with getting images from external hosts inlined:
https://modpagespeed.com/doc/domains#MapProxyDomain

It is alo possible to enable inlining of resources without explicit authorization:
https://modpagespeed.com/doc/domains#inline_without_auth

Does either of these options do what you have in mind?

**Comment by oschaaf** [comment]
I'm closing this feature request, because I think we already support this (and more), but please re-open if I misunderstand the request.
