### ISSUE TITLE
How to analyze the file cache inode usage and adjust the limit for better performance?

### ISSUE THREAD

**Issue by PikachuEXE** [pagespeed/ngx_pagespeed#1436]
We installed the module on a server with 100G for disk size and 6553600 for inode

The file cache folder is using 14G in disk size and 3340008 in inode.
It seems the inode usage is growing faster than disk space usage.

How do we analyze the performance of file cache and determine the limit for inode usage?
Can we also find out if a particular "segment" of file cache is rarely used?

**Comment by oschaaf** [comment]
Closing -- replied in the x-post to https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/atZsby0TAjY
