### ISSUE TITLE
No PSOL library binary available yet for v1.12.34.2?

### ISSUE THREAD

**Issue by SuperNami** [pagespeed/ngx_pagespeed#1437]
Would love to compile nginx with the latest version of pagespeed but unfortunately the latest PSOL binary is not uploaded yet: http://dl.google.com/dl/page-speed/psol/1.12.34.2.tar.gz

Not sure if compiling it myself would be the right way forward, with all the little quirks that come with it.. without an automation script.

**Comment by oschaaf** [comment]
You probably want https://dl.google.com/dl/page-speed/psol/1.12.34.2-x64.tar.gz or https://dl.google.com/dl/page-speed/psol/1.12.34.2-ia32.tar.gz

See https://github.com/pagespeed/ngx_pagespeed/issues/1337#issuecomment-266844908

Where did you you get that url? 
(If there's a stale doc somewhere, I'd like to update it).

**Comment by SuperNami** [comment]
Thanks Otto, I didn't retrieve the URL somewhere, I guessed it from previous instructions (where the version numbers were the same).

I have my own Ansible [playbook](https://github.com/SuperNami/ansible-nginx-role) to compile nginx with Pagespeed and other nginx modules, and I wanted to update the version numbers.

**Comment by oschaaf** [comment]
Ok, cool! Closing this issue then.
