### ISSUE TITLE
Update the docs for building a dynamic ngx_pagespeed module

### ISSUE THREAD

**Issue by Abubakar63** [pagespeed/ngx_pagespeed#1440]
I am pushing my head with this since last 1 day. I need your help now on this issue. I am going to explain this in detail.

I have an nginx version 1.10.2 installed in /etc/nginx and working perfectly fine. Now I want to integrate page speed module in this nginx. I am following this tutotrial https://modpagespeed.com/doc/build_ngx_pagespeed_from_source

I am running following command to install it 

```
bash <(curl -f -L -sS https://ngxpagespeed.com/install) \
     --nginx-version 1.10.3 \
     --dynamic-module \
```

it asks me to enter any extra configuration and I found extra configs in `nginx -V` and I wrote these

```
--with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_perl_module --with-http_random_index_module --with-http_secure_link_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-mail --with-mail_ssl_module --with-stream --with-stream_ssl_module --with-threads
```

After that I opened my config file and added
```
load_module "modules/ngx_pagespeed.so";
```

and restarted my nginx.

It gives me this error
```
module "/usr/share/nginx/modules/ngx_pagespeed.so" is not binary compatible in /etc/nginx/nginx.conf:5
```

Please if anyone can help me in this. I have also tried following this link https://www.digitalocean.com/community/tutorials/how-to-add-ngx_pagespeed-to-nginx-on-ubuntu-14-04 and install with pagespeed module. But I got my nginx messed up completely. Now I am not getting which nginx version is running :(

Kind Regards,
Abubakar Bilal

**Comment by oschaaf** [comment]
I did some debugging on where the signature in a module build according to our instructions would diverge from the server signature from, say, the one you can get from the nginx ppa.

```
1 ubuntu@lw-dev:~/tmp⟫ nginx 
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
ngx_pagespeed signature: [8,4,8,0000111111010111001111111111101110]
server        signature: [8,4,8,0000111111010111001111111111111110]
NGX_MODULE_SIGNATURE_30 diverges!
```

At https://github.com/nginx/nginx/blob/a6cb8210905f35977276cb3861184e4dad99cc2a/src/core/ngx_module.h you can see that `NGX_MODULE_SIGNATURE_30` corresponds to `NGX_HTTP_HEADERS`.
That doesn't get set in the nginx core as far as I can tell, and it doesn't show up in the `./configure' line.

To be continued.

**Comment by oschaaf** [comment]
Adding `--with-cc-opt='-DNGX_HTTP_HEADERS'` to nginx's `./configure` arguments (or modifying any existing `--with-cc-opt='xxx'` to include `-DNGX_HTTP_HEADERS`)  makes ngx_pagespeed.so binary compatible with the ppa version.

Stripping the arguments that are not relevant for binary compatibility, the following should build ngx_pagespeed as a dynamic for use with the latest stable at nginx's ppa (1.12.1):

```
bash <(curl -f -L -sS https://ngxpagespeed.com/install) \
     --nginx-version "1.12.1" \
     --dynamic \
     -a '--with-http_ssl_module                                                                                                                                                                
--with-http_realip_module                                                                                                                                                                 
--with-http_dav_module                                                                                                                                                                    
--with-http_gzip_static_module                                                                                                                                                            
--with-http_gunzip_module                                                                                                                                                                 
--with-threads                                                                                                                                                                            
--with-cc-opt="-DNGX_HTTP_HEADERS"'
```

When the  above script asks you if it should install nginx, you should probably decline, assuming you just want the dynamic module. 
Upon completion, the dynamic module should be ready for use at `~/nginx-1.12.1/objs/ngx_pagespeed.so` 

If you configure your package managed nginx to load this dynamic module, you may want to block updates for nginx by the package manager: The nginx version is included in the binary compatibility check. Blocking automatic updates implicates that you have to do some regular maintenance to keep up with important updates.

**Comment by oschaaf** [comment]
Added an entry to the [priority list](https://github.com/pagespeed/mod_pagespeed/wiki/Work-Prioritization) to update the docs to include the results of the research done in https://github.com/pagespeed/ngx_pagespeed/issues/1440#issuecomment-315565106

**Comment by itbdw** [comment]
Thanks for this great work! I succeeded with @oschaaf 's guide.

I upgrade nginx version to 1.12.1 by add nginx ppa.

```
sudo add-apt-repository ppa:nginx/stable
sudo apt-get update
apt install nginx
```

I also made a git repo to share the ngx_pagespeed.so file. Hope this can simplify the procedure adding the dynamic module to existing nginx on the server.

https://github.com/itbdw/nginx_pagespeed_dynamic_module

**Comment by secfigo** [comment]
If anyone is interesting, created gist with detailed information here.   https://gist.github.com/secfigo/f41a5f243610053d03ad410254540802

**Comment by pkiula** [comment]
Adding the `-DNGX_HTTP_HEADERS` stuff does not solve the issue mentioned here.
