### ISSUE TITLE
Prevent pagespeed from removing line breaks in JS

### ISSUE THREAD

**Issue by bbbenji** [pagespeed/ngx_pagespeed#1443]
I have a site which relies on a JS snippet which must be a certain format, meaning each value must be on a new line. Unfortunately this is a limitation required by a 3rd party.

example of good snippet:
```
<script type="text/javascript">
  client_email = 'user@github.com';
  order_id = '245323';
</script>
```
However, with pagespeed enabled the output becomes this:
`<script type="text/javascript">client_email='user@github.com';order_id='245323';</script>`

This renders the snippet invalid by the 3rd party. Disabling pagespeed fixes the problem immediately. How can I prevent this from happening while keeping the rest of pagespeed working for me?

**Comment by jmarantz** [comment]
Ideally you could blacklist the particular script block, but we don't
currently have a way to do that.

The next best best thing is to disable rewriting *any* inline JavaScript:
   ModPagespeedDisableFilters rewrite_javascript_inline
 ModPagespeedEnableFilters rewrite_javascript_external

**Comment by bbbenji** [comment]
`pagespeed DisableFilters rewrite_javascript_inline;`

Fixed the issue. Thank you @jmarantz
