### ISSUE TITLE
Image optimization issue for webp images

### ISSUE THREAD

**Issue by sankarkodali** [pagespeed/ngx_pagespeed#1445]
Dear Sir,

All the filters are enabled in config file, But my website https://www.automotive-technology.com page speed score is 54% only. webp image compression is not working.please check the below filters

pagespeed RewriteLevel PassThrough;
   pagespeed FetchHttps enable;
   pagespeed EnableFilters extend_cache;

   pagespeed EnableFilters insert_image_dimensions;
   pagespeed EnableFilters resize_images;
   pagespeed EnableFilters rewrite_images;
   pagespeed EnableFilters recompress_images;
   pagespeed EnableFilters resize_mobile_images;
   pagespeed EnableFilters inline_images;
   pagespeed EnableFilters resize_rendered_image_dimensions;
   pagespeed EnableFilters responsive_images;
   pagespeed EnableFilters convert_jpeg_to_progressive;
   pagespeed EnableFilters convert_png_to_jpeg;
   pagespeed EnableFilters convert_jpeg_to_webp;
   pagespeed EnableFilters convert_to_webp_lossless;
   pagespeed EnableFilters recompress_jpeg;
   pagespeed EnableFilters recompress_png;
   pagespeed EnableFilters recompress_webp;

   pagespeed EnableFilters inline_import_to_link;
   pagespeed EnableFilters move_css_to_head;
   pagespeed EnableFilters combine_css;
   pagespeed EnableFilters rewrite_css;
   pagespeed EnableFilters make_google_analytics_async;
   pagespeed EnableFilters rewrite_javascript;
   pagespeed EnableFilters inline_css;
   pagespeed EnableFilters combine_javascript;
   pagespeed EnableFilters insert_ga;
   pagespeed EnableFilters collapse_whitespace,remove_comments;

   pagespeed Domain *.automotive-technology.com;
   pagespeed Domain https://industry.automotive-technology.com;
   pagespeed LoadFromFile https://industry.automotive-technology.com/
                    /home/automotivetechno/public_html/industry;
   pagespeed MapOriginDomain http://localhost https://www.automotive-technology.com;
   pagespeed SslCertDirectory /etc/pki/tls/certs;
   pagespeed SslCertFile /etc/pki/tls/cert.pem;

   pagespeed CriticalImagesBeaconEnabled false;
   pagespeed LazyloadImagesAfterOnload off;

**Comment by oschaaf** [comment]
Webp compression is working (I see images being transcoded to .webp in the html).

**Comment by sankarkodali** [comment]
Dear Sir,

Please check the attachment. Page view source is showing images as extension in webp. But the same images in Google Page Speed Insights URL is showing .JPG images are uncompressable

![screenshot from 2017-07-29 12-57-32](https://user-images.githubusercontent.com/29781025/28743065-29b0a9c0-745e-11e7-88aa-feb67ae82c29.png)

**Comment by jmarantz** [comment]
PageSpeed Insights is not be sending Accept:image/webp: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.whatismybrowser.com%2Fdetect%2Fwhat-http-headers-is-my-browser-sending&tab=desktop
