### ISSUE TITLE
Completly disable pagespeed

### ISSUE THREAD

**Issue by discostur** [pagespeed/ngx_pagespeed#1447]
Hi,

im running two domains on the same nginx, domainA and domainB. DomainA should run with mod_pagespeed and domainB without, because it runs behind a CDN (akamai etc.).

What i try to do is to completly disable pagespeed for domainB whilte domainA runs with pagespeed. I setup filter rules to

```
pagespeed RewriteLevel PassThrough;
```

for domainB and it is almost shutdown, but it still changes my cash header for the index.html page. I have some global pagespeed settings:

```
pagespeed GlobalAdminPath /pagespeed_global_admin;
pagespeed MessageBufferSize 100000;
pagespeed UsePerVhostStatistics on;
pagespeed UseNativeFetcher on;
resolver 8.8.8.8;
pagespeed LRUCacheKbPerProcess     32768;       #(32MB Per Nginx Process)
pagespeed LRUCacheByteLimit        16384;       #(16KB size limit per object in LRU)
pagespeed ImageMaxRewritesAtOnce 20;
pagespeed RewriteLevel PassThrough;
```

Because of these settings, pagespeed still adds an cache-control header to my index.html from domainB where it shouldn't do anything. Here are the screenshots when i completly disable global_pagespeed_settings:

**Disabled**
<img width="546" alt="bildschirmfoto 2017-08-02 um 11 08 48" src="https://user-images.githubusercontent.com/2615420/28866676-f6b6e30e-7773-11e7-8617-318646509bdc.png">

**Enabled**
<img width="576" alt="bildschirmfoto 2017-08-02 um 11 09 06" src="https://user-images.githubusercontent.com/2615420/28866685-fc108cb0-7773-11e7-9c4c-7f6f8ab350ab.png">

Is there a chance to still use my global_pagespeed_settings and disable pagespeed completly for domainB while it is active for domainA? Because when pagepseed sets me cache headers, akamai will not work correctly for domainB.

Thanks

**Comment by oschaaf** [comment]
You could add the following in the domain that has turned pagespeed in passthrough mode:
```
pagespeed ModifyCachingHeaders off;
```

https://modpagespeed.com/doc/configuration#ModifyCachingHeaders

Alternatively, if you really want pagespeed turned off, on a domain I think you may want this instead:

```
server {
...
pagespeed off;
...
}
```

**Comment by discostur** [comment]
```
pagespeed ModifyCachingHeaders off;
```

@oschaaf that was exactly what i was searching for! Didn't find it by myself ... thanks for your fast help;)
