### ISSUE TITLE
Does the install script automatically rebuild nginx with the same configuration from a previous installation?

### ISSUE THREAD

**Issue by alexweissman** [pagespeed/ngx_pagespeed#1448]
I started by following the instructions on the [Pagespeed website](https://modpagespeed.com/doc/build_ngx_pagespeed_from_source) to rebuild nginx with the Pagespeed module using the automated script.

After extracting nginx, the script gave me this notice:

```
About to build nginx.  Do you have any additional ./configure
arguments you would like to set?  For example, if you would like
to build nginx with https support give --with-http_ssl_module
If you don't have any, just press enter.
```

I got nervous, so I quit and ran `nginx -V`.  As I am using a build of nginx that came preinstalled as part of a larger distribution, I didn't realize that there were a large number of configuration options (many of which I depend on, _like ssl_) that had been added the first time around.

I wasn't sure if this script would automatically detect my previous configuration and rebuild with those options in addition to the pagespeed module, so I tried the script again with the dry run (`-d`) option.  I got this output:

```
would run cd /home/alexw/nginx-1.13.3/
About to build nginx.  Do you have any additional ./configure
arguments you would like to set?  For example, if you would like
to build nginx with https support give --with-http_ssl_module
If you don't have any, just press enter.
> 
About to configure nginx with:
   ./configure --add-module=/home/alexw/ngx_pagespeed-latest-stable
Does this look right? [Y/n] Y
would run ./configure --add-module=/home/alexw/ngx_pagespeed-latest-stable
  with the following additional environment variables:
    MOD_PAGESPEED_DIR=
    PSOL_BINARY=
Build nginx? [Y/n] Y
would run make
Install nginx? [Y/n] Y
would run sudo make install

Nginx installed with ngx_pagespeed support compiled-in.
```

From what I can tell, I would have lost all of my other modules if I had just mindlessly pressed Enter at that prompt during an actual run.  Am I correct?

**Comment by oschaaf** [comment]
The script will install nginx configured with the flags it shows you (so you could very well be missing modules provided by your distribution). In the case you posted nginx's default install location would be used, which problaby is not the same as where the nginx binary from your distribution lives.
You can add the ./configure arguments of the distro provided nginx binary as shown in -V during the install process to ensure you get all the modules you need.

Alternatively, you could consider installing ngx_pagespeed as a dynamic module if the nginx version provided by your distribution is recent enough to support it. In which case the comments here may be of interest: https://github.com/pagespeed/ngx_pagespeed/issues/1440#issuecomment-315565106

**Comment by oschaaf** [comment]
Closing this issue, but please let us know you run into anything.

**Comment by alexweissman** [comment]
Thanks!  I think it would be helpful if the docs mentioned this.  A lot of people are running builds of nginx that they didn't build themselves (and may have no idea what all of this means)!

I've written some docs for my own project which clarify the process better: https://learn.userfrosting.com/going-live/vps-production-environment/additional-recommendations#install-and-configure-google-s-pagespeed-module.  Feel free to steal anything you find useful.
