### ISSUE TITLE
Images with non ascii characters in its name are not being rewritten

### ISSUE THREAD

**Issue by ozdemirburak** [pagespeed/ngx_pagespeed#1450]
When there is a image with a filename where non ascii characters lie, like `İstanbul.jpg` where Turkish İ is a problem here, it is not being processed by pagespeed.

I don't know if this is the expected behaviour, but I've tested this with an image with the name `Nevşehir.jpg` which was not being processed before I renamed it to `Nevsehir.jpg`. (See the ş to s transformation)

You can see an example [here](https://butcenegore.com/). Check the [image](https://butcenegore.com/uploads/cities/%C4%B0stanbul.jpg) on the column: `Ankara Çıkışlı 100 TL ile Haftalık Yurt İçi Uçak Biletleri`.

Current configuration is below, using the `v1.12.34.2-stable` pagespeed.

```nginx
pagespeed EnableFilters rewrite_images;
pagespeed EnableFilters lazyload_images;
pagespeed EnableFilters convert_jpeg_to_progressive,convert_png_to_jpeg,convert_jpeg_to_webp;
```

**Comment by oschaaf** [comment]
Hi, this is a known issue, tracked at https://github.com/pagespeed/ngx_pagespeed/issues/1023

**Comment by ozdemirburak** [comment]
Sorry, missed that one.
