### ISSUE TITLE
nginx 1.13.4 ‘ngx_http_core_try_files_phase’ was not declared in this scope

### ISSUE THREAD

**Issue by centminmod** [pagespeed/ngx_pagespeed#1451]
Another nginx 1.13.4 release which broke ngx_pagespeed compilations. 

* On CentOS 7.3 64bit with GCC 6.2.1. Full configure and error at https://gist.github.com/centminmod/b009a9b86eebd637b4e51d188d4a21e6
* 1.13.4 change log http://nginx.org/en/CHANGES

```
-lrt -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib \
-shared
../ngx_pagespeed-1.12.34.2-beta/src/ngx_pagespeed.cc: In function ‘ngx_int_t net_instaweb::{anonymous}::ps_preaccess_handler(ngx_http_request_t*)’:
../ngx_pagespeed-1.12.34.2-beta/src/ngx_pagespeed.cc:3011:31: error: ‘ngx_http_core_try_files_phase’ was not declared in this scope
   while (ph[i + 1].checker != ngx_http_core_try_files_phase &&
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/svr-setup/nginx-1.13.4'
make: *** [build] Error 2
```

configure options

> ./configure --with-ld-opt="-lrt -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib" --with-cc-opt="-m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -Wno-error=strict-aliasing -fstack-protector-strong -flto -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations -gsplit-dwarf" --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-compat --with-http_stub_status_module --with-http_secure_link_module --with-libatomic --with-http_gzip_static_module --add-dynamic-module=../ngx_brotli --add-dynamic-module=../ngx_pagespeed-1.12.34.2-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_preread_module --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.0 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.3.0 --add-module=../set-misc-nginx-module-0.31 --add-module=../echo-nginx-module-0.60 --add-module=../redis2-nginx-module-0.14 --add-module=../ngx_http_redis-0.3.7 --add-module=../memc-nginx-module-0.18 --add-module=../srcache-nginx-module-0.31 --add-module=../headers-more-nginx-module-0.32 --with-pcre=../pcre-8.41 --with-pcre-jit --with-zlib=../zlib-1.2.11 --with-http_ssl_module --with-http_v2_module --with-http_v2_hpack_enc --with-openssl=../libressl-2.6.0

**Comment by oschaaf** [comment]
Thanks for the report. It seems the breaking change was in https://github.com/nginx/nginx/commit/129b06dc5dfab7b4513a4f274b3778cd9b8a6a22

Looking at the specifics, it don't think it's going to be hard to address on our side.

**Comment by fmunteanu** [comment]
@oschaaf Otto, please let us know if there is a quick patch we could apply to fix the issue? 😃

**Comment by CWelshE** [comment]
@fmunteanu I just used `--nginx-version '1.13.3'` instead of `--nginx-version latest` until this issue is solved

**Comment by fmunteanu** [comment]
@CWelshE Cody, I'm not familiar with this switch? I run the Nginx build with `.configure --add-dynamic-module=ngx_pagespeed-1.12.34.2-stable`

**Comment by noogen** [comment]
Also saw this build error on Ubuntu 16.04.  Sticking with 1.13.3 in my build too, for now.

**Comment by AnoopAlias** [comment]
Same error

```
     ngx_pagespeed-1.12.34.2-stable/src/ngx_message_handler.cc
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4
 -grecord-gcc-switches -m64 -mtune=generic  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-local-typedefs -Wno-error -Wno-deprecated-declarations -DNDK_SET_VAR -DNDK_UPSTREAM_LIST --std=c++11 -I
 src/core -I src/event -I src/event/modules -I src/os/unix -I ngx_pagespeed-1.12.34.2-stable/psol/include -I ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/chromium/src -I ngx_p
agespeed-1.12.34.2-stable/psol/include/third_party/google-sparsehash/src/src -I ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I ng
x_pagespeed-1.12.34.2-stable/psol/include/third_party/grpc/src/include -I ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/protobuf/src/src -I ngx_pagespeed-1.12.34.2-stable/psol/
include/third_party/re2/src -I ngx_pagespeed-1.12.34.2-stable/psol/include/out/Release/obj/gen -I ngx_pagespeed-1.12.34.2-stable/psol/include/out/Release/obj/gen/protoc_out/instaweb -I n
gx_pagespeed-1.12.34.2-stable/psol/include/third_party/apr/src/include -I ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/aprutil/src/include -I ngx_pagespeed-1.12.34.2-stable/ps
ol/include/third_party/apr/gen/arch/linux/x64/include -I ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I ngx_pagespeed-1.12.34.2-stable/psol
/include/url -I /usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.1.7/src -I ngx_brotli/deps/brotli/include -I ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I ngx_devel_kit-0.3.0/src -I ngx_
devel_kit-0.3.0/objs -I objs/addon/ndk -I /opt/nDeploy-libmodsecurity/include/ -I ./pcre-8.41 -I ./libressl-2.5.5/.openssl/include -I ./zlib-1.2.11 -I objs -I src/http -I src/http/module
s -I src/http/v2 -I ngx_devel_kit-0.3.0/src -I src/stream \
        -o objs/addon/src/ngx_pagespeed.o \
        ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc
ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc: In function ‘ngx_int_t net_instaweb::{anonymous}::ps_preaccess_handler(ngx_http_request_t*)’:
ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc:3011:31: error: ‘ngx_http_core_try_files_phase’ was not declared in this scope
   while (ph[i + 1].checker != ngx_http_core_try_files_phase &&
```

**Comment by fmunteanu** [comment]
@greg-md, what is the switch @CWelshE is referring to? `--nginx-version '1.13.3'`

**Comment by Injust** [comment]
@fmunteanu That's the switch for the automated install at https://modpagespeed.com/doc/build_ngx_pagespeed_from_source.

**Comment by greg-md** [comment]
@fmunteanu yes, I was installing it from source as @Injust mentioned, so this helped.

**Comment by oschaaf** [comment]
For those who want to try out the candidate fix:  https://github.com/pagespeed/ngx_pagespeed/pull/1453
(diff: https://patch-diff.githubusercontent.com/raw/pagespeed/ngx_pagespeed/pull/1453.diff)

**Comment by fmunteanu** [comment]
@oschaaf Otto, I confirm the patch works beautifully. Thanks for your support!

**Comment by Injust** [comment]
@oschaaf Can also confirm that patch is working as intended. Thank you!

**Comment by centminmod** [comment]
@oschaaf  thanks confirmed working patch as well 👍

**Comment by AminZoubaa** [comment]
@oschaaf you are my hero tonight. I can confirm too, that it's working 👍

**Comment by kozhin** [comment]
@oschaaf, thanks for your support! When do you plan to release this fixed version?

**Comment by harichristian** [comment]
@oschaaf you save my day 👍

**Comment by lilmike** [comment]
Is there a planned release timeline for the fixed version? I'm currently holding back nginx-mainline on my arch linux server, but it's only a matter of time until the built 1.13.3 package from arch becomes unable to run because they upgrade a required library or something.
Thanks!
-Michael.

**Comment by Eckybrazzz** [comment]
The install with  bash <(curl -f -L -sS https://ngxpagespeed.com/install)      --nginx-version '1.13.3' works just fine but when calling the page I get `ERROR

The requested URL could not be retrieved

The following error was encountered while trying to retrieve the URL: http://techlabshost.com/

Connection to 34.235.174.83 failed.

The system returned: (111) Connection refused

The remote host or network may be down. Please try the request again.

Your cache administrator is root.


Generated Sun, 24 Sep 2017 10:08:04 GMT by newyork-s02-i01 (squid/3.5.26)`

**Comment by oschaaf** [comment]
Update -- we are working on an ngx_pagespeed-only point release for this.

**Comment by oschaaf** [comment]
Another update: ngx_pagespeed 1.12.34.3-stable was just released, and contains a change to address this issue: https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/9r2QSTepg9E

**Comment by noogen** [comment]
What about the existing of the file https://dl.google.com/dl/page-speed/psol/1.12.34.3-x64.tar.gz from the pagespeed download instruction here https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source 
```
psol_url=https://dl.google.com/dl/page-speed/psol/${NPS_RELEASE_NUMBER}.tar.gz
```

**Comment by oschaaf** [comment]
@noogen For building ngx_pagespeed `1.12.34.3` you actually need to use `https://dl.google.com/dl/page-speed/psol/1.12.34.2-x64.tar.gz`, because it is an nginx-only release.
I'll make an update to the docs to pull the right version, thanks for pointing this out.

**Comment by oschaaf** [comment]
@noogen testing this, the documented install process work fine for me. It pulls the right psol version from the `PSOL_BINARY_URL` file. Could you post more information about the problem you ran in to?

**Comment by centminmod** [comment]
cheers works here

```
nginx -V
nginx version: nginx/1.13.5
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)
built with LibreSSL 2.5.5
TLS SNI support enabled
```
> configure arguments: --with-ld-opt='-lrt -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -fstack-protector-strong --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -gsplit-dwarf' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-compat --with-http_stub_status_module --with-http_secure_link_module --add-dynamic-module=../nginx-module-vts --with-libatomic --with-http_gzip_static_module **--add-dynamic-module=../ngx_pagespeed-1.12.34.3-stable** --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_preread_module --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.0 --add-module=../ngx_cache_purge-2.4.2 --add-module=../ngx_devel_kit-0.3.0 --add-dynamic-module=../set-misc-nginx-module-0.31 --add-dynamic-module=../echo-nginx-module-0.61 --add-module=../redis2-nginx-module-0.14 --add-module=../ngx_http_redis-0.3.7 --add-module=../memc-nginx-module-0.18 --add-module=../srcache-nginx-module-0.31 --add-dynamic-module=../headers-more-nginx-module-0.32 --with-pcre=../pcre-8.41 --with-pcre-jit --with-zlib=../zlib-1.2.11 --with-http_ssl_module --with-http_v2_module --with-openssl=../libressl-2.5.5

**Comment by noogen** [comment]
Sorry, the build works for me with psol/1.12.34.2-x64.tar.gz too.  Thanks.

**Comment by Reborns** [comment]
Hi guys 
NginX 1.13.6 > ngx_pagespeed 1.12.34.3-stable > PSOL 1.12.34.2-x64.tar.gz  trows this error 
       /nginx/modules/nginx_pagespeed/src/ngx_server_context.cc
/nginx/modules/nginx_pagespeed/src/ngx_pagespeed.cc: In function ‘ngx_int_t net_instaweb::{anonymous}::ps_preaccess_handler(ngx_http_request_t*)’:
/nginx/modules/nginx_pagespeed/src/ngx_pagespeed.cc:3011:31: error: ‘ngx_http_core_try_files_phase’ was not declared in this scope
   while (ph[i + 1].checker != ngx_http_core_try_files_phase &&
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
objs/Makefile:2228: recipe for target 'objs/addon/src/ngx_pagespeed.o' failed

**Comment by oschaaf** [comment]
@Reborns the line numbers for nps 1.12.34.3 don't seem to match.. can you post the commands leading up to the error?

**Comment by Reborns** [comment]
@oschaaf  
Like this ? 

`cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fdebug-prefix-map=/nginx/nginx-1.13.6=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC -Wno-deprecated-declarations  -D_GLIBCXX_USE_CXX11_ABI=0 --std=c++11 -I src/core -I src/event -I src/event/modules -I src/os/unix -I /var/lib/gems/2.3.0/gems/passenger-5.1.8/src -I /nginx/modules/nginx_pagespeed/psol/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/chromium/src -I /nginx/modules/nginx_pagespeed/psol/include/third_party/google-sparsehash/src/src -I /nginx/modules/nginx_pagespeed/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/grpc/src/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/protobuf/src/src -I /nginx/modules/nginx_pagespeed/psol/include/third_party/re2/src -I /nginx/modules/nginx_pagespeed/psol/include/out/Release/obj/gen -I /nginx/modules/nginx_pagespeed/psol/include/out/Release/obj/gen/protoc_out/instaweb -I /nginx/modules/nginx_pagespeed/psol/include/third_party/apr/src/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/aprutil/src/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/apr/gen/arch/linux/x64/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I /nginx/modules/nginx_pagespeed/psol/include/url -I objs -I src/http -I src/http/modules -I src/http/v2 -I /nginx/modules/nginx_brotli/deps/brotli/include -I src/mail -I src/stream \
        -o objs/addon/src/ngx_rewrite_driver_factory.o \
        /nginx/modules/nginx_pagespeed/src/ngx_rewrite_driver_factory.cc
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fdebug-prefix-map=/nginx/nginx-1.13.6=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC -Wno-deprecated-declarations  -D_GLIBCXX_USE_CXX11_ABI=0 --std=c++11 -I src/core -I src/event -I src/event/modules -I src/os/unix -I /var/lib/gems/2.3.0/gems/passenger-5.1.8/src -I /nginx/modules/nginx_pagespeed/psol/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/chromium/src -I /nginx/modules/nginx_pagespeed/psol/include/third_party/google-sparsehash/src/src -I /nginx/modules/nginx_pagespeed/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/grpc/src/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/protobuf/src/src -I /nginx/modules/nginx_pagespeed/psol/include/third_party/re2/src -I /nginx/modules/nginx_pagespeed/psol/include/out/Release/obj/gen -I /nginx/modules/nginx_pagespeed/psol/include/out/Release/obj/gen/protoc_out/instaweb -I /nginx/modules/nginx_pagespeed/psol/include/third_party/apr/src/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/aprutil/src/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/apr/gen/arch/linux/x64/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I /nginx/modules/nginx_pagespeed/psol/include/url -I objs -I src/http -I src/http/modules -I src/http/v2 -I /nginx/modules/nginx_brotli/deps/brotli/include -I src/mail -I src/stream \
        -o objs/addon/src/ngx_rewrite_options.o \
        /nginx/modules/nginx_pagespeed/src/ngx_rewrite_options.cc
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fdebug-prefix-map=/nginx/nginx-1.13.6=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC -Wno-deprecated-declarations  -D_GLIBCXX_USE_CXX11_ABI=0 --std=c++11 -I src/core -I src/event -I src/event/modules -I src/os/unix -I /var/lib/gems/2.3.0/gems/passenger-5.1.8/src -I /nginx/modules/nginx_pagespeed/psol/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/chromium/src -I /nginx/modules/nginx_pagespeed/psol/include/third_party/google-sparsehash/src/src -I /nginx/modules/nginx_pagespeed/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/grpc/src/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/protobuf/src/src -I /nginx/modules/nginx_pagespeed/psol/include/third_party/re2/src -I /nginx/modules/nginx_pagespeed/psol/include/out/Release/obj/gen -I /nginx/modules/nginx_pagespeed/psol/include/out/Release/obj/gen/protoc_out/instaweb -I /nginx/modules/nginx_pagespeed/psol/include/third_party/apr/src/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/aprutil/src/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/apr/gen/arch/linux/x64/include -I /nginx/modules/nginx_pagespeed/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I /nginx/modules/nginx_pagespeed/psol/include/url -I objs -I src/http -I src/http/modules -I src/http/v2 -I /nginx/modules/nginx_brotli/deps/brotli/include -I src/mail -I src/stream \
        -o objs/addon/src/ngx_server_context.o \
        /nginx/modules/nginx_pagespeed/src/ngx_server_context.cc
/nginx/modules/nginx_pagespeed/src/ngx_pagespeed.cc: In function ‘ngx_int_t net_instaweb::{anonymous}::ps_preaccess_handler(ngx_http_request_t*)’:
/nginx/modules/nginx_pagespeed/src/ngx_pagespeed.cc:3011:31: error: ‘ngx_http_core_try_files_phase’ was not declared in this scope
   while (ph[i + 1].checker != ngx_http_core_try_files_phase &&
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
objs/Makefile:2228: recipe for target 'objs/addon/src/ngx_pagespeed.o' failed
make[2]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/nginx/nginx-1.13.6/debian/build-nginx'
Makefile:8: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/nginx/nginx-1.13.6/debian/build-nginx'
debian/rules:96: recipe for target 'build-arch.nginx' failed
make: *** [build-arch.nginx] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debian9 04:08:53 nginx-1.13.6 # `

**Comment by oschaaf** [comment]
@Reborns I was wondering about the commands that you executed yourself. 

The build error you posted was triggered by line `ngx_pagespeed.cc:3011:31`. 
For `1.12.34.3` that corresponds to https://github.com/pagespeed/ngx_pagespeed/blob/e6931ba03746a3a14ef43da310629090efebe907/src/ngx_pagespeed.cc#L3011.

That line does not mention `ngx_http_core_try_files_phase` so there's a mismatch.

The documented build instructions work fine for me with nginx-1.13.6:  https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source

So In particular, I wonder how you pulled ngx_pagespeed `1.12.34.3-stable`, because to it looks like you have another version.

**Comment by Reborns** [comment]
@oschaaf  
I'm very sorry, you were right. I used a different version . With the latest version  1.12.34.3-stable everything is fine  ..

**Comment by oschaaf** [comment]
@Reborns no problem, happy to hear it's working!
