### ISSUE TITLE
rewrite domain

### ISSUE THREAD

**Issue by i6666800** [pagespeed/ngx_pagespeed#1452]
hi,please look my site https://www.bbaodou.com/products.html,
I rewrite the cdn like this:
pagespeed MapRewriteDomain https://www.bbaodou.com/a3/cloud https://a3.leadongcdn.com/cloud;
but it doesn't work

**Comment by jmarantz** [comment]
I think you might have the arguments backwards.

https://modpagespeed.com/doc/domains#mapping_rewrite

**Comment by oschaaf** [comment]
Closing - @i6666800 please re-open if @jmarantz suggestion didn't help (I think it will!).

**Comment by i6666800** [comment]
Thanks for Reply，The above problem I have solved，But now I have a different question，The images that are displayed directly on the page are optimized, but those dynamically loaded images are not optimized

**Comment by oschaaf** [comment]
Images that are dynamically loaded via js can be optimized in-place (and probably are, as that is on by default): https://modpagespeed.com/doc/system#ipro
You won't see `.pagespeed.` urls for these images.

**Comment by i6666800** [comment]
sorry,I did not make it clear，I mean lazyload pictures，like this:
<img class="lazy" src="//a3.****.com/cloud/iiBqoKkiRiiSrirmojin/chanpin1_1-640-640.jpg" data-original="//a3.******.com/cloud/iiBqoKkiRiiSrirmojin/chanpin1_1-640-640.jpg" alt="PACKAGING" title="PACKAGING" data-pagespeed-url-hash="3606610562" onload="pagespeed.CriticalImages.checkImageForCriticality(this);" style="display: block;">
Such pictures do not seem to be optimized

**Comment by oschaaf** [comment]
If `a3.leadongcdn.com` goes back to your webserver/origin to fetch its inputs, you could authorize the domain for optimization:

```
pagespeed Domain a3.leadongcdn.com;
```
