### ISSUE TITLE
Pagespeed + naxsi

### ISSUE THREAD

**Issue by ManuelRighi** [pagespeed/ngx_pagespeed#1454]
Hello,
I'm try to compile nginx 1.12.1 + pagespeed 1.12.34.2-stable and naxsi with branch http2.
I receive this error:

objs/addon/src/ngx_url_async_fetcher.o:/opt/ngx_pagespeed-1.12.34.2-stable/src/ngx_url_async_fetcher.cc:89: first defined here
collect2: error: ld returned 1 exit status
objs/Makefile:382: recipe for target 'objs/nginx' failed
make[2]: *** [objs/nginx] Error 1
make[2]: Leaving directory '/opt/nginx_source/nginx-1.12.1/debian/build-nginx'
Makefile:8: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/opt/nginx_source/nginx-1.12.1/debian/build-nginx'
debian/rules:50: recipe for target 'build-arch.nginx' failed
make: *** [build-arch.nginx] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

If I use branch master on Naxsi, no problem .... is a pagespeed bug ?

Thanks
Manuel

**Comment by oschaaf** [comment]
Hi -- see https://github.com/pagespeed/ngx_pagespeed/issues/1194 for a workaround (reversing the module order if ngx_pagespeed and naxi)

Closing this as a duplicate.
