### ISSUE TITLE
Redis Database

### ISSUE THREAD

**Issue by Promaethius** [pagespeed/ngx_pagespeed#1457]
Redis servers usually come with several databases to keep application data separate from each other. I use database 0 for php sessions, 1 for database objects, and 2 for misc data.

Would it be possible to add a configuration option in the nginx conf to select a specific database?

**Comment by oschaaf** [comment]
Hi, this feature was requested earlier, it is being tracked at https://github.com/pagespeed/mod_pagespeed/issues/1609

You can subscribe to that issue to get updates.

Closing this one as a duplicate so we can track in one place.
