### ISSUE TITLE
Why there is no recompression for jpg?

### ISSUE THREAD

**Issue by kevin25** [pagespeed/ngx_pagespeed#1464]
I tried to find the recompression feature for jpg but no luck. Any alternative way?

**Comment by oschaaf** [comment]
See https://www.modpagespeed.com/doc/reference-image-optimize#recompress_jpeg

Also, adding `?PageSpeedFilters=+debug` to the querystring of a html request will make the module add debug comments after the images, and append the applied configuration in a html comment at the end of the document. That may be helpful in assessing the output.

**Comment by kevin25** [comment]
It's recompress_jpeg, not jpg? Because I compressed jpeg but no luck for jpg.
![screen shot 2017-08-31 at 11 50 24 am](https://user-images.githubusercontent.com/2909982/29932573-a604adc0-8e42-11e7-9686-f30993a2a518.png)

**Comment by jmarantz** [comment]
Just because PSI says it could be compressed further doesn't mean MPS didn't compress it.  You should take a look at the specific images in particular and see whether MPS serves them smaller than they are at origin.
