### ISSUE TITLE
Error with install nginx 1.13.5 + pagespeed the latest version.

### ISSUE THREAD

**Issue by hunterpl** [pagespeed/ngx_pagespeed#1471]
Hello,

Details:
Debian 9 Stretch up to date
Openssl draft18 for TLS 1.3
Additional modules during installation: headers-more-nginx-module, nginx_cookie_flag_module
I would like report the pagespeed can not be compiling with the latest nginx 1.13.5:

```
        /root/ngx_pagespeed-latest-stable/src/ngx_pagespeed.cc
/root/ngx_pagespeed-latest-stable/src/ngx_pagespeed.cc: In function 'char* net_instaweb::{anonymous}::ps_merge_srv_conf(ngx_conf_t*, void*, void*)':
/root/ngx_pagespeed-latest-stable/src/ngx_pagespeed.cc:1165:53: error: 'class net_instaweb::RewriteOptions' has no member named 'standby'
       if (!cfg_s->server_context->global_options()->standby()) {
                                                     ^~~~~~~
objs/Makefile:1391: recipe for target 'objs/addon/src/ngx_pagespeed.o' failed
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: Leaving directory '/root/nginx-1.13.5'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
Error: Failure running 'make', exiting.
```

Someone can fix the automatically installation from pagespeed? Please
" bash <(curl -f -L -sS https://ngxpagespeed.com/install) --nginx-version latest "
The problem still present from installation: " ngx_http_core_try_files_phase " 

`        -o objs/addon/src/ngx_pagespeed.o \
        /root/ngx_pagespeed-latest-stable/src/ngx_pagespeed.cc
/root/ngx_pagespeed-latest-stable/src/ngx_pagespeed.cc: In function 'ngx_int_t net_instaweb::{anonymous}::ps_preaccess_handler(ngx_http_request_t*)':
/root/ngx_pagespeed-latest-stable/src/ngx_pagespeed.cc:3011:31: error: 'ngx_http_core_try_files_phase' was not declared in this scope
   while (ph[i + 1].checker != ngx_http_core_try_files_phase &&
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
objs/Makefile:1391: recipe for target 'objs/addon/src/ngx_pagespeed.o' failed
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: Leaving directory '/root/nginx-1.13.5'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
Error: Failure running 'make', exiting.
`

Best Regards
Mateusz

**Comment by jmarantz** [comment]
Sounds like a mismatch between the version of the psol binary and the version of the nginx gasket (ngx_pagespeed.cc).  I think in this case it is probably an old library with a new gasket

**Comment by hunterpl** [comment]
Hello, i just updated my first post how can i fix this issue?

**Comment by oschaaf** [comment]
@hunterpl see https://github.com/pagespeed/ngx_pagespeed/issues/1455
Closing this as a duplicate
