### ISSUE TITLE
nginx 1.13.5 ‘ngx_http_core_try_files_phase’ was not declared in this scope

### ISSUE THREAD

**Issue by stevenzhu25** [pagespeed/ngx_pagespeed#1472]
Same as #1451 
Just Updated to Nginx 1.13.5 with openssl 1.1.0f

`./configure --prefix=/etc/nginx \
            --sbin-path=/usr/sbin/nginx \
            --modules-path=/usr/lib64/nginx/modules \
            --conf-path=/etc/nginx/nginx.conf \
            --error-log-path=/var/log/nginx/error.log \
            --pid-path=/var/run/nginx.pid \
            --lock-path=/var/run/nginx.lock \
            --user=nginx \
            --group=nginx \
            --build=CentOS \
            --builddir=nginx-1.13.2 \
            --with-select_module \
            --with-poll_module \
            --with-threads \
            --with-file-aio \
            --with-http_ssl_module \
            --with-http_v2_module \
            --with-http_realip_module \
            --with-http_addition_module \
            --with-http_xslt_module=dynamic \
            --with-http_image_filter_module=dynamic \
            --with-http_geoip_module=dynamic \
            --with-http_sub_module \
            --with-http_dav_module \
            --with-http_flv_module \
            --with-http_mp4_module \
            --with-http_gunzip_module \
            --with-http_gzip_static_module \
            --with-http_auth_request_module \
            --with-http_random_index_module \
            --with-http_secure_link_module \
            --with-http_degradation_module \
            --with-http_slice_module \
            --with-http_stub_status_module \
            --http-log-path=/var/log/nginx/access.log \
            --http-client-body-temp-path=/var/cache/nginx/client_temp \
            --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
            --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
            --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
            --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
            --with-mail=dynamic \
            --with-mail_ssl_module \
            --with-stream=dynamic \
            --with-stream_ssl_module \
            --with-stream_realip_module \
            --with-stream_geoip_module=dynamic \
            --with-stream_ssl_preread_module \
            --with-compat \
            --with-pcre=../pcre-8.41 \
            --with-pcre-jit \
            --with-zlib=../zlib-1.2.11 \
            --with-openssl=../openssl-1.1.0f \
            --add-module=~/nginx-ct
            --add-module=$HOME/ngx_pagespeed-${NPS_VERSION} ${PS_NGX_EXTRA_FLAGS}
`

Nginx build follow by https://www.vultr.com/docs/how-to-compile-nginx-from-source-on-centos-7, Add [Nginx-ct](https://github.com/grahamedgecombe/nginx-ct) as well as [ngx_pagespeed ](https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source)

Error Output:
`	/root/ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc
/root/ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc: In function 'ngx_int_t net_instaweb::{anonymous}::ps_preaccess_handler(ngx_http_request_t*)':
/root/ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc:3011:31: error: 'ngx_http_core_try_files_phase' was not declared in this scope
   while (ph[i + 1].checker != ngx_http_core_try_files_phase &&
                               ^
make[1]: *** [nginx-1.13.5/addon/src/ngx_pagespeed.o] Error 1
make[1]: Leaving directory `/root/nginx-1.13.5'
make: *** [build] Error 2
`
Should i use the one mentioned on that issue or wait for a new one?

**Comment by oschaaf** [comment]
@stevenzhu25 the same fix applies

**Comment by stevenzhu25** [comment]
The Same Fix doesn't actually applied.. @oschaaf

**Comment by oschaaf** [comment]
@stevenzhu25  ngx_pagespeed 1.12.34.3-stable was released, which includes the fix needed to address the build error you posted:
https://www.modpagespeed.com/doc/release_notes#release_1.12.34.3-stable

**Comment by stevenzhu25** [comment]
@oschaaf Just Tried. It's working!! Thank you

**Comment by oschaaf** [comment]
@stevenzhu25 great to hear that, thanks for confirming
