### ISSUE TITLE
‘NGX_HTTP_PRECONTENT_PHASE’ was not declared in this scope

### ISSUE THREAD

**Issue by hardik-tatvasoft** [pagespeed/ngx_pagespeed#1473]
Hello,

I am trying to install pagespeed with nginx and i am using this source.

https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source

also i have added this patch : https://patch-diff.githubusercontent.com/raw/pagespeed/ngx_pagespeed/pull/1453.diff

but after path i am getting new error : ‘NGX_HTTP_PRECONTENT_PHASE’ was not declared in this scope

Can you some one please help me.

Also how can i only install pagespeed module instead of affecting my old nginx setups. ?
I have configured using this:./configure --add-module=$HOME/ngx_pagespeed-${NPS_VERSION} ${PS_NGX_EXTRA_FLAGS}

at time of make i am getting issues.

pagespeed = ngx_pagespeed-1.12.34.2-stable
nginx = nginx-1.13.3
old nginx that is working fine : 1.10.2

**Comment by oschaaf** [comment]
Hi, that was my bad. But fortunately @PikachuEXE repaired compilation for older nginx systems with
https://github.com/pagespeed/ngx_pagespeed/pull/1470

**Comment by hardik-tatvasoft** [comment]
It was worked fine,

But after installation i have pagespeed on; this on default.conf on server block and it says below error : 
 [emerg] unknown directive "pagespeed" in /etc/nginx/conf.d/default.conf:24
nginx: configuration file /etc/nginx/nginx.conf test failed

Also I can not see this file : modules/ngx_pagespeed.so

Also i am bit confuse about use same nginx as that worked before. can you please guide me for the same ?

I want to use old nginx.
