### ISSUE TITLE
checking for psol ... not found

### ISSUE THREAD

**Issue by mifen2** [pagespeed/ngx_pagespeed#1478]
configuring additional modules
adding module in /root/ngx_pagespeed-1.12.34.2-beta
mod_pagespeed_dir=/root/ngx_pagespeed-1.12.34.2-beta/psol/include
build_from_source=false
checking for psol ... not found
./configure: error: module ngx_pagespeed requires the pagespeed optimization library.
Look in /tmp/nginx-1.12.1/objs/autoconf.err for more details.

**Comment by oschaaf** [comment]
Could you paste the commands you ran? The guide to building ngx_pagespeed can be found here: https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source

**Comment by discostur** [comment]
@oschaaf running the following script from the page you linked fails:

```
NPS_VERSION=1.12.34.3-stable
cd
wget https://github.com/pagespeed/ngx_pagespeed/archive/v${NPS_VERSION}.zip
unzip v${NPS_VERSION}.zip
cd ngx_pagespeed-${NPS_VERSION}/
NPS_RELEASE_NUMBER=${NPS_VERSION/beta/}
NPS_RELEASE_NUMBER=${NPS_VERSION/stable/}
psol_url=https://dl.google.com/dl/page-speed/psol/${NPS_RELEASE_NUMBER}.tar.gz
[ -e scripts/format_binary_url.sh ] && psol_url=$(scripts/format_binary_url.sh PSOL_BINARY_URL)
wget ${psol_url}
tar -xzvf $(basename ${psol_url})  # extracts to psol/
```

The file doesn't exist on the server:

https://dl.google.com/dl/page-speed/psol/1.12.34.3.tar.gz

**Comment by discostur** [comment]
@oschaaf thanks, all the earlier commands succeeded. I used PSOL 1.12.34.2-x64.tar.gz for NPS_VERSION 1.12.34.3-stable and now it is working as it should ;)

Thanks

**Comment by oschaaf** [comment]
Great, closing

**Comment by herath** [comment]
sudo yum install gcc-c++ pcre-devel zlib-devel make unzip libuuid-devel
