### ISSUE TITLE
Can't compile with nginx 1.3.5

### ISSUE THREAD

**Issue by kevin25** [pagespeed/ngx_pagespeed#1479]
Hello,
Is current pagespeed working with Nginx 1.3.5? I tried to compile with it but failed

`objs/Makefile:1429: recipe for target 'objs/addon/src/ngx_pagespeed.o' failed
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: Leaving directory '/usr/local/src/nginx-1.13.5'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
`

**Comment by oschaaf** [comment]
See https://github.com/pagespeed/ngx_pagespeed/issues/1455

**Comment by oschaaf** [comment]
(assuming you meant nginx 1.13.5 instead of 1.3.5)
Closing this as a duplicate

**Comment by kevin25** [comment]
@oschaaf Yes, it its.
