### ISSUE TITLE
auto install on cent os 6 failed

### ISSUE THREAD

**Issue by noctivityinc** [pagespeed/ngx_pagespeed#1480]
```
/root/ngx_pagespeed-latest-stable/src/ngx_pagespeed.cc: In function ‘ngx_int_t net_instaweb::{anonymous}::ps_preaccess_handler(ngx_http_request_t*)’:
/root/ngx_pagespeed-latest-stable/src/ngx_pagespeed.cc:3011:31: error: ‘ngx_http_core_try_files_phase’ was not declared in this scope
   while (ph[i + 1].checker != ngx_http_core_try_files_phase &&
                               ^
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: Leaving directory `/root/nginx-1.13.5'
```

**Comment by Lofesa** [comment]
Is a know issue with nginx above the 1.13.3. The 1.12.34.2 is not patched. You need to do a manual installation and apply the [patch](https://github.com/pagespeed/ngx_pagespeed/commit/6ba8658cf9c8ea8c7f0c043483927dac905846a1) before compiling

**Comment by knopkakhua** [comment]
use older nginx

**Comment by oschaaf** [comment]
For ngx_pagespeed 1.12.34.2 @knopkakhua his suggestion works.
ngx_pagespeed 1.12.34.3-stable was released last week, which addressed this for all nginx version
