### ISSUE TITLE
CSS minify breaks classes with exclamation mark or dollar sign

### ISSUE THREAD

**Issue by divadsn** [pagespeed/ngx_pagespeed#1491]
I've already seen in previous issues that the CSS optimizations are well-known for breaking CSS when special other special characters are being used. 

But sadly, I noticed on my website (https://www.codebucket.de) that the classes which are responsible for column width are not correctly displaying the page content. As the class names contain dollar signs, I think that these are being ignored when doing the minify.

Here is an example of how the website should look like:
![image](https://user-images.githubusercontent.com/28547847/31791589-583abf8c-b519-11e7-82ed-94392274170f.png)

NGINX version: 1.12.1
ngx_pagespeed version: latest

**Comment by jmarantz** [comment]
I haven't seen $ being used in CSS identifiers.  Are you sure it's legal?  The (verbose) CSS3 description makes it look like it's a delimiter.

https://www.w3.org/TR/css-syntax-3/#consume-a-token0

**Comment by divadsn** [comment]
I don't know, as I am not so much into CSS3, but apparently the theme author did use them 😕 

![image](https://user-images.githubusercontent.com/28547847/31797282-cb1ef504-b52d-11e7-9f26-d63ce0a74620.png)

**Comment by divadsn** [comment]
Any updates on that?

**Comment by jmarantz** [comment]
Did you file a bug with the theme author about using legal CSS syntax?  Closing for now.
