### ISSUE TITLE
Gzip compression isn't working

### ISSUE THREAD

**Issue by Redani** [pagespeed/ngx_pagespeed#1494]
Hello everyone,

I'm using pagespeed 1.11.33.4-0 for nginx, but i don't know why none of the static files are being compressed! here is the config I'm using, am I missing something?

Thanks for your help

pagespeed on;
pagespeed EnableFilters combine_css;
pagespeed EnableFilters combine_javascript;
pagespeed EnableFilters rewrite_css;
pagespeed EnableFilters rewrite_javascript;
pagespeed EnableFilters rewrite_style_attributes_with_url;
pagespeed EnableFilters remove_comments,collapse_whitespace,remove_quotes;
pagespeed DisableFilters rewrite_images;

**Comment by Lofesa** [comment]
Hi @Redani
Have you enabled gzip at server level?
In the http section of nginx config file you mus enable it
[Here](https://www.digitalocean.com/community/tutorials/how-to-add-the-gzip-module-to-nginx-on-ubuntu-14-04) you have a manual fom Digital Ocean, but you can google it for more info

**Comment by Redani** [comment]
Thanks Lofesa for your reply.
Yes I have now enabled the gzip and completely disabled pagespeed cause i realized that i wont be really using it!
I can do the most of what pagespeed do with webpack...

**Comment by Lofesa** [comment]
Well... If you don´t do it, perhaps @oschaaf or someone can close this
