### ISSUE TITLE
Psol 1.13.35.1 don´t exist

### ISSUE THREAD

**Issue by Lofesa** [pagespeed/ngx_pagespeed#1496]
Hi
Version 1.13.35.1 of pagespeed module is announced in the Pagespeed Release Notes but when run wget ${psol_url}  get the 404 error for the file https://dl.google.com/dl/page-speed/psol/1.13.35.1-x64.tar.gz

**Comment by oschaaf** [comment]
Release 1.13.35.1-beta is still in flight. 

Upon completion it will get announced over at:
https://groups.google.com/forum/#!forum/ngx-pagespeed-announce and
https://groups.google.com/forum/#!forum/mod-pagespeed-announce

**Comment by Lofesa** [comment]
Thx @oschaaf   and sorry for try to download so fast. I test Pagespeed Release Notes rather than the forums for new releases

**Comment by oschaaf** [comment]
No worries!

**Comment by oschaaf** [comment]
Fixed :-)
