### ISSUE TITLE
Request to make pagespeed_automatic.a available to download 

### ISSUE THREAD

**Issue by cryptofuture** [pagespeed/ngx_pagespeed#1507]
I suggest make `pagespeed_automatic.a` available to download separately, just the same as we could download binary psol versions now.
Reason: It takes quite long time to build. I maintain [nginx-hda-bundle](https://github.com/cryptofuture/nginx-hda-bundle) along with [PPA](https://launchpad.net/~hda-me/+archive/ubuntu/nginx-stable), and using `yes` or disabling debuging could not be considered as good solution.
I'm pretty sure every person who building nginx package alongside with ngx_pagespeed  module will be not happy to spend extra 30 minutes or an hour on it.
Sure its not the highest priority, but its shouldn't be to hard to make available to download `pagespeed_automatic.a` too.

**Comment by oschaaf** [comment]
Thanks for giving some context on this. 

One question: Would you be happy with an unattended ngx_pagespeed install where you can specify '--with-debug', or do you really need the debug build of pagespeed_automatic.a? (the debug build of pagespeed_automatic.a is significantly slower, and also has debug checks that explicitly are not around in release builds meant for production usage)

**Comment by cryptofuture** [comment]
Its ok just to have silent build with debug, possible just with binary psol archives(at least for me).

**Comment by oschaaf** [comment]
Great, because you *can* download the release build. For the latest beta the URL can be found at https://github.com/pagespeed/ngx_pagespeed/blob/35/PSOL_BINARY_URL.
Subsequently, you can point the build of ngx_pagespeed to the extracted pagespeed_automatic.a binary with an environment var, PSOL_BINARY.
Let me know if that helps!

**Comment by cryptofuture** [comment]
I'm using `1beaa2efb189c91cc7861caaf6a0277a241dfa39` alongside with 1.13.35.1-ia32.tar.gz and 1.13.35.1-x64.tar.gz. And its ask for y, or  `pagespeed_automatic.a`

**Comment by oschaaf** [comment]
I’ll try to do something about that. Could you copy the exact commands you are performing in here?

**Comment by cryptofuture** [comment]
IDK if you familiar with rules files, but it show exactly how I do it
[rules.txt](https://github.com/pagespeed/ngx_pagespeed/files/1503703/rules.txt)

**Comment by oschaaf** [comment]
@cryptofuture I had a look, setting both `PSOL_BINARY` and `PSOL_BUILDTYPE` should work.

For example: the following command doesn't ask any questions:
```
PSOL_BINARY=/home/ubuntu/ngx_pagespeed-1.13.35.1-beta/psol/lib/Release/linux/x64/pagespeed_automatic.a PSOL_BUILDTYPE=Release ./configure --add-module=/home/ubuntu/ngx_pagespeed-latest-stable --with-debug
````

Would this work for you?

**Comment by cryptofuture** [comment]
Yes this is exactly how I doing it now. But could it work with just PSOL_BUILDTYPE=Release, to avoid building `pagespeed_automatic.a` every time?

**Comment by oschaaf** [comment]
@cryptofuture I'm confused -- with the environment variables I mentioned you can point the build to the location where you extracted the release binary for `pagespeed_automatic.a` -- building `pagespeed_automatic.a` shouldn't be needed at all.

Subsequently `./configure` shouldn't be asking any questions.. even if you pass `--debug`. Are you observing something else? Maybe I'm lacking a proper understanding of the problem.

**Comment by cryptofuture** [comment]
> Subsequently ./configure shouldn't be asking any questions.. even if you pass --debug. Are you observing something else? Maybe I'm lacking a proper understanding of the problem.
Yes is ask for `y`, or pagespeed_automatic.a 
> You have set --with-debug for building nginx, but precompiled Debug binaries for
> PSOL, which ngx_pagespeed depends on, aren't available.  If you're trying to
> debug PSOL you need to build it from source.  If you just want to run nginx with
> debug-level logging you can use the Release binaries."
I could continue only with setting both `PSOL_BINARY` and `PSOL_BUILDTYPE`
I will stay with `v1.12.34.3` for this time, which is building without extra hassle.

**Comment by cryptofuture** [comment]
Seems like I had no uuid problem with `1.13.35.1`, but since I had debug, debug message confused me. Beside I had no access to `autoconf.err` so i hacked my build env to chroot inside on fail.
Overall adding `uuid-dev` to `Build-Depends:` helped me in my case
