### ISSUE TITLE
nginx with ngx_pagespeed failed to build

### ISSUE THREAD

**Issue by immunity20** [pagespeed/ngx_pagespeed#1508]
hello I try to build
bash <(curl -f -L -sS https://ngxpagespeed.com/install) --nginx-version latest
but building stucks for a long time at ngx_pagespeed.cc and later I get the error

cc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
objs/Makefile:1293: recipe for target 'objs/addon/src/ngx_pagespeed.o' failed
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 4
make[1]: Leaving directory '/root/nginx-1.13.7'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
Error: Failure running 'make', exiting.

**Comment by oschaaf** [comment]
Perhaps the system is running out of memory during the build. Shutting down any processes that you do not need for the build may help a bit in that case.

**Comment by immunity20** [comment]
Hello thank you very much , indeed it was issue about low memory i stopped many servers and for 500MB+  of RAM complied successfully
