### ISSUE TITLE
checking for psol ... not found (1.13.35.1-x64)

### ISSUE THREAD

**Issue by alsyundawy** [pagespeed/ngx_pagespeed#1511]
Use the available Release binaries? [Y/n] Y
mod_pagespeed_dir=/root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include
build_from_source=false
checking for psol ... not found
./configure: error: module ngx_pagespeed requires the pagespeed optimization library.
Look in /root/nginx/nginx-1.12.2/objs/autoconf.err for more details.

./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-select_module --with-poll_module --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_realip_module  --with-http_xslt_module --with-http_xslt_module=dynamic --with-http_image_filter_module --with-http_image_filter_module=dynamic --with-http_geoip_module --with-http_geoip_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module --with-http_perl_module=dynamic --with-mail --with-mail=dynamic --with-mail_ssl_module --with-stream --with-stream=dynamic --with-stream_ssl_module --with-stream_realip_module --with-stream_geoip_module --with-stream_geoip_module=dynamic --with-stream_ssl_preread_module --with-google_perftools_module --with-compat --with-pcre=/root/nginx/pcre-8.41 --with-pcre-jit --with-zlib=/root/nginx/zlib-1.2.11 --with-libatomic --with-openssl=/root/nginx/openssl-1.1.0g --with-debug --add-module=/root/nginx/ngx_devel_kit --add-module=/root/nginx/ngx_pagespeed-1.13.35.1-beta --add-module=/root/nginx/headers-more-nginx-module --add-module=/root/nginx/ngx_brotli --add-module=/root/nginx/ngx_cache_purge --add-module=/root/nginx/ngx_coolkit --add-module=/root/nginx/naxsi/naxsi_src  --add-module=/root/nginx/ngx_slowfs_cache --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie' ${PS_NGX_EXTRA_FLAGS="--with-cc=/opt/rh/devtoolset-2/root/usr/bin/gcc"}

using psol from https://dl.google.com/dl/page-speed/psol/1.13.35.1-x64.tar.gz 

Centos 6 & Nginx 1.12.2

**Comment by oschaaf** [comment]
"Look in /root/nginx/nginx-1.12.2/objs/autoconf.err for more details."

I wonder, what does that look like?

**Comment by alsyundawy** [comment]
----------------------------------------
checking for getaddrinfo()


----------------------------------------
checking for psol

/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
----------

#include <sys/types.h>
#include <unistd.h>

#include "pagespeed/kernel/base/string.h"
#include "pagespeed/kernel/base/string_writer.h"
#include "pagespeed/kernel/base/null_message_handler.h"
#include "pagespeed/kernel/html/html_parse.h"
#include "pagespeed/kernel/html/html_writer_filter.h"


int main() {


  GoogleString output_buffer;
  net_instaweb::StringWriter write_to_string(&output_buffer);

  net_instaweb::NullMessageHandler handler;
  net_instaweb::HtmlParse html_parse(&handler);
  net_instaweb::HtmlWriterFilter html_writer_filter(&html_parse);

  html_writer_filter.set_writer(&write_to_string);
  html_parse.AddFilter(&html_writer_filter);

  html_parse.StartParse("http:example.com");
  html_parse.ParseText(
      "<html ><body ><h1 >Test</h1 ><p>Test Text</p></body></html>\n");
  html_parse.FinishParse();

  printf("parsed as: %s", output_buffer.c_str());
    return 0;
}

----------
/opt/rh/devtoolset-2/root/usr/bin/gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 --std=c++11 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/chromium/src -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/google-sparsehash/src/src -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/grpc/src/include -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/protobuf/src/src -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/re2/src -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/out/Release/obj/gen -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/out/Release/obj/gen/protoc_out/instaweb -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/apr/src/include -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/aprutil/src/include -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/apr/gen/arch/linux/x64/include -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/include/url -o objs/autotest objs/autotest.cc -Wl,-z,relro -Wl,-z,now -pie /root/nginx/ngx_pagespeed-1.13.35.1-beta/psol/lib/Release/linux/x64/pagespeed_automatic.a -lstdc++ -lrt -pthread -lm -luuid

**Comment by oschaaf** [comment]
`/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -luuid`

So libuuid is missing. I thought we made changes to automatically install that when that happens.
Are you running the latest version of build_ngx_pagespeed.sh? (The one at https://ngxpagespeed.com/install)?

**Comment by alsyundawy** [comment]
ok thx, fixed with yum install -y libuuid-devel

**Comment by cryptofuture** [comment]
Seems like I have just the same problem with `1.13.35.1`, but since I had debug, debug message confused me. Beside I had no access to `autoconf.err` so i hacked my build env to chroot inside on fail.
Overall adding `uuid-dev` to `Build-Depends:` helped me in my case
