### ISSUE TITLE
No difference after enabling page speed

### ISSUE THREAD

**Issue by horaceleung** [pagespeed/ngx_pagespeed#1513]
I have installed the latest version of pagespeed for NGINX and have the following filters enabled in the conf file, however I do not really see much difference in the PageSpeed Insights score at all. Especially with the filters enabled I was expecting it to resolve the "Prioritise critical CSS/ above fold" issues etc.

I have curl'ed the site and can see the page speed header served (X-Page-Speed: 1.12.34.3-0) but not much visible increase of site performance.

Website URL:  https://goo.gl/L9JPWm

pagespeed on;
pagespeed FileCachePath /var/ngx_pagespeed_cache;
location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
  add_header "" "";
}
location ~ "^/pagespeed_static/" { }
location ~ "^/ngx_pagespeed_beacon$" { }
pagespeed EnableFilters prioritize_critical_css;
pagespeed EnableFilters combine_css,extend_cache,rewrite_images;
pagespeed EnableFilters rewrite_css,rewrite_javascript;

**Comment by oschaaf** [comment]
You may have to run a few More tests with insights for it to receive the fully optimized version from ngx_pagespeed. Also, when trying this: you need to wait about 30 seconds between tests for it to refetch the test target and re-analyse.
