### ISSUE TITLE
Keep resource leading slash when  html rewriting

### ISSUE THREAD

**Issue by kongzhenhao** [pagespeed/ngx_pagespeed#1517]
I found that when a pge url with no prefix path the leading slash of resource path were removed. It made me a bit of trouble. I opened an url A(htts://domain/prefixpath/a.action)，in this page it requested another url B(https://domain/b.action) by ajax, returned a html, and started to load resources(<script src="/js/c.js" .../>).  After html rewriting of B, the path of js turned into a relative path(js/c.js), then the js url turned into https://domain/prefixpath/js/c.js, but what i need is https://domain/js/c.js. How can i keep the leading slash of resoure path when html rewritting?

**Comment by jmarantz** [comment]
What version are you using?  I actually thought this was fixed a long time ago: https://github.com/pagespeed/mod_pagespeed/issues/503

What version of ngx_pagespeed are you using?

**Comment by kongzhenhao** [comment]
version v1.12.34.2-stable

**Comment by jmarantz** [comment]
You don't have 'trim_urls' enabled, do you?

**Comment by kongzhenhao** [comment]
I tried to make it disabled, and it works. Thank you very much~
