### ISSUE TITLE
combine css  404

### ISSUE THREAD

**Issue by chaihongjun** [pagespeed/ngx_pagespeed#1519]
when i use the filter combine css ,then the combinded css file cant be founded!(404)
https://css.example.com/m/common.css+site.css.pagespeed.cc.TIHnC1ljjl.css
and my original files:
https://css.example.com/m/common.css
https://css.example.com/m/site.css

**Comment by Lofesa** [comment]
Have you configured locatacion for the *.pagespeed.* elements?

**Comment by chaihongjun** [comment]
@Lofesa   I'm sorry, I don't understand what you mean.

**Comment by Lofesa** [comment]
In your config files, have you some thing like this:?

`#` Needs to exist and be writable by nginx.  Use tmpfs for best performance.
pagespeed FileCachePath /var/ngx_pagespeed_cache;

`#` Ensure requests for pagespeed optimized resources go to the pagespeed handler
`#` and no extraneous headers get set.
**location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
  add_header "" "";
}**
location ~ "^/pagespeed_static/" { }
location ~ "^/ngx_pagespeed_beacon$" { }

**Comment by chaihongjun** [comment]
@Lofesa  of course,I did.

`
...
location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {add_header "" "";}
location ~ "^/ngx_pagespeed_static/" {allow 127.0.0.1; deny all;}
location /ngx_pagespeed_message {allow 127.0.0.1; deny all;}
location ~ "^/ngx_pagespeed_beacon$" { }
location /pagespeed_console { }
location ~ ^/pagespeed_admin { }
`

**Comment by Lofesa** [comment]
Have you a load balancer or proxy?

**Comment by chaihongjun** [comment]
@Lofesa  It's incredible. It's all right , When i  reload nginx ,but
I have a new problem again
,why so many webp imgs were  disappeared?

**Comment by chaihongjun** [comment]
@Lofesa  I don't have those things，just a  server running CentOS

**Comment by Lofesa** [comment]
Hi @chaihongjun 
Pagespeed need some "shots" to make the work. Some page reload must be done until resources becomes optimized. They are stored in the pagespeed cache until they need a "refresh", the optimized resources are "live" in the pagespeed cache the time you gave set in their ttl.
Try to use ?PageSpeedFilters=+debug as param in your url and see in the html code the debug messages that are inserted.

**Comment by chaihongjun** [comment]
@Lofesa  So I should set ttl for these webp files?And How can I set ? In my nginx.conf ?
like this:
```
  location ~ .*\.(webp|gif|jpg|jpeg|png|bmp|swf|flv|mp4|ico|html)$ {
    expires 360d;
    access_log off;
    log_not_found off;
  }
```
am i right?

**Comment by chaihongjun** [comment]
@Lofesa  I got this:

**Comment by chaihongjun** [comment]
`

`

**Comment by chaihongjun** [comment]
@Lofesa  i got these comments:
`deadline_exceeded for filter ImageRewrite
deadline_exceeded for filter CacheExtender
`

**Comment by Lofesa** [comment]
Hi @chaihongjun 
Do you have webp files? or you have jpg files that are converted in to webp?
But yes, if you have webp files or jpg files that ae converted to webp by pagespeed you need to set the expires directive but not soo long. Pagespeed set the ttl for optimized resources at 1 year so the original resource don´t need that.... say 1 week, for example.
The deadline message say that pagespeed don´t optimize the resource in the 10s (the default) time to do that, but do the work in background, the next "shot" they become optimized.
