### ISSUE TITLE
module ngx_pagespeed requires the pagespeed optimization library

### ISSUE THREAD

**Issue by gm100861** [pagespeed/ngx_pagespeed#327]
[root@centos100 nginx-1.4.0]# uname -a
Linux centos100 2.6.18-238.el5xen #1 SMP Thu Jan 13 16:41:45 EST 2011 x86_64 x86_64 x86_64 GNU/Linux
[root@centos100 nginx-1.4.0]# cat /etc/issue
CentOS release 5.6 (Final)
Kernel \r on an \m

configuring additional modules
adding module in /root/ngx_pagespeed-release-1.5.27.2-beta/
mod_pagespeed_dir=/root/ngx_pagespeed-release-1.5.27.2-beta//psol/include
build_from_source=false
checking for psol ... not found
./configure: error: module ngx_pagespeed requires the pagespeed optimization library

view objs/autoconf.err：

/root/ngx_pagespeed-release-1.5.27.2-beta//psol/lib/Release/linux/x64/pagespeed_automatic.a(35.html_name.gp.o.o):html_name.gp.cc:(.text._ZNK12net_instaweb8HtmlName8Iterator4nameEv+0xa6): more undefined references to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)' follow
/root/ngx_pagespeed-release-1.5.27.2-beta//psol/lib/Release/linux/x64/pagespeed_automatic.a(1.logging.o.o): In function`std::basic_string<char, std::char_traits<char>, std::allocator<char> >\* logging::MakeCheckOpString<unsigned long, unsigned int>(unsigned long const&, unsigned int const&, char const_)':
/root/ngx_pagespeed-release-1.5.27.2-beta//psol/lib/Release/linux/x64/pagespeed_automatic.a(1.logging.o.o): In function `std::basic_string<char, std::char_traits<char>, std::allocator<char> >_ logging::MakeCheckOpString<int, int>(int const&, int const&, char const_)':
logging.cc:(.text._ZN7logging17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc[std::basic_string<char, std::char_traits<char>, std::allocator<char> >_ logging::MakeCheckOpString<int, int>(int const&, int const&, char const_)]+0x5b): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const_, long)'
logging.cc:(.text._ZN7logging17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc[std::basic_string<char, std::char_traits<char>, std::allocator<char> >\* logging::MakeCheckOpString<int, int>(int const&, int const&, char const_)]+0x6f): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const_, long)'

what can i do ？

**Comment by ozra** [comment]
I've made a download-sources-and-compile script that works flawlessly in Ubuntu 15 (my local machine), but not on my Debian 8 VPS - where I get above error. I've tried countless different compile approaches from the net, but they all fail the same way on the VPS. Differences in bash handling of line breaks or something?

**Comment by jeffkaufman** [comment]
Can you paste your script?

**Comment by ozra** [comment]
Hope I got it right after all the changes back and forth:

```bash
sudo apt-get install build-essential zlib1g-dev libpcre3 libpcre3-dev unzip
cd ~
mkdir -p tmp
cd ~/tmp

# check http://nginx.org/en/download.html for the latest version
NGX_VERSION=1.9.32.10
wget https://github.com/pagespeed/ngx_pagespeed/archive/release-${NGX_VERSION}-beta.zip
unzip release-${NGX_VERSION}-beta.zip
cd ngx_pagespeed-release-${NGX_VERSION}-beta/
wget https://dl.google.com/dl/page-speed/psol/${NGX_VERSION}.tar.gz
tar -xzvf ${NGX_VERSION}.tar.gz

cd ~/tmp
NGINX_VERSION=1.9.5
wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
tar -xvzf nginx-${NGINX_VERSION}.tar.gz
cd nginx-${NGINX_VERSION}/

./configure \
  --prefix=/usr/local/share/nginx --conf-path=/etc/nginx/nginx.conf \
  --sbin-path=/usr/local/sbin --error-log-path=/var/log/nginx/error.log \
  --with-http_v2_module --with-http_ssl_module --with-http_realip_module \
  --with-http_addition_module --with-http_sub_module --with-http_dav_module \
  --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module \
  --with-http_gzip_static_module --with-http_random_index_module \
  --with-http_secure_link_module --with-http_stub_status_module \
  --with-file-aio --with-ipv6 \
  --with-cc-opt='-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -march=native -mtune=native -D_GLIBCXX_USE_CXX11_ABI=0' \
  --add-module=../ngx_pagespeed-release-${NGX_VERSION}-beta

make
sudo make install
```

**Comment by ozra** [comment]
It's a cut n paste from different sources and changed bit by bit till working kind-of-stew. I think the snips are small enough to not be a license problem. This is free to use in any way as long as I'm not held responsible, and all that kahuna.

**Comment by jeffkaufman** [comment]
Can you add to the top:

    set -e

This will make the script stop if any of the individual commands fails, which should let us see where the problem is.  I suspect something is going wrong earlier in the process, and then things later don't see what they expect.

**Comment by ozra** [comment]
Eh, did you see my edit in the comment above? The ABI flag solved the problem...

**Comment by jeffkaufman** [comment]
> Debian 8 has GCC 5.2.1-22 - passing -D_GLIBCXX_USE_CXX11_ABI=0 with ./configure solves it!

Makes sense, thanks for reporting what works!

@morlovich is currently working on getting us working with C++11.

**Comment by ozra** [comment]
I wasted so many hours on this server, so I'm happy to save some one else the trouble. Not the favourite debugging to do ;-)
