### ISSUE TITLE
NgxBaseFetch::RequestCollection: Broken pipe error in logs with 1.5.27.3 and earlier

### ISSUE THREAD

**Issue by Tombar** [pagespeed/ngx_pagespeed#390]
Hello 

I've just deployed pagespeed 1.5.27.2 from a custom package I've build and while checking logs I saw this entries I don't completely understand.

2013/05/28 17:41:55 [error] 2957#0: *1663512 open() "/tmp/ngx_pagespeed_static/1.Hy2LQaukh5.gif" failed (2: No such file or directory), client: 141.0.11.25, server: minisitios-pagespeed, request: "GET /ngx_pagespeed_static/1.Hy2LQaukh5.gif HTTP/1.1", host: "www.site.com", referrer: "http://www.site.com/bla-ble-bli/"
2013/05/28 17:42:08 [error] 2960#0: *1664038 open() "/tmp/ngx_pagespeed_static/js_defer.vOMXhhVn4A.js" failed (2: No such file or directory), client: 66.87.130.250, server: minisitios-pagespeed, request: "GET /ngx_pagespeed_static/js_defer.vOMXhhVn4A.js HTTP/1.1", host: "www.site.com", referrer: "http://www.site.com/123/a/b/c/"
2013/05/28 17:42:31 [error] 2978#0: *1664921 open() "/tmp/ngx_pagespeed_static/js_defer.vOMXhhVn4A.js" failed (2: No such file or directory), client: 187.140.86.70, server: minisitios-pagespeed, request: "GET /ngx_pagespeed_static/js_defer.vOMXhhVn4A.js HTTP/1.1", host: "www.imanualidades.com", referrer: "http://www.site.com/01/21/a-b-c-d/"
2013/05/28 17:42:32 [error] 2960#0: *1664920 open() "/tmp/ngx_pagespeed_static/1.Hy2LQaukh5.gif" failed (2: No such file or directory), client: 187.140.86.70, server: minisitios-pagespeed, request: "GET /ngx_pagespeed_static/1.Hy2LQaukh5.gif HTTP/1.1", host: "www.site.com", referrer: "http://www.site.com/01/21/a-b-c-d/"

- Why is pagespeed using /tmp folder if my FileCachePath is /var/nginx-pagespeed-cache?

-  /tmp/ permissions are 777 and nginx is running as root

[root@nx1]:/home/tombar # ls /tmp/ -l
drwxrwxrwx 2 root root  4096 May 28 16:13 ngx_pagespeed_static

Regards and thanks for your hard work! 

M

**Comment by oschaaf** [comment]
Closing this, as with https://github.com/pagespeed/ngx_pagespeed/pull/876 there are no more per-request named pipes in use, which should make it impossible for this specific error message to occur.
