### ISSUE TITLE
Lazyload preloads images with display:none, contrary to JQuery's Lazyload

### ISSUE THREAD

**Issue by veitnachtmann** [pagespeed/ngx_pagespeed#395]
we have a lot of content that is never displayed on the site because the entire block has css: display:none.

with jquery lazyload (http://www.appelsiini.net/projects/lazyload) this works perfectly, I have about HALF the requests that ngx_pagespeed produces, since most pictures aren't shown anyways.

any way to fix this?

**Comment by samaraiza** [comment]
@jlporter You just saved my life (or at least a few days of it) with that skip_invisible setting that I didn't know existed. ARGH. Thanks!
