### ISSUE TITLE
support resizing transparent pngs 

### ISSUE THREAD

**Issue by NogaevPN** [pagespeed/ngx_pagespeed#403]
Hello, I'm using ngx_pagespeed in Debian 6 Stable, but resize images filter working only with *.jpg images, all .png images is not resized by ngx_pagespeed.

**Comment by jeffkaufman** [comment]
OpenCV is now gone, so I'd think we'd be able to do this now.  @huibaolin can we resize transparent pngs yet?  Or does this still need more work?

**Comment by argollo** [comment]
Howdy! Just checking in to see if there has been any progress on this or whether there's an alternative to using resize_images with .png files. Thanks!

**Comment by huibaolin** [comment]
We've added support for resizing transparent images, for both GIF and PNG formats in 1.11. This includes both beta and stable versions. Please give it a try.

Now the only type of image which we don't resize is animated GIF.

**Comment by argollo** [comment]
Thank you!
