### ISSUE TITLE
Uncaught ReferenceError: mod_pagespeed_I15t4UCyVJ is not defined

### ISSUE THREAD

**Issue by patschi** [pagespeed/ngx_pagespeed#476]
Sometimes I get this following error on my page:

<pre>Uncaught ReferenceError: mod_pagespeed_I15t4UCyVJ is not defined</pre>

(This about 10 times in the Google Chrome console)

After some refresh the error is gone and everything is working fine - Don't know why.

**Comment by pySilver** [comment]
@jeffkaufman any idea how to overcome similar issue at https://github.com/apache/incubator-pagespeed-mod/issues/634 ? the only solution im thinking of right now is a little bit ugly and requires another proxy layer.

**Comment by jeffkaufman** [comment]
@pySilver Sorry, I don't work on pagespeed anymore.  @oschaaf might be a better person to ask?
