### ISSUE TITLE
Segment fault bug

### ISSUE THREAD

**Issue by yaoweibin** [pagespeed/ngx_pagespeed#48]
I encountered segfault with the ab tests ( ab -n 10000 -c 10 http://127.0.0.1:1980/test/www/test.html). This is the backtrace:
#0 0x00000000004fad45 in net_instaweb::RewriteDriver::DeleteRewriteContext(net_instaweb::RewriteContext*) ()

(gdb) bt
#0 0x00000000004fad45 in net_instaweb::RewriteDriver::DeleteRewriteContext(net_instaweb::RewriteContext*) ()
#1 0x0000000000582ea2 in net_instaweb::Function::CallRun() ()
#2 0x0000000000592e8c in net_instaweb::QueuedWorkerPool::Run(net_instaweb::QueuedWorkerPool::Sequence_, net_instaweb::QueuedWorker_) ()
#3 0x0000000000582ea2 in net_instaweb::Function::CallRun() ()
#4 0x00000000005a6d86 in net_instaweb::Worker::WorkThread::Run() ()
#5 0x00000000005b2ec8 in net_instaweb::PthreadThreadImpl::InvokeRun(void*) ()
#6 0x00000036f6e0677d in start_thread () from /lib64/libpthread.so.0
#7 0x00000036f66d49ad in clone () from /lib64/libc.so.6

**Comment by songshaodong** [comment]
I also met the issue, is program code cause ?

**Comment by oschaaf** [comment]
@songshaodong Could you post a backtrace?

**Comment by songshaodong** [comment]
@oschaaf   Thanks, My problem has been resolved, memory overflow cause.

backtrace:

#0 0x00000032a960cd2b in pthread_once () from /lib64/libpthread.so.0
#1 0x00000032a8efe954 in backtrace () from /lib64/libc.so.6
#2 0x00000032a8e7054b in __libc_message () from /lib64/libc.so.6
#3 0x00000032a8e75e66 in malloc_printerr () from /lib64/libc.so.6
#4 0x00000032a8e79904 in _int_malloc () from /lib64/libc.so.6
#5 0x00000032a8e7a346 in calloc () from /lib64/libc.so.6
#6 0x00000032a8a0addf in _dl_new_object () from /lib64/ld-linux-x86-64.so.2
#7 0x00000032a8a071de in _dl_map_object_from_fd () from /lib64/ld-linux-x86-64.so.2
#8 0x00000032a8a0839a in _dl_map_object () from /lib64/ld-linux-x86-64.so.2
#9 0x00000032a8a12b05 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#10 0x00000032a8a0e266 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#11 0x00000032a8a125aa in _dl_open () from /lib64/ld-linux-x86-64.so.2
#12 0x00000032a8f26b20 in do_dlopen () from /lib64/libc.so.6
#13 0x00000032a8a0e266 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#14 0x00000032a8f26c77 in __libc_dlopen_mode () from /lib64/libc.so.6
#15 0x00000032a8efe825 in init () from /lib64/libc.so.6
#16 0x00000032a960cd33 in pthread_once () from /lib64/libpthread.so.0
#17 0x00000032a8efe954 in backtrace () from /lib64/libc.so.6
#18 0x00000032a8e7054b in __libc_message () from /lib64/libc.so.6
#19 0x00000032a8e75e66 in malloc_printerr () from /lib64/libc.so.6
#20 0x00000032a8e79904 in _int_malloc () from /lib64/libc.so.6
#21 0x00000032a8e7a6b1 in malloc () from /lib64/libc.so.6
#22 0x0000000000434ddc in ngx_alloc ()
#23 0x000000000040ac49 in ngx_palloc_large ()
#24 0x000000000040aa3f in ngx_palloc ()
#25 0x000000000040ae88 in ngx_pcalloc ()
#26 0x00000000004e68f3 in ngx_rtmp_init_session ()
#27 0x00000000004e6640 in ngx_rtmp_init_connection ()
#28 0x0000000000430ee3 in ngx_event_accept ()
#29 0x000000000043d86d in ngx_epoll_process_events ()
#30 0x000000000042d2f8 in ngx_process_events_and_timers ()
#31 0x000000000043b3ca in ngx_worker_process_cycle ()
#32 0x0000000000437c66 in ngx_spawn_process ()
#33 0x000000000043a232 in ngx_start_worker_processes ()
#34 0x0000000000439dd5 in ngx_master_process_cycle ()
#35 0x0000000000407b96 in main ()
