### ISSUE TITLE
RespectXForwardedProto not working.  Disables url rewriting.

### ISSUE THREAD

**Issue by freejack** [pagespeed/ngx_pagespeed#542]
Requests from external clients are serviced via https port 443 by our loadbalancer and then forwarded to http port 80 of the web servers.  I added the following to the server block:

pagespeed RespectXForwardedProto On;
pagespeed Domain www.domain1.com;
pagespeed Domain asdfasdfasdf.cloudfront.net;
pagespeed MapRewriteDomain asdfasdfasdf.cloudfront.net www.domain1.com;

When I disable RespectXForwardedProto, I can see pagespeed rewriting the urls to static resources although they're using http.  I need pagespeed to rewrite using https.  This is supposedly what RespectXForwardedProto should be doing but when I enable it there is no rewriting of the urls at all.  I confirmed that our loadbalancer is forwarding the source protocol via X-Forwarded-Proto.

Closed.  Was not aware that I had to config https.  Once I did that everything was fine.

**Comment by IanLewis** [comment]
I'm having a similar issue. What do you mean by "config https"?

**Comment by jmarantz** [comment]
See https://developers.google.com/speed/pagespeed/module/https_support

**Comment by IanLewis** [comment]
Yah. I read that. I enabled RespectXForwardedProto and pagespeed stopped all rewriting.

**Comment by jeffkaufman** [comment]
Does `pagespeed Domain https://YOURSITE` fix it?
