### ISSUE TITLE
Install mod_pagespeed under nginx on gentoo

### ISSUE THREAD

**Issue by nemessiss** [pagespeed/ngx_pagespeed#580]
I want to install mod_pagespeen under gentoo using emerge.
i added NGINX_ADD_MODULES="/root/ngx_pagespeed-1.7.30.1-beta" in make.conf.

When i try to compile nginx via emerge (emerge -D nginx) i receive the following message:
adding module in /root/ngx_pagespeed-1.7.30.1-beta
./configure: error: no /root/ngx_pagespeed-1.7.30.1-beta/config was found
- ERROR: www-servers/nginx-1.4.4::gentoo failed (configure phase):
-   configure failed
  *
- Call stack:
-     ebuild.sh, line  93:  Called src_configure
-   environment, line 3640:  Called die
- The specific snippet of code:
-       ./configure --prefix="${EPREFIX}"/usr --conf-path="${EPREFIX}"/etc/${PN}/${PN}.conf --error-log-path="${EPREFIX}"/var/log/${PN}/error_log --pid-path="${EPREFIX}"/run/${PN}.pid --lock-path="${EPREFIX}"/run/lock/${PN}.lock --with-cc-opt="-I${EROOT}usr/include" --with-ld-opt="-L${EROOT}usr/lib" --http-log-path="${EPREFIX}"/var/log/${PN}/access_log --http-client-body-temp-path="${EPREFIX}/${NGINX_HOME_TMP}"/client --http-proxy-temp-path="${EPREFIX}/${NGINX_HOME_TMP}"/proxy --http-fastcgi-temp-path="${EPREFIX}/${NGINX_HOME_TMP}"/fastcgi --http-scgi-temp-path="${EPREFIX}/${NGINX_HOME_TMP}"/scgi --http-uwsgi-temp-path="${EPREFIX}/${NGINX_HOME_TMP}"/uwsgi ${myconf} || die "configure failed";

the folder /root/ngx_pagespeed-1.7.30.1-beta/ exists on my compter:

dev ~ # ls -alh /root/ngx_pagespeed-1.7.30.1-beta/
total 89M
drwxr-xr-x  6 root   root 4.0K Dec 18 22:07 .
drwx------ 14 root   root 4.0K Dec 18 22:44 ..
-rw-r--r--  1 root   root   30 Nov  8 18:36 .gitignore
-rw-r--r--  1 root   root  89M Nov  7 21:00 1.7.30.1.tar.gz
-rw-r--r--  1 root   root  12K Nov  8 18:36 LICENSE
-rw-r--r--  1 root   root 4.8K Nov  8 18:36 README.md
-rw-r--r--  1 root   root 8.0K Nov  8 18:36 config
-rw-r--r--  1 root   root 2.9K Nov  8 18:36 cpp_feature
drwxr-x---  4 182960 5000 4.0K Nov  7 15:59 psol
drwxr-xr-x  2 root   root 4.0K Nov  8 18:36 scripts
drwxr-xr-x  2 root   root 4.0K Nov  8 18:36 src
drwxr-xr-x  2 root   root 4.0K Nov  8 18:36 test

As you can see the file (/root/ngx_pagespeed-1.7.30.1-beta/config) is there but i still receive the error message. 

Can you please help me?

**Comment by systocrat** [comment]
@nemessiss PLEASE don't set 777 on any modules that get compiled into software that gets run by root.
This will allow anyone to modify it, which means that the next time Nginx gets compiled, it could have malicious code by ANYONE who has a shell on the system.
