### ISSUE TITLE
Conditional Filters

### ISSUE THREAD

**Issue by nikolay** [pagespeed/ngx_pagespeed#627]
Any idea how to enable/disable a filter based on some condition, for example, user agent?

**Comment by oschaaf** [comment]
Closing this, feel free to re-open if needed!

**Comment by vladimir000** [comment]
Hello, Can we reopen?

It doesn't reject the options but it is doing nothing.

I tried disabling all filters in an if inside a location, and all the pagespeed filters i had enabled in the server block are still enabled.

**Comment by oschaaf** [comment]
@vladimir000 could you post the nginx version, ngx_pagespeed version, plus a configuration that shows the problem?

**Comment by ciarans** [comment]
Having the same problem

Im using https://github.com/openresty/lua-nginx-module and have rebuilt nginx with PageSpeed. 

in my nginx.conf file I set the following variable

```nginx
  set $gps_collapse_whitespace 0
```
In my access_by_lua_file I call Redis and set an appropriate value list so:

```lua
ngx.var.gps_collapse_whitespace = 1;
```

ngx_pagespeed seem to ignore this and does not recognise that the bariable has been updated;

```nginx
if ($gps_collapse_whitespace = 1) {
     pagespeed EnableFilters collapse_whitespace;
}
```

If I set  

```nginx
  set $gps_collapse_whitespace 1
```
 and do not call the lua script it works without any problems.

I am using dynamic if statements like this all over the place that are setting correctly i.e. a pre-rendering service

**Comment by oschaaf** [comment]
@ciarans Could it be a module ordering problem? Could you run nginx configured `--with-debug` with `error_log` set to `debug` in configuration, and subsequently run a single request that exhibits the problem? If you post or PM the resulting log lines, I can take a look.
