### ISSUE TITLE
404s on Some Rewritten Assets

### ISSUE THREAD

**Issue by nikolay** [pagespeed/ngx_pagespeed#673]
I have some assets that PageSpeed rewrites with `.pagespeed.ce.HASH` in them, which result in 404s. Any idea what those could be? What does the `.ce.` designate? The assets rewritten with just `.pagespeed.HASH` work fine.

**Comment by intelbg** [comment]
Hello, I can confirm this issue and until now I see that pagespeed LoadFromFile  works as a workaround. Is there any permanent solution so I should not config this for every domain and user?

**Comment by jmarantz** [comment]
Generally, LoadFromFile should be an optimization and not a workaround.  If this is broken in your environment, you need to understand why PageSpeed's http or https fetching is not working for you.

One thing I saw in another thread is that ngx_pagespeed has an option to use the nginx native fetcher, but that does not work for HTTPS.  If you are using native fetching, please turn it off.  See https://www.modpagespeed.com/doc/system#native-fetcher for details.  When you turn that off, ngx_pagespeed, will use Serf, the same fetcher that is used in mod_pagespeed, which has https support.  You may also need to configure https support.

See https://www.modpagespeed.com/doc/https_support for details about https fetching.
