### ISSUE TITLE
Duplicate Location headers

### ISSUE THREAD

**Issue by akamatgi** [pagespeed/ngx_pagespeed#725]
This issue was introduced in 1.8.31.2
With nginx running as a reverse proxy, if the upstream server responds with a 301 response, an extra Location header is added to the response.
This causes the browser (Chrome) to display an 'Duplicate Headers received from Server' error page.

**Comment by olemartinorg** [comment]
I had this exact problem in 1.10.33.2, and found this issue. Seems that part of #744 is gone from master now? I tested in 1.9.32.11 and that worked fine.

**Comment by crowell** [comment]
yep, looks like that commit didn't make it into the 1.10.33.x branch. i've reapplied it to master and trunk-tracking so it should be fixed in the next release.
@olemartinorg if you build from master now it should be fixed.

**Comment by WesCossick** [comment]
From my testing, the duplicate location header problem occurred in `1.10.33.4` but works in `1.10.33.5`.

**Comment by oschaaf** [comment]
@WesCossick Correct, see the release notes at https://developers.google.com/speed/pagespeed/module/release_notes#release_1.10.33.5-beta
