### ISSUE TITLE
Images below fold still loading after LazyloadImagesAfterOnload off

### ISSUE THREAD

**Issue by neptunian** [pagespeed/ngx_pagespeed#754]
Hi I just recompiled my nginx to 1.6.0 with the pagespeed module NPS_VERSION=1.8.31.4.  It's my first time using the module.

I tried to implement lazy loading images on scroll but it doesn't seem to be working.
Here is what I added to my conf:

pagespeed on;
pagespeed EnableFilters lazyload_images;
pagespeed LazyloadImagesAfterOnload off;

I want to lazy load and I do NOT want them all to forcefully load at the onload event. However this is still happening. Restarted my server many times and once the onload event occurs all images start downloading. I only want them to start when the user scrolls. Also the docs say an 'onscroll' event is attached to the page but a search for that event in the page doesn't turn up anything.

Here is a link to my site: http://sandygonzales.com/photography/test.html

**Comment by superdoret** [comment]
I have the same issue, but the problem is when I change my site to HTTPS.

Any ideas?

**Comment by oschaaf** [comment]
@superdoret Could you share your url, and give a some more detail about what happened before and after you switched to https?
When you switch to https, reading https://developers.google.com/speed/pagespeed/module/https_support might be helpful if you have not already done so.

**Comment by oschaaf** [comment]
@superdoret also - this issue is old and closed. Could you open a new issue if you think there's a bug, or post any questions you have to https://groups.google.com/forum/#!forum/ngx-pagespeed-discuss?
