### ISSUE TITLE
Log: [info] No threading detected. Own threads: 1 Rewrite, 1 Expensive Rewrite.

### ISSUE THREAD

**Issue by oschaaf** [pagespeed/ngx_pagespeed#808]
Not a real problem, but the message isn't very helpful -- or actually seems to raise concerns. 
Perhaps  the message can be degraded to debug instead of info level.

**Comment by jeffkaufman** [comment]
Looks like this is back.

**Comment by jeffkaufman** [comment]
@oschaaf would you be able to look at this one?  I'd like to put a fix for this in 1.10.33.2.

**Comment by oschaaf** [comment]
@jeffkaufman The following pull fixes the problem thoroughly, but introduces a smaller one where we log vague lines like
```
flush
.
```
https://github.com/pagespeed/ngx_pagespeed/pull/1071

**Comment by jeffkaufman** [comment]
Fixed in https://github.com/pagespeed/ngx_pagespeed/commit/37e1c3618a54da075b79acdb8074cb5f1599f537

**Comment by mysexyDate24com** [comment]
Hello everybody, i am getting this again:

No threading detected. Own threads: 1 Rewrite, 1 Expensive Rewrite.
2017/06/20 17:44:02 [info] 3378#3378: pagespeed: rollback gzip, explicit configuration in /etc/nginx/common.conf:37
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

Server: nginx 1.13.1 with pagespeed and brotli
Domain: https://mysexydate24.com/en-DE
OS: archlinux, latest
OpenSSL 1.1.0f  25 May 2017

**Comment by oschaaf** [comment]
@mysexyDate24com testing the latest stable ngx_pagespeed release on ubuntu 14.04, I can't confirm a regression of this issue. 

What version of ngx_pagespeed are you running? Does it help if you set the log level to warn?

```
oschaaf@ubuntu:/usr/local/nginx/sbin⟫ sudo  ./nginx -V
nginx version: nginx/1.13.1
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
configure arguments: --add-module=/home/oschaaf/ngx_pagespeed-latest-stable

oschaaf@ubuntu:/usr/local/nginx/sbin⟫ sudo  ./nginx -t
nginx: the configuration file /usr/local/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /usr/local/nginx/conf/nginx.conf test is successful
```

tail of error.log shows the messages do end up there (with the log level set info):

```
2017/06/21 13:12:41 [info] 55579#0: [ngx_pagespeed 1.12.34.2-0] No threading detected. Own threads: 1 Rewrite, 1 Expensive Rewrite.
2017/06/21 13:12:41 [info] 55579#0: pagespeed: rollback gzip, explicit configuration in /usr/local/nginx/conf/nginx.conf:36
2017/06/21 13:12:41 [info] 55579#0: [ngx_pagespeed 1.12.34.2-0] SharedMemCache: pagespeed_default_shm/metadata_cache, sectors = 128, entries/sector = 2226,  64-byte blocks/sector = 4452, total footprint: 52445184
2017/06/21 13:12:41 [info] 55579#0: [ngx_pagespeed 1.12.34.2-0] Initializing shared memory for path: /tmp/npsinstalled/ flush .
```

**Comment by mysexyDate24com** [comment]
ngx_pagespeed-1.12.34.2-beta

**Comment by oschaaf** [comment]
@mysexyDate24com you have `--error-log-path=stderr`, which is what triggers it.

**Comment by mysexyDate24com** [comment]
Great, that fixed it. Thank you very much!

**Comment by dungvaph03374** [comment]
nginx version: nginx/1.10.3
pagespeed version: ngx-1.13.35.1-beta

> built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
> built with OpenSSL 1.0.2g  1 Mar 2016
> TLS SNI support enabled
> configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/sbin/nginx --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-stream --with-stream_ssl_module --with-mail --with-mail_ssl_module --with-threads --add-module=/root/incubator-pagespeed-ngx-1.13.35.1-beta
