### ISSUE TITLE
IPRO interferes with sendfile 

### ISSUE THREAD

**Issue by oschaaf** [pagespeed/ngx_pagespeed#826]
It looks like IPRO interferes with sendfile.
Reported via https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/gCHeQ5BZFHQ

**Comment by jeffkaufman** [comment]
For now people should `Disallow` any resources that set  X-Sendfile.  We're planning to automate this too: https://github.com/pagespeed/ngx_pagespeed/issues/981

**Comment by crowell** [comment]
closed by 4bef2af22c95bede9794879971d5f9bfeeb337da
