### ISSUE TITLE
how to use nginx pagespeed console

### ISSUE THREAD

**Issue by xinghua** [pagespeed/ngx_pagespeed#831]
hello,

```
 I follow the document and my nginx.conf is 

server {

       listen 9402;
       server_name  test.com;

       pagespeed on;
       pagespeed Statistics on;
       pagespeed StatisticsLogging on;
       pagespeed LogDir /home/test/log/pagespeed;

         location / {};
          location /ngx_pagespeed_statistics { allow all; }
          location /ngx_pagespeed_message { allow all; }
          location /pagespeed_console { allow all;}
```

  }

but curl -s -v "http://test.com/pagespeed_console",  I get 404
It is easy to understand, nginx will find file "pagespeed_console" in root dir, but  i can not find any file named pagespee_console in nginx root dir.
So i wonder how to use pagespeed_console,  any erro in my nginx conf ?

**Comment by adrelanos** [comment]
I had to add `root /;` in the location block. This worked for me:

```
location ~ ^/pagespeed_admin {
    root /;
    auth_basic           "Administrator’s Area";
    auth_basic_user_file /etc/apache2/.htpasswd;
}
```

https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

    sudo htpasswd -c /etc/apache2/.htpasswd user1
