### ISSUE TITLE
ngx_pagespeed overrides Server header

### ISSUE THREAD

**Issue by akuryan** [pagespeed/ngx_pagespeed#864]
My nginx -V output:
nginx version: nginx/1.6.2
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-mail --with-mail_ssl_module --with-http_spdy_module --add-module=/tmp/tmp1ra9oc/rpmbuild//BUILD/nginx-1.6.2/headers-more-nginx-module-0.25 --add-module=/tmp/tmp1ra9oc/rpmbuild//BUILD/nginx-1.6.2/ngx_pagespeed-1.8.31.4-beta --with-file-aio --with-ipv6 --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'

If pagespeed is turned on, it sets Server header to 'nginx' for all dynamic resources.
It does not matter if I am trying to modify this header by means of changing nginx sources or by header-more module, as suggested in accepted answer here:
http://stackoverflow.com/questions/246227/how-do-you-change-the-server-header-returned-by-nginx

Is it possible to modify Server header to custom one with pagespeed turned on?

**Comment by akuryan** [comment]
@oschaaf Just wanted to inform you that this patch made it's way through and finally are playing on our production

**Comment by oschaaf** [comment]
@akuryan That is nice to hear, thanks!

**Comment by akuryan** [comment]
@oschaaf  
Hi
After long run, we found that, though normally Server header is kept intact, still, for some reasons, on some files it is still being dropped in favor of old value ('nginx')
Looks like, if file is being compressed by pagespeed - it is still drops our custom header from HttpHeadersMore

For example (HttpHeadersMore set to modify Server header):
/js/hcsliders/lib/jquery.jcarousel.min.js.pagespeed.ce._veNtSjbOF.js
Server:nginx

/js/hcsliders/skins/tango/skin.css.pagespeed.ce.fenyJITqUy.css
Server:nginx

/published/publicdata/JINANDREY/attachments/SC/images/hotimg/headbg.jpg
Server:CustomHeader

/webAsystSmsSender.php?act=get_phone_field
Server:CustomHeader

Hope this information will help you

**Comment by oschaaf** [comment]
@akuryan To get this to work for`.pagespeed.` resources and IPRO cache hits, ngx_pagespeed should be configured to run at a different position in the module chain.

`trunk-tracking` has a change that fixes a problem that arises when doing so, and also adds a flag to allow building nginx with ngx_pagespeed repositioned to run in front of the header module(s), see https://github.com/pagespeed/ngx_pagespeed/commit/a8141eadd3e22a66fcbc5dacecf97b9669c3a5ef

**Comment by jeffkaufman** [comment]
This should be fixed in the next release, right @oschaaf ?

**Comment by oschaaf** [comment]
@jeffkaufman yes
