### ISSUE TITLE
Though nginx + page speed are installed, I still have 2.4 s server speed?

### ISSUE THREAD

**Issue by mouazzz** [pagespeed/ngx_pagespeed#866]
Dear All,

I installed nginx as reverse proxy to apache and pagespeed on apache, and yet, I am seeing the same (Reduce server response time) error on Google page speed insight test. All installations are done correctly and completely, however, yet, I did not see any major improvement on speed.

What bothers me most is that one website shows a 2.4 second server response time, and another site (on the same server) shows a 1 second server response time, though both of them are wordpress and deployed on the same server.

What do you think I should do next? I am really hopeless now.

Thanks

-------------
[Update#1 - 27Dec2014]
I started analyzing plugins usage, deleting some plugins and doing some workarounds. I realized that basically optimizing the theme and plugins will enhance server response time. My initial thoughts were that there is something on the server itself that blocks certain pages and that the server itself requires optimization. If anyone thinks so, I appreciate some feedback.

After testing some native wordpress sites, with the default theme and no plugins, speed sky rocketed and such server response error has never been shown. So it turns out that the theme and plugins play major and critical role in how my server responds. 

anyway, thought to update everyone who read this ticket. If anyone has any suggestions, that would be much appreciated. Thanks.

**Comment by jeffkaufman** [comment]
In general, the pagespeed server plugin won't do anything to reduce server response time.  It can make changes to speed up overall loading time, but server response time is usually due to the configuration of your wordpress site.  Asking for help on a wordpress forum would probably be more likely to find someone who could help you with this.
