### ISSUE TITLE
Removing \n when collapsing whitespace

### ISSUE THREAD

**Issue by NodexTech** [pagespeed/ngx_pagespeed#868]
Is there a solid reason why \n is not removed at the END of closing html tags inside the collapse_whitespace module?

**Comment by jeffkaufman** [comment]
I don't completely remember, but I think it's because `</foo> </bar>` and `</foo></bar>` don't necessarily mean the same thing in html and we don't have a good automated way to tell when the whitespace is significant there.

(As for whether to use space or newline, they're both one character and newlines are probably more readable.)

**Comment by NodexTech** [comment]
I've been running various replace methods for years on whitespace which removes the \n - on literally thousands of websites and have not once had a problem. I just thought it was odd that it was not part of ngx_pagepseed

**Comment by jeffkaufman** [comment]
Here's a simple test showing the problem:

```
$ cat a.html
one
<i>example</i>
file
$ cat b.html
one<i>example</i>file
```

These display as "[one *example* file](http://www.jefftk.com/whitespace-test/a)" and "[one*example*file](http://www.jefftk.com/whitespace-test/b)".

**Comment by NodexTech** [comment]
I see the point but any designer or developer that relies on \n as a space deserves to have unexpected results. A bit harsh I know but a space is a space and a "\n" or a "\r" is not.

I am not sure how the module works internally but would some kind of expression such as a match on  </([a-z])>([a-z]) (to not strip) or </([a-z])>\s+([a-z]) to strip? work.

**Comment by jeffkaufman** [comment]
> any designer or developer that relies on ... deserves to have unexpected results

Unfortunately if you have this kind of approach while developing an automated optimizer (or web browser) you end up breaking a very large fraction of pages.  Most cases are worse than this one; this behavior has been consistently specified by all the html specs over the years and there are reasonable cases where someone might use it.  Imagine:

```
Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Fusce molestie ante <b>vitae</b>
iaculis varius. ...
```

It's completely reasonable for the author to expect this to render as "ante **vitae** iaculis" and not "ante **vitae**iaculis".

> would some kind of expression such as a match on ... work?

I'm not clear on what your regex is trying to do.

**Comment by NodexTech** [comment]
I'll write a better regex, my apologies!

**Comment by jeffkaufman** [comment]
Closing this bug: it doesn't sound like theres something practical PageSpeed can be doing better here.
