### ISSUE TITLE
Default value for pagespeed MaxCombinedCssBytes

### ISSUE THREAD

**Issue by episage** [pagespeed/ngx_pagespeed#877]
Default value for pagespeed MaxCombinedCssBytes MaxBytes; is not -1 as manual at https://developers.google.com/speed/pagespeed/module/filter-css-combine states.

I had configure it to -1 for PSM to combine CSS.
It said that "Contents is too big" before.

**Comment by episage** [comment]
PSM 1.9.32.3
nginx 1.6.2-5

**Comment by jeffkaufman** [comment]
It looks to me like the default really is `-1`:

```
rewrite_options.cc:
  const int64 RewriteOptions::kDefaultMaxCombinedCssBytes = -1;  // No size limit  
  ...
  AddBaseProperty(
      kDefaultMaxCombinedCssBytes,
      &RewriteOptions::max_combined_css_bytes_, "xcc",
      kMaxCombinedCssBytes,
      kQueryScope,
      "Maximum size allowed for the combined CSS resource.", true);
```

The "combined contents too big" error should only be triggered if `MaxCombinedCssBytes >= 0`, so it's weird that you would get it with a default-configured server.

Testing myself on [jefftk.com/css-combine-test](http://www.jefftk.com/css-combine-test/index?PageSpeedFilters=debug,combine_css) I see it successfully creating a 400kB css file, and I don't get the "combined contents too big" error.

Are you sure you hadn't previously set `MaxCombinedCssBytes` to something else?  If you remove the line where you set `MaxCombinedCssBytes` to -1 and load your page with `?PageSpeedFilters=+debug` you should see something at the bottom listing what options you've turned on:

```<!--
mod_pagespeed on
Filters:
cc	Combine Css
db	Debug
hw	Flushes html

Options:
AnalyticsID (ig) UA-27645543-1
AvoidRenamingIntrospectiveJavascript (aris) True
EnableRewriting (e) 1
FileCacheInodeLimit (afcl) 500000
RewriteLevel (l) Pass Through
Statistics (ase) True
StatisticsLogging (asle) True

#NumFlushes            0
#EndDocument after     434us
#Total Parse duration  358us
#Total Render duration 1962us
#Total Idle duration   76us
The following filters were disabled for this request:
	SupportNoscript
-->```

Does that list `MaxCombinedCssBytes`?

**Comment by episage** [comment]
Hi

I removed the line ```pagespeed MaxCombinedCssBytes -1; ```. ```MaxCombinedCssBytes``` does not show up at the end of the page. 

It was 2 weeks ago and I spotted the message in ```pagespeed_admin/message_history``` . I recompiled PSM with the latest version from trunk, changed the page source code in meantime and I can't reproduce it now.
