### ISSUE TITLE
PSM should set Content-Type: application/javascript on optimized JS

### ISSUE THREAD

**Issue by episage** [pagespeed/ngx_pagespeed#878]
On rewritten JS resources PSM sets 
Content-Type: application/x-javascript;

It should set application/javascript according to http://stackoverflow.com/questions/9664282/difference-between-application-x-javascript-and-text-javascript-content-types .

**Comment by jeffkaufman** [comment]
My memory from the last time this came up was that not all browsers accepted `application/javascript` and we needed to send the `x-` for compatibility. But I'm not remembering which, and they're probably four more years out of date now than when we last looked at it.

**Comment by morlovich** [comment]
Looking at the source code, we preserve known Javascript mimetypes of
the input (and use application/javascript when the original mimetype
is weird); it seems like
application/x-javascript is what nginx and Apache both appears to default to.

FWIW, the table in content_type.cc has a warning that text/javascript
has problems with some firewall gziping.
