### ISSUE TITLE
[system_server_context.cc] worker process 21273 exited on signal 11 (core dumped) 

### ISSUE THREAD

**Issue by episage** [pagespeed/ngx_pagespeed#887]
Hi

PSM ngx_pagespeed-release-1.9.32.3-beta throws segmentation fault at 

```
#0  0x000000000065616e in net_instaweb::SystemServerContext::CheckLegacyGlobalCacheFlushFile (this=0x14cb710) at net/instaweb/system/system_server_context.cc:160
160     net/instaweb/system/system_server_context.cc: No such file or directory.
(gdb) backtrace full
#0  0x000000000065616e in net_instaweb::SystemServerContext::CheckLegacyGlobalCacheFlushFile (this=0x14cb710) at net/instaweb/system/system_server_context.cc:160
        timestamp_ms = 140735252119120
        now_sec = 1422231326
        check_cache_file = false
        cache_flush_poll_interval_sec = 5
```

GDB backtrace full, nginx.conf, site config and PSM config:  https://www.dropbox.com/s/i96v0fuv5fmgbwn/psm_segfault.zip?dl=0

Can provide more detailed info if necessary

PSI:
![image](https://cloud.githubusercontent.com/assets/2196095/5894104/c2950a06-a4f3-11e4-9ed0-55d7437a8935.png)

It seems that the segfault occurs more frequently when the site is accessed via redirect from www.santelab.pl to santelab.pl

dmesg:
```
[814749.275277] nginx[21273]: segfault at 0 ip 000000000065616e sp 00007fff7ab5bbb0 error 4 in nginx[400000+d59000]
```

```
root@install:~/cl# nginx -V
nginx version: nginx/1.6.2
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt=-Wl,-z,relro --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_spdy_module --with-http_sub_module --with-http_xslt_module --with-mail --with-mail_ssl_module --add-module=/root/cl/nginx-1.6.2/debian/modules/nginx-auth-pam --add-module=/root/cl/nginx-1.6.2/debian/modules/nginx-dav-ext-module --add-module=/root/cl/nginx-1.6.2/debian/modules/nginx-echo --add-module=/root/cl/nginx-1.6.2/debian/modules/nginx-upstream-fair --add-module=/root/cl/nginx-1.6.2/debian/modules/ngx_http_substitutions_filter_module --add-module=/root/cl/ngx_pagespeed-release-1.9.32.3-beta
```

```
root@install:~/cl# ls -la /var/cache/psm/
total 36
drwxr-xr-x   5 www-data www-data  4096 Jan 26 00:43 .
drwxr-xr-x  10 root     root      4096 Jan 17 18:17 ..
-rw-------   1 www-data www-data    14 Jan 24 06:55 cache.purge
-rw-------   1 www-data www-data    13 Jan 26 00:43 !clean!time!
drwxrwxrwx   4 www-data www-data  4096 Jan 17 18:17 prop_page
drwxrwxrwx 238 www-data www-data 12288 Jan 24 21:03 rname
drwxrwxrwx   4 www-data www-data  4096 Jan 17 18:17 santelab.pl
```

**Comment by episage** [comment]
It happens from time to time. I think it occurs more frequently when site is accessed via redirect from www.santelab.pl to santelab.pl.

**Comment by oschaaf** [comment]
@jeffkaufman Looking at https://code.google.com/p/modpagespeed/source/browse/trunk/src/pagespeed/system/system_server_context.cc#114, it seems that there's a possibility for `cache_flush_timestamp_ms_ ` to be NULL/uninitialized when https://code.google.com/p/modpagespeed/source/browse/trunk/src/pagespeed/system/system_server_context.cc#160 is hit?

**Comment by oschaaf** [comment]
@episage 

I think you might be able to work around this by configuring this:
```
pagespeed EnableCachePurge on;
```

This would make cache purging work according to the new system, you can read about that here:
https://developers.google.com/speed/pagespeed/module/system#flush_cache

**Comment by morlovich** [comment]
void SystemServerContext::UpdateCachePurgeSet( looks suspect in that
it updates cache_flush_count_ but not cache_flush_timestamp_ms_
(Note that GetVariable should never return NULL)

**Comment by jeffkaufman** [comment]
Yes.  It looks like what happens is: in `CheckLegacyGlobalCacheFlushFile()` if `cache_flush_count_` is non-NULL then we don't initialize `cache_flush_timestamp_ms_`, which is a problem when we use it below.  The code seems to expect `cache_flush_count_` and `cache_flush_timestamp_ms_` to always be initialized together but, as @morlovich says, in `UpdateCachePurgeSet` we only load the flush count.

I think we just need:

```
       }
       if (cache_flush_count_ == NULL) {
         cache_flush_count_ = statistics()->GetVariable(kCacheFlushCount);
+      }
+      if (cache_flush_timestamp_ms_ == NULL) {
         cache_flush_timestamp_ms_ = statistics()->GetUpDownCounter(
             kCacheFlushTimestampMs);
       }
```

I'll fix it.

**Comment by jeffkaufman** [comment]
Fixed with [r4524](https://code.google.com/p/modpagespeed/source/detail?r=4524).
