### ISSUE TITLE
ngx_pagespeed.cc(1811)] Check failed: url.IsWebValid().

### ISSUE THREAD

**Issue by jdoss** [pagespeed/ngx_pagespeed#888]
I have nginx-1.6.2 + mod_security + ngx_pagespeed-release-1.9.32.3-beta which is causing Nginx child processes to die when ModSecurity and ngx_pagespeed are enabled together. If I turn off ModSecurity then ngx_pagespeed does not crash nginx. 

Here is the error log showing the crash, nginx -V and the gdb backtrace full on one of the core dumps:

https://gist.githubusercontent.com/jdoss/6161e4405f3ed42d53dd/raw/8fa2ddccb61077cd7a1b7b63cd38157512a3de87/nginx_pagespeed_modsec.txt

Here is my pagespeed settings in nginx.

```
pagespeed off;

pagespeed FileCachePath /var/ngx_pagespeed_cache;

pagespeed StatisticsPath /ngx_pagespeed_statistics;
pagespeed MessagesPath /ngx_pagespeed_message;
pagespeed ConsolePath /pagespeed_console;
pagespeed AdminPath /pagespeed_admin;

location /ngx_pagespeed_statistics { allow 127.0.0.1; deny all; }
location /ngx_pagespeed_message { allow 127.0.0.1; deny all; }
location /pagespeed_console { allow 127.0.0.1; deny all; }
location ~ ^/pagespeed_admin { allow 127.0.0.1; deny all; }

# Ensure requests for pagespeed optimized resources go to the pagespeed handler
# and no extraneous headers get set.
location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
  add_header "" "";
}
location ~ "^/pagespeed_static/" { }
location ~ "^/ngx_pagespeed_beacon$" { }
```

**Comment by oschaaf** [comment]
@jdoss thanks for the report, looking into it

**Comment by crowell** [comment]
@jdoss #892 and https://code.google.com/p/modpagespeed/source/detail?r=4533 combined should fix this issue. thanks!
