### ISSUE TITLE
C compiler cc is not found

### ISSUE THREAD

**Issue by bodigiti** [pagespeed/ngx_pagespeed#894]
Hi,

Installing on Ubuntu 14.04 LTS
Using these instructions:
https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source

Section "Download and build nginx with support for pagespeed"
PROBLEM occurs when attempting to execute the instruction 3 lines from the section's bottom
>./configure --add-module=$HOME/ngx_pagespeed-release-${NPS_VERSION}-beta

Following error occurs:
>./configure: error: C compiler cc is not found

**Comment by crowell** [comment]
it sounds like you are missing the `build-essential` package

to install the dependencies on ubuntu, run.

```sh
sudo apt-get install build-essential zlib1g-dev libpcre3 libpcre3-dev unzip
```

**Comment by bodigiti** [comment]
Hi, yes I do have build essentials installed.  Thank you for your reply.

**Comment by jeffkaufman** [comment]
What does `which cc` give you?  What about `cc --version`?

**Comment by bodigiti** [comment]
which cc = /usr/bin/cc
cc --version = cc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
FYI -- I attempted this install on two different servers, both Ubuntu 14.04
LTS.

On Mon, Feb 2, 2015 at 10:53 AM, Jeff Kaufman <notifications@github.com>
wrote:

> What does which cc give you? What about cc --version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/894#issuecomment-72480346>
> .
>



-- 
Nils 'Erik' Hendrick
Bodigiti - Web Design & Development
Office (904) 256-9226
Mobile (904) 710-1478
Skype: nerikh
Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
<http://bodigiti.com/website-services>

**Comment by jeffkaufman** [comment]
Does `nginx` build if you don't include the pagespeed module?  Running `./configure` without the `--add-module=$HOME/ngx_pagespeed-release-${NPS_VERSION}-beta`?

**Comment by bodigiti** [comment]
Running *./configure* ...not sure how to "run" it.  But when I attempt to
enter the following
>cd nginx-${NGINX_VERSION}/./configure
I receive an error:
*>nginx-1.6.2/./configure: Not a directory*


On Mon, Feb 2, 2015 at 12:46 PM, Jeff Kaufman <notifications@github.com>
wrote:

> Does nginx build if you don't include the pagespeed module? Running
> ./configure without the
> --add-module=$HOME/ngx_pagespeed-release-${NPS_VERSION}-beta?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/894#issuecomment-72501893>
> .
>



-- 
Nils 'Erik' Hendrick
Bodigiti - Web Design & Development
Office (904) 256-9226
Mobile (904) 710-1478
Skype: nerikh
Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
<http://bodigiti.com/website-services>

**Comment by crowell** [comment]
@bodigiti run
```sh
cd nginx-${NGINX_VERSION}
./configure
make
```

**Comment by bodigiti** [comment]
Yes, that works.  I was also able to complete install with [make install]

On Mon, Feb 2, 2015 at 1:04 PM, Jeffrey Crowell <notifications@github.com>
wrote:

> @bodigiti <https://github.com/bodigiti> run
>
> cd nginx-${NGINX_VERSION}
> ./configure
> make
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/894#issuecomment-72505160>
> .
>



-- 
Nils 'Erik' Hendrick
Bodigiti - Web Design & Development
Office (904) 256-9226
Mobile (904) 710-1478
Skype: nerikh
Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
<http://bodigiti.com/website-services>

**Comment by jeffkaufman** [comment]
Great!  If you now start over with https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source
 does that work?

**Comment by bodigiti** [comment]
*When I enter:*
cd
NGINX_VERSION=1.6.2
wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
tar -xvzf nginx-${NGINX_VERSION}.tar.gz
cd nginx-${NGINX_VERSION}/
./configure --add-module=$HOME/ngx_pagespeed-release-${NPS_VERSION}-beta
make

*It now gives me this:*
adding module in /root/ngx_pagespeed-release-1.9.32.3-beta
ngx_pagespeed: pagespeed optimization library not found:

   You need to separately download the pagespeed library:

     $ cd /path/to/ngx_pagespeed
     $ wget https://dl.google.com/dl/page-speed/psol/1.9.32.3.tar.gz
     $ tar -xzvf 1.9.32.3.tar.gz # expands to psol/

   Or see the installation instructions:
     https://github.com/pagespeed/ngx_pagespeed#how-to-build




On Mon, Feb 2, 2015 at 1:17 PM, Jeff Kaufman <notifications@github.com>
wrote:

> Great! If you now start over with
> https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source
> does that work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/894#issuecomment-72507940>
> .
>



-- 
Nils 'Erik' Hendrick
Bodigiti - Web Design & Development
Office (904) 256-9226
Mobile (904) 710-1478
Skype: nerikh
Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
<http://bodigiti.com/website-services>

**Comment by jeffkaufman** [comment]
That's good; that's progress.  It looks like maybe you forgot to run this part of the instructions?

```
cd ~/ngx_pagespeed-release-${NPS_VERSION}-beta/
wget https://dl.google.com/dl/page-speed/psol/${NPS_VERSION}.tar.gz
tar -xzvf ${NPS_VERSION}.tar.gz  # extracts to psol/
```

**Comment by bodigiti** [comment]
Ah, I did not realize I had to start from the top of the instructions, yet
again.  I have now run through all steps and no errors.  However, when I
attempt to run [service nginx start] it does not run, I receive a message
indicating *nginx: unrecognized service*


On Mon, Feb 2, 2015 at 1:37 PM, Jeff Kaufman <notifications@github.com>
wrote:

> That's good; that's progress. It looks like maybe you forgot to run this
> part of the instructions?
>
> cd ~/ngx_pagespeed-release-${NPS_VERSION}-beta/
> wget https://dl.google.com/dl/page-speed/psol/${NPS_VERSION}.tar.gz
> tar -xzvf ${NPS_VERSION}.tar.gz  # extracts to psol/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/894#issuecomment-72511554>
> .
>



-- 
Nils 'Erik' Hendrick
Bodigiti - Web Design & Development
Office (904) 256-9226
Mobile (904) 710-1478
Skype: nerikh
Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
<http://bodigiti.com/website-services>

**Comment by jeffkaufman** [comment]
Does nginx start if you run `sudo /usr/local/nginx/sbin/nginx` (or whatever path `make` said it was installing to)?

When you install nginx from source it doesn't set itself up with init scripts, so `service nginx start/stop` won't work.  Here's a guide on setting that up: http://www.rackspace.com/knowledge_center/article/ubuntu-and-debian-adding-an-nginx-init-script

**Comment by bodigiti** [comment]
I went through the Rackspace instructions, and Nginx is running now, but I
can not:
1) Identify status with [service nginx status]
2) Can not run any of these commands, so am confused how I started it
/etc/init.d/nginx start
/etc/init.d/nginx stop
/etc/init.d/nginx restart


On Mon, Feb 2, 2015 at 2:03 PM, Jeff Kaufman <notifications@github.com>
wrote:

> Does nginx start if you run sudo /usr/local/nginx/sbin/nginx (or whatever
> path make said it was installing to)?
>
> When you install nginx from source it doesn't set itself up with init
> scripts, so service nginx start/stop won't work. Here's a guide on
> setting that up:
> http://www.rackspace.com/knowledge_center/article/ubuntu-and-debian-adding-an-nginx-init-script
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/894#issuecomment-72516169>
> .
>



-- 
Nils 'Erik' Hendrick
Bodigiti - Web Design & Development
Office (904) 256-9226
Mobile (904) 710-1478
Skype: nerikh
Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
<http://bodigiti.com/website-services>

**Comment by bodigiti** [comment]
I rebooted the system, and stopped NGINX, now can not get it to start again
using /etc/init.d/nginx stop

On Mon, Feb 2, 2015 at 2:17 PM, Erik Hendrick <erik@bodigiti.com> wrote:

> I went through the Rackspace instructions, and Nginx is running now, but I
> can not:
> 1) Identify status with [service nginx status]
> 2) Can not run any of these commands, so am confused how I started it
> /etc/init.d/nginx start
> /etc/init.d/nginx stop
> /etc/init.d/nginx restart
>
>
> On Mon, Feb 2, 2015 at 2:03 PM, Jeff Kaufman <notifications@github.com>
> wrote:
>
>> Does nginx start if you run sudo /usr/local/nginx/sbin/nginx (or
>> whatever path make said it was installing to)?
>>
>> When you install nginx from source it doesn't set itself up with init
>> scripts, so service nginx start/stop won't work. Here's a guide on
>> setting that up:
>> http://www.rackspace.com/knowledge_center/article/ubuntu-and-debian-adding-an-nginx-init-script
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pagespeed/ngx_pagespeed/issues/894#issuecomment-72516169>
>> .
>>
>
>
>
> --
> Nils 'Erik' Hendrick
> Bodigiti - Web Design & Development
> Office (904) 256-9226
> Mobile (904) 710-1478
> Skype: nerikh
> Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
> <http://bodigiti.com/website-services>
>



-- 
Nils 'Erik' Hendrick
Bodigiti - Web Design & Development
Office (904) 256-9226
Mobile (904) 710-1478
Skype: nerikh
Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
<http://bodigiti.com/website-services>

**Comment by bodigiti** [comment]
Nginx starts with /usr/local/nginx/sbin/nginx

On Mon, Feb 2, 2015 at 2:39 PM, Erik Hendrick <erik@bodigiti.com> wrote:

> I rebooted the system, and stopped NGINX, now can not get it to start
> again using /etc/init.d/nginx stop
>
> On Mon, Feb 2, 2015 at 2:17 PM, Erik Hendrick <erik@bodigiti.com> wrote:
>
>> I went through the Rackspace instructions, and Nginx is running now, but
>> I can not:
>> 1) Identify status with [service nginx status]
>> 2) Can not run any of these commands, so am confused how I started it
>> /etc/init.d/nginx start
>> /etc/init.d/nginx stop
>> /etc/init.d/nginx restart
>>
>>
>> On Mon, Feb 2, 2015 at 2:03 PM, Jeff Kaufman <notifications@github.com>
>> wrote:
>>
>>> Does nginx start if you run sudo /usr/local/nginx/sbin/nginx (or
>>> whatever path make said it was installing to)?
>>>
>>> When you install nginx from source it doesn't set itself up with init
>>> scripts, so service nginx start/stop won't work. Here's a guide on
>>> setting that up:
>>> http://www.rackspace.com/knowledge_center/article/ubuntu-and-debian-adding-an-nginx-init-script
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/pagespeed/ngx_pagespeed/issues/894#issuecomment-72516169>
>>> .
>>>
>>
>>
>>
>> --
>> Nils 'Erik' Hendrick
>> Bodigiti - Web Design & Development
>> Office (904) 256-9226
>> Mobile (904) 710-1478
>> Skype: nerikh
>> Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
>> <http://bodigiti.com/website-services>
>>
>
>
>
> --
> Nils 'Erik' Hendrick
> Bodigiti - Web Design & Development
> Office (904) 256-9226
> Mobile (904) 710-1478
> Skype: nerikh
> Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
> <http://bodigiti.com/website-services>
>



-- 
Nils 'Erik' Hendrick
Bodigiti - Web Design & Development
Office (904) 256-9226
Mobile (904) 710-1478
Skype: nerikh
Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
<http://bodigiti.com/website-services>

**Comment by jeffkaufman** [comment]
What errors did `/etc/init.d/nginx start/stop/restart` give you?

**Comment by bodigiti** [comment]
No messages whatsoever, for any of them.

On Mon, Feb 2, 2015 at 3:07 PM, Jeff Kaufman <notifications@github.com>
wrote:

> What errors did /etc/init.d/nginx start/stop/restart give you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/894#issuecomment-72527668>
> .
>



-- 
Nils 'Erik' Hendrick
Bodigiti - Web Design & Development
Office (904) 256-9226
Mobile (904) 710-1478
Skype: nerikh
Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
<http://bodigiti.com/website-services>

**Comment by jeffkaufman** [comment]
Do they print `Starting nginx` or not even that?

**Comment by bodigiti** [comment]
No, the do absolutely nothing.

On Mon, Feb 2, 2015 at 3:22 PM, Jeff Kaufman <notifications@github.com>
wrote:

> Do they print Starting nginx or not even that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/894#issuecomment-72530178>
> .
>



-- 
Nils 'Erik' Hendrick
Bodigiti - Web Design & Development
Office (904) 256-9226
Mobile (904) 710-1478
Skype: nerikh
Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
<http://bodigiti.com/website-services>

**Comment by jeffkaufman** [comment]
Hmm.  Probably the `test -x` on line 18 is failing because `/usr/local/sbin/nginx` doens't exist, which makes sense since you installed into `/usr/local/nginx`.  What if you change `/usr/local/sbin/nginx` to `/usr/local/nginx/sbin/nginx` in `/etc/init.d/nginx`?

**Comment by bodigiti** [comment]
Yes, thank you, now it works.  I can start/stop/restart using the direct
path and also using [service nginx start/stop/restart]

On Mon, Feb 2, 2015 at 3:44 PM, Jeff Kaufman <notifications@github.com>
wrote:

> Hmm. Probably the test -x on line 18 is failing because
> /usr/local/sbin/nginx doens't exist, which makes sense since you
> installed into /usr/local/nginx. What if you change /usr/local/sbin/nginx
> to /usr/local/nginx/sbin/nginx in /etc/init.d/nginx?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/894#issuecomment-72533888>
> .
>



-- 
Nils 'Erik' Hendrick
Bodigiti - Web Design & Development
Office (904) 256-9226
Mobile (904) 710-1478
Skype: nerikh
Bodigiti.com <http://bodigiti.com/> | 6 Critical Areas to Website Success
<http://bodigiti.com/website-services>

**Comment by jeffkaufman** [comment]
Glad it's working, and sorry it took us so long to get there!
