### ISSUE TITLE
Unexpected "images Cache".

### ISSUE THREAD

**Issue by wongjdong** [pagespeed/ngx_pagespeed#896]
I  just want to deal with the file of 'css' or 'js'.
beacause,if turning ngx_pagespeed on, my Nginx is over~ “Over load”
There is too much images to deal with.
I had test that, turning on it only 10mins, there is over 8G cache ...

AND then I test in my local environment.I found that...
First, there is only three sentences in my config ,:

```
pagespeed on;
pagespeed FileCachePath /var/ngx_pagespeed_cache;
pagespeed RewriteLevel PassThrough;
```
And.
when I access a url which is a pic, there would be the pic's cache in `/var/ngx_pagespeed_cahce/....`
I have not open any Filter. why there is a file created????
So my Nginx is OVER LOAD,when I turning it on.
I think, how can i solve it? or?????

**Comment by wongjdong** [comment]
SO does css & js .
I have not open any Filter. And there is a file created .

I vim the css file ....
what is this.... 
h?^@^@^@^H?^A^X^A ^A(?Ȅ?^D0????^D8^A@^AJ^X
^LContent-Type^R^Htext/cssJ%
^DDate^R^]Wed, 14 Jan 1970 06:35:17 GMTJ(
^GExpires^R^]Wed, 14 Jan 1970 06:40:17 GMTJ^\
^MCache-Control^R^Kmax-age=300J^Z

**Comment by oschaaf** [comment]
@wongjdong If you want to start out configuration with no optimizations at all, you would also need to add `pagespeed InPlaceResourceOptimization off` in configuration. In Place Resource Optimization uses the cache and is the reason why you are seeing files being created. 
I'd recommend reading up on https://developers.google.com/speed/pagespeed/module/system, as you can also throttle the amount of concurrent image optimizations in the background via `ImageMaxRewritesAtOnce` if you need that.

**Comment by wongjdong** [comment]
@oschaaf THX~ There is no any cache at all, when I add pagespeed InPlaceResourceOptimization off in configuration. But there is no any optimizations at all..  Just like  set the pagespeed off..
But...   If I dont want to optimize the images. but  optimizing the CSS or JS file or orther optimizations. can  it work?

**Comment by oschaaf** [comment]
@wongjdong You can enable individual filters by specifying, for example:
```
pagespeed EnableFilters rewrite_javascript,rewrite_css;
```

**Comment by jeffkaufman** [comment]
It sounds like you want a configuration like:

```
pagespeed on;
pagespeed FileCachePath /var/ngx_pagespeed_cache;
pagespeed RewriteLevel PassThrough;
pagespeed InPlaceResourceOptimization off;
pagespeed EnableFilters rewrite_javascript,rewrite_css;
```

This will optimize js and css, and not images or anything else.

If this doesn't work for you, feel free to reopen!
