### ISSUE TITLE
outline_javascript not affected by pagespeed_no_defer

### ISSUE THREAD

**Issue by oppianmatt** [pagespeed/ngx_pagespeed#898]
We have some timing <scripts> in our head, but they are quite big so outline_javascript wants to make it external. Now that blocks the whole page as it fetches the external resource. So put the 'pagespeed_no_defer' attribute on the script tag but it still externalises.

e.g.
```
<script pagespeed_no_defer="" src="https://www.pitchup.com/tourers/England/Central/Worcestershire/Upton_Upon_Severn/_.pagespeed.jo.gPQqltANsC.js"></script>
```

Is there a way (like for javascript defer) to specify pagespeed NOT to externalise some resources but have the filter on for other javascripts?

**Comment by jeffkaufman** [comment]
The best thing would be to make your timing js smaller.  ;)  Assuming you can't do that, though, you could raise the threshold for outlining.  Alternatively, you could just turn off outlining entirely; outlining js is not always beneficial and your site may not be a good fit for it.

**Comment by oppianmatt** [comment]
First thing I asked about the js :) but it's a third party monitoring script. Disabling the outline_js filter for now, was only in there to outline some legacy js that gets written with template code. 

Would be nice to be able to selectively control the outlining process like defer.

**Comment by jeffkaufman** [comment]
Sorry it's not more configurable!
