### ISSUE TITLE
Attempting to fetch remote resources for which permission is not granted

### ISSUE THREAD

**Issue by mqudsi** [pagespeed/ngx_pagespeed#914]
Before anything else: I haven't look at the code for this, so I don't know if it's a misleading log entry or not. However, this log would indicate that that despite not having permission to fetch a remote resource, ngx_pagespeed is trying to do so anyway:

```
[Sun, 15 Feb 2015 16:08:26 GMT] [Info] [5679] No permission to rewrite 'https://code.jquery.com/jquery-1.9.0.min.js'
[Sun, 15 Feb 2015 16:08:26 GMT] [Info] [5679] No permission to rewrite 'https://s0.wp.com/wp-content/js/devicepx-jetpack.js'
[Sun, 15 Feb 2015 16:08:26 GMT] [Info] [5679] No permission to rewrite 'https://stats.wp.com/e-201507.js'
[Sun, 15 Feb 2015 16:08:26 GMT] [Info] [5679] No permission to rewrite 'https://code.jquery.com/jquery-1.9.0.min.js'
[Sun, 15 Feb 2015 16:08:26 GMT] [Info] [5679] No permission to rewrite 'https://s0.wp.com/wp-content/js/devicepx-jetpack.js'
[Sun, 15 Feb 2015 16:08:26 GMT] [Info] [5679] No permission to rewrite 'https://stats.wp.com/e-201507.js'
[Sun, 15 Feb 2015 16:08:26 GMT] [Info] [5679] Cannot fetch url 'https://code.jquery.com/jquery-1.9.0.min.js': as https is not supported
[Sun, 15 Feb 2015 16:08:26 GMT] [Info] [5679] Cannot fetch url 'https://s0.wp.com/wp-content/js/devicepx-jetpack.js': as https is not supported
[Sun, 15 Feb 2015 16:08:26 GMT] [Info] [5679] Cannot fetch url 'https://stats.wp.com/e-201507.js': as https is not supported
```

I'm guessing HTTPS isn't supported since I'm using the native fetcher (with `FetchHttps enable`). I do have `InlineResourcesWithoutExplicitAuthiraziotn Script,Stylesheet` enabled, I'm not clear on whether or not that should affect the rewrite of the above-mentioned scripts.

**Comment by jeffkaufman** [comment]
Yes, the native fetcher doesn't support nginx.

I think you're right that this comes from letting it inline resources without explicit authorization.  The first message, no permission to rewrite, is it deciding it can't rewrite the resource while keeping it on the remote server.  The second message is it deciding that it can't fetch it as part of trying to fetch it and (if small enough) inline it.

This looks like it working properly.
