### ISSUE TITLE
investigate rare DCHECK failure from rate_controller.cc

### ISSUE THREAD

**Issue by oschaaf** [pagespeed/ngx_pagespeed#915]
```
2015/02/15 19:15:52 [alert] 43449#0: [ngx_pagespeed 1.10.0.0-4537] [0215/191552:FATAL:rate_controller.cc(188)] Check failed: controller_->current_global_fetch_queue_size_->Get() > 0 (0 vs. 0)
nginx: worker process() [0x49da0c]
nginx: worker process() [0x49a979]
nginx: worker process() [0x6210e7]
nginx: worker process() [0x6117bf]
nginx: worker process() [0x4dad8b]
nginx: worker process() [0x61dc65]
nginx: worker process() [0x6117bf]
nginx: worker process() [0x8244d1]
nginx: worker process() [0x824223]
nginx: worker process() [0x824ed1]
nginx: worker process() [0x824a8f]
nginx: worker process() [0x90b16c]
nginx: worker process() [0x90b3e1]
nginx: worker process() [0x90b58f]
nginx: worker process() [0x908cad]
nginx: worker process() [0x908e12]
nginx: worker process() [0x8229f9]
nginx: worker process() [0x8268e9]
nginx: worker process() [0x826684]
nginx: worker process() [0x9e92ce]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7f2801df0182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f280068aefd]
```

This currently shows up as a miscellaneous test failure, in this case the system test script would fail on 
`TEST: OptimizeForBandwidth`
We might want to do log sanitization post-failure too in the test script, to avoid sending someone down a false trail by making suspicious log messages (like CHECK failures) stand out after a test fails.

**Comment by oschaaf** [comment]
Perhaps not so rare, this one: it happened again, now during the keepalive tests.
Looking at the code, should this be done with a mutex is being held?:
```
      DCHECK_GT(controller_->current_global_fetch_queue_size_->Get(), 0);
      controller_->current_global_fetch_queue_size_->Add(-1);
```

**Comment by oschaaf** [comment]
On second thought, I'm wondering if that would work.
If all fetchers operate on the same global shared data, wouldn't the rate controller generally need shared memory locks to be accurate - especially when there are multiple instances / multiple server contexts?
Or when there are multiple workers?

**Comment by jeffkaufman** [comment]
@morlovich

**Comment by morlovich** [comment]
This should be fixed by https://github.com/pagespeed/mod_pagespeed/commit/497250594733df48340463d53c8bbca476a66440 which is in 1.12 releases.
