### ISSUE TITLE
error in net/instaweb/automatic/system_tests/local_storage_cache.sh

### ISSUE THREAD

**Issue by oschaaf** [pagespeed/ngx_pagespeed#921]
The local storage cache system tests write out some messages to `stderr`, which is hard to see because there's a lot of informational lines being written to stderr when running the system tests (mostly by wget).

Output on stderr:
```
grep: .alt=A cup of joe.,: No such file or directory
grep: .alt=A cup of joe.,: No such file or directory
grep: .alt=A cup of joe.s ..joe...,: No such file or directory
grep: .alt=A cup of joe.s ..joe...);: No such file or directory
```

Looking at net/instaweb/automatic/system_tests/local_storage_cache.sh, it looks like some sort
of line/string continuation was intended, but I'm not sure.

```bash
check grep -q \
  "pagespeed.localStorageCache.inlineImg(.http://.*/images/Cuppa.png.," \
  ".alt=A cup of joe.," \
  ".alt=A cup of joe.," \
  ".alt=A cup of joe.s ..joe...," \
  ".alt=A cup of joe.s ..joe...);" \
  $FETCHED
```

**Comment by jeffkaufman** [comment]
Does #922 fix this?

**Comment by oschaaf** [comment]
@jeffkaufman no, this looks like a bad test. I don't know how to amend it, as I'm not sure what it was supposed to do

**Comment by jeffkaufman** [comment]
I would expect that test to just fail, because grep should return an error if it can't find an input file:

```
$ grep a b <(echo a b c)
grep: b: No such file or directory
/dev/fd/63:a b c
$ echo $?
2
```

But there's a `-q` on the `grep`, so it just prints a message to stderr and continues on:

```
$ grep -q a b <(echo a b c)
grep: b: No such file or directory
jefftk@asterix ~/g/google3/net/instaweb $ echo $?
0
```

The test should be:

```
SEARCH_FOR="pagespeed.localStorageCache.inlineImg(.http://.*/images/Cuppa.png.,"
SEARCH_FOR+=".alt=A cup of joe.,.alt=A cup of joe.,"
SEARCH_FOR+=".alt=A cup of joe.s ..joe...,.alt=A cup of joe.s ..joe...);"
check grep -q "$SEARCH_FOR" $FETCHED
```

I'll fix it.
