### ISSUE TITLE
Support configurable TTL for IPRO resources

### ISSUE THREAD

**Issue by JoyceBabu** [pagespeed/ngx_pagespeed#928]
I wish to set the cache expiration for static files to 30 days. I have the following nginx config

    location ~*.*\.(?:gif|jpg|jpeg|png|ico|3gp|flv|mpg|mpeg|mp4|mp3|swf|txt|xml|pdf|zip)$ {
        expires 1M;
        try_files $uri @backend;
    }

WIth pagespeed disabled, the output is as expected and I can see the correct header `Cache-Control: max-age=2592000`

But when pagespeed is enabled, the expires header is modified to `Cache-Control: max-age=300`. I have tried setting `RewriteLevel` to `PassThrough` and removed all `EnableFilters` lines and still the max-age is set to 300.

**Comment by jeffkaufman** [comment]
Could you try turning off IPRO?

    pagespeed InPlaceResourceOptimization off;

**Comment by JoyceBabu** [comment]
Thank you Jeff. IPRO was causing the problem.

Is it possible to increase cache interval for in-place optimized resources?

**Comment by jeffkaufman** [comment]
IPRO uses a shortened cache lifetime for resources it rewrites because if you change your pagespeed configuration settings it needs to be able to start serving the resources with the modified settings.

Would you be able to use our standard filters that modify urls to include a content hash, which lets us serve them with very long cache lifetimes?

**Comment by JoyceBabu** [comment]
Most of the js, css and image files are currently served using the standard filter. But there are some files that cannot be optimized using the standard filter
- Javascript files added to page using `document.write`
- Javascript files lazy loaded on demand
- Photos and images that I want Googlebot to crawl and index

According to Akamai CDN stats, files optimized using standard filter has about 95-99.5% cache hit rate. Whereas files optimized by IPRO is having only 50-75% cache hit rate.

**Comment by jeffkaufman** [comment]
We should add an option to IPRO to use the origin cache lifetime on served resources, or otherwise make this configurable.

**Comment by jeffkaufman** [comment]
Added to [Accepted Feature Requests](https://github.com/pagespeed/mod_pagespeed/wiki/Accepted-Feature-Requests).

**Comment by JoyceBabu** [comment]
Great. Thanks :)

**Comment by jeffkaufman** [comment]
Looking at this again; was this with LoadFromFile?  Typically with IPRO we do use the origin cache lifetime on served resource.  With LoadFromFile you need to set this; that's `LoadFromFileCacheTtlMs`, but looking now I think we need to write doc for that.

**Comment by JoyceBabu** [comment]
Yes, it was from LoadFromFile.

Is `LoadFromFileCacheTtlMs` used only for client side caching? If the original resource is modified, will PS detect it and re-optimize the new image before the TTL expires?

**Comment by jmarantz** [comment]
Correct; this is just for passing a TTL to clients.  The underlying system
still stat()s the file on every request to see if it actually changed.

**Comment by JoyceBabu** [comment]
Thank you for the clarification @jmarantz.

In that case, isn't it better to set the `max-age` to a large value?
