### ISSUE TITLE
1.JiBnMqyl6S.gif Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by vinvin27** [pagespeed/ngx_pagespeed#937]
I got this issue after activated filters on my nginx :(

Im using prestashop with url friendly :/

**Comment by jeffkaufman** [comment]
Is that the full error?  Could you "view source" on the page, find the reference to `1.JiBnMqyl6S.gif`, and paste the surrounding html here?

When you say prestashop with url friendly you mean this, right? http://doc.prestashop.com/display/PS15/System+Administrator+Guide#SystemAdministratorGuide-NginxfriendlyURLs  This looks like it might interact badly with ngx_pagespeed; I'm not sure yet.

**Comment by vinvin27** [comment]
Hey Jeff :)

Thanks for you reply ! 

yes, thats this url rewriting ! In fact, it s this one : http://pastie.org/10036442
the full error : 
Failed to load resource: the server responded with a status of 404 (Not Found)
https://example.com/pagespeed_static/1.JiBnMqyl6S.gif 

And an example where it is called :
<img width="20" pagespeed_lazy_src="/themes/buyshop/img//facebook.png" pagespeed_url_hash="4182883865" src="/pagespeed_static/1.JiBnMqyl6S.gif" onload="pagespeed.lazyLoadImages.loadIfVisibleAndMaybeBeacon(this);">


but I haven't got /pagespeed_static/ on my server... 

thanks

**Comment by jeffkaufman** [comment]
That's a tiny (1x1) gif that PageSpeed uses as a placeholder when lazyloading images.  PageSpeed should handle serving it; here's an example: http://ngxpagespeed.com/pagespeed_static/1.JiBnMqyl6S.gif

Do you have this line in your config?

     location ~ "^/pagespeed_static/" { }

(From https://developers.google.com/speed/pagespeed/module/configuration)

**Comment by vinvin27** [comment]
Yes I got it !
My nginx config : http://pastie.org/10036535

**Comment by jeffkaufman** [comment]
I think this is probably a bad interaction with your rewrite rules.  Probably the simplest fix would be to disable `lazyload_images` by removing it from the list on line 105.

**Comment by jeffkaufman** [comment]
(Or you could try to see what rewrite rule might be catching this file under `/pagespeed_static/`.

**Comment by vinvin27** [comment]
Yes thanks you Jeff :)

**Comment by vinvin27** [comment]
<img width="20" onload="alert(document.cookie);" pagespeed_lazy_src="/themes/buyshop/img//facebook.png" pagespeed_url_hash="4182883865" src="/pagespeed_static/1.JiBnMqyl6S.gif" onload="pagespeed.lazyLoadImages.loadIfVisibleAndMaybeBeacon(this);">

**Comment by mtx-z** [comment]
For anyone having this issue (404 on the GIF file from /pagespeed_static/), i fixed it adding:
`pagespeed LazyloadImagesBlankUrl "https://www.gstatic.com/psa/static/1.gif";`
to my config.
