### ISSUE TITLE
ngx_pagespeed doesn't support "Transfer-Encoding: chunked" with "Content-Encoding: gzip"

### ISSUE THREAD

**Issue by bacek** [pagespeed/ngx_pagespeed#940]
Switching on keep-alive support and FetchWithGzip cause pagespeed to fail on most of the sites. For example http://www.yandex.ru/, http://lenta.ru, etc.

There is sample response:

2015/03/23 08:02:57 [debug] 11773#0: NgxFetch 00007F18F4001B00: Handle headers
Server: nginx
Date: Mon, 23 Mar 2015 05:02:57 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Status: 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 1cdbdcb0-5576-4159-9d16-eb83bb06caf5
X-Runtime: 0.142807
Set-Cookie: is_mobile=0; path=/; domain=.lenta.ru
Content-Encoding: gzip

600a
<gzip encoded content>
2015/03/23 08:02:57 [debug] 11773#0: NgxFetch 00007F18F4001B00: Handle body (3599 bytes)
2015/03/23 08:02:57 [warn] 11773#0: inflation failure, size=-1
2015/03/23 08:02:57 [debug] 11773#0: NgxFetch 00007F18F4001B00: async fetch write failure
2015/03/23 08:02:57 [debug] 11773#0: NgxFetch 00007F18F4001B00: CallbackDone: FAIL

Looks like NgxFetch has to de-chunk response before passing it to underlying AsyncFetch. (which is InflatingFetch in this case)

**Comment by oschaaf** [comment]
@bacek That is surprising, the native fetcher sends `http/1.0` requests, and I thought `transfer-encoding` was a `http/1.1` feature. That said, if in practice we get responses with chunked transfer encoding anyway, I agree it would be good to be able to decode those properly.

**Comment by bacek** [comment]
Ooops. Looks like it as my local changes to set HTTP to 1.1.

OTOH, most of the servers (starting with nginx) wont use gzip with HTTP/1.0. So it's nice-to-have HTTP/1.1 support in NgxFetch.
