### ISSUE TITLE
MessageBufferSize' is global and is ignored at this scope

### ISSUE THREAD

**Issue by wolololo** [pagespeed/ngx_pagespeed#953]
Do you have any idea what might be causing it? .

	# Recent log messages. Like statistics, these are generally not to be shown
	# to the public, so this has access controls as well.
	pagespeed MessageBufferSize 100000;
	location /ngx_pagespeed_message {
		allow 127.0.0.1;
		deny all;
	}

2015/04/14 15:30:26 [warn] 2485#0: [ngx_pagespeed 1.9.32.3-4448] [0414/153026:WARNING:google_message_handler.cc(38)] 'MessageBufferSize' is global and is ignored at this scope
2015/04/14 15:34:00 [info] 3028#0: [ngx_pagespeed 1.9.32.3-4448] No threading detected. Own threads: 1 Rewrite, 1 Expensive Rewrite.
2015/04/14 15:34:00 [warn] 3028#0: [ngx_pagespeed 1.9.32.3-4448] [0414/153400:WARNING:google_message_handler.cc(38)] 'MessageBufferSize' is global and is ignored at this scope
2015/04/14 15:34:01 [warn] 3032#0: [ngx_pagespeed 1.9.32.3-4448] [0414/153401:WARNING:google_message_handler.cc(38)] 'MessageBufferSize' is global and is ignored at this scope

**Comment by oschaaf** [comment]
`MessageBufferSize` can not be configured at `server{}` scope, you need to move it up one level into the `http{}` scope.

**Comment by wolololo** [comment]
Thank you! The problem has been resolved.

Do you have any idea about following output?

2015/04/14 15:50:24 [info] 3126#0: [ngx_pagespeed 1.9.32.3-4448] No threading detected. Own threads: 1 Rewrite, 1 Expensive Rewrite.

**Comment by oschaaf** [comment]
That is an informational message, you can ignore it.

**Comment by wolololo** [comment]
Thank you. Peace be with you.
