### ISSUE TITLE
Failed to stat errors on deleted resources

### ISSUE THREAD

**Issue by Lux-Delux** [pagespeed/ngx_pagespeed#955]
Hey guys. I've recently deleted some of my images that were previously compressed by pagespeed.

After I deleted them I also deleted everything from /var/ngx_pagespeed_cache/ and restarted nginx.

However I'm still getting regular errors and warnings like so:

```
2015/04/19 09:40:55 [error] 1962#0: [ngx_pagespeed 1.9.32.3-4448] Failed to stat /var/www/tapebrain.com/htdocs/wp-content/uploads/2014/05/Daisy-Ridley-720x304.jpg: No such file or directory
2015/04/19 09:40:55 [warn] 1962#0: [ngx_pagespeed 1.9.32.3-4448] 720x304xDaisy-Ridley-720x304.jpg:0:Resource based on http://tapebrain.com/wp-content/uploads/2014/05/Daisy-Ridley-720x304.jpg but cannot access the original
 ```

I'm using LoadFromFile in my config like so:

```
pagespeed LoadFromFile "http://tapebrain.com/"
                       "/var/www/tapebrain.com/htdocs/";
pagespeed LoadFromFileRuleMatch Disallow .*;
pagespeed LoadFromFileRuleMatch Allow \.(css|js|pdf|gif|jpe?g|png|woff|ico|bmp)$;
```

pagespeed works fine but I'm worried by these errors (or is this normal?). Is there something else I should do to refresh pagespeed from trying to grab non existing resources?

edit: the pages previously using the deleted images have been updated so they don't point to them.

Cheers

**Comment by jeffkaufman** [comment]
In general, deleting files directly from PageSpeed's cache won't do what you want.  We have a "metadata" section of our cache that stores information about the files in the cache, which means that even after you delete the file we'll still think it's there and try to load it.  That's what you're seeing, and it's somewhat inefficient.

To flush the cache, see the documentation here: https://developers.google.com/speed/pagespeed/module/system#flush_cache

This is also not generally a change you need to make: as long as you update your html pages not to reference the images any more then there's no need to delete them from the cache; PageSpeed will remove them from the cache when it needs the space for something else.

**Comment by Lux-Delux** [comment]
Thanks for replying.

The thing is I did try the recommended method too

`sudo touch /var/ngx_pagespeed_cache/cache.flush`

after waiting a bit the errors didn't go away so I did

`sudo rm -rf /var/ngx_pagespeed_cache/*`

But yeah the errors are still filling up my logs

**Comment by jeffkaufman** [comment]
You're saying you:

1) Got `stat` errors in the log for files you've removed from disk.
2) Ran `sudo touch /var/ngx_pagespeed_cache/cache.flush`
3) Still saw `stat` errors.
4) Deleted the files from `/var/ngx_pagespeed_cache/`
5) Still saw `stat` errors.

Is that correct?

Looking more at your pasted errors, I was wrong the first time about what was happening.  That error is saying that you're receiving a request for `720x304xDaisy-Ridley-720x304.jpg`, which PageSpeed thinks is derived from `Daisy-Ridley-720x304.jpg`, and (via `LoadFromFile`) it can't find that original on disk.

If you look in your access logs, can you find the referrers for the `720x304xDaisy-Ridley-720x304.jpg` requests?  It sounds like there's still a reference to the old image out there somewhere and people are still trying to load it.

**Comment by Lux-Delux** [comment]
Ah indeed you are right, there still seem to be requests for images from some shady looking sites that hotlinked.

Guess I'll need to fix that on my end. Cheers
