### ISSUE TITLE
pagespeed removing domain name from redirect links

### ISSUE THREAD

**Issue by bml13** [pagespeed/ngx_pagespeed#959]
I have a wordpress web site that when a not logged in user wants to add a post, he will be asked to login in first and the link will be: 
https://example.com/login/?redirect_to=https://example.com/new-ad/
but when pagespeed is on the link will be
https://example.com/login/?redirect_to=https:///new-ad/

This problem happens also with wordpress social login, after it logs you in using facebook it redirects to:
https://wp-login.php/  instead of https://example.com/wp-login.php/

How to solve this problem? what configuration i am missing?

**Comment by jeffkaufman** [comment]
Could you paste your configuration?

**Comment by bml13** [comment]
I put it here: https://gist.github.com/bml13/9e93477de4e94bc9ad3c

**Comment by bml13** [comment]
It was related to proxy server and wordpress configuration and not to pagespeed.
