### ISSUE TITLE
HSTS Strict-Transport-Secuirity header seems to be stripped by pagespeed for static optimized files 

### ISSUE THREAD

**Issue by creativeprogramming** [pagespeed/ngx_pagespeed#960]
I've: `add_header Strict-Transport-Security "max-age=15552000; includeSubdomains; preload";`

If i test a dynamic php page all is fine, a static unoptimized file also is fine but when i test an optimized resource from pagespeed the server repsonds without the Strict-Transport-Security header

I also tried to force it here:

```
location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
        access_log off;

        add_header "" "";
add_header Strict-Transport-Security "max-age=15552000; includeSubdomains; preload";

}
```

Pagespeed version (from headers): 
X-Page-Speed: 1.9.32.3-4448
nginx version: nginx/1.6.2

--- before submitting this issue i also tried to upgrade all to stable nginx version (1.8.0) and add the new `always` parameter to all the HSTS headers: 
```
add_header Strict-Transport-Security "max-age=15552000; includeSubdomains; preload" always
```
cleaned all the caches (i'm using loadFromFiles if this can matter) but i get only this:

```
HTTP/1.1 200 OK
Server: nginx
Content-Type: application/javascript
Content-Length: 177643
Connection: keep-alive
Keep-Alive: timeout=60
Vary: Accept-Encoding
Last-Modified: Wed, 29 Apr 2015 20:03:37 GMT
Date: Wed, 29 Apr 2015 20:03:37 GMT
Expires: Wed, 29 Apr 2015 20:08:37 GMT
Cache-Control: max-age=300,private
X-Page-Speed: 1.9.32.3-4448
```

still missing Strict-Transport-Security header.

Am I doing something wrong? Can you reproduce the issue on an HSTS enabled site?

**Comment by jeffkaufman** [comment]
Why do you want to set HSTS on your resources?  The header tells the browser "only interact with this domain over HTTPS for X amount of time".  Which means its sufficient to put it on your html.

**Comment by creativeprogramming** [comment]
Thanks for reply, yes after reasoning about this and checking how others are implementing HSTS and the specs I understood that it's required to put it just on the html document.

Anyway my worry was about this:

> The HSTS header can be stripped by the attacker if this is the user's first visit 
(or when max-age expired, http://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)

So I was worrying about a possible downgrade attack done using hotlinking to static resources embedded from a malicious third party site

Anyway I understand now that it makes not sense to send the header on that resources as pagespeeds strips also session cookies (cookieless serving of static resources) so there's nothing to worry about
