### ISSUE TITLE
Pagespeed Shutdown ?

### ISSUE THREAD

**Issue by MiteshShah** [pagespeed/ngx_pagespeed#964]
https://developers.google.com/speed/pagespeed/service/Deprecation

I guess its just google pagespeed service shutdown not the pagesped development.
So we can use pagespeed compile and build it on our servers.

Just want to confirm

**Comment by jeffkaufman** [comment]
Only PageSpeed Service is being shut down, not mod_pagespeed or ngx_pagespeed.  This is included in the announcement you link to, which suggests users of PageSpeed Service consider switching to the PageSpeed Modules (mod_pagespeed/ngx_pagespeed).
