### ISSUE TITLE
Nginx-1.8.0 Make Install Failing

### ISSUE THREAD

**Issue by grouptable** [pagespeed/ngx_pagespeed#973]
I have successfully configured nginx with the added module for pagespeed. Like below:

./configure --user=nginx --group=nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid  --with-rtsig_module --with-select_module --with-poll_module --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_spdy_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-mail --with-mail_ssl_module --with-cpp_test_module  --with-cpu-opt=CPU --with-pcre  --with-pcre-jit  --with-md5-asm  --with-sha1-asm  --with-zlib-asm=CPU --with-libatomic --with-debug --with-ld-opt="-Wl,-E" --with-pcre=path --add-module=$HOME/ngx_pagespeed-release-${NPS_VERSION}-beta

However, when I run 'make' command, I get the following error. 

make -f objs/Makefile
make[1]: Entering directory `/home/vnadmin/nginx-1.8.0'
cd path \
        && if [ -f Makefile ]; then make distclean; fi \
        && CC="cc" CFLAGS="-O2 -fomit-frame-pointer -pipe " \
        ./configure --disable-shared  --enable-jit
/bin/sh: 1: cd: can't cd to path
make[1]: *** [path/Makefile] Error 2
make[1]: Leaving directory `/home/vnadmin/nginx-1.8.0'
make: *** [build] Error 2

Could you please suggest a fix for this? Thanks.

**Comment by grouptable** [comment]
The version of Pagespeed module is the latest: NPS_VERSION=1.9.32.3

**Comment by crowell** [comment]
the part of your config that looks wrong is `--with-pcre=path` "path" is supposed to be the actual path to pcre.

see here for details http://wiki.nginx.org/InstallOptions
