### ISSUE TITLE
emerge nginx  with pagespeed failed on gentoo

### ISSUE THREAD

**Issue by AlexeyBalin** [pagespeed/ngx_pagespeed#977]
I  have Added 
NGINX_ADD_MODULES="/usr/src/ngx_pagespeed" in /etc/portage/make.conf
and try
emerge -av www-servers/nginx

result: http://1cl.in/p/33
emerge --info   http://1cl.in/p/34

Thanks for your help

**Comment by jeffkaufman** [comment]
Do you have the `trunk-tracking` branch checked out in your ngx_pagespeed repo?

**Comment by AlexeyBalin** [comment]
Yes, before build, i run:
cd /usr/src/
git clone https://github.com/pagespeed/ngx_pagespeed.git
cd ngx_pagespeed
wget https://dl.google.com/dl/page-speed/psol/1.9.32.3.tar.gz
tar -xzvf 1.9.32.3.tar.gz

**Comment by jeffkaufman** [comment]
It looks like commit https://github.com/pagespeed/ngx_pagespeed/commit/4df7460d62ee9551a62ed589548300215f598603 got backported to master and should not have been?

We'll revert that commit and then this should work.  Sorry!

**Comment by crowell** [comment]
commit has been reverted

**Comment by AlexeyBalin** [comment]
Thanks! all worked now!
