### ISSUE TITLE
Treat sendfile triggers as pagespeed off

### ISSUE THREAD

**Issue by jeffkaufman** [pagespeed/ngx_pagespeed#981]
Responses with `X-Sendfile` or `X-Accel-Redirect` should not be processed by PageSpeed.  It's not safe to make any changes to the headers and the body is generally misleadingly empty.

**Comment by crowell** [comment]
closed by 4bef2af22c95bede9794879971d5f9bfeeb337da

**Comment by jeffkaufman** [comment]
Dup of https://github.com/pagespeed/mod_pagespeed/issues/1050
