### ISSUE TITLE
nginx repeatedly deleting cache.flush on certain sites

### ISSUE THREAD

**Issue by paulie51** [pagespeed/ngx_pagespeed#988]
Hi,

We're running a (slightly old) version of ngx_pagespeed on a server with approx 150 sites.

Nginx configuration : 

nginx version: nginx/1.7.9
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)
TLS SNI support enabled
configure arguments: --prefix=/usr/share --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --user=nginx --group=nginx --with-ipv6 --with-file-aio --with-http_ssl_module --with-http_realip_module --with-http_sub_module --with-http_dav_module --with-http_gzip_static_module --with-http_stub_status_module --add-module=../ngx_pagespeed-release-1.9.32.3-beta

We pre-populate the PagespeedCache directory with a cache.flush file with FTP user permissions to allow the cache to be flushed manually via FTP, on some sites this file is repeatedly being deleted by Nginx (so presumably by Pagespeed).

There doesn't appear to be any consistency across which sites are affected, other than its recurring on specific sites as far as we can see.  It may be related to the frequency with which this file is touched, but we haven't seen a specific pattern.

Is this deliberate behaviour? If so is there anything we can do to prevent it / why?  We can get it around it fairly easily but it strikes me it may be a bug / undesired behaviour,

Paul.

**Comment by jeffkaufman** [comment]
That's strange.  PageSpeed shouldn't be deleting that file.

For our debugging, did you set `EnableCachePurge on`?

**Comment by paulie51** [comment]
Sorry for the delay in replying, I meant to post the configs originally, no we don't, we have the following configuration : 

    pagespeed on;
    pagespeed FileCachePath /XXX/ngx_pagespeed_cache;
    location /ngx_pagespeed_statistics { allow XXX.XXX.XXX.XXX;deny all; }
    location /ngx_pagespeed_message { allow XXX.XXX.XXX.XXX;deny all; }
    location /pagespeed_console { allow XXX.XXX.XXX.XXX;deny all; }
    location ~ ^/pagespeed_admin { allow XXX.XXX.XXX.XXX;deny all; }
    pagespeed StatisticsPath /ngx_pagespeed_statistics;
    pagespeed MessagesPath /ngx_pagespeed_message;
    pagespeed ConsolePath /pagespeed_console;
    pagespeed AdminPath /pagespeed_admin;
    location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" { add_header "" ""; }
    location ~ "^/ngx_pagespeed_static/" { }
    location ~ "^/ngx_pagespeed_beacon$" { }
    #Without this pagespeed only works for non-www
    pagespeed Domain www.XXX;
    pagespeed Domain ipv4.XXX;

    #Work for https
    pagespeed MapOriginDomain http://XXX https://XXX;
    pagespeed MapOriginDomain http://www.XXX https://www.XXX;

We identified that nginx was doing it through audit if this helps : 

time->Tue Jul 21 09:49:11 2015
type=PATH msg=audit(1437468551.772:1523243): item=1 name="/XXX/ngx_pagespeed_cache/cache.flush" inode=1452477 dev=08:05 mode=0100644 ouid=10058 ogid=494 rdev=00:00 nametype=DELETE
type=PATH msg=audit(1437468551.772:1523243): item=0 name="/XXX/ngx_pagespeed_cache/" inode=1443702 dev=08:05 mode=040755 ouid=495 ogid=494 rdev=00:00 nametype=PARENT
type=CWD msg=audit(1437468551.772:1523243):  cwd="/root"
type=SYSCALL msg=audit(1437468551.772:1523243): arch=c000003e syscall=87 per=400000 success=yes exit=0 a0=7f5274008cb8 a1=7f5274008cb8 a2=1651af0 a3=7f5274008cb8 items=2 ppid=1 pid=709516 auid=504 uid=495 gid=494 euid=495 suid=495 fsuid=495 egid=494 sgid=494 fsgid=494 tty=(none) ses=148299 comm="nginx" exe="/usr/sbin/nginx" key=(null)

I can't find anything significant that matches that time in the nginx logs...

Paul

**Comment by jmarantz** [comment]
It is possible the file is being deleted as part of cache cleaning.
Usually i think it should be OK because it would only be deleted if all the
older files were also deleted.  But it would spoil your hack for setting
it's permissions for ftp access.

A workaround is to set the flush filename outside the directory tree for
the cache.

Josh

**Comment by paulie51** [comment]
Cheers, I wasn't aware of that being a possibility (I did look!) and after some digging have found it, should anyone else end up here : 

https://developers.google.com/speed/pagespeed/module/system

"You can change the polling interval and name of the cache-flush file in the configuration file. If you set the polling interval to 0, the cache flushing feature will be disabled. If you specify the cache flush filename as a relative path, PageSpeed will look for that file in the FileCachePath directory. If you use an absolute path, then the caches associated with multiple virtual hosts can be flushed all at once. "

pagespeed CacheFlushFilename alternate_filename;

Paul.

**Comment by jeffkaufman** [comment]
Reopen if using an absolute path doesn't work out?
