### ISSUE TITLE
nginx 1.9.x compatible release

### ISSUE THREAD

**Issue by nikolay** [pagespeed/ngx_pagespeed#998]
What's up with 1.9.32.5 (and even 1.9.32.6)? I see mod_pagespeed has been released two weeks ago.

**Comment by crowell** [comment]
1.9.32.5 was a test release of a fix for a known bug. This release has not been signed/packaged for wide use.

1.9.32.6 is in the process of being built and released now, for wide adoption.

**Comment by nikolay** [comment]
@crowell Thank you!
